README.md
Just fixing a few spelling issues and adding commas.
=> Grammatical updates

.github/CONTRIBUTING.md
This PR fixes the link to CODE_OF_CONDUCT.md in CONTRIBUTING.md
=> Fix the link to CODE_OF_CONDUCT.md in CONTRIBUTING.md

packages/rome/error.ts
Seems to be a copy paste error
=> Fix getAnsi on RomeDiagnosticsError

package.json, packages/rome/LICENSE, packages/rome/package.json
set packages al MIT licensed as specified in the readme instead of private
=> set license MIT in package.json

packages/@romejs/core/common/constants.ts, packages/@romejs/core/master/commands/test.ts, packages/@romejs/core/master/fs/MemoryFileSystem.ts, packages/@romejs/core/master/fs/Resolver.ts, packages/@romejs/core/master/linter/CompilerLinter.ts, packages/@romejs/core/master/project/ProjectManager.ts, packages/@romejs/js-compiler/api/compile.ts, packages/@romejs/project/load.ts, packages/@romejs/project/types.ts
These shouldn't be configurable. We should minimize the amount of config options we expose.
=> Remove some project config options

scripts/node
Changed the condition so that the script could handle new versions of node.js e.g. v14.
=> Update condition for node script

packages/@romejs/js-ast/typescript/TSTypePredicate.ts, packages/@romejs/js-parser/__rtests__/__rfixtures__/typescript/arrow-function/asserts-with-predicate-types/input.ts, packages/@romejs/js-parser/__rtests__/__rfixtures__/typescript/arrow-function/asserts-with-predicate-types/output.txt, packages/@romejs/js-parser/__rtests__/__rfixtures__/typescript/arrow-function/asserts/input.ts, packages/@romejs/js-parser/__rtests__/__rfixtures__/typescript/arrow-function/asserts/output.txt, packages/@romejs/js-parser/__rtests__/__rfixtures__/typescript/class/predicate-types/output.txt, packages/@romejs/js-parser/__rtests__/__rfixtures__/typescript/function/asserts-with-predicate-types/input.ts, packages/@romejs/js-parser/__rtests__/__rfixtures__/typescript/function/asserts-with-predicate-types/output.txt, packages/@romejs/js-parser/__rtests__/__rfixtures__/typescript/function/asserts/input.ts, packages/@romejs/js-parser/__rtests__/__rfixtures__/typescript/function/asserts/output.txt, packages/@romejs/js-parser/parser/typescript.ts
Add support for `TSAssertsKeyword` mentioned in #12 
[TSAssertsKeyword](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions)
**Use cases:**
```
(value: unknown): value is string => true;
(value: unknown): asserts value => {};
(value: unknown): asserts value is string => {};
```
=> Add TSAssertsKeyword support

.github/CONTRIBUTING.md
See #39
Adds documentation to clarify running the commands on Windows.
=> Add Windows section to CONTRIBUTING.md

packages/@romejs/js-compiler/transforms/compile/validation/optimizeImports.ts, packages/@romejs/js-parser/xhtmlEntities.ts
=> Replace blacklist/whitelist with better names

packages/@romejs/js-compiler/__rtests__/lint.ts, packages/@romejs/js-compiler/transforms/lint/index.ts, packages/@romejs/js-compiler/transforms/lint/noUnsafeFinally.ts
Prevents unsafe finally by throw, continue, break and return statements. Fixes issue #94
=> Disallow no unsafe finally

packages/@romejs/codec-source-map/base64.ts
- Refactor to use uppercase and lowercase terms, this really doesn't matter but I just wanted a nice simple change for my first PR.
=> Refactor to use uppercase and lowercase terms.

packages/@romejs/js-generator/generators/auxiliary/CatchClause.ts
=> Fix codegen for Optional Catch Binding

packages/rome/package.json
First of all, thank you for being thoughtful about this. 
I've updated the link to point to the actual PR
=> Update link in the postinstall message

packages/@romejs/core/master/fs/MemoryFileSystem.ts, packages/@romejs/js-parser/test-fixtures/es2018/regexp-named-capture-group/1/input.js, packages/@romejs/js-parser/test-fixtures/es2018/regexp-named-capture-group/1/output.txt, packages/@romejs/js-parser/test-fixtures/es2018/regexp-named-capture-group/2/input.js, packages/@romejs/js-parser/test-fixtures/es2018/regexp-named-capture-group/2/output.txt, packages/@romejs/js-parser/test-fixtures/es2018/regexp-named-capture-group/3/input.js, packages/@romejs/js-parser/test-fixtures/es2018/regexp-named-capture-group/3/output.txt, packages/@romejs/js-parser/test-fixtures/es2018/regexp-named-capture-group/4/input.js, packages/@romejs/js-parser/test-fixtures/es2018/regexp-named-capture-group/4/output.txt, packages/@romejs/js-parser/test-fixtures/es2018/regexp-named-capture-group/5/input.js, packages/@romejs/js-parser/test-fixtures/es2018/regexp-named-capture-group/5/output.txt
I forgot to add tests in my previous PR https://github.com/facebookexperimental/rome/pull/247
This PR adds tests for named backreference as well as named capture group 
I was also thinking of adding more tests to the project in general. Let me know if this is something you'd like to see and what should be the priority. I was thinking start with the formatter maybe since it was refactored recently and followed along a little bit?
=> Add tests for named capture group and named back reference

packages/@romejs/js-compiler/transforms/lint/preferTemplate.ts
Add auto-fix for prefer template lint rule
=> Prefer template auto fix

packages/@romejs/cli-reporter/Reporter.ts
We were measuring the length of the pre-formatted string. Introduced a `markupifyLength` method to `Reporter` that gets the actual formatted length.
=> Fix Reporter#table padding

packages/@romejs/core/master/commands/ci.ts
After I've been merging PRs, I've generally been checking out `master` and manually running:
```
./scripts/dev-rome lint --fix; ./scripts/dev-rome test --update-snapshots
```
This is in case the PR is stale and we have formatter updates in trunk, or the snapshot now requires changes.
This seems to be a pretty common case so I added `rome ci --fix` which will implicitly add those flags.
It would be cool in the future to have a GitHub bot so we could comment `@romejsbot fix-ci` which would check out a PR, run that command, then commit the result.
=> Add `ci --fix` flag

packages/@romejs/js-parser/parser/classes.ts, packages/@romejs/js-parser/parser/comments.ts, packages/@romejs/js-parser/test-fixtures/es2015/class/inner-comments/input.js, packages/@romejs/js-parser/test-fixtures/es2015/class/inner-comments/output.txt
=> Fix class body inner comments

packages/@romejs/cli-reporter/select.ts, packages/@romejs/core/client/commands/lint.ts, packages/@romejs/core/master/Master.ts, packages/@romejs/core/master/linter/Linter.ts, packages/@romejs/diagnostics/descriptions.ts, packages/@romejs/js-ast-utils/index.ts, packages/@romejs/js-ast-utils/removeShallowLoc.ts, packages/@romejs/js-compiler/transforms/lint/preferTemplate.test.md, packages/@romejs/js-compiler/transforms/lint/preferTemplate.ts, packages/@romejs/js-compiler/types.ts, packages/@romejs/string-markup/format.ts
Commit messages contain a breakdown
=> Misc `rome lint --review` polish

packages/@romejs/codec-js-manifest/convert.ts, packages/@romejs/codec-js-manifest/dependencies.test.md, packages/@romejs/codec-js-manifest/dependencies.ts, packages/@romejs/codec-js-manifest/index.ts, packages/@romejs/codec-js-manifest/name.ts, packages/@romejs/codec-js-manifest/types.ts, packages/@romejs/core/master/fs/MemoryFileSystem.ts, packages/@romejs/core/master/project/ProjectManager.ts
This turns `Manifest['name']` from a `string` into `{packageName?: string, org?: string}`.
=> Turn Manifest['name'] into an object

packages/@romejs/js-compiler/api/lint.ts
We were doing two passes when it could have been done in one. Also excluded comments from being chosen as attachment targets, which would have previously broken if you had a leading block comment since we'd visit it first before the actual node to attach it to.
=> Optimize lint suppression addition

packages/@romejs/codec-source-map/base64.ts, packages/@romejs/codec-source-map/util.ts, packages/@romejs/core/common/fileHandlers.ts
Fix some typo and try to improve readability.
=> Minor fixes

packages/@romejs/cli-reporter/select.ts, packages/@romejs/cli-reporter/types.ts, packages/@romejs/core/master/commands/config.ts
=> Remove some unnecessary code

package.json, packages/@romejs/js-formatter/Printer.ts, packages/@romejs/project/types.ts
=> Bail to break mode when a LineSuffixToken is emitted

packages/@romejs/js-parser/parser/modules.ts, packages/@romejs/js-parser/test-fixtures/experimental/export-extensions/ns-and-named/input.test.md, packages/@romejs/js-parser/test-fixtures/experimental/export-extensions/ns-default/input.test.md, packages/@romejs/js-parser/test-fixtures/experimental/export-extensions/ns/input.test.md, packages/@romejs/js-parser/test-fixtures/flow/declare-export/export-star-as/input.test.md, packages/@romejs/js-parser/test-fixtures/flow/type-exports/star-as-from/input.test.md
=> Fix namespaceSpecifier not being added to ExportExternalDeclaration

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, README.md, packages/@romejs-integration/vscode/package.json, packages/rome/package.json, website/docs/community/contributing.md, website/docs/introduction/getting-started.md, website/docs/introduction/installation.md, website/docusaurus.config.js, website/src/pages/index.js
This PR updates the code of conduct to vanilla Contributor Covenant v2.0 with a dedicated email I'm in the process of setting up.
It also updates the references to `facebookexperimental` with our new `romejs` org!
=> Update Code of Conduct

.editorconfig
This covers the `.cjs` files in the scripts folder
=> Add .cjs to editorconfig indent setup

packages/@romejs/js-ast-utils/doesNodeMatchPattern.ts, packages/@romejs/js-formatter/builders/typescript/TypeAliasTypeAnnotation.ts
=> Fix TS type formatting

packages/@romejs/js-ast-utils/doesNodeMatchPattern.ts, packages/@romejs/js-parser/parser/modules.ts
=> Fix export statement parsing

website/package.json, website/yarn.lock
The changes in docusaurus didn't break the website.
=> Bump docusaurus version

packages/@romejs/string-utils/isEscaped.test.ts
=> Add test for string-utils/isEscaped.ts

packages/@romejs/string-utils/escapeSplit.test.ts, packages/@romejs/string-utils/naturalCompare.test.ts, packages/@romejs/string-utils/orderByNatural.test.ts, packages/@romejs/string-utils/preserveCasing.test.ts, packages/@romejs/string-utils/removeCarriageReturn.test.ts, packages/@romejs/string-utils/sliceEscaped.test.ts
I added some simple tests for the rest of the string-utils. Mostly, they just help document what the utilities do.
=> Add more tests for string-utils

scripts/lint/add.cjs
based on the work from #531 @yassere
=> update script to use testLint method for tests file generation

packages/@romejs/compiler/lint/rules/react/noAccessStateInSetState.test.md
I see this error: https://github.com/romejs/rome/runs/722493223
It looks like my snapshots need to update (introduced in #538 .I should have rebased master and pushed)
=> update snapshots for noAccessStateInSetState

packages/@romejs/compiler/lint/rules/js/noDuplicateCase.test.md, packages/@romejs/compiler/lint/rules/js/noDuplicateCase.test.ts, packages/@romejs/compiler/lint/rules/js/noDuplicateCase.ts
=> Add numeric literal support to noDuplicateCase lint rule

packages/@romejs/compiler/lint/rules/jsx-a11y/htmlHasLang.test.md, packages/@romejs/compiler/lint/rules/jsx-a11y/htmlHasLang.test.ts, packages/@romejs/compiler/lint/rules/jsx-a11y/htmlHasLang.ts, packages/@romejs/compiler/lint/rules/jsx-a11y/iframeHasTitle.test.md, packages/@romejs/compiler/lint/rules/jsx-a11y/iframeHasTitle.test.ts, packages/@romejs/compiler/lint/rules/jsx-a11y/iframeHasTitle.ts, packages/@romejs/js-ast-utils/isEmptyTemplateLiteral.ts
Fixes #562 
Fixes #563 
Added more test cases an utility that checks if the template literal is empty
=> Added more test cases for two rules

packages/@romejs/compiler/lint/rules/js/noDuplicateCase.test.md, packages/@romejs/compiler/lint/rules/js/noDuplicateCase.test.ts, packages/@romejs/compiler/lint/rules/js/noDuplicateCase.ts
Support the Bigint in the rule noDuplicateCase
=> support bigInt literals in noDuplicateCase

packages/@romejs/compiler/lint/rules/js/noDuplicateCase.test.md, packages/@romejs/compiler/lint/rules/js/noDuplicateCase.test.ts, packages/@romejs/compiler/lint/rules/js/noDuplicateCase.ts
I changed it to check duplicate raw value rather than the node references.
so, it can check duplicate JSReferenceIdentifier.
and I added checking duplicate null value also.
=> improve noDuplicateCase

packages/@romejs/compiler/lint/rules/react/noThisInSFC.ts
I broke it in https://github.com/romejs/rome/pull/575
=> fix: switch isJSXElement to type check in noThisInSFC

packages/@romejs/events/Event.test.ts
I tried to write these tests in a way that demonstrates how all the Event methods work.
I'm not sure about how I used `setTimeout` to test `wait`. Is that ok or is it fragile?
=> Add tests for Event

packages/@romejs/compiler/lint/rules/js/noFunctionAssign.test.md, packages/@romejs/compiler/lint/rules/js/noFunctionAssign.test.ts
=> Uncomment test for noFunctionAssign lint rule

packages/@romejs/compiler/scope/Scope.test.md, packages/@romejs/compiler/scope/Scope.test.ts
This PR adds the input code passed to the scope inside the snapshot test. This way, there's a better understanding of the expected result
=> added input next to the dumped scope

packages/@romejs/core/common/utils/Locker.test.ts
Please feel free to criticize the structure or comments of these tests. The idea is that I wanted them to demonstrate how locks work, so I definitely want to know if I made it confusing.
=> Add tests for Locker

.github/workflows/ci.yml
This updates the branch name in our CI config. Are there any other steps to restore our CI, or is this enough?
=> Update github CI workflow

packages/@romejs/formatter/index.test.ts
small fix as I was going through some files
=> fix spelling in a value passed to addToAdvice

packages/@romejs/events/Bridge.test.ts
These tests are certainly not comprehensive, but they hopefully cover the basics.
=> Add tests for Bridge

packages/@romejs/core/worker/WorkerAPI.ts
=> Catch diagnostics in WorkerAPI analyzeDependencies

website/src/_includes/layouts/sections/head.njk, website/src/contributing/team.md, website/src/styles/_global.scss, website/src/styles/_header.scss, website/src/styles/_sidebar.scss, website/src/styles/_table-of-contents.scss, website/src/styles/_team.scss, website/src/styles/_variables.scss, website/static/js/index.js
- Change link colors
- Make sidebar menu titles less contrasty, so it's not confused with links
- Fix white flickering when on dark mode
- Tweak style of teams page
=> Website update

packages/@romejs/cli-diagnostics/highlightCode.ts, packages/@romejs/string-markup/grid/ansi.ts, packages/@romejs/string-markup/grid/tagFormatters.ts, packages/@romejs/string-markup/types.ts
=> Add function call JS syntax highlighting

packages/@romejs/core/common/FileNotFound.ts, packages/@romejs/core/server/dependencies/DependencyGraph.ts, packages/@romejs/core/server/linter/Linter.ts, packages/@romejs/core/server/lsp/LSPServer.ts, packages/@romejs/core/server/project/ProjectManager.ts
Closes #652
Not really sure how to effectively integration test this.
=> Linter: Handle deleted paths

website/README.md
This PR adds instructions for rule documentation and change yarn to npm in the website README.md
=> Website: update readme with instructions for rule documentation 

packages/@romejs/core/worker/WorkerAPI.ts
This prevents the LSP server from crashing on parse errors.
=> Catch parse diagnostics in WorkerAPI analyzeDependencies

packages/@romejs/core/common/bridges/WorkerBridge.ts
=> Change direction of WorkerBridge log event

packages/@romejs/codec-semver/parse.test.md, packages/@romejs/codec-semver/parse.test.ts, packages/@romejs/codec-semver/parse.ts
=> Allow star version qualifier in semver loose mode

website/src/_includes/layouts/base.njk, website/src/styles/_global.scss
Added it to the bottom since it would be a pain to put it at the top and update the styling to push everything down.
=> Add WIP banner to website to indicate development status - closes #713

packages/@romefrontend/cli/cli.ts, packages/@romefrontend/core/client/ClientRequest.ts, packages/@romefrontend/core/common/bridges/ServerBridge.ts, packages/@romefrontend/core/server/Server.ts, packages/@romefrontend/core/server/ServerRequest.ts
=> Add markers to all ServerQueryResponse types

website/src/_includes/homepage-screenshot.md
=> Prevent unicode character be rendered as emoji

packages/@romefrontend/compiler/suppressions.test.md, packages/@romefrontend/compiler/suppressions.test.ts, packages/@romefrontend/compiler/suppressions.ts, packages/@romefrontend/diagnostics/categories.ts, packages/@romefrontend/diagnostics/descriptions/suppressions.ts
=> add diagnostics and tests when incorrect prefix used for suppression

packages/@romefrontend/cli-reporter/Reporter.ts, packages/@romefrontend/cli/cli.ts, packages/@romefrontend/core/client/Client.ts, packages/@romefrontend/core/common/types/client.ts, packages/@romefrontend/core/common/utils/Logger.ts, packages/@romefrontend/core/server/Server.ts, packages/@romefrontend/core/server/lsp/protocol.test.ts, website/src/docs/cli/debugging.md
=> Remove --verbose flag and Reporter#verbose

packages/@romefrontend/core/common/bridges/WorkerBridge.ts, packages/@romefrontend/core/server/ServerRequest.ts, packages/@romefrontend/core/server/WorkerManager.ts, packages/@romefrontend/core/worker/Worker.ts
Following up on this comment: https://github.com/romefrontend/rome/pull/708#issuecomment-654478164
=> Rename file to ref in WorkerBridge

GOVERNANCE.md, website/src/contributing/team.md
As per title, adding myself to the core contributors team.
Updated `GOVERNANCE.md` and `team.md`
=> Added ematipico to the core contributors team

website/static/js/index.js
=> randomly shuffle team list in contributors page

packages/@romefrontend/core/server/commands/check.ts, packages/@romefrontend/core/server/commands/ci.ts
=> Flags description

website/src/contributing/team.md, website/static/js/index.js
in other pages, except where they intend to have an effect these are breaking because of the values being undefined so added an if to handle those
=> apply null/undefined checks in website static js

website/src/_includes/layouts/base.njk, website/src/styles/_global.scss, website/src/styles/_variables.scss
This PR improves breadcrumbs style, here's how it looks:
It's scrollable on mobile:
=> Website: Improve breadcrumbs style

package.json, website/.eleventy.js, website/package-lock.json, website/package.json, website/src/_data/environment.js, website/src/_includes/layouts/base.njk, website/src/styles/_global.scss, website/src/styles/_mixins.scss, website/src/styles/_sidebar.scss
A few things that should have gone in:
- Remove .eleventy.ts from lint ignore
- Add `ELEVENTY_ENV` that we can use to customize the build for production
- Add charset utf-8 meta that would cause unicode characters to sometimes break
- Fix borders overlapping with yellow stripe
=> #834 fixes

website/src/_includes/layouts/base.njk, website/src/styles/_global.scss, website/static/js/index.js
2 seconds after scrolling we hide the WIP banner with a transition.
=> [website] Fade out WIP banner on scroll

.github/labeler.yml, .github/workflows/labeler.yml
Adds some rules and a GitHub action to automatically label PRs according to file changes!
This way we don't need to enforce any PR prefix requirement, or be overly specific around what exactly the title refers to, since the labels will be self describing.
=> Setup automatic PR labeler

.github/ISSUE_TEMPLATE/config.yml, .github/workflows/ci.yml
See commit titles for description of each change.
=> CI workflow and issue template nits

tsconfig.json
This PR adds the `noEmit` option to `tsconfig.json`. When running `tsc` to perform a type check, if you forgot the `--noEmit` flag, it would automatically compile every single file... I didn't realize this could be specified as a config option.
Ran `tsc` and verified no new files were created.
=> Add noEmit to tsconfig.json

.github/labeler.yml
Adds some more paths to the governance and tooling label.
CI
=> Add more paths to autolabeler

.github/ISSUE_TEMPLATE/03_task.md
Change task issue template emoji from 🚀 to 📎. Rocket ship can appear to be release related. Paperclip is more utilitarian.
N/A
=> Change task issue template emoji

packages/@romefrontend/cli-flags/Parser.ts, packages/@romefrontend/cli-layout/grid/formatANSI.ts, packages/@romefrontend/cli/cli.ts, packages/@romefrontend/cli/testWorker.ts, packages/@romefrontend/codec-js-manifest/index.ts, packages/@romefrontend/codec-json/stringify.ts, packages/@romefrontend/consume/Consumer.ts, packages/@romefrontend/core/client/commands/run.ts, packages/@romefrontend/core/server/commands/check.ts, packages/@romefrontend/core/server/commands/config.ts, packages/@romefrontend/core/server/lsp/LSPServer.ts, packages/@romefrontend/core/server/lsp/utils.ts, packages/@romefrontend/core/server/testing/TestServerRunner.ts, packages/@romefrontend/project/load.ts, packages/@romefrontend/project/utils.ts
Adds safe array Consumer methods that protect us from out of bounds errors.
Fixes #776
CI
=> Add safe Consumer array methods

.github/ISSUE_TEMPLATE/01_bug.md
=> Fix typo in bug issue template

website/src/_includes/layouts/base.njk, website/src/index.md, website/static/js/index.js
- made the docsearch script non-blocking by adding it after the document is ready, this helps to make site a little bit faster (https://github.com/romefrontend/rome/pull/860#issuecomment-661282218)
- [lighthouse report](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fromefrontend.dev%2F#seo) suggested to have more meaningful text links, so changed them
No plan, just a review from my peers.
=> docs: make script non blocking and tweaked some link

scripts/ast-create-node.ts
just adding a small fix for the script. relates to #866
=> fix path for file generation in ast-create-node script

CONTRIBUTING.md
Added an update to Contributing.md
The example in the add isn't the most accurate since lots of the existing node types don't follow the format that is expected by the script (such as the nodeType name having the language prefix)
=> update doc with ast-create-node script

scripts/lint-create-rule.ts
should fix #876 
after updating the regex when the command is run it goes on to successfully write all the boilerplate code to all the required files
=> update regex to replace / with _

packages/core/server/lsp/LSPServer.ts
Closes #885 
Manually tested by running `./rome run scripts/run-vscode-extension.ts` then opening a non-Rome project.
=> fix: Prevent LSP Server crashing in non-Rome projects

website/src/_includes/scripts/index.js, website/src/styles/_global.scss
Manually checking/testing Netlify deploy.
=> Try and fix white theme flashing by defering transition styles

website/src/_includes/layouts/base.liquid, website/src/_includes/scripts/index.js
Should squeeze a tiny bit more performance.
Manually testing and profiling Netlify deploy.
=> Defer website script execution

packages/cli-flags/Parser.ts, packages/core/common/constants.ts, packages/core/server/fs/Resolver.ts, packages/core/server/fs/resolverSuggest.ts, packages/path/index.ts, scripts/ast-create-node.ts, scripts/ast-delete-node.ts, scripts/build-release.ts, scripts/generated-files/ast.ts, scripts/generated-files/lint-rules.ts, scripts/generated-files/virtual-modules.ts, scripts/lint-create-rule.ts
No reason for these to be separate.
Ran tests locally. CI.
=> Combine FilePath append and appendList methods

README.md
Updated rome/README.md with some additional information.
=> Updated rome/README.md

.git-blame-ignore-revs, .gitattributes, internal/cli/server.ts, internal/core/client/commands/run.ts, internal/core/server/fs/Resolver.ts, internal/js-parser/parser.ts, internal/web-ui/index.tsx, website/src/_includes/scripts/index.js, website/src/blog/posts/test.md
Removes some unnecessary files that were in the root and removes a bunch of leftover `console.log`s.
CI
=> Remove misc files and console.logs

internal/cli-layout/format.ts
This condition seems pretty frequent that a special case here will have some measurable performance impact.
CI
=> Add optimization for single escaped markup with no columns

internal/cli-diagnostics/printAdvice.ts, internal/cli-flags/Parser.ts, internal/cli-flags/serializeCLIFlags.ts, internal/core/server/ServerRequest.ts, internal/core/server/commands/init.ts, internal/core/server/fs/RecoveryStore.ts
=> Simplify some SerializeCLITarget types to strings instead of objects

internal/cli-reporter/select.ts
Fixes #918 
Manual test on local machine
=> fix: apply correct markup to select

internal/core/server/Server.ts, internal/core/server/ServerRequest.ts
I was completely wrong and this was meant to still function. cc @yassere. Everything access `req.reporter` so this is fairly safe to do. It was a one line fix but I reordered the properties.
Tested one of the broken commands.
=> Fix silent request query property

website/.eleventy.js, website/src/_includes/docs/cli-screenshots/check.md, website/src/_includes/docs/cli-screenshots/init.md, website/src/_includes/docs/cli-screenshots/lint-review.md, website/src/_includes/docs/cli-screenshots/lint-suggestions.md, website/src/_includes/docs/cli-screenshots/recover-list.md, website/src/_includes/docs/intro.md, website/src/_includes/layouts/base.liquid, website/src/_includes/scripts/index.js, website/src/styles/_prism.scss, website/src/styles/_sidebar.scss
Fixes some issues raised by @samccone and a few other bugs I noticed. Notably the sidebar is now completely scrollable and not confined to just the table of contents.
Netlify
=> Website accessibility tweaks

internal/core/server/fs/glob.ts
This prevents a situation where `flush()` would sometimes await a `flushing` promise that never resolves.
Tested manually.
=> fix: Prevent hang in watchFilesFromArgs

website/src/blog/posts/2020-08-08_introducing_rome.md
Addressing some nits and minor feedback.
=> Blog post tweaks

website/src/_includes/docs/getting-started.md, website/src/_includes/layouts/base.liquid, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/jsx-a11y/altText.md, website/src/docs/lint/rules/jsx-a11y/htmlHasLang.md, website/src/docs/lint/rules/jsx-a11y/lang.md, website/src/docs/lint/rules/jsx-a11y/noAutofocus.md, website/src/docs/lint/rules/jsx-a11y/noOnChange.md, website/src/docs/lint/rules/ts/noExplicitAny.md, website/src/docs/lint/rules/ts/preferInterfaces.md
Implements #939 
Just CI and making sure it doesn't break.
=> docs: few documentation around rules

internal/core/client/Client.ts
=> chore: removed USER and PATH from rage --summary

README.md
fix error link in README.md
None
=> Fixes link to Team documentation

website/src/_includes/docs/linting.md
A couple of small grammar fixes I came across reading the docs.
n/a
=> Small grammar fixes

internal/core/server/fs/MemoryFileSystem.ts
=> Treat recursive watch on Android the same as Linux

.vscode/settings.json
Removing `.vscode` directory, it went there because of rushing time during release.
CI
=> chore: remove vscode files from repo

README.md
Updates the alt text of the main README's logo.
=> chore: update logo alt text (#1002)

internal/core/client/Client.ts
Fix for #1003 
```
$ ./rome rage
Building trunk 
ℹ Rage enabled 😠
✔ Rage archive written to Rage-20200809T035008489Z.tgz
```
=> Fix filelink in rage output

internal/typescript-helpers/index.ts
=> refactor(typescript-helpers): use Record for Dict type

internal/codec-js-regexp/index.test.ts
Part of #1023 
Adds test for codec-js-regexp/index.ts
=> Added test for codec-js-regexp/index.ts

internal/codec-source-map/SourceMapConsumer.test.ts
Part of #1023 
Adds test for codec-source-map/SourceMapConsumer.ts
=> Added test for codec-source-map/SourceMapConsumer.ts

internal/codec-source-map/MappingList.test.ts
Part of #1023 
Adds test for codec-source-map/MappingList.ts
=> Added test for codec-source-map/MappingList.ts

internal/js-ast-utils/isJSXElement.test.ts
part of #1023 
follow up pr for #1074 
`./rome ci` ---all tests passed
=> test: updated tests to use template instead of helper

internal/ast-utils/removeLoc.test.ts
Part of #1023 
Adds test for ast-utils/removeLoc.ts
=> Added test for ast-utils/removeLoc.ts

CONTRIBUTING.md
update contributing docs to show how to run test runner on specific files
=> docs: update contributing docs to add path flag

internal/codec-source-map/SourceMapConsumerCollection.test.ts
Part of #1023 
Adds test for codec-source-map/SourceMapConsumerCollection.ts
=> Added test for codec-source-map/SourceMapConsumerCollection.ts

internal/js-ast-utils/cleanJSXText.test.ts
Part of #1023 
Adds test for js-ast-utils/cleanJSXText.ts
=> Added test for js-ast-utils/cleanJSXText.ts

internal/js-ast-utils/createPropertyKey.test.ts
Part of #1023 
Adds test for js-ast-utils/createPropertyKey.ts
=> test: js-ast-utils/createPropertyKey.ts

website/src/_includes/docs/linting.md
This fixes a typo in the Linting section from the website
Old sentence:
`Reviewing: We offer an interactive CLI command to make this process even easier. It allows you to go through each diagnostic and perform actions on them such inserting a suppression comment or applying a specific fix.`
New sentence:
`Reviewing: We offer an interactive CLI command to make this process even easier. It allows you to go through each diagnostic and perform actions on them such as inserting a suppression comment or applying a specific fix.`
=> fix typo in website's linting section

README.md
##Summary
Language Improvements
=> Revamped the Language flow

internal/js-ast-utils/getBindingIdentifiers.test.ts
Part of #1023 
Adds test for js-ast-utils/getBindingIdentifiers.ts
=> Added test for js-ast-utils/getBindingIdentifiers.ts

internal/js-ast-utils/getImportSpecifiers.test.ts
Part of #1023 
Adds test for js-ast-utils/getImportSpecifiers.ts
=> Added test for js-ast-utils/getImportSpecifiers.ts

internal/js-ast-utils/getJsxElementName.test.ts
part of #1023
added tests for getJsxElementName.ts
`./rome test` --all tests passed
=> test: add tests for getJsxElementName.ts

internal/js-ast-utils/isFunctionNode.test.ts
part of #1023 
added tests for `ast-js-utils/isFunctionNode.ts`
`./rome test` --all tests passed
=> tests: add tests for isFunctionNode

internal/js-ast-utils/isNodeLike.test.ts
Part of #1023 
Adding test for isNodeLike
`./rome test` passed
`./rome check` passed
`./node_modules/.bin/tsc` passed
=> add test for isNodeLike

internal/js-ast-utils/hasJSXAttribute.test.ts
Part of #1023 
Adds test for js-ast-utils/hasJSXAttribute.ts
=> Added test for js-ast-utils/hasJSXAttribute.ts

internal/js-ast-utils/getJSXAttribute.test.ts, internal/js-ast-utils/getRequireSource.ts, internal/js-ast-utils/isBinary.test.ts
Part of #1023 
Adds test for js-ast-utils/getJSXAttribute.ts
=> Added test for js-ast-utils/getJSXAttribute.ts

internal/js-ast-utils/assertMultipleNodes.test.ts, internal/js-ast-utils/assertSingleNode.test.ts, internal/js-ast-utils/assertSingleOrMultipleNodes.test.ts
part of #1023 
added tests for 
`js-ast-utils/assertMultipleNodes.ts`
`js-ast-utils/assertSingleNode.ts`
`js-ast-utils/assertSingleOrMultipleNodes.ts`
`./rome test` --all tests passed.
=> tests: added tests for nodeAssertion files

internal/cli-flags/Parser.test.md, internal/cli-flags/Parser.ts
Closes #993 
I checked the the result of the output but I didn't check if it actually works. 
I would like some feedback first and then I will test it manually.
=> feat: auto completion for zsh

website/src/_includes/scripts/index.js, website/src/styles/_sidebar.scss
- Limit sidebar width
- Change location.hash on scroll
Manually on netlify deploy preview
=> fix(website): Limit sidebar width and Change location.hash on scroll

website/src/styles/_sidebar.scss
Fix my last merge
Manually on netlify deploy preview
=> fix(website): Sidebar have a fixed width size

internal/string-diff/index.test.ts, internal/string-diff/index.ts
=> test: add original tests for string-diff

internal/project/load.ts
Fixes https://github.com/romefrontend/rome/issues/1181#issue-695280963
Manually checked on a brand new project
=> fix: correctly validate format configuration

website/src/_includes/docs/cli.md
Add site documentation for zsh completions
Adding site documentation for #1160 (auto completion for zsh)
=> Add zsh completion documentation

website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/js/noUnnecessaryContinue.md
documentation in website for `noUnnecessayContinue` seems to broken because of indentation, fixed it!
=> fix(docs): documentation for noUnnecessaryContinue

website/src/_includes/docs/getting-started.md
=> docs: Add npx command for invoking Rome

internal/toml-parser/parser/string.ts
This PR fixes a small regression
CI
=> fix: optional chain

website/src/docs/lint/rules/js/preferOptionalChaining.md
this PR fixes the website documentation for preferOptionalChaining lint rule
closes #1214
=> fix: documentation #1214

website/src/_includes/action-links.liquid
Rome Toolchain moved Twitter accounts recently after the name change, the existing Twitter link leads to the old, unused account.
=> fix twitter link

website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/js/noArguments.md, website/src/docs/lint/rules/js/noDelete.md, website/src/docs/lint/rules/js/noDuplicateImportSource.md, website/src/docs/lint/rules/js/noNegationElse.md, website/src/docs/lint/rules/js/noUndeclaredVariables.md, website/src/docs/lint/rules/js/noUnusedTemplateLiteral.md, website/src/docs/lint/rules/js/useBlockStatements.md, website/src/docs/lint/rules/js/useSingleVarDeclarator.md
Adds more links to comparable ESLint rules and adds a few descriptions to rules that had none.
=> docs: add more descriptions and ESLint rules to lint rules

CONTRIBUTING.md
=> fix typo Getting Started text

website/src/_includes/docs/rjson.md
=> minor typo fix

website/static/_redirects
This PR updates the redirects of the website.
It redirects any `http` URL to `https` url.
Waiting PR deploying and testing it.
=> chore(website): redirect from http to https

internal/compiler/lint/rules/react/noUselessFragment.test.md, internal/compiler/lint/rules/react/noUselessFragment.test.rjson, internal/compiler/lint/rules/react/noUselessFragment.ts, website/src/docs/lint/rules/react/noUselessFragment.md
fix #1238
#1238 occurred because "noUselessFragment" reports a lint error and the fixing changes "alternate" into "undefined". 
I added a test case for ensuring it.
=> fix(lint): ignore conditional fragment in noUselessFragment

internal/compiler/transforms/compile/transpile/optionalChaining.test.md, internal/compiler/transforms/compile/transpile/optionalChaining.test.ts, internal/compiler/transforms/compile/transpile/optionalChaining.ts
As ensuring with [the test case](https://github.com/rome/tools/pull/1248/files#diff-c9ef94c68ffb9713ca465eb168dc9c59d3961c075b201b486d6ffa39f9f3403eR48) this pr will fix #1199.
Furthermore, I found unreported bugs and those will be fixed too. 
```js
// ./bug.js
a10?.c.d();
```
It throws "Not implemented non js memeber expression case" error, but as I know `a10?.c.d();` is valid syntax.
```bash
$ ./rome compile ./bug.js
✖ Not implemented non js memeber expression case
```
compile success
```bash
$ ./rome compile ./bug.js
a10 == void 0 ? void 0 : a10.c.d();
```
I added [Test cases](https://github.com/rome/tools/compare/main...yeonjuan:issue-1199?expand=1#diff-c9ef94c68ffb9713ca465eb168dc9c59d3961c075b201b486d6ffa39f9f3403e).
=> fix(compiler): handle optionalChaining properly

internal/js-ast-utils/removeShallowLoc.test.ts
Part of #1023 
Adds test for js-ast-utils/removeShallowLoc.ts
=> test: add test for js-ast-utils/removeShallowLoc.ts

internal/js-ast-utils/isConditional.test.ts, internal/js-ast-utils/isConditional.ts, internal/js-ast-utils/template.ts
- Implement tests for `isConditional`
```
./rome test
✔ 3_840 tests passed!
```
=> test: add tests for isConditional

internal/parser-core/utils.test.ts
Part of #1023 
Adds test for parser-core/utils.ts
=> test: add test for parser-core/utils.ts

internal/js-ast-utils/template.test.ts
Part of #1023 
Adds test for js-ast-utils/template.ts
=> test: add test for js-ast-utils/template.ts

test.js
`test.js` file seems to have been added in #1235 by mistake. this pr remove `test.js`
=> chore: remove test.js

internal/core/server/testing/TestServerWorker.ts
=> fix(test): ci failing

internal/compiler/lint/rules/js/noUndeclaredVariables.ts, internal/compiler/lint/utils/getLangSuggestions.ts
While I take a look at the project to solve ci problem.
I found some codes to refactor.
=> chore: minor refactor

GOVERNANCE.md, website/src/credits.md
Adds @jer3m01 to the list of core contributors in `GOVERNANCE.md` & on the website.
`yarn build` is successful.
=> chore: add jer3m01 to core contributors

scripts/update-contributor-credits.ts
adding alt attribute is more compliant to `<img />`
=> fix: add avatar img alt

internal/ast/css/selectors/CSSCombinator.ts, internal/css-parser/parser/selectors.ts, internal/css-parser/test-fixtures/selectors/input.test.md, internal/formatter/builders/css/selectors/CSSCombinator.ts
This PR will fix a typo that I made before. 😅 ("sibling" -> "sibling") 
test case
=> chore(css-parser): fix typo

GOVERNANCE.md, website/src/credits.md
Added yeonjuan as a core contributor.
=> chore: add yeonjuan to core contributors

internal/js-ast-utils/valueToNode.test.ts, internal/js-ast-utils/valueToNode.ts
part of #1023
added tests for js-ast-utils/valueToNode.ts
./rome test --all tests passed
=> add test for js-ast-utils/valueToNode.ts

internal/ast-utils/assertRoot.test.ts, internal/ast-utils/assertRoot.ts, internal/ast-utils/isRoot.test.ts, internal/ast-utils/isRoot.ts
- Add tests to isRoot function
- Adds tests to assertRoot function
```
./rome check --apply
ℹ 1_733 files linted
✔ No known problems!
```
```
./rome test internals/ast-utils
✔ 5 tests passed!
./rome test
✔ 3_841 tests passed!
```
=> test: Adds tests for ast-utils - isRoot, assertRoot

internal/codec-config/json/parse.ts
=> fix(codec-config): rjson block comment parsing on `/`

internal/cli-layout/Grid.ts, internal/cli-layout/format.test.ts, website/src/docs/lint/rules/js/noShoutyConstants.md, website/src/docs/lint/rules/jsx-a11y/noPositiveTabindex.md, website/src/docs/lint/rules/jsx-a11y/useMediaCaption.md, website/src/docs/lint/rules/react/noStringRefs.md, website/src/docs/lint/rules/react/useSortComp.md
Fixes #971. Thanks @jer3m01 for the consistent repro!
Added a new test, ran `./rome ci`
=> Fix markup format ranges spanning multiple lines

internal/browsers-db/README.md
Add more information to the format of the data in `browsers-db`.
=> docs(browsers-db): improve README

internal/compiler/suppressions.test.ts, internal/css-parser/index.ts, internal/css-parser/parser/declaration.ts, internal/css-parser/parser/keyframe.ts, internal/css-parser/parser/value.ts, internal/diagnostics/descriptions/parsers/cssParser.ts
remove console.log and fix typo
pass tests
=> chore: remove console.log, fix typo

internal/markup/README.md, internal/markup/tags.ts
Adds a README for all markup tags, attributes and examples.
=> docs(markup): add README

.github/workflows/nightly.yml, .gitignore, internal/consume/Consumer.ts, internal/core/common/types/bundler.ts, internal/core/server/bundler/Bundler.ts, internal/core/server/commands/bundle.ts, internal/core/server/fs/MemoryFileSystem.ts, internal/core/worker/Worker.ts, public-packages/rome/package.json, scripts/build-nightly.ts, scripts/build-release.ts, scripts/update-version.ts
This PR adds a GitHub action on a cron job that triggers a workflow depending on the `nightly` environment that requires approval. I'll manually approve it whenever it's triggered to remove the possibility for someone committing something dangerous.
Manually testing triggering the workflow once landed.
=> feat(releases): Add automatic nightly releases

CODEOWNERS
=> fix(CODEOWNERS): folder typo

internal/codec-browsers/test-fixtures/individual/last-months/input.test.md
This PR updates test fixtures around code browsers. No code has changed in the process.
CI
=> chore: updated snapshot tests

website/src/_includes/docs/project-config.md
=> docs: fix typo

internal/formatter/node/parentheses.ts, internal/formatter/test-fixtures/typescript/parentheses/asExpression/input.test.md, internal/formatter/test-fixtures/typescript/parentheses/asExpression/input.ts
…ression
fixes #1401 
test case
=> fix(ts-formatter): handle logical expression parentheses in ts as expression

CODEOWNERS, internal/compiler/transforms/compile/css-handler/prefix/prefixes/display.ts
title
also add css prefix to jer3m01 in CODEOWNERS
ci
=> refactor(css-prefix): map values instead of writing multiple times

README.md
The old link was broken, so small edit using the link from the website.
=> fix: Update Discord Link

internal/cli-flags/Parser.test.md, internal/cli-flags/Parser.test.ts, internal/consume/Consumer.ts
This PR fixes #1395.
This PR adds a test to make sure that the kebab case is kept as is.
=> fix: invalid flag message wrong string case

CONTRIBUTING.md
- updated the link to the discord server
- added a new phrase around the generated files
=> docs: contributing tips

internal/binary-transport/README.md
Wrote up a quick explainer of what the purpose of this binary transport was and how it worked
=> docs: writeup explainer for @internal/binary-transport

internal/resources/factories.ts
WebSocket resources aren't currently used, but this should be a "close" listener.
=> fix: change listener type in createResourceFromWebSocket factory

internal/collections/index.ts
Calling `clear()` on a MappedSet should also clear the internal Set.
=> fix: clear private set in MappedSet#clear

scripts/update-nightly-version.ts
This PR fixes the nightly version by adding `1` to the month, as they start from `0`.
Next nightly release.
=> ci: fix nightly release version

internal/resources/Resource.ts, internal/resources/factories.ts, internal/resources/index.ts, internal/resources/types.ts, package.json
Closes https://github.com/rome/tools/issues/1545
The majority of the changes is just linting. I removed `resources` and `prelude.ts` from the `ignore` linting section.
Current CI
=> chore: enable lint for resources folder

internal/events/EventQueue.ts
Fixes a typo: EventQueueCallack -> EventQueueCallback
=> chore: rename callback type in EventQueue

scripts/dev-rome.cjs
Updates `EXPECTED_MAJOR` to match version in package.json engines field.
=> chore(scripts): update node major version in dev-rome script

internal/core/worker/integrations/eslint.ts
=> fix(integrations): remove hardcoded path

internal/core/worker/integrations/prettier.ts, internal/core/worker/workerLint.ts, internal/diagnostics/categories.ts, internal/project/constants.ts, internal/project/integrations/loadPrettier.ts, internal/project/load.ts, internal/project/types.ts, internal/project/utils.ts, website/src/_includes/docs/project-config.md
Part of #1570 
This PR adds a new integration: `prettier`.
The number of options is limited but it should cover the majority of cases.
Added some documentation too.
Manually checked on a different project.
=> feat(integrations, project): prettier

internal/core/server/commands/check.ts
Added warnings when running integrations:
Current CI
=> chore: add warning when running integrations

internal/core/common/types/client.ts
=> fix(core): programmatic is false by default

.github/ISSUE_TEMPLATE/01_bug.yml
Following [planning proposal](https://discord.com/channels/678763474494423051/852243421099327488/857346176306249769), this PR attempts to create the first form schema using a YAML configuration.
Please let me know what fields make sense. 
None
=> chore: github form schema

internal/codec-js-manifest/index.test.ts, internal/codec-js-manifest/normalize/fields.ts, internal/codec-js-manifest/normalize/index.ts, internal/codec-spdx-license/parse.ts, internal/core/common/IntegrationLoader.ts, internal/core/server/commands/init.ts, internal/core/server/fs/MemoryFileSystem.ts, internal/core/server/fs/Resolver.ts, internal/core/server/project/ProjectManager.ts, internal/core/server/utils/getManifest.ts, internal/project/load.ts
Closes https://github.com/rome/tools/issues/1607
This change should hold the check on licenses and dependencies.
Current cI
=> feat(project): avoid validate manifest

internal/core/worker/WorkerAPI.ts
Diagnostic `metadata` was renamed to `description` so this method should be updated to add the warning to the correct spot.
=> fix(core): add advice correctly in interceptDiagnostics

internal/core/server/commands/config.ts
This reverts a change I've done some PR ago. It wasn't meant to be done in that way and the documentation wasn't updated.
CI
=> fix(cli): revert incorrect change of config enable/disable

website/src/_includes/docs/cli-commands.md, website/src/_includes/docs/intro.md, website/src/_includes/docs/project-config.md
This PR adds more documentation around the configuration of the `format` section and the `lint` section.
It also removes some old reference to RJSON.
CI
=> doc: add configuration for format and lint

.github/FUNDING.yml, .github/ISSUE_TEMPLATE/01_bug.yml, .github/ISSUE_TEMPLATE/02_task.yml, .github/ISSUE_TEMPLATE/03_umbrella.yml, internal/core/server/commands/check.ts
- remove `FUNDING.yml`
- fix bug report form
CI
=> chore: miscellaneous changes

website/src/_includes/docs/linting.md
We removed dependency verification and manifest from `rome check`. This PR updates the documentation part.
Current CI
=> docs: rephrasing of formatting

internal/core/server/ServerRequest.test.ts, internal/core/server/commands/init.ts, internal/core/server/fs/MemoryFileSystem.ts, internal/core/server/project/ProjectManager.test.ts, internal/core/server/project/ProjectManager.ts, internal/diagnostics/descriptions/projectManager.ts, internal/project/constants.ts, internal/project/utils.ts
Relative to #1596
This PR removes the `.config` folder from the project. Now the configuration file will live in the project root folder.
Existing CI
=> feat(project, cli): remove .config folder

.github/workflows/ci.yml
This PR enables the CI in the PRs too
Current CI
=> ci: enable on PRs

crates/cli/fixtures/input.json, crates/cli/src/bin/cli.rs, crates/cli/src/lib.rs, crates/cli/tests/main.rs, crates/formatter/src/format_json.rs, crates/formatter/src/lib.rs, crates/formatter/src/printer.rs
Some refactoring to let me dig into the project
Add an e2e test for the cli format command
=> refactor(cli,formatter): more idiomatic rust

crates/rslint_lexer/src/lib.rs, crates/rslint_lexer/src/tests.rs, crates/rslint_parser/test_data/inline/err/binding_identifier_invalid.rast, crates/rslint_parser/test_data/inline/err/export_decl_not_top_level.rast, crates/rslint_parser/test_data/inline/err/import_decl_not_top_level.rast, crates/rslint_parser/test_data/inline/err/invalid_method_recover.rast, crates/rslint_parser/test_data/inline/err/method_getter_err.rast, crates/rslint_parser/test_data/inline/ok/async_method.rast, crates/rslint_parser/test_data/inline/ok/class_expr.rast, crates/rslint_parser/test_data/inline/ok/continue_stmt.rast, crates/rslint_parser/test_data/inline/ok/function_decl.rast, crates/rslint_parser/test_data/inline/ok/method_getter.rast, crates/rslint_parser/test_data/inline/ok/method_setter.rast, crates/rslint_parser/test_data/inline/ok/object_expr_async_method.rast, crates/rslint_parser/test_data/inline/ok/object_expr_getter_setter.rast, crates/rslint_parser/test_data/inline/ok/object_expr_getter_setter_computed.rast, crates/rslint_parser/test_data/inline/ok/object_expr_method.rast, crates/rslint_parser/test_data/inline/ok/return_stmt.rast, crates/rslint_parser/test_data/inline/ok/static_method.rast, crates/rslint_parser/test_data/inline/ok/switch_stmt.rast, crates/rslint_parser/test_data/inline/ok/yield_expr.rast, crates/rslint_regex/src/parser.rs
```
> cargo test -p rslint_lexer
...
test result: ok. 62 passed;
...
> cargo test -p rslint_parser
...
test result: ok. 12 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s
test result: ok. 7 passed; 0 failed; 2 ignored; 0 measured; 0 filtered out; finished in 1.10s
...
```
=> Break newline and space "\n " into two tokens

.github/workflows/ci.yml, rust-toolchain.toml
This PR closes #1727
The version pinned is `1.56.1`. 
I also specificied the components as suggested by this recent article: https://fasterthanli.me/articles/my-ideal-rust-workflow
Current CI
=> chore: pin channel version

crates/rslint_parser/src/ast/generated/nodes.rs, xtask/src/codegen/generate_nodes.rs
Follow the instruction of #1756, try to optimize the `.clone()`
fix #1756
=> feat(codegen): optimize cast codegen for enums

crates/rslint_parser/src/parser.rs, crates/rslint_parser/src/syntax/stmt.rs, crates/rslint_parser/test_data/inline/err/invalid_method_recover.rast, crates/rslint_parser/test_data/inline/err/var_decl_err.rast
Small PR to address the last part of the recovery usage.
```
cargo lint
cargo test
cargo format
```
=> feat: correct unknown nodes on partial recovery

CONTRIBUTING.md
This PR closes #1810 
Here the [rendered version](https://github.com/rome/tools/blob/49e38f852a09ab5ec79f7b814768787768a491ca/CONTRIBUTING.md)
Please let me know if there's something I missed!
Current CI
=> doc: update contributing file

xtask/src/compare/results.rs
This implements detailed coverage report for xtask compare, reporting better diffs, see #1844
```
cargo xtask coverage --json > base_results.json 
```
Break the parser (comment some random code out), then
```
cargo xtask coverage --json > new_results.json
cargo xtask compare ./base_results.json ./new_results.json  --markdown
```
=> feat(xtask): Generate detailed coverage report for xtask compare

CONTRIBUTING.md, crates/rslint_parser/docs/authoring_parse_rules.md
Start writing a guide on how to implement parsing rules. This isn't intended to be the final version. We want to revisit the guide after we finished our changes to the parser.
=> "Short" guide on how to author parsing rules

.github/workflows/main.yml, .github/workflows/pul_request.yml, .github/workflows/test262.yml, crates/rome_cli/Cargo.toml, crates/rome_core/Cargo.toml, crates/rome_formatter/Cargo.toml, crates/rome_path/Cargo.toml, crates/rome_rowan/Cargo.toml, crates/rome_rowan/src/green/token.rs, crates/rslint_errors/Cargo.toml, crates/rslint_lexer/Cargo.toml, crates/rslint_parser/Cargo.toml, crates/rslint_parser/src/event.rs, crates/rslint_parser/src/syntax/stmt.rs, crates/rslint_regex/Cargo.toml, crates/rslint_syntax/Cargo.toml, crates/rslint_text_edit/Cargo.toml, crates/tests_macros/Cargo.toml, rust-toolchain.toml
This PR updates the toolchain to use rust `1.57.0` and edition `2021`.
The CI workflow are also updated.
Followed cargo instructions which are:
1. run `cargo fix --edition`
2. update `edition` filed to `2021`
3. verify that the fix worked with `cargo build`
=> feat: new rust version and edition

README.md
=> fix typo, duplicate preposition

xtask/src/libs/mod.rs
Continuation of: https://github.com/rome/tools/pull/1902
This is just the summary at the end.
=> xtask coveragelibs summary at the end

crates/rslint_parser/src/token_source.rs
Fix ```unwrap``` panic on https://github.com/rome/tools/pull/1915
=> fix: return first/last token when index is out of bounds

crates/rome_formatter/src/formatter.rs
While `debug_assert!` is removed in release builds, its done by expanding the macro to an `if cfg!()` and not by using a `#[cfg()]` attribute. This means while the expression will never be executed it still has to be valid, which isn't the case here as `self.printed_token` does not exist in release builds. I replaced all `debug_assert!` with normal assertions wrapped in `cfg_if` to ensure the whole statement is removed in release builds (as a side note, despite looking like a block the `cfg_if` macro does not create a new lexical scope, which is why I opted to do a `drop(printed_tokens);` in `format_delimited` to release the `RefCell`)
I also added a number of additional `#[cfg()]` attributes to various language items to remove warnings about imports or variables being unused.
=> fix(rome_formatter): fix the release build of the formatter

CONTRIBUTING.md
Added a small documentation to `CONTRIBUTING.md` about the new `!bench` command.
I think we should also add something about `xtask`, which can be covered by  #1971 
Current CI
=> doc: add reference to `!bench` comment

crates/rslint_parser/test_data/inline/ok/import_as_as_as_identifier.js, crates/rslint_parser/test_data/inline/ok/import_as_as_as_identifier.rast
There was two missing files from https://github.com/rome/tools/pull/1970
This PR adds them
=> test: add missing test file

.github/workflows/bench.yml
=> ci: fix bench by removing pull_request check

crates/rslint_lexer/src/lib.rs, crates/rslint_lexer/src/tests.rs
Better handling of new lines to facilitate the work of the formatter. see https://github.com/rome/tools/pull/1974#discussion_r789627340
=> split newline tokens

crates/rslint_parser/src/ast/generated/nodes.rs, xtask/codegen/js.ungram
=> Remove the JsName variant in the AnyJsImportClause enum

crates/rome_formatter/src/cst.rs
=> fix: Add JS_IMPORT match arm

crates/rome_lsp/src/handlers.rs, crates/rome_lsp/src/server.rs
This PR is part of #2003 
It adds an utility function that converts `lspower::lsp::FormattingOptions` to `rome_formatter::FormatOptions`
I couldn't test myself as the formatting doesn't work on the VSCode extension. No idea why.
=> feat(rome_lsp): convert LSP formatting options correctly

editors/vscode/package.json
This PR adds few metadata to the `package.json` of the VScode extension.
Here's a link to the page that explains each field: https://code.visualstudio.com/api/references/extension-manifest
None
=> chore(vscode): categories and keywords

website/src/blog/posts/2022-02-08_rome-formatter-and-rust-update.md
=> Add new Rome Formatter and Rust Update blog post

website/src/blog/posts/2022-02-08_rome-formatter-and-rust-update.md
=> chore(website): some grammar fixes

crates/rome_formatter/tests/specs/ts/expression/type_expression.ts.snap
Fixes the CI, where a snapshot was outdated
CI
=> fix: broken snapshot

website/src/credits.md
The PR #2074 was pointed to `latest` which didn't trigger a push to the website.
I took its commits and this PR will point to `master`, so it should publish to the website now.
Existing CI
=> chore(website): core contributors to alumni

crates/rome_formatter/src/format_element.rs
This adds a manual implementation of `Debug` to `FormatElement` and most of the formatter IR structures and enums, adjusted to be easier to read.
<details>
<summary>Previous output</summary>
```rust
List(
List {
content: [
Group(
Group {
content: List(
List {
content: [
Token(
Dynamic {
text: "runtimeAgent",
source: 460..472,
},
),
Token(
Dynamic {
text: ".",
source: 472..473,
},
),
Token(
Dynamic {
text: "getProperties",
source: 473..486,
},
),
],
},
),
},
),
Group(
Group {
content: List(
List {
content: [
Token(
Dynamic {
text: "(",
source: 486..487,
},
),
Indent(
Indent {
content: List(
List {
content: [
Line(
Line {
mode: Soft,
},
),
Token(
Dynamic {
text: "objectId",
source: 493..501,
},
),
Token(
Dynamic {
text: ",",
source: 501..502,
},
),
Line(
Line {
mode: SoftOrSpace,
},
), …
```
=> refactor(rome_formatter): improve debug printing of FormatElement

crates/rslint_errors/src/file.rs
The error package determines the line numbers by searching the positions of the `\n` and `\r` characters and taking them as the start of a new line.
The problem with this approach is that it creates two lines for a `\r\n`: It first assumes a line break after `\r` and then after `\n`.
This PR fixes the line counting for `\r\n` by testing if a `\r` is followed by a `\n` and if so, don't treat it as a line break (only the following `\n`).
closes #2124 
Added a new test, testing `line_starts` for `\n`, `\r\n` and `\r`. 
Verified that the diagnostics emitted by
```bash
cargo coverage --filter callOfConditionalTypeWithConcreteBranches --detailed
```
now points to the correct line numbers.
=> fix(rslint_errors): Fix line numbers for files using `\r\n`

website/src/_includes/action-links.liquid
Our opencollective is no longer active, so this removes the link.
=> chore(website): remove opencollective link

.github/workflows/bench_parser.yml, crates/rslint_parser/src/syntax/class.rs, xtask/bench/src/lib.rs, xtask/bench/src/libs-js.txt, xtask/bench/src/libs-ts.txt, xtask/bench/src/main.rs
Allow multiple suites when benchmarking the parser and the formatter.
```
> cargo bench_parser --help
cargo bench
Benchmark parser and formatter.
USAGE:
cargo bench [option]
OPTIONS
--save-baseline     Allows different runs to be compared.
--feature           Possible values: parser, formatter
--criterion=[true/false]  Run a series of statistical test to assess with the this run is faster or slower than previous runs.
--suites=<IDS>      Runs the specified benchmarks. Use comma as separator.
Valid values are:
*: will run all benchmarks;
js: will benchmark all javascript libraries;
ts: will benchmark all typescript libraries;
Default is "*".
--filter=<file>     Filters out tests that don't match the query.
--help              Prints this help.
```
These are all the libraries:
```
Summary …
```
=> chore(rslint_parser): support for multiple suites when bechmarking the parser

xtask/bench/src/libs-ts.txt
=> chore: fix TypeScript checker.ts link to be to raw file

crates/rome_lsp/src/handlers/formatting.rs
=> fix(lsp): minor logic bug with formatting with errors setting

Cargo.lock, crates/rome_analyze/Cargo.toml, crates/rome_lsp/Cargo.toml
This PR changes the tracing level when releasing for production
=> chore: change tracing level for prod

.github/workflows/release.yml, CONTRIBUTING.md, editors/vscode/package.json, editors/vscode/scripts/updateVersionForPrerelease.js, editors/vscode/scripts/updateVersionPrerelease.js
The job wasn't triggered, probably due to wrong  cheks
=> ci: change condition

website/package-lock.json, website/package.json, website/src/_includes/docs/philosophy.md, website/src/index.md
This PR restores the "Philosophy" section of the website and removes a bullet point from it.
Also, updated few libraries. 
None
=> chore(website): restore philosophy.md section and update packages

website/src/styles/_content.scss, website/src/styles/_fonts.scss, website/src/styles/index.scss
Fixes font not loading in blog and incorrect line-height on h1/h2 for mobile
=> fix(website): CSS bugs

.github/workflows/deploy_playground.yml
=> fix(playground): main not master branch

.github/workflows/deploy_playground.yml
Forgot to run `npm run build` before deploying. Also forgot to deploy to production environment.
=> fix(playground): More dumb fixes

CONTRIBUTING.md
This PR updates the "Getting Started" instructions and removes some outdated information.
=> docs(contributing): update getting started instructions

.github/workflows/bench_formatter.yml, .github/workflows/bench_parser.yml
Git is now failing checking out main (not what I've expected).
Let's try the action :D
Test in prod
=> chore: Fix benchmark CI take 2

.github/workflows/bench_formatter.yml, .github/workflows/bench_parser.yml
Don't clean the untracked files when checking out main or the PR benchmark results get deleted.
=> chore: fix benchmark part 3

crates/rome_cli/src/metrics.rs
The metrics measurement layer in the CLI makes use of the `std::time::Instant` to measure timings, that internally uses a platform-specific representation of time points on a high-resolution steady clock. This works well for doing precise measurements of timings but not so much for testing, and the tests for the metrics layer are currently failing on M1 Macs due to a lack of precision in the underlying representation.
This PR introduces a `Timepoint` trait private to the `metrics` module providing a generic abstraction over time measurements. It's implemented for `Instant` as well as `TestTime`, a newtype struct wrapping an integer and performing straightforward arithmetic operations over it, in order to guarantee reproducible results for the tests working with timings on all platforms.
=> fix(tests): use a platform-independent abstraction over time measurements in the CLI timings tests

crates/rome_rowan/src/cursor.rs
The current implementation of `last_token` iterates over the whole sub-tree to find the last token. This is problematic because `last_token` is called frequently inside the formatter:
* To determine if there's any trailing comment
* Inside `join_element` to determine the number of lines between two nodes.
This PR adds a `Direction` to `PreorderTraversal` and uses `Direction::Prev` to get the last token. This reduces the complexity from `O(nodes)` to `O(log(nodes))` (or `O(depth)` to be precise). The sole exception is if the last node is a node without any token (either a list or an array hole. It then is necessary to navigate one level up to the previous token. But that's still `O(log(nodes))`.
This significantly improves the formatter's performance:
```
group …
```
=> perf(rome_rowan): Refactor `last_token` to iterate from the back

.github/workflows/deploy_playground.yml
=> fix(playground): run npm build after wasm-pack

crates/rome_formatter/docs/implement_the_formatter.md
This PR adds two bullet points to help contributors to implement formatting.
[Rendered](https://github.com/rome/tools/blob/6b1853104e90e182a6c621b14fff6ea57d7a9065/crates/rome_formatter/docs/implement_the_formatter.md)
=> doc: add more suggestions around formatter

website/src/_includes/docs/status.md
Closes #2280 
This PR adds more information in the website about the language we support:
- added a small section about the support of the JS language
- added a small section about the support of the TS langauge
- updated the status of JSX formatting
Check the deployed site on cloudflare pages
=> website: add supported languages, updated status

website/src/_includes/layouts/base.liquid
This PR adds a link to our playground, right under the "Credits" section.
=> website: add a link to our playground

website/src/_includes/docs/formatter.md
This PR adds documentation about suppression comments for the formatter.
For the time being, I preferred to have a section under the formatter because it's the only tool we have. Once we will release multiple tools that will benefit from different suppression (lint, bundler, etc.), we can revisit it and have it inside a dedicated section.
Website
=> doc(website): add suppression explanation

CONTRIBUTING.md, crates/rome_formatter/docs/implement_the_formatter.md, crates/rome_js_parser/docs/write_tests.md, crates/rome_playground/README.md, crates/rome_playground/package-lock.json, crates/rome_playground/package.json, crates/rome_playground/postcss.config.js, crates/rome_playground/src/App.tsx, crates/rome_playground/src/IndentStyleSelect.tsx, crates/rome_playground/src/LineWidthInput.tsx, crates/rome_playground/src/SourceTypeSelect.tsx, crates/rome_playground/src/main.tsx, crates/rome_playground/src/types.ts, crates/rome_playground/tailwind.config.js, crates/rome_playground/vite.config.ts, crates/rome_playground/workers-site/index.js, website/src/_includes/docs/formatter.md
This PR
- moves some documentation of the parser inside its own `docs/` file, inside its crate;
- adds a new paragraph in the `CONTRIBUTING.md` where it points to the instructions of how to run the playground locally; 
- adds a small feature in the playground where the syntax highlighting changes based on the language;
Check the rendered markdown
=> docs: enhancements, add documentation for playground

website/src/_includes/docs/getting-started.md
This PR adds links to the binaries. The point to the latest version of binary, based on their architecture.
Test the deployed website
=> docs(website): add link to binaries

website/src/_includes/docs/formatter.md
=> chore(website): Grammar and style fixes

CHANGELOG.md, npm/rome/README.md, npm/rome/package.json
This PR:
- adds `CHANGELOG.md` to our repo
- adds `README.md` to the npm package
- adds `engines` and `license` to `package.json`
Check the wording of the files
=> chore: add CHANGELOG.md and README.md to npm

.github/ISSUE_TEMPLATE/config.yml, website/src/_includes/docs/getting-started.md
=> chore(website): Getting Started copy

Cargo.lock, crates/rome_playground/src/App.tsx, crates/rome_playground/src/SourceTypeSelect.tsx, crates/rome_playground/src/lib.rs, crates/rome_playground/src/types.ts
Closes #2338 
Choosing "Script" also resets TypeScript and JSX, making them disabled.
Checked locally that works
=> feat(rome_playground): add support for source type

crates/rome_js_parser/docs/authoring_parse_rules.md, crates/rome_js_parser/src/parser/parse_lists.rs, crates/rome_js_parser/src/syntax/class.rs, crates/rome_js_parser/src/syntax/expr.rs, crates/rome_js_parser/src/syntax/jsx/mod.rs, crates/rome_js_parser/src/syntax/module.rs, crates/rome_js_parser/src/syntax/object.rs, crates/rome_js_parser/src/syntax/stmt.rs, crates/rome_js_parser/src/syntax/typescript/statement.rs, crates/rome_js_parser/src/syntax/typescript/types.rs, rust-toolchain.toml
Changelog: https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html
Detailed Changelog: https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1600-2022-04-07
tldr: 
* LLVM 14
* `cargo --timings`
* `RUSTFLAGS="-C instrument-coverage" cargo build`
=> chore: Upgrade to Rust 1.60.0

.github/workflows/deploy_playground.yml, .github/workflows/deploy_playground_on_main.yml
=> fix: Outdated path crates/rome_playground -> website/playground

crates/rome_js_formatter/src/utils/binary_like_expression.rs
=> chore: Document binary like expression formatting

.github/workflows/deploy_playground.yml
Finally, finally getting the workflow to work. I removed the paths requirement entirely because it allowed me to test the workflow on this PR itself, and because I'm not really sure what was preventing the workflow from being run with other PRs.
=> ci(playground): Trying, yet again, to fix deploy_playground workflow trigger

CONTRIBUTING.md
Fixes a link in CONTRIBUTING.md and a code line punctuation mark mismatch.
=> docs: fix contributing link

crates/rome_js_parser/src/lexer/mod.rs
We are doing something dangerous, that was the cause of https://github.com/rome/tools/pull/2344.
When parsing the contents of string literals, regexes (https://english.stackexchange.com/questions/508834/what-is-the-plural-form-of-regex) and string templates; we normally do
```rust
while let Some(byte) = self.next_byte() {
...
}
```
This is dangerous because sometimes we check with an ```if```, if we are in a linebreak. Although the Unicode committee try to avoid ambiguity when creating Unicode chars, we fall into traps because we also use ```from_utf8_unchecked``` out of char boundaries.
An example is the ‍ Zero Width Joiner Unicode char (https://unicode-table.com/en/200D/) that caused the #2344 bug. Its bytes are ```E2 80 8D```, and  ```from_utf8_unchecked``` will return an ````\r```` …
=> feature(rome_js_parser): better handle of unicode for string literals, templates and regex

xtask/codegen/src/ast.rs
Change `-------------------Generating AST for {}-------------------` to 
`-------------------Generating Grammar for {}-------------------`
`cargo codegen grammar` not only generates `ast` facade, so change to `Grammar` would be more precise
run `cargo codegen grammar` should see 
```bash
-------------------Generating Grammar for json-------------------
```
=> chore(xtask): 🤖 fix typo

crates/rome_fs/src/fs/os.rs
This PR adds `.svn`, `.hg` and `.yarn`
No plan, it should work as is.
=> chore(rome_fs): add `svn`,  `hg` and `yarn` to ignored folders

Cargo.lock, crates/rome_js_formatter/Cargo.toml, crates/rome_js_formatter/src/ts/auxiliary/construct_signature_type_member.rs, crates/rome_js_formatter/tests/specs/prettier/typescript/as/as.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/comments/interface.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/comments/method_types.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/compiler/functionOverloadsOnGenericArity1.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/compiler/privacyGloImport.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/conformance/types/union/unionTypeConstructSignatures.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/custom/new/newKeyword.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/custom/typeParameters/callAndConstructSignatureLong.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/interface/ignore.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/new/new-signature.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/webhost/webtsc.ts.snap, crates/rome_js_formatter/tests/specs/ts/expression/type_member.ts.snap
Fixes #2419
Added a new test in our suite
=> fix(rome_js_formatter): add space after new token

editors/vscode/package-lock.json, editors/vscode/package.json
Update of the VScode version number
No plan
=> release(vscode): 0.6.0

.github/workflows/deploy_playground.yml, website/playground/src/App.tsx, website/playground/src/DesktopPlayground.tsx
When people currently try to open a PR from a fork, the deploy playground workflow fails. This disables that workflow for PRs from forks.
Tested by opening a PR for this branch on a fork
=> fix(ci): Deploy playground only on main Rome repo

website/playground/pnpm-lock.yaml
This PR fixes the current broken build. We upgraded `pnpm` but we forgot to update the lock file.
Merging it, it should fix the issue
=> fix(playground): update lock file

crates/rome_js_parser/Cargo.toml, crates/rome_js_syntax/Cargo.toml, crates/rome_json_syntax/Cargo.toml
Replace repository link from `rslint` to `rome` in `cargo.toml`
Note: keep the link in  `credits.md` unchanged, so I think it is alright.
None
=> fix(cargo.toml): 🐛 fix repo link

website/src/_includes/layouts/base.liquid
I figured we should have a link on our website
=> chore(website): Added careers link

website/playground/pnpm-lock.yaml, website/playground/src/DesktopPlayground.tsx, website/playground/src/MobilePlayground.tsx, website/playground/src/TreeView.tsx, website/playground/src/types.ts, website/playground/src/utils.ts
I found myself wanting to compare with how Prettier represents the code in their IR. Turns out Prettier smartly exposes a function that lets you convert code to their IR.
After the JSON serialization PR is merged, I'll move this to a React JSON View
Check out the playground link and play around with it
=> feature(playground): Prettier IR tab

website/playground/README.md, website/playground/src/App.tsx, website/playground/src/LineWidthInput.tsx, website/playground/src/lib.rs, website/playground/src/utils.ts
=> ci: 🎡 fix broken ci

.github/workflows/pull_request_js.yml, editors/vscode/scripts/updateVersionForPrerelease.mjs, editors/vscode/src/commands/syntaxTree.ts, editors/vscode/src/lsp_requests.ts, editors/vscode/src/main.ts, website/.eleventy.js, website/api/server.js, website/playground/package.json, website/playground/pnpm-lock.yaml, website/playground/src/App.tsx, website/playground/src/LineWidthInput.tsx, website/playground/src/SourceTypeSelect.tsx, website/playground/src/TreeView.tsx, website/playground/src/utils.ts, website/playground/vite.config.ts, website/playground/workers-site/index.js, website/src/_data/env.js, website/src/_includes/scripts/funding.js, website/src/_includes/scripts/index.js
Upgrade rome to 0.6.0 and reformat the playground and website files
CI?
=> chore: Reformat JS files with Rome 0.6.0

crates/rome_js_semantic/src/events.rs
1. fix typo
1. no need to test, I guess.
=> fix(rome_js_sematic): typo

crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/semantic_model.rs, crates/rome_js_semantic/src/tests/assertions.rs, crates/rome_js_semantic/src/tests/references.rs
This PR addresses all the comments of https://github.com/rome/tools/pull/2761.
=> feature(rome_js_semantic): more docs for semantic events

crates/rome_js_formatter/src/utils/format_conditional.rs, crates/rome_js_formatter/tests/spec_test.rs, crates/rome_js_parser/src/syntax/expr.rs, crates/rome_js_parser/src/tests.rs, crates/rome_js_semantic/src/tests/mod.rs, crates/rome_rowan/src/syntax/node.rs, rust-toolchain.toml, xtask/codegen/src/ast.rs, xtask/coverage/src/symbols/msts.rs, xtask/coverage/src/ts/ts_microsoft.rs
1. Upgrade toolchain to latest stable version1.62.0
2. https://blog.rust-lang.org/2022/06/30/Rust-1.62.0.html
3. Fix clippy
1. `cargo test` should pass.
2. Check if the clippy fix is correctly.
=> chore: upgrade toolchain to latest stable version 1.62.0

.github/workflows/pull_request_js.yml, editors/vscode/package-lock.json, editors/vscode/package.json, editors/vscode/src/commands/syntaxTree.ts, editors/vscode/src/main.ts, website/package.json, website/playground/package.json, website/playground/pnpm-lock.yaml, website/playground/src/App.tsx, website/playground/src/DesktopPlayground.tsx, website/playground/src/utils.ts, website/playground/tailwind.config.js, website/playground/vite.config.ts, website/playground/workers-site/index.js, website/pnpm-lock.yaml, website/src/_data/env.js, website/src/_includes/scripts/funding.js, website/src/_includes/scripts/index.js
This PR updates the files under the playground folder, by formatting them with the latest version of `rome`.
CI should pass
=> chore(playground): update formatting files

website/.eleventy.js, website/api/constants.js, website/api/server.js, website/package.json, website/playground/src/DesktopPlayground.tsx
Some files slipped from being formatted. This PR fixes the issue 
CI should pass
=> ci: format files outside `src` folder

website/playground/src/lib.rs
Work around the nuisance that Firefox returns undefined for ```performance.measure(...)```.
See: https://stackoverflow.com/questions/69666408/how-to-use-performance-measure-in-firefox
=> fix performance.measure returning undefined on firefox

crates/rome_js_analyze/src/semantic_analyzers/no_arguments.rs, website/src/docs/lint/rules/noArguments.md
1. Fix #2857 
1. check the generated markdown.
=> fix(rome_js_analyze): lint-rule-doc

npm/rome/README.md
This PR adds some badges to the `README.md` file, making it a little bit nicer and providing some useful information.
[Rendered](https://github.com/rome/tools/blob/dd07d82b7ff7ee17718a5315867ada3b74dfffb7/npm/rome/README.md)
=> chore: add badges to `README.md`

website/package.json, website/pnpm-lock.yaml
The `--parallel` command did something different from what I thought. I restored `npm-run-all`.
Tested locally and the command now works
=> chore(website): fix incorrect command

website/playground/src/DesktopPlayground.tsx
Tiny fix in the new playground, nothing major
=> fix(playground): correct placeholder

website/playground/package.json, website/playground/pnpm-lock.yaml
1. Downgrade `vite` to `2.9.5`
1. No need to test I guess, or you could run the code locally.
=> fix(playground): malformed prettier formating result

npm/rome/scripts/update-nightly-version.mjs
This PR remove the double quotes from the version number emitted in a nightly release
Merge it and trigger the workflow the next day
=> ci: remove double quotes from the version

.github/workflows/pull_request_js.yml
Now that we have nightly builds, we should use the `preview` of our action.
Merge it and rebase another PR. Unfortunately this workflow can't be manually triggered.
=> ci: using the preview version of `setup-rome`

website/src/styles/_content.scss
1. Tweak lint rule page UI, make the category more recognizable
1. See the screenshot or test locally
=> chore(website): Tweak lint rule page UI, make category more recognizable

editors/vscode/package-lock.json, editors/vscode/package.json, editors/vscode/scripts/updateVersionForPrerelease.mjs, website/api/server.js, website/package.json, website/pnpm-lock.yaml, website/src/_includes/scripts/funding.js
1. Update `rome` to `next` instead of `next-0.7.0`, keep the same as our CI
1. Pass all CI
=> fix(CI): broken format result

npm/rome/README.md, website/src/_includes/layouts/base.liquid
This PR adds a paragraph with a link to our technical documentation to the `README.md` file, as well as a link in our website.
Check the deployed versions
=> chore: add paragraph to our technical documentation

website/playground/src/lib.rs
1. Fix #2904 
1. The diagnostic should display the right result, and escape the tag that could cause xss attack.
=> fix(playground): potential xss attack

.cargo/config.toml, crates/rome_js_parser/src/lexer/mod.rs, crates/rome_js_parser/src/lib.rs, crates/rome_js_parser/src/lossless_tree_sink.rs, crates/rome_js_parser/src/parse.rs
This PR adds `rome_rowan` and `rome_js_parser` to the uploaded crates for our technical documentation.
I fixed some warning but I am not sure if they are correct
Merge and check the deployed result.
=> docs: adds `rome_rowan` and the `rome_js_parser` to the deployed crates

crates/rome_cli/src/commands/check.rs, crates/rome_cli/src/termination.rs, crates/rome_cli/src/traversal.rs, crates/rome_cli/tests/main.rs, crates/rome_diagnostics/src/lib.rs
This PR fixes the printing of a message and it sets the limit of printable diagnostics to a higher limit
=> fix(rome_cli): better printing of message

crates/rome_cli/src/commands/init.rs
The init message was awful, I changed a bit how it's written using `\n` and `\t`. It seems a little bit better now
=> chore: init message using newlines and tabs

editors/vscode/package-lock.json, editors/vscode/package.json
=> chore(vscode): upgrade dependencies

crates/rome_lsp/src/handlers/formatting.rs, crates/rome_lsp/tests/server.rs
This fixes a secondary issue outlined in #2953 where the editor would show an error when formatting a file with syntax errors if `format_with_errors` is disabled. While this is conceptually an error at the workspace level (the language server requests a formatted version of the document but the workspace cannot provided a response because the configuration forbids it), this error should not be propagated up to the user (since it's directly caused by an explicit user setting): instead the error is caught in the language server and an empty response is returned to the editor for the formatting request.
I added an additional test case in the LSP test suite verifying the server correctly returns `None` to a `textDocument/formatting` request if the document has syntax errors
=> fix(rome_lsp): silently ignore FormatWithErrorsDisabled errors in the language server

crates/rome_js_analyze/src/semantic_analyzers/js/use_camel_case.rs
Fixing a small issue that is breaking the build.
The project is not building. This PR fixes this.
=> fix(rome_js_analyze): fixing broken build

crates/rome_cli/tests/configs.rs, crates/rome_cli/tests/main.rs, crates/rome_service/src/configuration/javascript.rs
Fixes #2996 
Created a new test, using the same configuration of the issue.
=> fix(rome_service): inject defaults for missing globals

crates/rome_formatter/src/builders.rs, crates/rome_formatter/src/format_element.rs, crates/rome_formatter/src/printer/mod.rs
This PR adds an alignment `FormatElement` that allows explicitly aligning content by a specific amount of spaces rather than using `indent` that uses the configured indent string.
Aligning by an explicit number of spaces is e.g. needed when formatting conditional expressions where the content should be aligned to `"? "` and `: `.
Prettier's  `align` IR supports not only positive numbers but also 
* negative numbers (for dedenting)
* NEGATIVE_INFINITE: TO dedent to root
* strings: To use a specific indent string sequence other than spaces
I'll add the functionality once needed (NEGATIVE_INFINITE will be needed for template literals)
I added a new doc test that demonstrates the new IR element.
=> feat(rome_formatter): `Align` IR element

website/playground/package.json, website/playground/pnpm-lock.yaml, website/playground/src/DesktopPlayground.tsx, website/playground/workers-site/pnpm-lock.yaml
1. codemirror grammar formatter ir
1. Testing locally or see my preview video.
=> feat: 🎸 finish codemirror formatter ir

website/src/_includes/docs/philosophy.md
This PR restores the project management section of the website.
The section has been revisited to reflect the new open source philosophy, in line with how the private company and the staff team works.
=> chore(website): add project management section

crates/rome_cli/tests/snapshots/downgrade_severity.snap, crates/rome_cli/tests/snapshots/should_disable_a_rule.snap, crates/rome_service/src/configuration/linter/rules.rs, xtask/codegen/src/generate_configuration.rs
Updates snapshot from my last PR
CI should pass
=> ci: update snapshots

crates/rome_js_parser/src/lexer/mod.rs
1. Refactor `lexer.rs` lexing regular expression, using a `bitflags` to represent regex flag instead of 7 boolean variables.
Reducing memory usage from 7 bytes to 1 byte.
1. All CI should pass.
=> refactor(rome_js_parser): refactor regex flag

crates/rome_analyze/src/visitor.rs, crates/rome_cli/tests/snap_test.rs, crates/rome_diagnostics/src/diagnostic.rs, crates/rome_formatter/src/builders.rs, crates/rome_formatter/src/lib.rs, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/tests/spec_tests.rs, crates/rome_js_formatter/src/js/auxiliary/case_clause.rs, crates/rome_rowan/src/green/node.rs, crates/rome_rowan/src/green/token.rs, crates/rome_rowan/src/syntax/trivia.rs, crates/rome_rowan/src/utility_types.rs, rust-toolchain.toml, xtask/coverage/src/lib.rs
1. The latest stable rust-toolchain has been released, see https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html
2. Fixing some lint errors introduced by this upgrade.
1. CI should pass.
=> chore: update rust-toolchain to 1.63.0

crates/rome_service/src/configuration/javascript.rs, editors/vscode/configuration_schema.json
Just fixed `as-needed` to `asNeeded` in comment.
Sorry, my mistake. (#3065)
The CI should not fail
=> fix(rome_service): the property for config should be camelCase

.github/workflows/release_cli.yml
The packaging of WASM bindings is currently failing: https://github.com/rome/tools/runs/7963483695?check_suite_focus=true
This PR should fix the workflow.
I should be able to dispatch the workflow manually. And if so, it should not fail
=> ci: fix path for WASM artifacts

website/src/_includes/docs/project-config.md
This PR adds a small paragraph that explains how to opt-in a rule that is not recommended.
Uploaded website should render
=> docs(website): turn a rule on

crates/rome_formatter/src/lib.rs, crates/rome_formatter/src/printer/mod.rs
This PR improves the formatters performance by only adding unique source markers inside the printer and adding `take_*` methods to take the source markers to avoid the need to copy all markers to a new vec.
`cargo test`. I added a new unit test for mapped markers in #3092 that verifies that only unique markers are added (and are mapped to the right location)
=> perf(rome_formatter): Improve Printer source map performance

editors/vscode/package-lock.json, editors/vscode/package.json, npm/backend-jsonrpc/package.json, npm/backend-jsonrpc/pnpm-lock.yaml, npm/rome/package.json, npm/rome/pnpm-lock.yaml, website/playground/package.json, website/playground/pnpm-lock.yaml, website/playground/src/romeWorker.ts, website/playground/tsconfig.json
This aligns all our internal npm projects to use the same version of TypeScript
The CI should pass
=> chore: use same typescript version across the board

CHANGELOG.md, CONTRIBUTING.md, crates/rome_cli/src/commands/help.rs, crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs, editors/vscode/package.json, npm/rome/package.json, website/src/_includes/docs/architecture.md, website/src/_includes/docs/cli-commands.md, website/src/_includes/docs/cli.md, website/src/_includes/docs/formatter.md, website/src/_includes/docs/linter.md, website/src/_includes/docs/project-config.md, website/src/docs/lint/rules/noUnusedVariables.md, website/src/index.md, xtask/lintdoc/src/main.rs
Closes #2991 
Rendered [changelog](https://github.com/rome/tools/blob/release/0.9.0/CHANGELOG.md).
Rendered website.
=> release: 0.9.0

website/.eleventy.js, website/package.json, website/pnpm-lock.yaml, website/src/blog/feed.liquid
This PR adds a simple RSS feed to the website. The only issue I found it that we are not able to actually put the whole content of a blog post due to some malformed HTML. 
As alternative, I put the description inside the content
The rendered website should create a new `/feed.xml` page
=> chore(website): add RSS feed

website/src/_includes/docs/linter.md
Closes https://github.com/rome/tools/issues/3164
=> docs(website): add section to explain how fixes work

xtask/bench/src/features/formatter.rs
Remove an unnecessary clippy macro
Current CI
=> chore: removes clippy macro, not needed

crates/rome_cli/src/commands/help.rs, website/src/_includes/docs/formatter.md
It just threw me off while reading CLI help 👼
=> docs: fix typo in formatter help section

website/src/_includes/docs/status.md
This PR updates the support section
=> chore(website): update status section

CHANGELOG.md, npm/rome/package.json
=> release: 0.9.2

Cargo.lock, crates/rome_cli/Cargo.toml, crates/rome_cli/src/termination.rs, crates/rome_cli/tests/snap_test.rs
`command_exe` during the testing phase is something like `main-HASH`. 
Before I added `cfg_if` inside the function, but it's not ideal. I have now removed and did a string replace inside the logic of the snapshot. It's much better like this.
CI should pass
=> test: refactor function name

npm/rome/tests/daemon/formatContent.test.mjs, npm/rome/tests/daemon/formatFiles.test.mjs
This PR refactors the Node.js API tests of the daemon. Creating a new instance of the daemon for each test has its toll, because it requires to spawn a new server and then tear it down.
This PR makes sure to use just one for all the tests
No change in logic, current tests should pass
=> test(npm): create only one instance of `Rome`

website/src/_includes/docs/project-config.md
From last release we forgot to remove from the website the second `rules` field. This PR removes from the website
=> docs(website): update the configuration rules

website/src/credits.md
=> chore(website): add inspiration section

crates/rome_formatter/src/printer/mod.rs
This PR fixes an issue where the printer panics if group ids aren't written to the document in the same order as they have been created because `resize` shrinks a vector if its size exceeds the argument.
I added a new printer test verifying that the printer no longer panics if group ids aren't added in the same order as they have been created with `f.group_id`.
=> fix(rome_formatter): Panic for out of order group id

website/src/docs/lint/rules/noAsyncPromiseExecutor.md, website/src/docs/lint/rules/noUnusedVariables.md, xtask/lintdoc/src/main.rs
Fix PR adds a newline at the end of the lists.
Check https://github.com/rome/tools/pull/3235 for more information
Check the emitted markdown
=> docs(website): add newline

.github/workflows/stale.yml
This change should tell the bot to not close stale issues/PRs.
Merge it and see if it works
=> ci: don't close stale issues/PRs

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/react.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_useless_fragments.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_fragment_syntax.rs, crates/rome_js_analyze/tests/specs/nursery/useFragmentSyntax.jsx, crates/rome_js_analyze/tests/specs/nursery/useFragmentSyntax.jsx.snap, crates/rome_js_syntax/src/jsx_ext.rs, crates/rome_rowan/src/ast/batch.rs, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/useFragmentSyntax.md
Closes #2712 
Added some test case
=> feat(rome_js_analyzer): rule `useFragmentSyntax`

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/react.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_array_index_key.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_children_prop.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_dangerously_set_inner_html.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_void_elements_with_children.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs, crates/rome_js_analyze/tests/specs/nursery/noArrayIndexKey.jsx, crates/rome_js_analyze/tests/specs/nursery/noArrayIndexKey.jsx.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/noArrayIndexKey.md
Closes https://github.com/rome/tools/issues/3292
Added test cases to catch all the possible combinations
=> feat(rome_js_analyzer): rule `noArrayIndex`

website/playground/src/DesktopPlayground.tsx
This PR removes the red text set for the div that contains the code. This was incorrectly showing the colours of our diagnostics, which are already coloured.
Check the new playground
=> chore(playground): remove red text

Cargo.lock, Cargo.toml, crates/rome_analyze/Cargo.toml, crates/rome_cli/Cargo.toml, crates/rome_formatter/Cargo.toml, crates/rome_fs/Cargo.toml, crates/rome_js_analyze/Cargo.toml, crates/rome_js_formatter/Cargo.toml, crates/rome_js_parser/Cargo.toml, crates/rome_lsp/Cargo.toml, crates/rome_rowan/Cargo.toml, crates/rome_service/Cargo.toml, xtask/bench/Cargo.toml, xtask/coverage/Cargo.toml
This PR takes advantage of the new [workspace dependencies](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table) and moves crates that we use most across the workspace in one in single place.
The current CI should pass
=> chore: use cargo workspace dependencies

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_restricted_globals.rs, crates/rome_js_analyze/tests/specs/nursery/noRestrictedGlobals.js, crates/rome_js_analyze/tests/specs/nursery/noRestrictedGlobals.js.snap, crates/rome_js_semantic/src/semantic_model.rs, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/noRestrictedGlobals.md
Closes #3341 
Closes #2978 
Added some test case
=> feat(rome_js_analyze): new rule `noRestrictedGlobals`

CHANGELOG.md, editors/vscode/package.json, npm/rome/package.json
Patch release.
The changelog should highlight only the hotfixes.
Proof-read
=> release: 0.10.1

website/.eleventy.js, website/package.json, website/src/_includes/docs/project-config.md, website/src/docs/lint/rules/index.md, xtask/lintdoc/src/main.rs
Small chore for the website:
- better wording for the `Nursery` group
- added anchor link for titles of the rules
- finally added the version at the footer of the website
- updated an outdated section of the website
Check the deployed website
=> docs(website): small QoL for rules page

crates/rome_cli/src/commands/daemon.rs, crates/rome_cli/src/service/mod.rs
Fixes #3414
This PR adds special handling for the `rome/shutdown` command in the `SocketTransport` to make it gracefully handle the connection being immediately terminated by the server on reception of the shutdown request.
Unfortunately this area of the CLI is hard to test since the tests would need to actually start and stop a daemon instance on the host system. Additionally in this case since the read and write tasks write their error directly to `stderr` (since they cannot share access to the `Console` object) it wouldn't be possible for the tests to ensure that nothing was printed to the output.
Instead I simply ran the `rome start` and `rome stop` commands in sequence to ensure it never printed an error message (I ran this a few times to make sure it couldn't be triggered randomly …
=> fix(rome_cli): prevent the socket transport from printing an error on shutdown

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_explicit_any.rs, crates/rome_js_analyze/tests/specs/nursery/noExplicitAny/invalidClass.ts, crates/rome_js_analyze/tests/specs/nursery/noExplicitAny/invalidClass.ts.snap, crates/rome_js_analyze/tests/specs/nursery/noExplicitAny/invalidFunction.ts, crates/rome_js_analyze/tests/specs/nursery/noExplicitAny/invalidFunction.ts.snap, crates/rome_js_analyze/tests/specs/nursery/noExplicitAny/invalidTypeAndInterface.ts, crates/rome_js_analyze/tests/specs/nursery/noExplicitAny/invalidTypeAndInterface.ts.snap, crates/rome_js_analyze/tests/specs/nursery/noExplicitAny/invalidVariable.ts, crates/rome_js_analyze/tests/specs/nursery/noExplicitAny/invalidVariable.ts.snap, crates/rome_js_analyze/tests/specs/nursery/noExplicitAny/valid.ts, crates/rome_js_analyze/tests/specs/nursery/noExplicitAny/valid.ts.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/noExplicitAny.md
=> feat(rome_js_analyze): new rule `noExplicitAny`

crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/noPositiveTabindex.md
=> fix(docs): set correct version for NoPositiveTabindex rule

crates/rome_service/src/configuration/linter/rules.rs
=> ci: fix codegen

crates/rome_js_analyze/src/analyzers/nursery/use_anchor_content.rs, website/src/docs/lint/rules/useAnchorContent.md
Another issue not caught by me, apologies. This one is sneaky because netlifly doesn't deploy the website from PRs of external contributors. 
Not sure why, but that particular markdown can't be parsed by our website. I had this issue before myself.
The website should deploy now
=> ci: non-parsable markdown

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_const_assign.rs, crates/rome_js_analyze/tests/specs/nursery/noConstAssign.js, crates/rome_js_analyze/tests/specs/nursery/noConstAssign.js.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, rome.json, website/playground/src/romeWorker.ts, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/noConstAssign.md
Closes #3362 
I thought that the entity of the work to implement this rule was bigger. I also checked the `eslint` implementation, and it's in line with ours.
Added some cases, please let me know if you have more cases that we should add.
=> feat(rome_js_analyze): rule `noConstAssign`

.github/workflows/release_js_api.yml, npm/js-api/package.json
The workflow to package `@rometools/js-api` was failing. The PR should apply the correct changes to fix the bug
Manually dispatch the workflow
=> ci(js-api): compile backends

website/playground/package.json, website/playground/pnpm-lock.yaml, website/playground/src/DesktopPlayground.tsx, website/playground/src/MobilePlayground.tsx
I noticed slowness in the playground code input when typing fast, and checking the CodeMirror repository, [they suggest](https://github.com/uiwjs/react-codemirror/blob/b2341d3f8fb94345cbb759382870d81c61606812/core/README.md?plain=1#L182-L185) wrapping the extensions with `useMemo` hook to avoid that.
I also bumped all dependencies without breaking changes.
| Current | After |
| --------| ------|
| <video src="https://user-images.githubusercontent.com/11046907/197338933-7c94bec3-9c20-46d8-a17b-d6b8322e3a27.mov"/>|<video src="https://user-images.githubusercontent.com/11046907/197339103-183d892c-9aaa-474e-8954-6e645a25d682.mov"/>|
=> chore(playground): reduce CodeMirror input slowness

crates/rome_cli/tests/commands/format.rs, crates/rome_cli/tests/snapshots/main_commands_format/applies_custom_trailing_comma.snap, crates/rome_cli/tests/snapshots/main_commands_format/trailing_comma_parse_errors.snap
Fix https://github.com/rome/tools/pull/3474#pullrequestreview-1152678021
`cargo test -p rome_cli`
=> test(rome_cli): trailing comma cli tests

crates/rome_js_analyze/src/analyzers/correctness/use_simplified_logic_expression.rs, crates/rome_js_analyze/src/analyzers/style/no_negation_else.rs, crates/rome_js_analyze/tests/specs/correctness/useSimplifiedLogicExpression.js, crates/rome_js_analyze/tests/specs/correctness/useSimplifiedLogicExpression.js.snap, crates/rome_js_analyze/tests/specs/style/noNegationElse/issue_3141.js, crates/rome_js_analyze/tests/specs/style/noNegationElse/issue_3141.js.snap, website/src/docs/lint/rules/useSimplifiedLogicExpression.md
Closes https://github.com/rome/tools/issues/3454
I run this rule in the Rome classic code base this case popped up all over the place, for cases that were all valid. We should not consider these cases as errors.
Moved the previous test case as valid
=> fix(rome_js_analyze): remove double negation check

.github/ISSUE_TEMPLATE/01_bug.yml
It updates the label of the bug type
N/A
=> chore: update issue template

website/src/_includes/scripts/index.js
I requested a new search from algolia and configured our search crawler. I still need to figure out how to give other members of the team access to the crawler and search configuration
Searching for `noDang` shows search results
=> fix(website): Search

editors/vscode/package.json, editors/vscode/src/commands/index.ts, editors/vscode/src/main.ts
Closes #3524
https://user-images.githubusercontent.com/11046907/198582133-cc61345e-ed8a-4d1c-91f2-88b5280db41e.mov
=> feat(editors): add Restart LSP Server command

crates/rome_analyze/CONTRIBUTING.md, crates/rome_js_formatter/src/lib.rs
fix crate name, invalid links, etc in linter and formatter docs.
=> docs: update formatter and linter docs

CHANGELOG.md, editors/vscode/package-lock.json, editors/vscode/package.json, npm/js-api/package.json, npm/rome/package.json
[Rendered changelog](https://github.com/rome/tools/blob/release/v10.0.1/CHANGELOG.md#1001)
N/A
=> release: v10.0.1

crates/rome_js_parser/src/syntax/class.rs, crates/rome_js_parser/test_data/inline/err/super_expression_in_constructor_parameter_list.js, crates/rome_js_parser/test_data/inline/err/super_expression_in_constructor_parameter_list.rast, crates/rome_js_parser/test_data/inline/ok/super_expression_in_constructor_parameter_list.js, crates/rome_js_parser/test_data/inline/ok/super_expression_in_constructor_parameter_list.rast
Fix https://github.com/rome/tools/issues/3613
`cargo test`
=> fix(rome_js_parser): Allow super in constructor parameter #3613

.github/CODEOWNERS
I added myself to some crates
N/A
=> chore: add @ematipico to some crates

editors/vscode/package.json
Closes https://github.com/rome/tools/issues/3701
Merge it and publish a new release (nightly)
=> chore: remove preview from VSCode extension

.github/ISSUE_TEMPLATE/01_bug.yml, .github/workflows/stale.yml
Closes https://github.com/rome/tools/issues/3753
N/A
=> ci: change stable bot wording

website/src/pages/internals/language_support.mdx
Closes https://github.com/rome/tools/issues/3631
I added the version of TS that we support. Let me know if it's wrong.
=> docs(website): add language support page

crates/rome_rowan/src/ast/batch.rs
Remove `dbg!` macro call in `batch.rs`
NA
=> chore: remove dbg

crates/rome_js_parser/src/syntax/stmt.rs, crates/rome_js_parser/test_data/inline/ok/async_continue_stmt.js, crates/rome_js_parser/test_data/inline/ok/async_continue_stmt.rast
Fix https://github.com/rome/tools/issues/3612
`cargo test -p rome_js_parser`
=> fix(rome_js_parser): async label #3612

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/analyzers/nursery.rs, crates/rome_js_analyze/src/analyzers/nursery/no_empty_interface.rs, crates/rome_js_analyze/tests/specs/nursery/noEmptyInterface/invalid.ts, crates/rome_js_analyze/tests/specs/nursery/noEmptyInterface/invalid.ts.snap, crates/rome_js_analyze/tests/specs/nursery/noEmptyInterface/valid.ts, crates/rome_js_analyze/tests/specs/nursery/noEmptyInterface/valid.ts.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noEmptyInterface.md
Implement [no-empty-interface](https://typescript-eslint.io/rules/no-empty-interface)
Unit tests
=> feat(rome_js_analyze): add noEmptyInterface rule

website/src/playground/PlaygroundLoader.tsx, website/src/playground/utils.ts
=> feat(website): Throttle playground URL update

crates/rome_analyze/src/diagnostics.rs, crates/rome_analyze/src/rule.rs, crates/rome_analyze/src/signals.rs
This PR removes `FileId` from `AnalyzerDiagnostic`. It also fixes a few snapshots containing invalid syntax.
Current CI should pass
=> chore(rome_analyze): remove `FileId` from diagnostics

benchmark/package-lock.json, website/package.json, website/pnpm-lock.yaml
Upgrade Prettier on Playground and benchmark
=> chore: Upgrade Prettier

Cargo.lock, crates/rome_analyze/Cargo.toml, crates/rome_console/Cargo.toml, crates/rome_js_formatter/Cargo.toml, crates/rome_json_formatter/Cargo.toml, crates/rome_lsp/Cargo.toml, crates/rome_wasm/Cargo.toml, xtask/codegen/Cargo.toml
=> chore: Remove unused dependencies

crates/rome_fs/src/fs/memory.rs
This PR adds a read-only mode for the `MemoryFileSystem`, intended to help with the testing in #3851 by avoiding the need to introduce additional tests relying on the `OsFileSystem` in the CLI test suite.
I've added a new test case to check the read-only filesystem reports the correct error when files are open with write access
=> feat(rome_fs): implement a read-only mode for MemoryFileSystem

.cargo/config.toml, .github/workflows/main.yml, .github/workflows/pull_request.yml
This PR updates the `lint` alias to reflect the same commands we use in CI
N/A
=> chore: update lint alias

editors/vscode/src/main.ts
This change improves the logging and error messaging surrounding connection errors to the server process, to help with debugging issues like #3933 that are hard to reproduce as they don't generate enough information to narrow down the bug.
This change should pass typechecking, besides that I've tested locally that the name of the server pipe is correctly being logged
=> fix(vscode): improve the logging of connection errors

editors/vscode/package-lock.json, editors/vscode/package.json, npm/js-api/package.json
Fixes incorrect version for VSCode and the JS API packages
=> chore: correctly bump extension version

website/src/pages/configuration.mdx
Adds default value for `indentSize`
Verify default added to docs: http://localhost:3000/configuration#formatterindentsize
=> docs: Add default for indentSize

website/src/pages/configuration.mdx
=> docs: fix typo in configuration.mdx

crates/rome_js_analyze/src/analyzers/suspicious/no_explicit_any.rs, crates/rome_js_analyze/tests/specs/suspicious/noExplicitAny/invalidClass.ts.snap, crates/rome_js_analyze/tests/specs/suspicious/noExplicitAny/invalidFunction.ts.snap, crates/rome_js_analyze/tests/specs/suspicious/noExplicitAny/invalidTypeAndInterface.ts.snap, crates/rome_js_analyze/tests/specs/suspicious/noExplicitAny/invalidVariable.ts.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noExplicitAny.md
This PR improves diagnostic and docs for `noExplicitAny`
Snapshot updated.
=> docs(noExplicitAny): add a diagnostic note and info in docs

crates/rome_analyze/CONTRIBUTING.md
This PR fixes and improves the CONTRIBUTING docs for custom visitor.
=> docs(rome_analyze): complete custom visitor example

crates/rome_analyze/CONTRIBUTING.md
=> docs(rome_analyze): fix typos and improve docs

website/src/pages/linter/index.mdx
This PR fixes rules' categories, simplifies some sentences, uses shorter sentences, and makes several improvements (e.g. one sentence by line for easy diffs).
=> docs(linter): minor fixes and improvements

website/src/pages/linter/index.mdx
update the linter cli options
In online website:
https://docs.rome.tools/linter/#use-the-linter-via-cli
In the latest rome cli version:
=> docs(rome_linter): fix the linter cli options

.github/workflows/pull_request.yml, crates/rome_cli/tests/snap_test.rs, crates/rome_service/src/configuration/linter/rules.rs, website/src/pages/lint/rules/noSelfAssignment.md
- fixed some issues around paths in the snapshots;
- updates the documentation for a new merged lint rule;
- updates the way `nextest` is installed;
CI should pass. 
In my previous commits, I created a new workflow just for windows to check if my fix works.
=> ci: run test on windows

crates/rome_js_analyze/src/analyzers/complexity/use_optional_chain.rs, crates/rome_js_analyze/tests/specs/complexity/useOptionalChain/logicalAndCases6.js, crates/rome_js_analyze/tests/specs/complexity/useOptionalChain/logicalAndCases6.js.snap, crates/rome_js_analyze/tests/specs/complexity/useOptionalChain/validCases.ts, crates/rome_js_analyze/tests/specs/complexity/useOptionalChain/validCases.ts.snap, crates/rome_js_syntax/src/expr_ext.rs
=> fix(useOptionalChain): ignore expr ending with a bin expr

crates/rome_diagnostics/src/error.rs, rust-toolchain.toml
Upgrades rust to `1.67.1`. Fixed an issue around diagnostics.
CI
=> chore: toolchain upgrade

crates/rome_js_analyze/src/semantic_analyzers/suspicious/no_catch_assign.rs, crates/rome_js_analyze/tests/specs/suspicious/noCatchAssign.js.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noCatchAssign.md
Improve  `noCatchAssign` docs.
No change.
=> docs(rome_js_analyze): improve `noCatchAssign` docs

Cargo.lock, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json
Run `cargo update` to remove vulnerabilities and update dependencies
Current CI should pass
=> chore: update dependencies

rust-toolchain.toml
Upgrade rust to 1.68.0
CI should pass
=> chore: upgrade toolchain to 1.68.0

CONTRIBUTING.md
Tiny fixes for `CONTIRUBUTING.md` 
I think we use astro.build, and pnpm currently.
=> chore: update website info on CONTRIBUTING.md

crates/rome_js_analyze/src/analyzers/correctness/no_unnecessary_continue.rs, crates/rome_js_analyze/tests/specs/correctness/noUnnecessaryContinue.js, crates/rome_js_analyze/tests/specs/correctness/noUnnecessaryContinue.js.snap
Fix #4314.
Regression test included.
No change.
=> fix(rome_js_analyze): keep comments `noUnnecessaryContinue`

website/src/pages/configuration.mdx
Updated the `configuration.mdx` to fix a typo.
Not applicable
=> Fix typo in configuration.mdx

editors/vscode/README.md
=> docs(vscode): document quick fix action 

.github/workflows/main.yml
This PR is follow-up for #4389.
=> chore: suppress support longpaths steps in ubuntu-latest

.editorconfig, crates/rome_cli/src/vcs.rs, crates/rome_service/src/configuration/formatter.rs, crates/rome_service/src/configuration/javascript.rs, crates/rome_service/src/configuration/linter/mod.rs, crates/rome_service/src/configuration/mod.rs, crates/rome_service/src/configuration/organize_imports.rs, crates/rome_service/src/configuration/parse/json/files.rs, crates/rome_service/src/configuration/parse/json/formatter.rs, crates/rome_service/src/configuration/parse/json/javascript.rs, crates/rome_service/src/configuration/parse/json/linter.rs, crates/rome_service/src/configuration/parse/json/organize_imports.rs, crates/rome_service/src/configuration/string_set.rs, crates/rome_service/src/lib.rs, crates/rome_service/src/settings.rs, editors/vscode/configuration_schema.json, justfile, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json
=> chore: create newtype for string sets

.github/workflows/main.yml, .github/workflows/pull_request.yml
=> ci: fix build action

.github/workflows/pull_request.yml
=> ci: use latest os for tests

.github/workflows/main.yml
The action was throwing errors
Tests should run now
=> ci: fix binary names

CHANGELOG.md, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/snapshots/main_commands_check/should_not_disable_recommended_rules_for_a_group.snap, crates/rome_service/src/configuration/linter/rules.rs, xtask/codegen/src/generate_configuration.rs
I think I finally go it right! 
We were excluding disabled and enabled rules from each other, instead, they should be two separate checks.
With this change, there are no regressions and fixes https://github.com/rome/tools/issues/4502
Added test case
=> fix(rome_service): rules to disable and enable

crates/rome_cli/tests/snapshots/main_commands_lsp_proxy/lsp_proxy_help.snap
Closes https://github.com/rome/tools/issues/4505
By mistake, I pushed the fix here https://github.com/rome/tools/commit/763508aa1fe26c434d8576e4b013e85e858ac9fb directly on `main`. My bad.
This PR updates the snapshot test I forgot to update.
=> chore: update snapshot

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/rome_cli/src/cli_options.rs, crates/rome_cli/tests/snapshots/main_commands_check/check_help.snap, crates/rome_cli/tests/snapshots/main_commands_ci/ci_help.snap, crates/rome_cli/tests/snapshots/main_commands_format/format_help.snap, crates/rome_cli/tests/snapshots/main_commands_init/init_help.snap, crates/rome_cli/tests/snapshots/main_commands_lsp_proxy/lsp_proxy_help.snap, crates/rome_cli/tests/snapshots/main_commands_migrate/migrate_help.snap, crates/rome_service/src/configuration/formatter.rs, crates/rome_service/src/configuration/mod.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json
Upgrade `bpaf`, which contains some fixes and enhancements.
Updated the snapshots
=> chore: upgrade `bpaf`

CHANGELOG.md
=> fix(docs): fix typo in lint rule name

website/src/pages/cli.mdx
This adds documentation for ROME_BINARY
=> docs: Add documentation for ROME_BINARY

CHANGELOG.md, crates/rome_cli/src/cli_options.rs, crates/rome_cli/src/execute/traverse.rs, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/commands/ci.rs, crates/rome_cli/tests/commands/format.rs, crates/rome_cli/tests/snapshots/main_commands_check/check_help.snap, crates/rome_cli/tests/snapshots/main_commands_check/doesnt_error_if_no_files_were_processed.snap, crates/rome_cli/tests/snapshots/main_commands_ci/ci_help.snap, crates/rome_cli/tests/snapshots/main_commands_ci/doesnt_error_if_no_files_were_processed.snap, crates/rome_cli/tests/snapshots/main_commands_format/doesnt_error_if_no_files_were_processed.snap, crates/rome_cli/tests/snapshots/main_commands_format/format_help.snap, crates/rome_cli/tests/snapshots/main_commands_lsp_proxy/lsp_proxy_help.snap, crates/rome_cli/tests/snapshots/main_commands_migrate/migrate_help.snap
Closes https://github.com/rome/tools/issues/4621
The implementation was relatively straightforward, with no particular things to add. 
Added a test case for each relevant command
=> feat(rome_cli): add `--no-errors-on-unmatched` optoin

Cargo.lock, crates/rome_aria_metadata/Cargo.toml, crates/rome_diagnostics_macros/Cargo.toml, crates/rome_markup/Cargo.toml, crates/tests_macros/Cargo.toml, xtask/codegen/Cargo.toml
https://github.com/rust-lang/rust/issues/113152
=> fix: Regression building proc-macro2 1.0.59 with nightly

CHANGELOG.md, crates/rome_js_analyze/tests/specs/correctness/noUnusedVariables/validExport.ts, crates/rome_js_analyze/tests/specs/correctness/noUnusedVariables/validExport.ts.snap, crates/rome_js_semantic/src/events.rs
Fix a part of #4688
I update snapshot tests
=> fix(rome_js_analtzer): semantic analyzer handles ts export declaration clause correctly

Cargo.lock, crates/rome_analyze/src/categories.rs, crates/rome_analyze/src/rule.rs, crates/rome_analyze/src/services.rs, crates/rome_analyze/src/signals.rs, crates/rome_js_formatter/src/utils/string_utils.rs, crates/rome_js_syntax/Cargo.toml, crates/rome_js_transform/Cargo.toml, crates/rome_js_transform/src/declare_transformation.rs, crates/rome_js_transform/src/lib.rs, crates/rome_js_transform/src/registry.rs, crates/rome_js_transform/src/transformers/mod.rs, crates/rome_js_transform/src/transformers/ts_enum.rs, crates/rome_parser/src/lib.rs, crates/rome_rowan/src/file_source.rs, npm/backend-jsonrpc/src/workspace.ts
Foundation of the transformer
I will create the testing suite in the next PR
=> feat: transformations

website/src/pages/cli.mdx, xtask/codegen/src/generate_website.rs
Revert `cli.mdx` because it contains features that haven't been released yet.
Manually checked that `cargo codegen-website` doesn't update the file.
=> chore: revert the `cli.mdx`

editors/vscode/package.json
=> chore: revert VSCode extension

npm/rome/README.md
=> docs(README): announcing Biome

npm/rome/README.md
=> fix(README): fix link
