rome/tools

rust-toolchain.toml
Release blog: https://blog.rust-lang.org/2022/05/19/Rust-1.61.0.html
tldr: https://twitter.com/m_ou_se/status/1527413077632765965
=> chore: Upgrade to Rust 1.61.0

crates/rome_formatter/src/format_element.rs, crates/rome_formatter/src/macros.rs, crates/rome_formatter/src/prelude.rs, crates/rome_formatter/src/printer/mod.rs, crates/rome_formatter/src/printer/printer_options/mod.rs, crates/rome_js_formatter/src/options.rs
This PR introduces the new IR element `BestFitting`. The IR matches Prettier's `ConditionalGroupContent`. This IR can be useful if the best representation depends on the available space. `BestFitting` defers the choice of how to print the element to the printer by providing multiple variants. The printer picks the element that best fits given the circumstances (that's where its name is coming from but I'm open to better names).
The printer picks the first variant that fits on the current line and falls back to print the last variant in expanded mode if no variant fits.
Part of #2579
I added an integration test as part of the documentation of the `best_fitting` function.
=> feature(formatter): Add `BestFitting` IR element

.gitignore, website/.gitignore
https://github.com/rome/tools/pull/2596 removed a `package-lock.json` file from the website folder which caused confusion, and https://github.com/rome/tools/pull/2574 added a `report.md` file which shouldn't be committed. This PR adds both of those files to `.gitignore` to make sure they do not get added to the repo accidentally.
Verified that these two files don't show up in git any longer.
=> fix(repo): Update .gitignore.

crates/rome_js_formatter/src/js/statements/do_while_statement.rs, crates/rome_js_formatter/src/js/statements/empty_statement.rs, crates/rome_js_formatter/src/js/statements/if_statement.rs, crates/rome_js_formatter/tests/specs/js/module/statement/do_while.js, crates/rome_js_formatter/tests/specs/js/module/statement/do_while.js.snap, crates/rome_js_formatter/tests/specs/js/module/statement/if_else.js, crates/rome_js_formatter/tests/specs/js/module/statement/if_else.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/empty-statement/body.js.snap
Closes #2448
I cherry-picked the implementation of the former PR, which aligns its behaviour to prettier. 
The PR changes how `if/else` and `do/while` statements are formatted where the body is an empty statement, by matching Prettier's behaviour:
```js
// before
if(a); else ;
// now
if (a);
else;
```
New tests to cover the case
=> fix(rome_js_formatter): empty statements in `if/else` and `do/while`

crates/rome_rowan/src/cursor/node.rs, crates/rome_rowan/src/cursor/token.rs, crates/rome_rowan/src/cursor/trivia.rs
Hand write the traversal of `next_token` and `prev_token` to speedup the traversal.
The new comment formatting will make heavy use of these two methods which is why it's important that they are fast.
```
❯ critcmp main fused
group                                    PR                                  main
-----                                    -----                                  ----
formatter/checker.ts                     1.00    239.2±1.22ms    10.9 MB/sec    1.01    240.8±3.49ms    10.8 MB/sec
formatter/compiler.js                    1.00    139.6±3.00ms     7.5 MB/sec    1.04    145.4±1.99ms     7.2 MB/sec
formatter/d3.min.js                      1.00    104.7±1.04ms     2.5 MB/sec    1.04    108.9±2.69ms     2.4 MB/sec
formatter/dojo.js                        1.00 …
```
=> perf(rowan): Speedup `next_token` and `prev_token` implementations

Cargo.lock, crates/rome_cli/src/commands/help.rs, crates/rome_cli/src/lib.rs, crates/rome_console/Cargo.toml, crates/rome_console/src/lib.rs, crates/rome_js_formatter/tests/spec_test.rs, crates/rome_service/src/lib.rs
This PR disables the formatting of markup in the console output when:
- The CLI is called with the `--no-colors` argument
- The standard output stream is not a Unix TTY / Windows Console handle (checked with the `atty` crate)
- The `TERM=dumb` or `NO_COLOR` environment variables are defined
Additionally I also took the opportunity to update the CLI help to use Markup
=> feat(rome_cli): disable markup formatting when unsupported

Cargo.lock, crates/rome_js_parser/src/lib.rs, crates/rome_js_parser/src/symbols.rs, xtask/coverage/Cargo.toml, xtask/coverage/src/lib.rs, xtask/coverage/src/main.rs, xtask/coverage/src/symbols/mod.rs, xtask/coverage/src/symbols/msts.rs, xtask/coverage/src/symbols/utils.rs
see https://github.com/rome/tools/issues/2488
This PR parses Microsoft/ts .symbols file;
We are running only files without any errors.
```
symbols/msts: Ran 5946 tests in 19.05s
┌───────────┬────────┬────────┬────────┬──────────┐
│ Tests ran │ Passed │ Failed │ Panics │ Coverage │
├───────────┼────────┼────────┼────────┼──────────┤
│      5946 │   1613 │   4328 │      5 │    27.13 │
└───────────┴────────┴────────┴────────┴──────────┘
```
All ```parse_*``` functions are simplified versions of ```nom```, just to avoid including another crate.
```Symbol``` and ```symbols``` are fake and only exist to make the coverage test to compile and run.
=> feature(rome_js_parser): coverage test suite for ts symbols file

crates/rome_js_formatter/tests/specs/prettier/js/comments/html-like/comment.js.snap, crates/rome_js_parser/src/syntax/expr.rs, crates/rome_js_parser/src/syntax/jsx/jsx_parse_errors.rs, crates/rome_js_parser/src/syntax/jsx/mod.rs, crates/rome_js_parser/src/syntax/typescript/ts_parse_error.rs, crates/rome_js_parser/test_data/inline/err/ts_type_assertions_not_valid_at_new_expr.rast
Reverts #2508 because `parse_any_jsx_tag` returns `Absent` even when it parsed out the opening element and the tags content.
PR #2508 added a checkpoint in the parse binary expression to rewind if that happens but not to any other call sites of the function. Parsing a tag with an incomplete JSX child then gets skipped by the parser because the parse list assumes that it reached the end.
PR #2508 mentions that it fixes a bug when parsing `let a = <number> undefined`. I haven't been able to reproduce this issue except if JSX is enabled but type assertions aren't valid in TS when JSX is enabled.
=> fix(parser): Fix JSX parser dropping content

crates/rome_js_formatter/src/formatter.rs
…ivia
The trailing trivia of the previous token can never contain a new line. Any new line is always part of the current tokens leading trivia, thus, this check is not necessary
`cargo test`
=> perf(formatter): Remove `prev_token` traversal from format leading trivia

crates/rome_js_formatter/src/utils/member_chain/flatten_item.rs, crates/rome_js_formatter/src/utils/member_chain/groups.rs, crates/rome_js_formatter/src/utils/member_chain/mod.rs
This PR refactors the member chain formatting into two stages:
* Building the member chain groups
* Formatting the groups
Doing so allows us to format the elements in left-to-right order.
`cargo test`
=> refactor(formatter): Member chain: left to right formatting

crates/rome_js_formatter/src/utils/binary_like_expression.rs
Refactors the binary like expression formatting to lazily write the expressions rather than allocating vectors with the sub results. 
The basic idea remains the same. The implementation flattens an expression. What's different to before is that this is now a two-stage process:
1. Flatten the binary expression  and specify for each "part" how it should be formatted (left, right, or a group)
2. Format the flattened expressions 
I think this also improves readability because it makes it clear what concepts exist in this algorithm (left hand side, right hand side, and a sub-group). 
`cargo test`
=> refactor(formatter): Change binary like expression to format left to right

CHANGELOG.md, crates/rome_analyze/src/analyzers/no_double_equals.rs, crates/rome_analyze/src/analyzers/use_while.rs, crates/rome_analyze/tests/specs/noDoubleEquals.js.snap, crates/rome_analyze/tests/specs/useWhile.js.snap, crates/rome_cli/tests/main.rs, editors/vscode/package-lock.json, editors/vscode/package.json, npm/rome/package.json, website/src/_includes/docs/ci.md, website/src/_includes/docs/formatter.md, website/src/_includes/docs/linter.md, website/src/index.md
Closes #2506 
I excluded `--no-colors` because we don't didn't document it yet and I don't want to rush into things.
Sections are now separated by tool. We might want to review the sections in the future (together with the CLI and the global arguments, but **not in this PR**).
Check the deployed website and it's correct
=> release: 0.6.0

crates/rome_analyze/src/signals.rs, crates/rome_formatter/src/printed_tokens.rs, crates/rome_js_formatter/src/builders.rs, crates/rome_js_formatter/src/utils/mod.rs, crates/rome_js_parser/src/parse.rs, crates/rome_js_parser/src/tests.rs, crates/rome_js_semantic/src/tests/events.rs, crates/rome_js_semantic/src/tests/scopes.rs, crates/rome_rowan/src/cursor/node.rs, crates/rome_rowan/src/syntax.rs, crates/rome_rowan/src/syntax/node.rs, crates/rome_rowan/src/syntax_node_text.rs
This PR fixes #2657 by modifying the `find_diff_range` function (used internally by the analyzer to calculate the modified range of a code action) to calculate the end of the range by comparing tokens from the end of the tree back towards the start until a mismatching token is found.
In order to support this, an additional `direction` parameter has been added to the `descendants_tokens`, `descendants_with_tokens` and `preorder_with_tokens` methods of `SyntaxNode` to allow callers to create reverse-order iterators.
I preferred this over implementing `DoubleEndedIterator` for the `PreorderWithTokens` iterator since the backward-iteration mechanism already existed, while it would have been impractical to support both forward and backward iteration at the same time due how the syntax tree …
=> fix(rome_analyze): fix the find_diff_range function

crates/rome_formatter/src/lib.rs, crates/rome_js_formatter/src/builders.rs, crates/rome_js_formatter/src/js/lists/variable_declarator_list.rs, crates/rome_js_formatter/src/separated.rs
Rename `MissingRequiredChild` to `SyntaxError` to account for other syntax errors, for example, when a rest element has a trailing comma.
`cargo test`
=> refactor(formatter): Rename `FormatError::MissingRequiredChild` to `SyntaxError`

crates/rome_formatter/src/lib.rs
Deletes the unsupported language and capability disabled errors as they are no longer used.
`cargo test`
=> chore(rome_formatter): remove unused `FormatError` variants

crates/rome_formatter/src/macros.rs, crates/rome_formatter/src/printer/mod.rs
This is a minimal fix for the `BestFitting` element that was broken by #2645. It now attempts to fit the first variant in flat mode on a single line. If that doesn't fit, it continues attempting the remaining variants in `PrintMode::Expanded` before defaulting to the `most_expanded` variant. This seems to match the original intention based on the doc comments for the `best_fitting` macro. @MichaReiser?
I don't know if this will be sufficient for our needs, but I believe that matching the exact behavior of Prettier's `conditionalGroup` could involve heavy enough changes to our "fits" measurement and printing that it may be worth trying this out first.
Happy to close this, though, if we'd rather go with a different approach.
Removed the `ignore` from the broken `best_fitting` doc test.
=> fix(rome_formatter): measure first variant of BestFitting in flat mode

crates/rome_js_formatter/src/builders.rs, crates/rome_rowan/src/syntax/trivia.rs
This removes the need to take a snapshot before formatting leading trivia by collecting the comments into a `Vec`. The performance characteristics of the new implementation should be similar to the old because it removes the need to allocate a temporary `VecBuffer` to be able to reverse the written comments in the end. 
I find this solution slightly easier to reason about and results in slightly less code: 
Before:
*  3.5%  10.9% 422.4KiB rome_js_formatter
*  0.1%   0.4%   9.7KiB rome_js_formatter <rome_js_formatter::builders::FormatLeadingTrivia as rome_formatter::Format<rome_js_formatter::context::JsFormatContext>>::fmt
After:
*  3.3%  10.6% 407.1KiB rome_js_formatter
* `FormatLeadingTrivia` no longer shows up. 
It also gives us the option to use a `SmallVec` to store comments if …
=> refactor(rome_js_formatter): avoid snapshot when formatting skipped token trivia

crates/rome_analyze/src/analyzers/no_delete.rs, crates/rome_analyze/src/analyzers/no_double_equals.rs, crates/rome_analyze/src/analyzers/use_single_var_declarator.rs, crates/rome_analyze/src/analyzers/use_while.rs, crates/rome_analyze/src/assists/flip_bin_exp.rs, crates/rome_analyze/src/lib.rs, crates/rome_analyze/src/registry.rs, crates/rome_analyze/src/signals.rs, crates/rome_analyze/tests/spec_tests.rs, crates/rome_css_syntax/src/syntax_node.rs, crates/rome_js_syntax/src/syntax_node.rs, crates/rome_json_syntax/src/syntax_node.rs, crates/rome_lsp/src/utils.rs, crates/rome_rowan/src/raw_language.rs, crates/rome_rowan/src/syntax.rs, crates/rome_service/src/file_handlers/javascript.rs, crates/rome_service/src/file_handlers/mod.rs, crates/rome_service/src/workspace.rs, crates/rome_service/src/workspace/server.rs
This PR is part of the general goal of making the analyzer language-agnostic. It adds a `Root` associated type on the `Language` trait in `rome_rowan` bound to the `AstNode<Language = Self>` trait (as well as `Clone`, `Debug` and `Eq` for convenience) and corresponding to the "document root" node type for this language (eg. `JsAnyRoot` for JavaScript).
This lets most of the analyzer be agnostic over the language it's processing, except at the root level in the `analyze` function since the `RuleRegistry` only has a factory for JS rules at the moment. As an extension of this, the `Workspace` also only supports emitting code actions strongly typed to the JavaScript language for now.
=> feat(rome_rowan): add the root node as an associated type on the language trait

crates/rome_js_formatter/src/utils/binary_like_expression.rs, crates/rome_rowan/src/lib.rs, crates/rome_rowan/src/macros.rs
This PR add a new `declare_union` for creating union AST nodes scoped to a local module, without having to add them to `js.ungram` and `rome_js_syntax`. Its usage looks like the following example:
```rust
declare_union! {
/// Documentation
#[allow(dead_code)]
pub(crate) UnionName = NodeType | OtherNodeType
}
```
The resulting union type is an enum with a variant for each node type in the union and implementing:
- the `AstNode` trait
- the `Debug` and `Display` traits
- the `Clone`, `PartialEq`, `Eq` and `Hash` traits with derive
- the `From` trait for each variants
- the `Into` trait for `SyntaxNode` and `SyntaxElement`
The macro is designed to fail to compile when the union would contain node types from different languages, as the `AstNode` trait must have a single `Language` associated …
=> feat(rome_rowan): add a `declare_union` macro for one-off union AstNodes

crates/rome_analyze/src/signals.rs
This PR fixes #2693 by ensuring the start and end of the range returned by `find_diff_range` do not cross. This can happen if the only difference between the previous and new syntax trees are removed tokens: the results of the linear search for the start and end of the range will cross as the new range starts at the start of the new different token from the start of the tree, and ends at the end of the first different token from the end of the tree. In the case of a removal these will be the first token after the removal, and last token before the removal respectively.
I added a new `diff_range_remove` test to verify this case is handled correctly
=> fix(rome_analyze):  handle find_diff_range in case tokens were only removed

crates/rome_analyze/src/analyzers.rs, crates/rome_analyze/src/analyzers/use_single_case_statement.rs, crates/rome_analyze/src/registry.rs, crates/rome_analyze/tests/specs/useSingleCaseStatement.js, crates/rome_analyze/tests/specs/useSingleCaseStatement.js.snap
This adds the [useSingleCaseStatement](https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/js/useSingleCaseStatement.md) rule back after it was removed in the analyzer refactor
I added a snapshot test for the rule reusing the examples for the rule from Rome JS
=> feat(rome_analyze): implement the useSingleCaseStatement rule

crates/rome_analyze/src/signals.rs
In #2694 I implemented a simplified solution (clamping the resulting range) to prevent the end of the diff range from crossing the start of the range when calculating the diff of a token removal operation. Unfortunately this solution isn't entirely correct and can result in mismatches between the two ranges (due to the clamping being applied to the new range independently from the original range)
With this PR I implemented a fix that completely removes the root cause of the issue by preventing the search for the endpoint of the modified range from crossing the start of the range in the first place, eliminating the need for the clamping operation on the resulting index
Fixes #2696 
I also fixed the `diff_range_remove` test case, it turns out I made a mistake when calculating the values the …
=> fix(rome_analyze): prevent the range end search of find_diff_range from crossing the start of the range

crates/rome_rowan/src/ast/mod.rs, crates/rome_rowan/src/cursor/node.rs, crates/rome_rowan/src/raw_language.rs, crates/rome_rowan/src/syntax/node.rs
This PR adds the ability to consume an `AstSeparatedList` from the back by implementing `DoubleEndedIterator`.
The reason why I implemented this is because there have been cases where I needed to retrieve the last elements of a list. This will be useful, for example, inside the formatter when implementing the formatting of call arguments.
Checking a separated list from the back adds a bit more of complexity because the **last** separator is not mandatory, which means that we should handle cases where this is not an error. 
In order to achieve that, I had to make the slots peekable, because sometimes we don't want to consume two slots. An example is when we have `[1, separator, 3, separator, 5]`. We want to consume only `5` in the first iteration, but then we want to consume `separator` …
=> feat(rome_rowan): implement `DoubleEndedIterator` for node lists

crates/rome_analyze/src/analyzers/no_compare_neg_zero.rs, crates/rome_analyze/src/analyzers/no_delete.rs, crates/rome_analyze/src/analyzers/no_double_equals.rs, crates/rome_analyze/src/analyzers/no_negation_else.rs, crates/rome_analyze/src/analyzers/use_single_case_statement.rs, crates/rome_analyze/src/analyzers/use_single_var_declarator.rs, crates/rome_analyze/src/analyzers/use_valid_typeof.rs, crates/rome_analyze/src/analyzers/use_while.rs, crates/rome_analyze/src/registry.rs, crates/rome_analyze/src/signals.rs, crates/rome_analyze/tests/specs/noCompareNegZero.js.snap, crates/rome_analyze/tests/specs/noDelete.js.snap, crates/rome_analyze/tests/specs/noDoubleEquals.js.snap, crates/rome_analyze/tests/specs/noNegationElse.js.snap, crates/rome_analyze/tests/specs/useSingleCaseStatement.js.snap, crates/rome_analyze/tests/specs/useSingleVarDeclarator.js.snap, crates/rome_analyze/tests/specs/useValidTypeof.js.snap, crates/rome_analyze/tests/specs/useWhile.js.snap, crates/rome_diagnostics/src/diagnostic.rs, crates/rome_diagnostics/src/emit.rs, crates/rome_diagnostics/src/lib.rs, crates/rome_lsp/src/utils.rs
This PR replicates the builder pattern implemented on `rome_diagnostic::Diagnostic` for the `RuleDiagnostic` type used internally by the analyzer rules. It should expose all the capabilities of normal diagnostics (including multiple labels and footers) with the notable exception of:
- `file_id`: at the moment diagnostics are considered to belong to the file currently being analyzed
- `code`: this property has its value set to the name of the rule that emitted the diagnostic
- `suggestions`: rules that emit quick fix suggestions are expected to do so by emitting a code action
Additionally, it adds a new optional `summary` field to diagnostics containing a plain-text description of the issue, aimed at rendering contexts that don't support rich formatting (such as diagnostic popovers in …
=> feat(rome_analyze): improve the diagnostics builder in the analyzer

crates/rome_analyze/tests/specs/flipBinExp.js, crates/rome_analyze/tests/specs/flipBinExp.js.snap, crates/rome_js_parser/src/lexer/mod.rs, crates/rome_js_parser/src/syntax/jsx/mod.rs, crates/rome_js_parser/test_data/inline/err/jsx_or_type_assertion.js, crates/rome_js_parser/test_data/inline/err/jsx_or_type_assertion.rast, crates/rome_js_syntax/src/source_type.rs
Addresses #2625. Because TypeScript allows JSX in `.js` files by default, we allow the same. Also makes adoption easier because many users have React components in a `.js` file.
The existing tests for JSX should suffice.
=> feature(rome_js_parser): JSX support in .js files

crates/rome_formatter/src/buffer.rs, crates/rome_formatter/src/macros.rs, crates/rome_js_formatter/src/builders.rs
This PR ensures that the `buffer` argument of `dbg_write!` is compatible with the `buffer` argument of `write!` so that the two can be swapped without any changes to the debugged code.
The current implementation hasn't been compatible because the `dbg_write!` macro called into `Inspect::new` that expected a `&mut Buffer` which requires the use of `&mut buffer` if an implementation uses a local `Buffer` variable.
This PR changes the macro implementation to use `Buffer.inspect` instead that works for any mutable `Buffer`.
I changed the `dbg_write` macro test to pass in `buffer` without `&mut`.
=> fix(rome_formatter): `dbg_write` API compatibility with `write`

crates/rome_js_semantic/src/tests/assertions.rs
Some tools seems to display ```dbg!(...)``` even when tests succeed (clion is an example). So this PR removes all printing of tests.
=> fix(rome_js_semantic): remove dbg from semantic tests

crates/rome_js_analyze/src/analyzers/no_unused_template_literal.rs
1. use `make::js_string_literal` instead construct a `SyntaxToken` by hand
1. cargo test
=> refactor(rome_js_analyze): use `js_string_literal` helper function

Cargo.lock, crates/rome_formatter/Cargo.toml, crates/rome_formatter/src/buffer.rs, crates/rome_formatter/src/builders.rs, crates/rome_formatter/src/lib.rs, crates/rome_formatter/src/token.rs, crates/rome_js_formatter/src/builders.rs, crates/rome_js_formatter/src/js/any/function.rs, crates/rome_js_formatter/src/js/expressions/static_member_expression.rs, crates/rome_js_formatter/src/js/expressions/string_literal_expression.rs, crates/rome_js_formatter/src/js/expressions/unary_expression.rs, crates/rome_js_formatter/src/js/statements/if_statement.rs, crates/rome_js_formatter/src/js/statements/return_statement.rs, crates/rome_js_formatter/src/prelude.rs, crates/rome_js_formatter/src/ts/types/union_type.rs, crates/rome_js_formatter/src/utils/binary_like_expression.rs, crates/rome_js_formatter/tests/specs/js/module/comments.js, crates/rome_js_formatter/tests/specs/js/module/comments.js.snap
This PR replaces the usages of `split_trivia` where it is used to move the leading and trailing trivia of a "to be parenthesised" expression with `format_parenthesize` that manually formats the leading / trailing comments as part of the parentheses. 
```javascript
/* leading */ "string" /* trailing */;
// Becomes
/* leading */ ("string") /* trailing */;
```
Formatting the comments of the content as part of the parentheses requires a way to signal to the formatter that these comments have already been formatted and that it shouldn't format the comments again when formatting the `"string"` token. This is done by storing the "manually" formatted comments inside of the `FormatState` and checking for every comment if the comment has already been formatted. 
The advantage of this approach is …
=> refactor(rome_js_formatter): Introduce `format_parenthesize`

crates/rome_js_analyze/src/analyzers.rs, crates/rome_js_analyze/src/analyzers/no_multiple_spaces_in_regular_expression_literals.rs, crates/rome_js_analyze/src/registry.rs, crates/rome_js_analyze/tests/specs/noMultipleSpacesInRegularExpressionLiterals.js, crates/rome_js_analyze/tests/specs/noMultipleSpacesInRegularExpressionLiterals.js.snap
1. Resolved https://github.com/rome/tools/issues/2716
1. cargo test
=> feat(rome_js_analyze):noMultipleSpacesInRegularExpressionLiterals

crates/rome_formatter/src/builders.rs, crates/rome_formatter/src/format_element.rs, crates/rome_formatter/src/format_extensions.rs, crates/rome_formatter/src/printer/mod.rs
Introduces a new reference-counted `FormatElement`. Useful for situations where the same content is part of the resulting IR twice but with different parent formatting. To this point, it has been necessary to clone the whole sub-tree. The ref counted FormatElement on the other hand only requires bumping the ref count. 
`cargo test`
=> refactor(rome_formatter): Add `Interned` `FormatElement`

crates/rome_formatter/src/arguments.rs, crates/rome_formatter/src/builders.rs, crates/rome_formatter/src/format_element.rs, crates/rome_formatter/src/format_extensions.rs, crates/rome_formatter/src/lib.rs, crates/rome_formatter/src/printer/mod.rs, crates/rome_formatter/src/token.rs
It's necessary to move leading comments outside a group to prevent that the comments expand the enclosing group:
```javascript
/* a comment */
[1]
```
The `/* a comment */` belongs to the `[` group token that is part of a group wrapping the whole `[1]` expression. It's important that the comment `/* a comment */` gets moved out of the group element to avoid the `[1]` group expanding because of the line break inserted by the comment.
The `group_elements` implementation so far used `split_trivia` to accomplish this. This PR changes `group_elements` to use a custom buffer that splits the leading trivia while it's being written. 
I decided to change Group to store a Box<[FormatElement]> to avoid boxing List elements.
`cargo test`
=> refactor(rome_formatter): `GroupElementsBuffer`

crates/rome_js_formatter/src/js/expressions/assignment_expression.rs, crates/rome_js_formatter/src/js/objects/property_object_member.rs, crates/rome_js_formatter/src/lib.rs, crates/rome_js_formatter/src/utils/assignment_like.rs, crates/rome_js_formatter/src/utils/binary_like_expression.rs, crates/rome_js_formatter/tests/specs/js/module/assignment/assignment.js, crates/rome_js_formatter/tests/specs/js/module/assignment/assignment.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/assignment-expression/assignment_expression.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/assignment/chain-two-segments.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/assignment/chain.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/assignment/issue-1966.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/assignment/issue-3819.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/babel-plugins/import-meta.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/logical-assignment/logical-assignment.js.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/as/assignment2.ts.snap
This PR closes #2416 
This PR adds `Chain` and `ChainTail` to the list of layouts and implements them. I left out on purpose `ChainTailArrowFunction` to not add too code, mostly because this PR moves code around and it might cause some confusion.
I moved the implementation of `write_assignment_like` inside the `format` function of `JsAnyAssignmentLike` for two important reasons:
- I needed access to `JsAnyAssignmentLike` variants in order to understand whether a group should be added or not;
- I needed access to the parent of `JsAnyAssignmentLike`, which was needed for the implementation of the new layout;
I also moved few functions inside the struct itself, because they needed to be exposed. The only loose function is used else where, so I kept there. 
I created two new tests for the new …
=> feat(rome_js_formatter): assignment expressions with layout

.gitignore, crates/rome_js_formatter/tests/prettier_tests.rs
part of https://github.com/rome/tools/issues/2555
To achieve printing diff between `main` branch and pull request branch,  a few steps we need to do list below
1. save `prettier compatibility metric` on `main`  branch 
2. switch to `pull request branch` 
3. save `prettier compatibility metric` on `pull request`  branch
4. compare two metrics and echo the diff.
Obviously, `Markdown`  is not a good format for comparing, so we need to add an extra format to save metrics, which is `Json` 
just like `Parser conformance`
This pull request introduces these two changes:
1. Add an option to report the prettier compatibility metric in `json` or `markdown` format.
2. Support choosing file_name to save.
No need to test
=> test(rome_js_formatter): support report prettier metric as a json file

crates/rome_js_formatter/src/js/any/class.rs, crates/rome_js_formatter/src/js/classes/extends_clause.rs, crates/rome_js_formatter/src/js/declarations/class_declaration.rs, crates/rome_js_formatter/src/js/declarations/class_export_default_declaration.rs, crates/rome_js_formatter/src/js/expressions/class_expression.rs, crates/rome_js_formatter/src/separated.rs, crates/rome_js_formatter/src/ts/auxiliary/implements_clause.rs, crates/rome_js_formatter/src/ts/lists/type_argument_list.rs, crates/rome_js_formatter/src/ts/lists/type_list.rs, crates/rome_js_formatter/src/utils/format_class.rs, crates/rome_js_formatter/src/utils/mod.rs, crates/rome_js_formatter/tests/specs/prettier/js/class-comment/superclass.js.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/class-comment/class-implements.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/class-comment/declare.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/class-comment/generic.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/class/extends_implements.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/classes/break-heritage.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/classes/break.ts.snap, crates/rome_js_formatter/tests/specs/ts/class/implements_clause.ts.snap, xtask/codegen/src/formatter.rs
This PR brings Rome's class formatting closer to Prettier's.
Manually verified the output of each updated snapshot test with prettier's to make sure they match (except for comment positioning)
**Before**:
File Based Average Prettier Similarity: 74.79%
Line Based Average Prettier Similarity: 69.89%
**After**:
File Based Average Prettier Similarity: 74.99%
Line Based Average Prettier Similarity: 70.40%
=> feature(rome_js_formatter): Class formatting (including heritage)

crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/tests/assertions.rs, crates/rome_js_semantic/src/tests/references.rs
This PR is the part that matches declarations and scopes of the main PR (https://github.com/rome/tools/pull/2489).
For more details: https://github.com/rome/tools/issues/2488
This PR implements hoisting.
We decided that the event extraction will not generate diagnostics. This will be a task to whoever read these events.
This PR also contains renaming some functions that did not enter in the last PR.
=> feature(rome_js_semantic): Hoisting

crates/rome_js_formatter/src/js/expressions/call_arguments.rs, crates/rome_js_formatter/src/js/lists/constructor_parameter_list.rs, crates/rome_js_formatter/src/lib.rs, crates/rome_js_formatter/tests/specs/js/module/class/class.js, crates/rome_js_formatter/tests/specs/js/module/class/class.js.snap, crates/rome_js_formatter/tests/specs/ts/call_expression.ts, crates/rome_js_formatter/tests/specs/ts/call_expression.ts.snap
This PR fixes #2756
It checks if the last argument is not a rest operator. And if so, it doesn't add the trailing separator.
FYI, I copied the exact same check we have in `parameters_list.rs`
Added two new tests, one for TS and one for JS
=> fix(rome_js_formatter): don't add trailing operator on rest arguments

crates/rome_js_formatter/src/js/bindings/object_binding_pattern_property.rs, crates/rome_js_formatter/src/js/classes/constructor_class_member.rs, crates/rome_js_formatter/src/js/classes/getter_class_member.rs, crates/rome_js_formatter/src/js/classes/method_class_member.rs, crates/rome_js_formatter/src/js/classes/property_class_member.rs, crates/rome_js_formatter/src/js/classes/setter_class_member.rs, crates/rome_js_formatter/src/js/objects/literal_member_name.rs, crates/rome_js_formatter/src/ts/auxiliary/property_signature_type_member.rs, crates/rome_js_formatter/src/ts/classes/method_signature_class_member.rs, crates/rome_js_formatter/src/utils/mod.rs
This PR deletes `FormatMemberName` because:
a) It doesn't call into the nodes formatting logic and, therefore, doesn't respect "rome ignore" comments
b) The `JsLiteralMemberName` formatter already takes care of normalizing the member name
`cargo test`
=> refactor(rome_js_formatter): Delete `FormatMemberName`

crates/rome_js_formatter/tests/prettier_tests.rs
1.  Moving the overall metrics back to the top.
1. No need to test, I guess?
=> chore: Move Prettier compat metrics to the top

crates/rome_js_formatter/src/js/expressions/call_arguments.rs, crates/rome_js_formatter/src/js/lists/call_argument_list.rs, crates/rome_js_formatter/src/js/lists/object_assignment_pattern_property_list.rs, crates/rome_js_formatter/src/js/lists/object_binding_pattern_property_list.rs, crates/rome_js_formatter/src/js/lists/parameter_list.rs, crates/rome_js_formatter/src/js/module/named_import_specifier.rs, crates/rome_js_formatter/src/separated.rs, crates/rome_js_formatter/src/ts/lists/enum_member_list.rs, crates/rome_js_formatter/src/ts/lists/tuple_type_element_list.rs, crates/rome_js_formatter/src/ts/lists/type_argument_list.rs, crates/rome_js_formatter/src/ts/lists/type_list.rs, crates/rome_js_formatter/src/ts/lists/type_parameter_list.rs, crates/rome_js_formatter/tests/specs/prettier/js/comments/export-and-import.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/import/comments.js.snap
`format_separated` used to group all elements by default. This is often undesired and also comes with a performance cost (printer needs to test if the elements fit).
This PR changes the default of `format_separated` so that it doesn't group the elements except if enabled explicitly using `nodes_grouped`.
This PR further fixes the formatting of named import specifiers to more closely match Prettier's formatting.
`cargo test` and I compared the snapshot changes with Prettier to make sure they match.
=> refactor(rome_js_formatter): Remove unnecessary groups from `format_separated`

crates/rome_js_formatter/src/ts/bindings/type_parameters.rs, crates/rome_js_formatter/src/ts/classes/extends_clause.rs, crates/rome_js_formatter/src/ts/declarations/interface_declaration.rs, crates/rome_js_formatter/tests/specs/prettier/typescript/interface/comments-generic.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/interface/generic.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/interface/long-extends.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/interface2/break.ts, crates/rome_js_formatter/tests/specs/prettier/typescript/interface2/break.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/interface2/comments-declare.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/interface2/comments.ts.snap, crates/rome_js_formatter/tests/specs/ts/declaration/interface.ts.snap
This PR improves the formatting of TS interface declarations. 
> **Note**: ~~There's an unresolved stability issue around formatting comments which will require #2768 to be resolved~~
Verified the updated snapshots manually and compared them with prettier
**File Based Average Prettier Similarity**: 76.01%  -> 76.26%  
**Line Based Average Prettier Similarity**: 70.85%  -> 71.23%
=> feature(rome_js_formatter): TS Interface formatting

crates/rome_js_formatter/src/check_reformat.rs, crates/rome_js_formatter/src/context.rs, crates/rome_js_formatter/src/lib.rs, crates/rome_js_formatter/src/utils/assignment_like.rs, crates/rome_js_formatter/src/utils/member_chain/flatten_item.rs, crates/rome_js_formatter/src/utils/member_chain/groups.rs, crates/rome_js_formatter/src/utils/member_chain/mod.rs, crates/rome_js_formatter/src/utils/string_utils.rs, crates/rome_js_formatter/tests/check_reformat.rs, crates/rome_js_formatter/tests/prettier_tests.rs, crates/rome_js_formatter/tests/spec_test.rs, crates/rome_service/src/file_handlers/javascript.rs, website/playground/src/lib.rs
Remove the `Copy` from `JsFormatContext` to allow storing non-copyable data in the context. The idea is to store the extracted comments as an `Rc<Comments>` but this isn't possible today because `Rc` (nor `Comments`) implements `Copy`.
The rust compiler is so kind to point me towards all places where we now need to call `clone` (only in tests).
=> refactor(rome_js_formatter): Remove `Copy` from `JsFormatContext`

crates/rome_analyze/src/lib.rs, crates/rome_analyze/src/registry.rs, crates/rome_css_syntax/src/generated/nodes.rs, crates/rome_js_analyze/src/analyzers/no_negation_else.rs, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/src/registry.rs, crates/rome_js_syntax/src/generated/nodes.rs, crates/rome_json_syntax/src/generated/nodes.rs, crates/rome_rowan/src/ast/mod.rs, crates/rome_rowan/src/green.rs, crates/rome_rowan/src/macros.rs, crates/rome_rowan/src/raw_language.rs, xtask/codegen/src/generate_analyzer.rs, xtask/codegen/src/generate_nodes.rs, xtask/lintdoc/src/main.rs
This PR adds a new `KIND_SET` associated constant to the `AstNode`, representing the set of `SyntaxKind` values that can be cast into this node (the `can_cast` function would return true for these values). This allows code to statically list out all node types that match a certain node type, to optimize query matching in the analyzer for instance.
This code uses the new feature to list the variants of `JsSyntaxKind` that can be cast into `JsAnyRoot`:
```rust
let root_kinds: Vec<_> = JsAnyRoot::KIND_SET.iter().collect();
assert_eq!(root_kinds.as_slice(), &[
JsSyntaxKind::JS_MODULE,
JsSyntaxKind::JS_SCRIPT,
JsSyntaxKind::JS_EXPRESSION_SNIPPED,
]);
```
This is mostly a codegen change, and with most operations on `SyntaxKindSet` being `const` almost all these operations are checked at compile …
=> feat(rome_rowan): expose the kind of AstNode as a constant

crates/rome_js_formatter/src/js/classes/property_class_member.rs, crates/rome_js_formatter/src/ts/classes/property_signature_class_member.rs, crates/rome_js_formatter/src/utils/assignment_like.rs, crates/rome_js_formatter/src/utils/object.rs, crates/rome_js_formatter/tests/specs/prettier/js/class-comment/class-property.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/classes-private-fields/with_comments.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/classes/property.js.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/assignment/issue-2485.ts.snap
This adds `TsPropertySignatureClassMember` and `JsPropertyClassMember` to be formatted as "assignment like"
This PR implements https://github.com/rome/tools/issues/2424
The next fix on the table would be to finish up certain conditions to trigger the correct layout, but with this PR, we completed the number of nodes that require this type of formatting.
Made sure that the updated snapshots are correct
PR 
**File Based Average Prettier Similarity**: 77.22%  
**Line Based Average Prettier Similarity**: 72.43%  
`main`
**File Based Average Prettier Similarity**: 77.16%  
**Line Based Average Prettier Similarity**: 72.41%
=> feat(rome_js_formatter): class property members as assignment like

Cargo.lock, crates/rome_analyze/Cargo.toml, crates/rome_analyze/src/query.rs, crates/rome_analyze/src/registry.rs, crates/rome_analyze/src/syntax.rs, crates/rome_control_flow/Cargo.toml, crates/rome_control_flow/src/builder.rs, crates/rome_control_flow/src/lib.rs
This PR adds a new `rome_control_flow` containing the data structures needed to represent a control flow graph, as well as associated helpers for building such a graph.
The control flow graph is an auxiliary data structure to the syntax tree representing the execution order of statements and expressions in the function as a graph of "basic blocks" comprised of a flattened list of instruction. There are currently 3 kind of instructions: `Statement` denotes the execution of a certain syntax node that may have some side effects but does not explicitly impact the control flow, `Jump` signals an edge from the current block to another block in the function (the edge may be conditional in which case it will generally be associated with an expression), and finally `Return` represents an exit …
=> feat(rome_control_flow): add the control flow crate

crates/rome_js_formatter/src/utils/member_chain/flatten_item.rs, crates/rome_js_formatter/src/utils/member_chain/groups.rs, crates/rome_js_formatter/src/utils/member_chain/mod.rs, crates/rome_js_formatter/tests/specs/js/module/arrow/call.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/function-first-param/function_expression.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/method-chain/comment.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/method-chain/issue-4125.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/optional-chaining/comments.js.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/method-chain/comment.ts.snap
This PR adds again a check on the breaking logic of the member chain. The check is around comments. I also fixed the previous logic, where the check for certain comments was incorrectly done.
`cargo test` and checked that snapshots are correctly updated
PR 
**File Based Average Prettier Similarity**: 77.33%  
**Line Based Average Prettier Similarity**: 72.59%  
`main`
**File Based Average Prettier Similarity**: 77.25%  
**Line Based Average Prettier Similarity**: 72.45%
=>  fix(rome_js_formatter): breaking logic for member chains

crates/rome_js_analyze/src/analyzers.rs, crates/rome_js_analyze/src/analyzers/no_unnecessary_continue.rs, crates/rome_js_analyze/src/registry.rs, crates/rome_js_analyze/tests/specs/noUnnecessaryContinue.js, crates/rome_js_analyze/tests/specs/noUnnecessaryContinue.js.snap, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/noUnnecessaryContinue.md
1.  Resolved #2746 
1. cargo test
=> feat(rome_js_analyze): noUnnecessaryContinue

crates/rome_js_analyze/src/analyzers/use_block_statements.rs, crates/rome_js_analyze/tests/specs/useBlockStatements.js.snap, website/src/docs/lint/rules/useBlockStatements.md
1. Add whitespace to `{` and `}`
1. cargo test
=> fix(rome_js_analyze): make useBlockStatement fixed code a little nicer.

crates/rome_js_analyze/src/control_flow/visitor.rs, crates/rome_js_analyze/tests/specs/noDeadCode/NestedFunctions.js, crates/rome_js_analyze/tests/specs/noDeadCode/NestedFunctions.js.snap
The `JsAnyControlFlowRoot` union in the control flow analysis for JS was missing the object member and class member nodes, causing the control flow for these functions to "leak" into the parent context, causing an erroneous CFG and potentially false positive diagnostics to be emitted
I've added an additional snapshot test for the `noDeadCode` rule checking a single expression statement at the root level does not get marked as unreachable because of previous return instructions in nested function types
=> fix(rome_js_analyze): add missing control flow root nodes

crates/rome_js_analyze/src/analyzers.rs, crates/rome_js_analyze/src/analyzers/no_comment_text.rs, crates/rome_js_analyze/src/registry.rs, crates/rome_js_analyze/tests/specs/noCommentText.tsx, crates/rome_js_analyze/tests/specs/noCommentText.tsx.snap, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/noCommentText.md
1. Resolved #2751 
1.  check the new snapshot test
=> feat(rome_js_analyze): noCommentText

crates/rome_js_formatter/src/js/lists/variable_declarator_list.rs, crates/rome_js_formatter/src/utils/assignment_like.rs, crates/rome_js_formatter/src/utils/member_chain/groups.rs, crates/rome_js_formatter/src/utils/member_chain/mod.rs, crates/rome_js_formatter/tests/specs/js/module/assignment/assignment.js, crates/rome_js_formatter/tests/specs/js/module/assignment/assignment.js.snap, crates/rome_js_formatter/tests/specs/js/module/declarations/variable_declaration.js, crates/rome_js_formatter/tests/specs/js/module/declarations/variable_declaration.js.snap, crates/rome_js_formatter/tests/specs/js/module/expression/import_meta_expression/import_meta_expression.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/assignment/issue-10218.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/assignment/issue-7091.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/assignment/issue-7961.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/assignment/issue-8218.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/assignment/lone-arg.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/assignment/unary.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/member/expand.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/method-chain/break-last-member.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/ternaries/indent-after-paren.js.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/non-null/member-chain.ts.snap, crates/rome_js_formatter/tests/specs/ts/assignment/assignment.ts, crates/rome_js_formatter/tests/specs/ts/assignment/assignment.ts.snap, crates/rome_js_formatter/tests/specs/ts/declaration/variable_declaration.ts, crates/rome_js_formatter/tests/specs/ts/declaration/variable_declaration.ts.snap, crates/rome_js_syntax/src/expr_ext.rs
This PR partly implements prettier functionality  `isPoorlyBreakableMemberOrCallChain` for `assignment_like` nodes. These nodes have `BreakAfterOperator` layout.
- https://github.com/prettier/prettier/blob/a043ac0d733c4d53f980aa73807a63fc914f23bd/src/language-js/print/assignment.js#L329
Also this PR fixes `assignment_like` content wrapping. See more details in comments.
Add new test cases.
Current:
**File Based Average Prettier Similarity**: 77.64%  
**Line Based Average Prettier Similarity**: 72.78%  
Main:
**File Based Average Prettier Similarity**: 77.33%  
**Line Based Average Prettier Similarity**: 72.59%
=> feat(rome_js_formatter): poorly breakable member or call chain

crates/rome_js_semantic/src/semantic_model.rs
This PR implements three improvements to the SemanticModel
1 - ```Scope::ancestors``` that will make it easier to navigate upwards the scope tree;
2 - ```Scope``` equality;
3 - Better typing on the ```declaration``` method (and in the extension method);
3.1 - Also allow to get declarations of ```JsIdentifierAssignment```.
```
> cargo test -p rome_js_semantic -- ok_semantic_model_events_sink
```
=> feat(rome_js_semantic): scope navigation improvements

.github/workflows/release_cli.yml, .github/workflows/release_lsp.yml
This PR simply uncomments the `schedule` event for the CLI and LSP release workflows. The release schedule is the same one that was used for Rome JS, it should trigger a release build at 00:00 UTC on every workday. The publishing step still requires a manual validation from a member of the staff team in order to actually get pushed to npm or the VS Marketplace
The scheduled workflow should start running automatically once the branch is merged to main
=> feat(ci): enable nightly builds

crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/semantic_model.rs, crates/rome_js_semantic/src/tests/assertions.rs, crates/rome_js_semantic/src/tests/references.rs
This PR extract ```JsIdentifierAssignment``` as ```Write``` and ```HoistedWrite``` events and integrate these events in the ```SemanticModel```. 
This means that now we can get declarations on statements like:
```
a = 1;
a++;
```
```
> cargo -p rome_js_semantic -- ok_reference_write
> cargo -p rome_js_semantic -- ok_hoisting_write
> cargo test -p rome_js_semantic -- ok_semantic_model
```
=> feat(rome_js_semantic): get declaration for JsIdentifierAssignment

crates/rome_js_analyze/src/analyzers/no_dead_code.rs, crates/rome_js_analyze/tests/specs/noDeadCode/HighComplexity.js, crates/rome_js_analyze/tests/specs/noDeadCode/HighComplexity.js.snap
This changes the implementation of the `noDeadCode` lint rule to select between two different implementations of the reachability analysis (simple and fine) based on a "complexity score" for the function.
This score is an arbitrary number, roughly related to the cyclomatic complexity of the function: the formula might look similar but the actual value being returned is slightly different as our `ControlFlowGraph` doesn't exactly match the strict definition of a control flow graph of basic blocks, and the algorithm doesn't detect connected components for efficiency.
If that score is determined to be over 20 for a given function the rule will only run the "simple" analysis that calculates reachability for all instructions in the function but doesn't attempt to determine a "terminator …
=> perf(rome_analyze): fallback to a simple analysis in noDeadCode for complex functions

crates/rome_js_semantic/src/semantic_model.rs
This PR implements the ```all_references``` for the semantic model, which, of course, returns all references of a declaration. This method is needed in a lot of fixes of semantic lint rules.
Will mainly be used together with https://github.com/rome/tools/pull/2852.
```
> cargo test -p rome_js_semantic -- ok_semantic_model
```
=> feat(rome_js_semantic): implements all_reference for the semantic model

.github/workflows/pull_request.yml, .github/workflows/release_lsp.yml
This adds an additional job to the `pull_request` workflow that builds the CLI and tries to run it in CI mode over the `editors` (VSCode extension) and `website` directories. This step is "information only" and is marked as `continue-on-error` to avoid causing the workflow to fail since those parts of the codebase are also tested using the latest release of the CLI in their corresponding workflow, and unreleased changes in the linter or formatter may lead to differences between the two set of warnings and errors being emitted.
I also included a small fix in the LSP release workflow, the path to the version update script was out of sync with the actual file in the repo
Run the workflow and check that it works as expected
=> ci: run the CLI on the VSCode extension and website codebase in the Rust PR workflow

crates/rome_js_analyze/src/control_flow/nodes.rs, crates/rome_js_analyze/src/control_flow/nodes/statement.rs, crates/rome_js_analyze/src/control_flow/nodes/variable.rs, crates/rome_js_analyze/src/control_flow/visitor.rs, crates/rome_js_analyze/tests/specs/noDeadCode/JsVariableStatement.js, crates/rome_js_analyze/tests/specs/noDeadCode/JsVariableStatement.js.snap
This PR modifies how control flow instructions are emitted for variable statements: instead of considering the entire statement as a side effect, each initializer expression now creates it own instruction. This means variable declarations without an initializer are not considered to have any side effects in terms of control flow, checking whether the variable itself it unused will be part of the semantic analysis
Fixes #2869
I've added additional test cases in `JsVariableStatement.js` to check the correct warnings are being emitted
=> fix(rome_js_analyze): only emit control flow side-effects for variable declarators with an initializer

crates/rome_js_semantic/src/semantic_model.rs
This PR enriches the Semantic Model with information about if references are "reading" or "writing". This can really simplify rules like https://github.com/rome/tools/pull/2849#issuecomment-1181544741
One interesting point is what to do with initializers. Today I **do not** flag initializers as writes.
```
> cargo test -p rome_js_semantic -- ok_semantic_model
```
=> feat(rome_js_semantic): Enrich the semantic model with read/write information

Cargo.lock, crates/rome_rowan/Cargo.toml, crates/rome_rowan/benches/mutation.rs, crates/rome_rowan/src/ast/batch.rs, crates/rome_rowan/src/ast/mod.rs, crates/rome_rowan/src/syntax/node.rs, crates/rome_rowan/src/syntax_node_text.rs, crates/rome_rowan/src/tree_builder.rs
This PR allows batch mutation for ```SyntaxNode```. It solves the problem that when you have a list of nodes to mutate,  after the first mutation, the rest of ```SyntaxNode``` is not valid anymore.
The API follows a transaction style, which I think blends better with Rust (instead of closures)
```rust
let mut batch = root.begin();
batch.replace_node(a, c);
batch.replace_node(b, d);
let root = batch.commit();
```
All tests can be run with:
```
> cargo test -p rome_rowan -- ok_batch_mutation
```
See https://github.com/rome/tools/pull/2852#discussion_r920062297 for a more detailed discussion of the algorithm.
=> feat(rome_rowan): batch mutation for syntax nodes

crates/rome_formatter/src/buffer.rs, crates/rome_formatter/src/format_element.rs, crates/rome_formatter/src/lib.rs, crates/rome_js_formatter/src/js/expressions/call_arguments.rs, crates/rome_js_formatter/src/lib.rs, crates/rome_js_formatter/src/prelude.rs, crates/rome_js_formatter/src/utils/mod.rs
Use `memoized.inspect` to make formatting decision on only later written content instead of the buffer inspection methods `labelled` and `will_break.
The buffer methods are preferred when inspecting content that gets written before needing to know if the content will break or is labelled.
`cargo test`
=> refactor(rome_formatter): Use `memoized.inspect` over `buffer.inspect`

crates/rome_js_analyze/src/semantic_analyzers/js.rs, crates/rome_js_analyze/src/semantic_analyzers/js/no_shouty_constants.rs, crates/rome_js_analyze/tests/specs/js/noShoutyConstants.js, crates/rome_js_analyze/tests/specs/js/noShoutyConstants.js.snap, crates/rome_rowan/src/ast/batch.rs, crates/rome_rowan/src/syntax/node.rs, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/noShoutyConstants.md
Implements https://github.com/rome/tools/issues/2836
```
warning[js/noShoutyConstants]: Redundant constant declaration.
┌─ noShoutyConstants.js:1:7
│
1 │ const FOO = "FOO";
│       -----------
2 │ console.log(FOO, FOO2);
│             --- Used here.
·
6 │ console.log(FOO, FOO4);
│             --- Used here.
Suggested fix: Use the constant value directly
| @@ -1,6 +2,5 @@
0   | - const FOO = "FOO";
1   | - console.log(FOO, FOO2);
2 0 |   
1 | + console.log("FOO", FOO2);
2 | + 
3 3 |   const FOO2 = "FOO2", a = "FOO3", FOO4 = "FOO4";
4 4 |   
5   | - console.log(FOO, FOO4);
5 | + console.log("FOO", FOO4);
=  note: You should avoid declaring constants with a string that's the same
value as the variable name. It introduces a level of unnecessary
indirection when it's only two additional …
```
=> feat(rome_js_analyze): noShoutyConstants

Cargo.lock, crates/rome_formatter/src/buffer.rs, crates/rome_formatter/src/formatter.rs, crates/rome_formatter/src/lib.rs, crates/rome_formatter/src/macros.rs, crates/rome_js_formatter/Cargo.toml, crates/rome_js_formatter/src/builders.rs, crates/rome_js_formatter/src/context.rs, crates/rome_js_formatter/src/js/classes/property_class_member.rs, crates/rome_js_formatter/src/js/module/import_named_clause.rs, crates/rome_js_formatter/src/jsx/auxiliary/expression_child.rs, crates/rome_js_formatter/src/lib.rs, crates/rome_js_formatter/src/utils/assignment_like.rs, crates/rome_js_formatter/src/utils/format_conditional.rs, crates/rome_js_formatter/src/utils/mod.rs, crates/rome_js_formatter/tests/specs/js/module/declarations/variable_declaration.js, crates/rome_js_formatter/tests/specs/js/module/declarations/variable_declaration.js.snap, crates/rome_rowan/src/syntax/token.rs
This PR adds a debug-only tracking that verifies if the formatter checked the suppression comments for every node. Doing so is useful in cases where our implementation bypasses the node's `FormatNodeRule` implementation that otherwise handles suppressions automatically.
Fixed the existing tests that started failing because of missing suppression checks.
=>  feature(rome_js_formatter): Track suppression handling 

Cargo.lock, crates/rome_cli/Cargo.toml, crates/rome_cli/src/bin/rome.rs, crates/rome_lsp/Cargo.toml, crates/rome_lsp/src/main.rs, xtask/bench/Cargo.toml, xtask/bench/src/main.rs
This change adds the `mimalloc` crate as a dependency of `rome_cli`, `rome_lsp` and `xtask_bench`, and uses the provided `MiMalloc` allocator in the resulting binaries instead of the default (system) allocator on Windows
Since the benchmark actions are being run on Linux, here is the improvements I measured when running all the benchmark suites on my machine:
```
group                                    mimalloc                               sysalloc
-----                                    --------                               --------
analyzer/css.js                          1.00      2.2±0.13ms     5.3 MB/sec    2.41      5.3±1.75ms     2.2 MB/sec
analyzer/index.js                        1.00      4.5±0.34ms     7.2 MB/sec    2.42     10.9±2.81ms     3.0 MB/sec
analyzer/lint.ts …
```
=> feat: replace the system allocator with mimalloc on Windows

crates/rome_js_analyze/src/semantic_analyzers/js.rs, crates/rome_js_analyze/src/semantic_analyzers/js/no_function_assign.rs, crates/rome_js_analyze/tests/specs/js/noFunctionAssign.js, crates/rome_js_analyze/tests/specs/js/noFunctionAssign.js.snap, crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/semantic_model.rs, crates/rome_js_semantic/src/tests/references.rs, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/noFunctionAssign.md
Closes https://github.com/rome/tools/issues/2878
```
> cargo rome-cli check crates/rome_js_analyze/tests/specs/js/noFunctionAssign.js 
```
=> feature(rome_js_analyze): no function reassign lint rule

crates/rome_analyze/src/context.rs, crates/rome_analyze/src/lib.rs, crates/rome_analyze/src/matcher.rs, crates/rome_analyze/src/query.rs, crates/rome_analyze/src/registry.rs, crates/rome_analyze/src/services.rs, crates/rome_analyze/src/signals.rs, crates/rome_analyze/src/syntax.rs, crates/rome_analyze/src/visitor.rs, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/src/semantic_analyzers/js/no_arguments.rs, crates/rome_js_analyze/src/semantic_services.rs, crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/semantic_model.rs
This change merges the execution of the multiple phases of the analyzer into the `Analyzer` struct itself. This allows some derived data like the line suppression cache to be reused between phases, generally improving the performances of the analysis.
In order to support this I've modified the way the way the semantic model is generate to use a `Visitor`, and added a new `finish` hook to visitors called once the entire file has been visited to give them an opportunity to mutate the service bag and inject additional services for subsequent phases.
In turn, in order to provide the visitors with a mutable access to the service bag I changed the way ownership of the bag is managed from using reference counting to using normal Rust references tied to an explicit `'phase` lifetime: the service …
=> refactor(rome_analyze): merge analyzer phases

Cargo.lock, crates/rome_css_syntax/src/lib.rs, crates/rome_formatter/src/comments.rs, crates/rome_formatter/src/formatter.rs, crates/rome_formatter/src/lib.rs, crates/rome_formatter/src/token.rs, crates/rome_js_formatter/Cargo.toml, crates/rome_js_formatter/src/builders.rs, crates/rome_js_formatter/src/context.rs, crates/rome_js_formatter/src/js/module/import_named_clause.rs, crates/rome_js_formatter/src/js/statements/block_statement.rs, crates/rome_js_formatter/src/jsx/auxiliary/expression_child.rs, crates/rome_js_formatter/src/lib.rs, crates/rome_js_formatter/src/utils/assignment_like.rs, crates/rome_js_formatter/src/utils/binary_like_expression.rs, crates/rome_js_formatter/src/utils/format_conditional.rs, crates/rome_js_formatter/src/utils/member_chain/mod.rs, crates/rome_js_formatter/tests/specs/js/module/assignment/assignment_ignore.js, crates/rome_js_formatter/tests/specs/js/module/assignment/assignment_ignore.js.snap, crates/rome_js_formatter/tests/specs/js/module/expression/binary_expression.js, crates/rome_js_formatter/tests/specs/js/module/expression/binary_expression.js.snap, crates/rome_js_formatter/tests/specs/js/module/statement/block_statement.js, crates/rome_js_formatter/tests/specs/js/module/statement/block_statement.js.snap, crates/rome_js_syntax/src/lib.rs, crates/rome_js_syntax/src/suppression.rs, crates/rome_json_syntax/src/lib.rs, crates/rome_rowan/src/raw_language.rs, crates/rome_rowan/src/syntax.rs
This PR changes how the formatter extracts formatter suppression comments. The existing implementation lazily traversed to a node's first token and it checks if the token has any leading suppression comments inside of `context.is_suppressed()`.
This PR iterates over the CST before starting the actual formatting to extract all suppressed nodes and it stores them in an index that can be queried during formatting.
This is mainly preparing for the migration to extract leading and trailing node comments with the re-work of the comments handling. Determining if a node is suppressed then becomes as simple as iterating over the leading comments of a node and determining if it has any suppression comment. 
This change also shows that the current implementation that calls `node.first_token` is …
=> refactor(rome_formatter): Pre-compute suppressions

crates/rome_js_analyze/src/analyzers/js/use_template.rs, crates/rome_js_analyze/tests/specs/js/useTemplate.js, crates/rome_js_analyze/tests/specs/js/useTemplate.js.snap
1. Handle case comments in trivia when merging `Vec<JsAnyExpression>` into a `JsTemplate`
2. For more details, you could see https://github.com/rome/tools/pull/2803#discussion_r920826576
1. cargo test
=> fix(rome_js_analyze/useTemplate):  comments in trivia when merge `Vec<JsAnyExpression>` into a `JsTemplate`

Cargo.lock, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/src/utils.rs, crates/rome_js_analyze/src/utils/rename.rs, crates/rome_js_analyze/src/utils/tests.rs, crates/rome_js_analyze/tests/specs/js/noShoutyConstants.js, crates/rome_js_analyze/tests/specs/js/noShoutyConstants.js.snap, crates/rome_js_semantic/src/semantic_model.rs, crates/rome_lsp/src/capabilities.rs, crates/rome_lsp/src/handlers.rs, crates/rome_lsp/src/handlers/rename.rs, crates/rome_lsp/src/server.rs, crates/rome_rowan/src/ast/batch.rs, crates/rome_rowan/src/syntax/trivia.rs, crates/rome_service/Cargo.toml, crates/rome_service/src/file_handlers/javascript.rs, crates/rome_service/src/file_handlers/json.rs, crates/rome_service/src/file_handlers/mod.rs, crates/rome_service/src/file_handlers/unknown.rs, crates/rome_service/src/lib.rs, crates/rome_service/src/workspace.rs, crates/rome_service/src/workspace/server.rs
This PR is the first step to implementing https://github.com/rome/tools/issues/2903.
It introduces an ```rename``` extension method to the ```BatchMutation```.
I still need to understand what to do when the cursor is not at a symbol.
```
> cargo test -p rome_js_analyze -- rename
```
or directly using the lsp.
=> feat(rome_lsp): renaming symbols

Cargo.lock, crates/rome_analyze/Cargo.toml, crates/rome_analyze/src/lib.rs, crates/rome_analyze/src/registry.rs, crates/rome_analyze/src/rule.rs, crates/rome_js_analyze/src/analyzers/js/use_template.rs
This PR adds a new `suppressed_nodes` method to the `Rule` trait. This hook allows lint rules to emit dynamic node suppressions for their own query, for instance to prevent the rule from matching again on a node that would be removed by a previously-emitted code action.
I've modified the `UseTemplate` rule to use this new method instead of recursively checking for nested binary expressions, this rule has tests checking the rule does not trigger again on recursive string concatenation expressions
=> feat(rome_analyze): allow rules to dynamically emit local suppressions

crates/rome_cli/src/commands/check.rs, crates/rome_cli/src/commands/ci.rs, crates/rome_cli/src/commands/format.rs, crates/rome_cli/tests/configs.rs, crates/rome_cli/tests/main.rs, crates/rome_lsp/src/server.rs, crates/rome_service/src/configuration/mod.rs, crates/rome_service/src/lib.rs
This PR removes `root` from the configuration file.
I completely misinterpreted the meaning of that field from Rome classic. That fields was used in case of nested projects, which is something we don't have at the moment.
Removed test cases around `root`.
=> refactor(rome_service): remove `root` field from configuration

crates/rome_js_analyze/src/analyzers/js/no_dead_code.rs, crates/rome_js_analyze/tests/specs/js/noDeadCode/HighComplexity.js, crates/rome_js_analyze/tests/specs/js/noDeadCode/HighComplexity.js.snap
The additional control flow edges created by exception and finalization handlers were not being accounted for in the calculation of the complexity score for a control flow graph instance. This led to functions with a high control flow complexity being mistakenly run through the fine reachability analysis, with very poor performances due its exponential nature.
A new test case has been added to the `HighComplexity` tests for the `noDeadCode` rule that exhibits a pathological case of exponential complexity increase
=> fix(rome_js_analyze): include the exception handlers in the complexity score of the CFG

crates/rome_formatter/src/lib.rs, crates/rome_js_formatter/src/lib.rs, crates/rome_lsp/Cargo.toml, crates/rome_lsp/src/documents.rs, crates/rome_lsp/src/handlers/analysis.rs, crates/rome_lsp/src/handlers/formatting.rs, crates/rome_lsp/src/handlers/rename.rs, crates/rome_lsp/src/handlers/text_document.rs, crates/rome_lsp/src/line_index.rs, crates/rome_lsp/src/main.rs, crates/rome_lsp/src/server.rs, crates/rome_lsp/src/session.rs, crates/rome_lsp/src/utils.rs, crates/rome_service/src/file_handlers/javascript.rs
This is a partial fix for #2932, it doesn't fix the root cause and format-on-paste will still cause range formatting errors but at least it will not crash the language server process. I've added additional checks at two levels: one is at the start of the `format_range` function in the formatter itself, while the other is in the `LineIndex` struct that's used to translate line + column positions into text offsets.
I've also made the `LineIndex` type crate-private, this makes it easier to detect unused code in order to review all possible "unsafe" vector indexing operation this type is doing ("unsafe" as "out of bounds index triggers a panic", there's no actual unsafety in the Rust language sense of the term)
Finally while I was debugging the issue I've added additional tracing …
=> fix(rome_lsp): fix panics on out of bounds formatting range

crates/rome_js_syntax/src/suppression.rs
This fixes an issue where Rome panicked when parsing suppression comments from a block comment without the closing `*/`.
This PR gracefully handles the case where a block comment has no closing `*/` by trying to remove a trailing `*` or `/` at the end of the comment and otherwise take the comment as is.
I verified that running rome over rome classic no longer panics and added a unit test to the suppression comment parsing.
=> fix(rome_js_syntax): Don't panic on unclosed block comment

crates/rome_lsp/Cargo.toml, crates/rome_lsp/src/config.rs, crates/rome_lsp/src/handlers/analysis.rs, crates/rome_lsp/src/server.rs, crates/rome_lsp/src/session.rs, crates/rome_lsp/tests/server.rs, crates/rome_service/src/configuration/formatter.rs, crates/rome_service/src/configuration/mod.rs, editors/vscode/package.json
Closes #2938 .
Now that we have a configuration file, users should use that as source to change Rome's defaults. The options in the VSCode were always a beta, with the idea that they were going to be removed once the configuration file was available.
Now it's the time to remove them.
I enabled the serialization of `format_with_errors` and assigned its value to the `WorkspaceSettings`. This field it hasn't been used yet in the CLI. I will make a further PR to enable it.
Current tests should pass. I manually built the VSCode extension and verified that the options don't exist anymore.
=> refactor(vscode): remove beta formatter options

crates/rome_rowan/src/ast/mod.rs, crates/rome_rowan/src/cursor/node.rs, crates/rome_rowan/src/green/node.rs, crates/rome_rowan/src/syntax/node.rs
Fix the `last` and `size_hint` implementations of the `SyntaxSlots` iterator.
* `size_hint` should return the count of the remaining items in the iterator and not the total count of the underlying list.
* `last` should return the last element remaining in the iterator, ignoring previously returned elements from calling `next_back`
I added new tests that verified the incorrect behaviour and then fixed the implementation
=> fix(rome_rowan): Slots iterator `last` and `size_hint`

.cargo/config.toml, .github/workflows/release_cli.yml, .github/workflows/release_lsp.yml
Link-Time Optimization was previously enabled only in production builds (running on CI) since it makes the compilation times longer, but release builds take a long time anyway so the difference seems marginal while enabling whole-project optimization brings in important improvements to performance (for instance the various functions making up the control flow graph visitor can be almost entirely inlined)
Measured cold compilation times for the CLI in release mode:
Without LTO: `105.1s (1m 45.1s)`
With LTO: `113.2s (1m 53.2s)`
This is a change to the optimization options of the compiler, it shouldn't have any observable side effects (besides improving performances)
=> chore(cargo): always enable LTO in release mode

crates/rome_cli/tests/main.rs, crates/rome_css_factory/src/generated/node_factory.rs, crates/rome_js_analyze/src/analyzers/js/use_single_var_declarator.rs, crates/rome_js_analyze/src/analyzers/ts/use_shorthand_array_type.rs, crates/rome_js_analyze/tests/specs/js/useSingleVarDeclarator.js, crates/rome_js_analyze/tests/specs/js/useSingleVarDeclarator.js.snap, crates/rome_js_factory/src/generated/node_factory.rs, crates/rome_js_factory/src/make.rs, crates/rome_json_factory/src/generated/node_factory.rs, website/src/docs/lint/rules/useSingleVarDeclarator.md, xtask/codegen/src/generate_node_factory.rs
This PR fixes #2945 by improving how trivia is handled as tokens are moved in the syntax tree mutation. Since that rule isn't really safe to apply I've downgraded its applicability to `MaybeIncorrect`, and modified the CLI tests that were relying on this
I also fixed the issue of separated lists created with the node factory API having an empty slot at the end of the list if the trailing separator was `None` by having the factory function take two iterators (one for the list elements and one for the separators) instead of a single iterator of pairs of list element + an optional separator token. The content of the two iterators are interleaved while building the list, and the separator iterator can simply be one item shorter than the elements iterator in order to omit the last separator …
=> fix(rome_js_analyze): improve trivia handling in useSingleVarDeclarator

Cargo.lock, crates/rome_js_analyze/Cargo.toml, crates/rome_js_analyze/benches/iai.rs, crates/rome_js_analyze/src/semantic_analyzers/js.rs, crates/rome_js_analyze/src/semantic_analyzers/js/use_camel_case.rs, crates/rome_js_analyze/src/utils.rs, crates/rome_js_analyze/src/utils/rename.rs, crates/rome_js_analyze/tests/specs/js/useCamelCase.js, crates/rome_js_analyze/tests/specs/js/useCamelCase.js.snap, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/useCamelCase.md
Implements https://github.com/rome/tools/issues/2903.
```
> cargo rome-cli check ./crates/rome_js_analyze/tests/specs/js/useCamelCase.js
```
This PR implements only the happy path for camel case. It does not support nice camel case for abbreviations and acronyms.
Given that we rename different bindings to possibly the same name, they can conflict. The renaming is correctly dealing with this. So if we have:
```js
let snake_case
snake_case = 1;
let _snake_case
console.log(_snake_case);
```
After renaming everything in one go, we have:
```js
let snakeCase
snakeCase = 1;
let snakeCase2
console.log(snakeCase2);
```
But this is not reflected in the diagnostic phase. Because there is no conflict there. This is something we may need to address in another PR.
```
warning[js/useCamelCase]: Prefer …
```
=> feat(rome_js_analyze): useCamelCase

website/playground/package.json, website/playground/pnpm-lock.yaml
1. Fixing wrong Rome ast codemirror grammar
2. Screenshot:
**Main**
**Current Branch**
3. For more details, you could see patch pr https://github.com/IWANABETHATGUY/lang-rome-ast/commit/8134a49cb672290c930a8e6993c599833086ac37
1. Running the playground locally or see my screenshot.
=> fix(playground): rome ast codemirror grammar

.gitattributes, .github/workflows/pull_request.yml
This adds additional entries to the `.gitattributes` configuration to mark the following files as auto-generated:
- The rule group modules in `rome_js_analyze`, eg. `crates/rome_js_analyze/src/analyzers/ts.rs` or `crates/rome_js_analyze/src/semantic_analyzers/js.rs`
- The configuration structure generated for the analyzer rules in `crates/rome_service/src/configuration/linter/rules.rs`
- All the generated rule documentation pages for the website in `website/src/docs/lint/rules`
Additionally I also added the `cargo codegen configuration` command to the list of codegen commands being run on CI
The diffs for these files should not be hidden by default for future PRs, I don't think it will update the currently open ones though
=> chore(git): mark additional generated files in the gitattributes

crates/rome_js_analyze/Cargo.toml, crates/rome_js_analyze/src/analyzers/js/no_debugger.rs, crates/rome_js_analyze/src/analyzers/js/no_delete.rs, crates/rome_js_analyze/src/analyzers/js/no_unnecessary_continue.rs, crates/rome_js_analyze/src/utils.rs, crates/rome_js_analyze/tests/spec_tests.rs, crates/rome_js_analyze/tests/specs/js/noDelete.js, crates/rome_js_analyze/tests/specs/js/noDelete.js.snap, crates/rome_js_analyze/tests/specs/js/noUnnecessaryContinue.js.snap, crates/rome_js_analyze/tests/specs/js/useBlockStatements.js, crates/rome_js_analyze/tests/specs/js/useBlockStatements.js.snap, crates/rome_js_parser/Cargo.toml, crates/rome_js_parser/src/lib.rs, crates/rome_js_parser/src/test_utils.rs, crates/rome_js_parser/src/tests.rs, crates/rome_rowan/src/ast/batch.rs, crates/rome_service/src/configuration/linter/rules.rs
This PR fixes #2966 by changing the behavior of the `remove_node` batch mutation method in syntax lists, making it actually remove the corresponding slot from the list instead of replacing the previous node with an empty slot.
In order to make this work the batch mutation now has to track the number of removed slots in a node to adjust the indices of other modifications being applied to the same node, in turn this means I had to change the ordering semantics of mutation changes slightly so that modifications that apply to the same node are sorted in increasing order by the index of the slot they are modifying.
To test this change and protect from future regressions I modified the analyzer tests to perform additional checks on the syntax tree emitted by code actions. These checks include: …
=> fix(rome_js_analyze): fix the removal of nodes from syntax lists in batch mutations

crates/rome_js_analyze/tests/specs/jsx/noImplicitBoolean.jsx, crates/rome_js_analyze/tests/specs/jsx/noImplicitBoolean.jsx.snap
1. Disable the case that has syntax error due to broken CI
2. Diable for now, recover the case later if we have solution to testing analyzer that have syntax error.
1. CI should pass.
=> fix: broken ci

crates/rome_js_analyze/src/analyzers/js/use_block_statements.rs, crates/rome_js_analyze/tests/specs/js/useBlockStatements.js, crates/rome_js_analyze/tests/specs/js/useBlockStatements.js.snap, website/src/docs/lint/rules/useBlockStatements.md
This PR fixes #2943 by introducing additional logic in the code generating the auto-fix for the rule to inspect the tokens and nodes being modified, and move or add trivia pieces accordingly.
I also fixed the query used by the rule to ensure it would trigger separately for if statements and else clauses, ensuring both the consequent and alternate statements would have a diagnostic and code action emitted, and not only the first one visited by the rule.
I added a number of additional test cases in the snapshot tests for the rule to verify the handling of empty statements in if-else chains and indentation
=> fix(rome_js_analyze): improve the handling of trivia in `useBlockStatements`

crates/rome_js_formatter/src/js/any/function.rs, crates/rome_js_formatter/src/js/declarations/function_declaration.rs, crates/rome_js_formatter/src/js/declarations/function_export_default_declaration.rs, crates/rome_js_formatter/src/js/expressions/arrow_function_expression.rs, crates/rome_js_formatter/src/js/expressions/function_expression.rs, xtask/codegen/src/formatter.rs
Remove the exception for `FormatJsAnyFunction` in the code gen and instead move the shared logic for formatting a `JsAnyFunction` to `FormatFunction`
=> refactor(rome_js_formatter): Extract `JsAnyFunction` formatter into `FormatFunction`

crates/rome_js_formatter/src/js/expressions/parenthesized_expression.rs, crates/rome_js_formatter/src/js/expressions/sequence_expression.rs, crates/rome_js_formatter/src/js/statements/return_statement.rs, crates/rome_js_formatter/src/js/statements/throw_statement.rs, crates/rome_js_formatter/src/utils/binary_like_expression.rs, crates/rome_js_formatter/src/utils/mod.rs, crates/rome_js_formatter/tests/specs/js/module/export/expression_clause.js.snap, crates/rome_js_formatter/tests/specs/js/module/expression/logical_expression.js.snap, crates/rome_js_formatter/tests/specs/js/module/statement/return.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/binary-expressions/inline-object-array.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/binary-expressions/return.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/bind-expressions/await.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/comments-closure-typecast/closure-compiler-type-cast.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/comments-closure-typecast/comment-in-the-middle.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/comments-closure-typecast/issue-4124.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/comments-closure-typecast/issue-8045.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/comments-closure-typecast/issue-9358.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/comments-closure-typecast/nested.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/comments-closure-typecast/non-casts.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/comments/return-statement.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/return/binaryish.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/return/comment.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/throw_statement/binaryish.js.snap, crates/rome_js_formatter/tests/specs/prettier/js/throw_statement/comment.js.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/as/as.ts.snap, crates/rome_js_formatter/tests/specs/prettier/typescript/private-fields-in-in/basic.ts.snap
This PR ensures that `throw` and `return` add parentheses around the argument for binary like expressions, sequence expressions and if the argument has any leading comments.
I manually reviewed all snapshot cases. The differences to prettier are around
* formatting of binary like expressions -> separate PR
* when to add or omit parentheses -> not part of this PR
* comments -> requires the comments refactoring.
File Based Average Prettier Similarity: 77.98% -> 78.02%
Line Based Average Prettier Similarity: 73.23% -> 73.20%
The main reason why line based regresses is that the parenthesized / comments issues tend to spawn over multiple lines. However, these must be addressed as part of their own PR as they require significant architectural changes.
=> feat(rome_js_formatter): Format `throw` and `return` argument

crates/rome_js_analyze/src/semantic_analyzers/js.rs, crates/rome_js_analyze/src/semantic_analyzers/js/no_import_assign.rs, crates/rome_js_analyze/tests/specs/js/noImportAssign.js, crates/rome_js_analyze/tests/specs/js/noImportAssign.js.snap, crates/rome_service/src/configuration/linter/rules.rs, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/noImportAssign.md
1. Resolved #2923 
1. cargo test
=> feat(rome_js_ananlyze): noImportAssign

crates/rome_service/src/configuration/linter/rules.rs
1. Fixing the broken ci introduced by https://github.com/rome/tools/pull/2922
1. All CI should pass.
=> ci: 🎡 fix broken ci

crates/rome_js_analyze/src/semantic_analyzers/js.rs, crates/rome_js_analyze/src/semantic_analyzers/js/no_shouty_constants.rs, crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs, crates/rome_js_analyze/src/utils.rs, crates/rome_js_analyze/src/utils/batch.rs, crates/rome_js_analyze/src/utils/tests.rs, crates/rome_js_analyze/tests/specs/js/noUnusedVariables.js, crates/rome_js_analyze/tests/specs/js/noUnusedVariables.js.snap, crates/rome_js_semantic/src/semantic_model.rs, crates/rome_service/src/configuration/linter/rules.rs, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/noUnusedVariables.md, xtask/lintdoc/src/main.rs
Closes https://github.com/rome/tools/issues/2979.
```
>  cargo run -p rome_cli -- check crates/rome_js_analyze/tests/specs/js/noUnusedVariables.js 
```
=> feat(rome_js_analyze): `noUnusedVariable` rule

crates/rome_js_parser/src/syntax/typescript.rs, crates/rome_js_parser/src/syntax/typescript/statement.rs, crates/rome_js_parser/src/syntax/typescript/types.rs, crates/rome_js_parser/test_data/inline/ok/built_in_module_name.rast, crates/rome_js_parser/test_data/inline/ok/built_in_module_name.ts
1. Fixed #2959 
2. Some of `is_reserved_type_name` is allowed in `TsModuleDeclaration` but not in `interface` and `type` alias, you could see more details here https://github.com/rome/tools/issues/2959#issuecomment-1198930538 
1. Should pass all  testcases newly added.
=> fix(rome_js_parser): 🐛TsModuleDeclaration name should allow builtin types

crates/rome_formatter/src/builders.rs, crates/rome_formatter/src/format_element.rs, crates/rome_formatter/src/printer/mod.rs
This PR adds a new IR that allows to reduce the indention for some content nested inside of an `align` or `indent`.
The behaviour of the element depends on whether the closest ancestor is an `align` or `indent`
* `align`: Removes the `align` spaces
* `indent`: Reduces the indention level by one *EXCEPT* if the level is 0, in which case this is a no-op
This is necessary for the formatting of nested conditional expressions where the `consequent` gets wrapped in an `align` but any nested consequent should be indented by one level (and not an indent). That's why the formatter uses `dedent(indent(...))` to undo the `align` but enforce an `indent`.
I added a new builder test showing the behaviour of the `dedent` element.
=> feat(rome_formatter): `Dedent` IR

crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/semantic_model.rs, crates/rome_js_semantic/src/tests/assertions.rs, crates/rome_js_semantic/src/tests/references.rs, crates/rome_js_semantic/src/tests/scopes.rs
This PR implements the "is_exported" query in the SemanticModel.
It will be first used by the ```noUnusedVariables``` lint rule (https://github.com/rome/tools/issues/2979) to avoid false flags like 
```js
error[[js/noUnusedVariables](https://rome.tools/docs/lint/rules/noUnusedVariables/)]: This function is unused.
┌─ main.js:1:17
│
1 │ export function f() {
```
```
>  cargo test -p rome_js_semantic -- ok_semantic_model_is_exported
```
=> feat(rome_js_semantic): semantic model "is_exported" query

crates/rome_formatter/src/builders.rs, crates/rome_formatter/src/format_element.rs, crates/rome_formatter/src/format_extensions.rs, crates/rome_formatter/src/formatter.rs, crates/rome_formatter/src/lib.rs, crates/rome_formatter/src/printer/mod.rs, crates/rome_formatter/src/printer/printer_options/mod.rs, crates/rome_js_formatter/tests/specs/js/module/arrow/call.js.snap, crates/rome_js_formatter/tests/specs/jsx/element.jsx.snap
This changes the behaviour of the printer if an `indent` is nested inside an `align`.
The existing behaviour was to convert the `align` to an `indent`.
This PR changes the behaviour to keep the spaces as is, so that an `align(2) > indent` results in a `______` sequence with `IndentStyle::Space(4)`
This PR further improves `Memoized` so that it avoids creating an `Interned` element on the heap if it has no content.
I expanded the doc test on `align` to show how the IR behaves differently depending on the `IndentStyle`
There are two snapshots that changed because of a fix in `fits` in combination with the indent width ([see this comment](https://github.com/rome/tools/pull/3021#discussion_r939568614))
=> feat(rome_formatter): `align > indent` nesting with `IndentStyle::Space`

crates/rome_analyze/src/lib.rs, crates/rome_analyze/src/matcher.rs, crates/rome_js_analyze/src/lib.rs, editors/vscode/scripts/updateVersionForPrerelease.mjs, editors/vscode/src/main.ts, website/playground/package.json, website/playground/pnpm-lock.yaml, website/playground/public/mermaid.html, website/playground/src/App.tsx, website/playground/src/DesktopPlayground.tsx, website/playground/src/IndentStyleSelect.tsx, website/playground/src/MermaidGraph.tsx, website/playground/src/MobilePlayground.tsx, website/playground/src/SettingsMenu.tsx, website/playground/src/SourceTypeSelect.tsx, website/playground/src/lib.rs, website/playground/src/romeWorker.ts, website/playground/src/types.ts, website/playground/src/utils.ts, website/src/_includes/scripts/funding.js
This PR add a new "Control Flow Graph" tab in the playground displaying the control flow graph for the currently selected function (the function that contains either the cursor or the start of the current selection) using mermaid.js
In order to extract the CFG from the analyzer I introduced a concept of "matcher layer" that can wrap an existing query matcher and intercept incoming query matches from the visitors. Calling the analyzer through the existing `analyze` entry point simply uses an empty layer function, this is all statically dispatched so it should all get inlined and come out as zero-cost in the end.
=> feat(playground): display the control flow graph in the playground

crates/rome_analyze/src/rule.rs, crates/rome_analyze/src/signals.rs, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/src/utils.rs, crates/rome_js_analyze/src/utils/batch.rs, crates/rome_js_analyze/src/utils/rename.rs, crates/rome_js_analyze/tests/spec_tests.rs, crates/rome_rowan/benches/mutation.rs, crates/rome_rowan/src/ast/batch.rs, crates/rome_service/src/file_handlers/javascript.rs, crates/rome_service/src/lib.rs
This PR removes the `N: AstNode<Language=L>` constraint from the `BatchMutation` and changes the `root` to a `SyntaxNode<L>`.
The main motivation for this change is that I want to use the `BatchMutation` for removing all `ParenthesizedExpression`s in the formatter but this isn't possible because:
* The formatter accepts any Js node as the root and there's no `JsAnyNode`
* It isn't guaranteed that the `root` type doesn't change in case the `root` node is a `JsParenthesizedExpression` that gets removed.
`cargo test && rustcs`
=> refactor(rome_rowan): Remove `AstNode` constraint from `BatchMutation`

rome.json, website/playground/package.json, website/playground/pnpm-lock.yaml
1. FIx serval grammar cases see video below: 
for such piece of code
```js
class test {
declare readonly test = 1;
}
```
**before:** 
https://user-images.githubusercontent.com/17974631/183243944-6a7b1b91-e6df-4ec5-80db-5467492e0f3a.mp4
**after:** 
https://user-images.githubusercontent.com/17974631/183243951-af55c5ba-340c-4b87-add8-caf0d1867961.mp4
2. Adding a new temporary `rome.json` to workaround the false positive `noUnusedVariable` rule.
1. See my preview video or testing locally
=> fix(playground): 🐛 fix rome  ast grammar error

.gitattributes, Cargo.lock, crates/rome_cli/Cargo.toml, crates/rome_cli/tests/main.rs, crates/rome_cli/tests/snap_test.rs, crates/rome_cli/tests/snapshots/apply_noop.snap, crates/rome_cli/tests/snapshots/apply_ok.snap, crates/rome_cli/tests/snapshots/apply_suggested.snap, crates/rome_cli/tests/snapshots/apply_suggested_error.snap, crates/rome_cli/tests/snapshots/downgrade_severity.snap, crates/rome_cli/tests/snapshots/lint_error.snap, crates/rome_cli/tests/snapshots/maximum_diagnostics.snap, crates/rome_cli/tests/snapshots/no_lint_if_linter_is_disabled.snap, crates/rome_cli/tests/snapshots/no_lint_if_linter_is_disabled_when_run_apply.snap, crates/rome_cli/tests/snapshots/should_disable_a_rule.snap, crates/rome_cli/tests/snapshots/should_disable_a_rule_group.snap, crates/rome_cli/tests/snapshots/upgrade_severity.snap, crates/rome_console/src/markup.rs, crates/rome_fs/src/fs.rs, crates/rome_fs/src/fs/memory.rs
This PR improves the CLI tests by creating a snapshot. The snapshot will contain:
- the content of the configuration file, if it exists
- the files contained inside the memory file system during the test run of a single test (excluded the configuration file)
- the messages printed by the console, if any (excluded the timing messages)
The reason why I created snapshots it's because I found myself at struggle sometimes, when I needed to test specific cases. Also, there have been few issue before where some messages where not supposed to be there, and I couldn't catch them early. The snapshots, somehow, might help the testing experience a bit.
The snapshot have been added to some existing cases, but not all of them. I had to exclude some runs because of some issue that I couldn't debug (some …
=> test(rome_cli): add snapshots for file system and console session

crates/rome_css_factory/src/generated/node_factory.rs, crates/rome_js_factory/src/generated/node_factory.rs, crates/rome_json_factory/src/generated/node_factory.rs, xtask/codegen/src/generate_node_factory.rs
This PR adds node factory methods for unknown nodes. This is certainly more of an edge case, but I have a use case in the formatter when encountering an invalid parenthesized expression in which case the node should be replaced
as an unknown node so, for as far as the formatter is concerned, parenthesized expressions do not exist.
The new API can be used like this:
```rust
let unknown = rome_js_factory::make::js_unknown_expression(
root.slots().map(|slot| slot.into_syntax_element()),
);
```
An alternative would be to directly use the `SyntaxNode::new_detached` APIs. This works but is less accessible and
it might be convenient to search for all places where we construct unknown nodes.
=> feat(rome_js_syntax): Node factories for unknown nodes

crates/rome_cli/tests/configs.rs, crates/rome_cli/tests/main.rs, crates/rome_service/src/configuration/linter/rules.rs, xtask/codegen/src/generate_configuration.rs
Closes #3015 
The first attempt of the configuration of the rules tried to be too smart (using `IndexMap`) but it wasn't well designed and it couldn't be extended easily and as a consequence we have `rules.js.rules`, which was very redundant.
Fortunately `flatten` directive form `serde` seems to fit the bill here, and it works as expected.
At the moment the enabled/disabled rules are always computed every time we get a diagnostic from a rule. Same for when we have to create an `AnalysisFilter`. This is not efficient. We should look into ways to cache this information, although this would require some work around lifetimes, because `RuleFilter` only works with references and caching them might only be possible if we use the lifetime coming `App`. 
Updated the tests, and now it all passes! …
=> refactor(rome_service): change how rules config is shaped

Cargo.lock, crates/rome_analyze/src/categories.rs, crates/rome_lsp/src/requests/syntax_tree.rs, crates/rome_service/src/file_handlers/javascript.rs, crates/rome_service/src/file_handlers/json.rs, crates/rome_service/src/file_handlers/mod.rs, crates/rome_service/src/file_handlers/unknown.rs, crates/rome_service/src/settings.rs, crates/rome_service/src/workspace.rs, crates/rome_service/src/workspace/server.rs, website/playground/Cargo.toml, website/playground/src/lib.rs, website/playground/src/romeWorker.ts
Fixes #3012 
This PR refactors the Playground to use the WASM bindings to the Workspace API. These bindings currently live in the playground crate itself along with a few utilities, but I plan on eventually moving this code out into its own crate in a later refactor (as part of the Node API umbrella).
The core of the change is relatively simple, and only requires adding a few methods to the workspace in order to access the internal debug representations rendered by the playground (like the formatter IR or the control flow graph). The WASM binding glue is implemented over the existing serde implementations for all the Workspace-related types, using the `serde-serialize` feature of `wasm-bindgen`. Unfortunately since these types go through serialization they are represented as untyped `any` …
=> refactor(playground): refactor the playground to use the WASM bindings for the workspace

crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/semantic_model.rs, crates/rome_js_semantic/src/tests/references.rs
This PR improves the semantic model ```ìs_exported``` query to take ```module.exports``` into consideration.
```
cargo test -p rome_js_semantic -- ok_semantic_model_is_exported
```
=> feature(rome_js_semantic): Semantic model supporting "module.exports"

crates/rome_analyze/Cargo.toml, crates/rome_cli/Cargo.toml, crates/rome_console/Cargo.toml, crates/rome_control_flow/Cargo.toml, crates/rome_css_factory/Cargo.toml, crates/rome_css_syntax/Cargo.toml, crates/rome_flags/Cargo.toml, crates/rome_formatter/Cargo.toml, crates/rome_fs/Cargo.toml, crates/rome_js_analyze/Cargo.toml, crates/rome_js_factory/Cargo.toml, crates/rome_js_formatter/Cargo.toml, crates/rome_js_parser/Cargo.toml, crates/rome_js_semantic/Cargo.toml, crates/rome_json_factory/Cargo.toml, crates/rome_lsp/Cargo.toml, crates/rome_markup/Cargo.toml, crates/rome_service/Cargo.toml, website/playground/Cargo.toml
Fix a typo that got copy-pasted in many `Cargo.toml` files, and add a `repository` field to the manifests
N/A
=> fix(cargo): fix a typo in cargo manifests and add a repository field

crates/rome_cli/src/commands/check.rs, crates/rome_cli/src/commands/ci.rs, crates/rome_cli/src/commands/format.rs, crates/rome_cli/src/commands/help.rs, crates/rome_cli/src/execute.rs, crates/rome_cli/src/lib.rs, crates/rome_cli/src/traversal.rs, crates/rome_cli/tests/main.rs, crates/rome_cli/tests/snap_test.rs, crates/rome_cli/tests/snapshots/apply_noop.snap, crates/rome_cli/tests/snapshots/apply_ok.snap, crates/rome_cli/tests/snapshots/does_not_format_if_disabled.snap, crates/rome_cli/tests/snapshots/downgrade_severity.snap, crates/rome_cli/tests/snapshots/format_stdin_successfully.snap, crates/rome_cli/tests/snapshots/format_stdin_with_errors.snap, crates/rome_cli/tests/snapshots/lint_error.snap, crates/rome_cli/tests/snapshots/maximum_diagnostics.snap, crates/rome_cli/tests/snapshots/no_lint_if_linter_is_disabled.snap, crates/rome_cli/tests/snapshots/no_lint_if_linter_is_disabled_when_run_apply.snap, crates/rome_cli/tests/snapshots/should_disable_a_rule.snap, crates/rome_cli/tests/snapshots/should_disable_a_rule_group.snap, crates/rome_cli/tests/snapshots/upgrade_severity.snap, crates/rome_console/src/codespan/mod.rs, crates/rome_console/src/diff.rs, crates/rome_console/src/lib.rs, crates/rome_diagnostics/src/emit.rs, crates/rome_service/src/lib.rs
Closes #3042 
The implementation of `read` is very simple at the moment and it doesn't take in consideration the `prompt` for now. But it's there because it will be needed in the future.
I also enhanced the CLI snapshot to take the "in" messages in consideration.
New test cases added
=> feat(rome_cli): format code via `stdin`

crates/rome_service/src/configuration/mod.rs
Removing a debug ```println``` at ```rome_service```.
=> fix(rome_service): removing println about config file

website/src/_includes/docs/project-config.md
`indentStyle` was misspelled as `identStyle` in example at the top.
I don't really know why GitHub marks the last line as changed, I haven't touched it.
Sorry I removed a lot of the template, didn't feel it was necessary for such a simple change. Sorry if this was out of line.
=> Fix typo in project-config.md

crates/rome_js_parser/src/syntax/function.rs, crates/rome_js_parser/test_data/inline/ok/ts_parameter_option_binding_pattern.rast, crates/rome_js_parser/test_data/inline/ok/ts_parameter_option_binding_pattern.ts
1. Part of #2310
2. Fix syntax error when using Optional binding on `.d.ts` or `.ts`
1. Checkout the new snapshot
=> fix(rome_js_parser): Syntax error when using optional binding on .d.ts

crates/rome_formatter/src/builders.rs, crates/rome_formatter/src/format_element.rs, crates/rome_formatter/src/printer/mod.rs
This PR extends the `dedent` IR element to support dedenting by one level or to the start of the line.
I intentionally called the mode `root` because it may become necessary in the future that it's possible to mark a root which is different to the start of the line.
This IR is necessary to correctly format `TemplateLiteral`s where inserting any indent characters that weren't present of the template in the source changes the `template`s content at runtime.
I added a doc test demonstrating how the IR can be used and verifies that the printer correctly resets the indent level.
=> feat(rome_formatter): Dedent to Root IR

crates/rome_js_formatter/tests/prettier_tests.rs
Ignore test files with unsupported syntax (bind, tuple, record, ...) from the coverage report.
The motivation of doing so is that we should focus on improving compatibility on syntax that we support. It's obvious that our formatting won't match Prettier's for syntax that the rome parser does not support.
**File Based Average Prettier Similarity**: 79.75% -> 81.53%
**Line Based Average Prettier Similarity**: 76.52% -> 78.29%
=> test(rome_js_formatter): Ignore unsupported syntax from coverage

crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs, crates/rome_js_analyze/tests/specs/js/noUnusedVariables/noUnusedVariables.ts, crates/rome_js_analyze/tests/specs/js/noUnusedVariables/noUnusedVariables.ts.snap
Expands https://github.com/rome/tools/issues/2979.  
Accept "unused variable" when it is a binding inside Typescript function type. Example:
```ts
function f(fn: (title: string) => boolean) { }
```
```title``` is not used, but it is useful here.
```
> cargo test -p rome_js_analyze
```
=> feat(rome_js_analyze): support unused bindings inside typescript function type

crates/rome_formatter/src/macros.rs, crates/rome_js_formatter/src/utils/binary_like_expression.rs
This fixes an issue where using `write!` with a borrowed value didn't compile at the end of a block
```
error[E0597]: `right` does not live long enough
--> crates/rome_js_formatter/src/utils/binary_like_expression.rs:529:70
|
529 |                 write!(f, [format_sub_expression(parent.operator()?, &right)])
|                            ------------------------------------------^^^^^^-
|                            |                                         |
|                            |                                         borrowed value does not live long enough
|                            a temporary with access to the borrow is created here ...
530 |             }
|             -
|             |
|             `right` dropped here while still borrowed
|             ... and the …
```
=> fix(rome_formatter): `write!` dropped while still borrowed 

crates/rome_formatter/src/lib.rs, crates/rome_formatter/src/token.rs, crates/rome_js_formatter/src/context.rs, crates/rome_js_formatter/src/separated.rs, crates/rome_js_parser/src/lexer/mod.rs, crates/rome_js_syntax/src/source_type.rs, crates/rome_service/src/configuration/formatter.rs, crates/rome_service/src/configuration/javascript.rs
1. Part of #3054 
2. From Rust 1.62 it's now possible to derive the Default trait on enums, we could track down and remove the manual implementations for these
3. See https://rust-lang.github.io/rfcs/3107-derive-default-enum.html
1. The CI should pass.
=> refactor: Using default derive macro instead of manual implementation for Enum

crates/rome_bin/src/main.rs
The `rome_bin` distribution is temporarily using "internal" arguments starting with `__` to control the daemon server process, but the `pico_args` library forbids argument names from starting with anything other than `-` in debug mode. I modified the parsing logic to use a subcommand instead of an argument, since those do not have the same naming restrictions.
This change sits at the very top-level of the entire binary distribution, so it's not really easily testable except by first building the CLI then having the tests actually run the resulting binary. Not impossible, but for now I've just manually run `cargo rome-cli-dev __run_server` and checked that it didn't panic on start
=> fix(rome_bin): fix the parsing of the internal CLI arguments for the daemon server in debug mode

website/playground/src/DesktopPlayground.tsx, website/playground/src/TreeView.tsx
This PR improves our playground to make use of the full height for the right hand side panels rather than 70% (which may result in scroll bars on small screens)
=> feat(playground): Use full height for right side panels

crates/rome_js_analyze/src/assists/js.rs, crates/rome_js_analyze/src/assists/js/inline_variable.rs, crates/rome_js_analyze/src/utils.rs, crates/rome_js_analyze/tests/specs/js/inlineVariable.js, crates/rome_js_analyze/tests/specs/js/inlineVariable.js.snap, crates/rome_lsp/tests/server.rs, crates/rome_service/src/file_handlers/javascript.rs
This PR introduces a simple `inlineVariable` code assist, available on all variable declarations that only have have read-only references. The rule inlines the initializer expression for that variable into all the places it's used and removes the original variable declaration node, using logic that's largely shared with the existing `noShoutyConstants` rule
I've added a test file for the rule verifying that "read-only variables" can be inlined while writable variables are not
=> feat(rome_js_analyze): add an `inlineVariable` code action

Cargo.lock, crates/rome_cli/Cargo.toml, crates/rome_cli/src/commands/check.rs, crates/rome_js_formatter/src/check_reformat.rs, crates/rome_js_formatter/tests/check_reformat.rs, crates/rome_lsp/Cargo.toml, crates/rome_rowan/Cargo.toml, xtask/bench/Cargo.toml, xtask/codegen/Cargo.toml, xtask/coverage/Cargo.toml, xtask/coverage/src/reporters.rs, xtask/coverage/src/results.rs
Upgrades our dependencies 
```
Updating crates.io index
Updating anyhow v1.0.53 -> v1.0.62
Updating async-trait v0.1.52 -> v0.1.57
Updating autocfg v1.0.1 -> v1.1.0
Updating backtrace v0.3.65 -> v0.3.66
Updating bumpalo v3.9.1 -> v3.11.0
Updating bytemuck v1.11.0 -> v1.12.1
Updating bytes v1.1.0 -> v1.2.1
Updating cast v0.2.7 -> v0.3.0
Updating cc v1.0.72 -> v1.0.73
Updating countme v3.0.0 -> v3.0.1
Updating crc32fast v1.3.1 -> v1.3.2
Updating criterion v0.3.5 -> v0.3.6
Updating criterion-plot v0.4.4 -> v0.4.5
Updating crossbeam v0.8.1 -> v0.8.2
Updating crossbeam-channel v0.5.2 -> v0.5.6
Updating crossbeam-deque v0.8.1 -> v0.8.2
Updating crossbeam-epoch v0.9.6 -> v0.9.10
Updating crossbeam-queue v0.3.5 -> v0.3.6
Updating crossbeam-utils v0.8.6 -> v0.8.11
Updating ctor v0.1.21 -> v0.1.23 …
```
=> chore: Upgrade rust dependencies

crates/rome_js_analyze/src/semantic_analyzers/js/no_shouty_constants.rs, crates/rome_js_analyze/tests/specs/js/noShoutyConstants.js, crates/rome_js_analyze/tests/specs/js/noShoutyConstants.js.snap, crates/rome_rowan/src/cursor/node.rs, crates/rome_rowan/src/syntax_node_text.rs, website/src/docs/lint/rules/noShoutyConstants.md
Closes https://github.com/rome/tools/issues/3077.
```
> cargo test -p rome_js_analyze -- shouty
```
with two new cases
```js
let foo = "foo";
const A = "A";
export default A;
```
=> fix(rome_js_analyze): fix noShoutyConstants with lowercase and being exported

crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs, crates/rome_js_analyze/tests/specs/js/noUnusedVariables/noUnusedVariables.ts, crates/rome_js_analyze/tests/specs/js/noUnusedVariables/noUnusedVariables.ts.snap, crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/semantic_model.rs, editors/vscode/src/commands/index.ts, editors/vscode/src/session.ts, website/playground/src/types.ts
Address some of the issues of https://github.com/rome/tools/pull/3076
We should be able to remove: 
```
> cargo test -p rome_js_analyze -- ok_semantic_model_is_exported
```
=> feat(rome_js_semantic): semantic model is_exported support for type alias, enum, interface

crates/rome_js_analyze/src/analyzers/jsx/no_implicit_boolean.rs, crates/rome_rowan/src/ast/batch.rs, crates/rome_rowan/src/ast/mutation.rs, crates/rome_rowan/src/cursor/trivia.rs, crates/rome_rowan/src/syntax/node.rs, crates/rome_rowan/src/syntax/token.rs, crates/rome_rowan/src/syntax/trivia.rs
This PR adds the `with_leading_trivia_pieces` and `with_trailing_trivia_pieces` methods to `SyntaxToken` that accept a `SyntaxTriviaPiece` iterator instead of an iterator over `(kind, &str)` tuple.
The motivation for adding this overload is because it is often necessary to merge trivia from different tokens. Unfortunately, just doing
```
token.with_leading_trivia(existing_pieces.map(|piece| (piece.kind(), piece.text()))
```
It does not work because `text()` returns data owned by `piece` which goes out of scope as soon as the `map closure` returns.
The workaround thus far has been to collect the pieces and map over the piece references which comes at the cost of an additional vector allocation. Avoiding the extra allocation will be more important in the formatter where this method will …
=> feat(rome_rowan): `with_*_trivia_pieces`

crates/rome_js_analyze/tests/specs/js/noUnusedVariables/noUnusedVariables.js, crates/rome_js_analyze/tests/specs/js/noUnusedVariables/noUnusedVariables.js.snap, crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/tests/assertions.rs, crates/rome_js_semantic/src/tests/references.rs
Expands https://github.com/rome/tools/issues/2979 with correctly not flagging self-invoking functions as unused.
I don't consider this implementation complete yet. But we need to think about how to deal with complex expressions in these cases.
```
> cargo test -p rome_js_analyze -- no_unused_variables
```
=> feat(rome_js_semantic): semantic read events for self invoking functions

crates/rome_rowan/src/lib.rs, crates/rome_rowan/src/syntax/element.rs, crates/rome_rowan/src/syntax/node.rs, crates/rome_rowan/src/syntax/token.rs, crates/rome_rowan/src/syntax_rewriter.rs
This PR introduces a new `SyntaxRewriter` that is an alternative to the `BatchMutation` for use cases where it's possible to mutate the tree while traversing. 
I first started using the `BatchMutation` but ran into problems when replacing nested nodes:
```javascript
(a + (b + c))
```
The batch mutation would add two changes:
1. Replacing `(b + c)` with `b + c`
2. Replacing `(a + (b + c))` with `a + (b + c)`
As you can see, the second change will override the first change. The main problem is that the `BatchMutation` doesn't give access to the updated child nodes which is something the `SyntaxRewriter` enables you. 
#3092 uses the new rewriter to remove parenthesized expressions and balance logical expressions. 
https://github.com/rome/tools/blob/31ac27f99bff8af8303f952f5fc6a9147204bfb2/cra …
=> feat(rome_rowan): `SyntaxRewriter`

website/src/_includes/docs/project-config.md
At the current docs the keys are `format`, but when using it in rome.json it causes a crash saying:
```
Error: Rome couldn't load the configuration file, here's why: 
unknown field `format`, expected one of `formatter`, `linter`, `javascript` at line 7 column 10
```
This PR fixes the key to the correct one `formatter`.
Started the server and it was all ok.
=> docs(website): fix typo on project-config.md

.github/workflows/pull_request_js.yml, .github/workflows/runtime.yml, npm/rome/package.json, npm/rome/pnpm-lock.yaml, npm/rome/src/index.ts, npm/rome/tests/index.test.ts, npm/rome/tsconfig.json, npm/rome/vitest.config.js
Part of https://github.com/rome/tools/issues/3073
This PR starts works around the runtime APIs. This PR implements only few methods compared to the one proposed:
- `formatFiles`
- `formatContent`
- `parseContent`
The return type of these methods are not final yet and should not be part of the review. For example having `content` for `formatFiles` doesn't make sense. 
What's should be reviewed should be the input types for each API.
There are some tests that will fail once we start the actual work, there's some workflow with the GitHub actions and a compilation test with just TypeScript. Not sure if we really need a bundler for now.
Added new tests and updated an existing workflow. The reason why I didn't add `npm/rome` path to the existing format workflow is because we use `setup-rome`, …
=> feat(npm): API facade and first compile pipeline

Cargo.lock, crates/rome_cli/Cargo.toml, crates/rome_cli/src/metrics.rs, crates/rome_fs/src/interner.rs, crates/rome_js_formatter/Cargo.toml, crates/rome_js_formatter/tests/prettier_tests.rs, crates/rome_lsp/Cargo.toml, crates/rome_lsp/src/server.rs, crates/rome_lsp/src/session.rs
1. Part of #3054 
2.  With the standard library Mutex and RwLock being const-constructible it's now possible to use these in the DiffReport of the Prettier test suite
1. Passing CI
=> refactor: use `std::sync::Mutex` instead of `parking_lot::Mutex`

crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs, crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/semantic_model.rs, crates/rome_js_semantic/src/tests/assertions.rs, crates/rome_js_semantic/src/tests/references.rs, xtask/coverage/src/symbols/msts.rs
This PR start to use the semantic model with our coverage test suites. See https://github.com/rome/tools/issues/3038.
This new "example" actually compares our scope resolution to other tools. Our compliance percentage is still quite low, especially because:
1 - Javascript tools use start/end as characters, we as bytes; when tests cases have Unicode it is very hard to compare values;
2 - Some tools treat trivia differently than us, so we need to sometimes use ```text_range```, and sometimes use the trimmed range;
3 - Some tools create scopes that, as I understand, are not necessary.
```
> cargo test -p rome_js_semantic
> cargo run -p rome_js_semantic --example coverage_scope --release
```
=> feat(rome_js_semantic): Improvements to scope resolution

.github/workflows/pull_request.yml, .github/workflows/pull_request_js.yml, .github/workflows/runtime.yml, npm/backend-jsonrpc/package.json, npm/backend-jsonrpc/src/index.ts, npm/backend-jsonrpc/tsconfig.json, npm/rome/package.json, npm/rome/pnpm-lock.yaml, npm/rome/src/index.ts, npm/rome/tests/index.test.ts
Part of https://github.com/rome/tools/issues/3073
In this PR the Node.js API are hooked to the WASM bindings. 
**This PR only focuses on hooking the `*Content` APIs**. The file system APIs are left out on purpose. For the being also custom configuration left out on purpose, and will be implemented as part of a different PR.
Things that are relevant for the review:
- error handling is left out on purpose until I understand how to handle errors coming from the workspace;
- this PR focuses only on the happy path
- all methods of the `Workspace` of the WASM bindings are synchronous, but there were made asynchronous ( with `await`) because it would allow us to easily swap backend in the future without too many problems.
- I changed the release target of `@rometools/backend-jsonrpc` to `es2020` …
=> feat(npm): hook `*Conent` APIs to WASM bindings

website/playground/vite.config.ts
Playground's development environment is broken.
Fixed vite.config.ts
Error: The request url "/Users/bhbs/Documents/GitHub/tools/npm/wasm-web/rome_wasm_bg.wasm" is outside of Vite serving allow list.
<details>
<summary>Full text</summary>
```sh
> playground@0.0.0 start /Users/bhbs/Documents/GitHub/tools/website/playground
> vite
vite v2.9.5 dev server running at:
> Local: http://localhost:3000/
> Network: use `--host` to expose
ready in 120ms.
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
The request url "/Users/bhbs/Documents/GitHub/tools/npm/wasm-web/rome_wasm_bg.wasm" is outside of Vite serving allow list.
- …
```
=> chore(playground): allow vite to reference npm directory

.github/workflows/pull_request.yml, crates/rome_wasm/src/lib.rs, npm/rome/src/index.ts, website/playground/src/romeWorker.ts
This PR makes the methods compiled by `wasm_bindgen` camel case. The reason why I changed it is because now the emitted types will be inline with the types emitted by the [`backend-jsonrpc` package](https://github.com/rome/tools/blob/main/npm/backend-jsonrpc/src/workspace.ts#L227-L245), and this make the integration between the two backend easier.
This is mostly a compile time change, as you can see the changes are reflected in the playground. The CI should pass.
=> refactor(rome_wasm): change method names to be camel case

crates/rome_formatter/src/buffer.rs, crates/rome_formatter/src/builders.rs, crates/rome_formatter/src/format_element.rs, crates/rome_formatter/src/formatter.rs, crates/rome_formatter/src/lib.rs, crates/rome_formatter/src/macros.rs, crates/rome_js_formatter/src/check_reformat.rs, crates/rome_js_formatter/src/context.rs, crates/rome_js_formatter/src/js/expressions/template_element.rs, crates/rome_js_formatter/src/js/lists/template_element_list.rs, crates/rome_js_formatter/src/lib.rs, crates/rome_js_formatter/src/utils/assignment_like.rs, crates/rome_js_formatter/src/utils/jsx.rs, crates/rome_js_formatter/src/utils/member_chain/mod.rs, crates/rome_js_formatter/src/utils/object.rs, crates/rome_js_formatter/src/utils/string_utils.rs, crates/rome_js_formatter/tests/check_reformat.rs, crates/rome_js_formatter/tests/prettier_tests.rs, crates/rome_js_formatter/tests/spec_test.rs, crates/rome_service/src/file_handlers/javascript.rs, crates/rome_service/src/settings.rs, crates/rome_wasm/build.rs, xtask/bench/src/features/formatter.rs, xtask/codegen/src/generate_bindings.rs
This PR extracts a `FormatOptions` trait from the `FormatContext`. 
The reason for splitting `FormatOptions` and `FormatContext` is the context is intended to store data that is relevant for the formatting of an object like the extracted comments, a source map etc. The information about source maps, comments etc. things that consumers shouldn't be concerned about.
The `FormatOptions` on the other hand are relevant for users because it allows them to customize the formatting of an object.
This PR isn't adding any new behaviour.
`cargo test`
=> refactor(rome_formatter): Extract `FormatOptions`

crates/rome_formatter/src/comments.rs, crates/rome_formatter/src/lib.rs, crates/rome_formatter/src/token.rs, crates/rome_js_formatter/src/context.rs, crates/rome_js_formatter/src/lib.rs
This PR introduces a new `FormatLanguage` trait that formatters for a specific language must implement.
The `format_*` function family in the `rome_formatter` have rather complicated type parameters that Rust isn't always able to infer and some have a large number of parameters. Making this worse, new features like the pre-processing of AST nodes and the comments refactoring will further increase the parametrization of these functions.
This is why this PR introduces the new `FormatLanguage` trait that groups the language specific types and expose methods to customize the formatter's behaviour.
This PR isn't adding any new functionality. Ran `cargo test`
=> refactor(rome_formatter): `FormatLanguage` trait

crates/rome_js_formatter/src/js/expressions/assignment_expression.rs, crates/rome_js_formatter/src/js/expressions/pre_update_expression.rs, crates/rome_js_formatter/src/js/expressions/unary_expression.rs, crates/rome_js_formatter/src/parentheses.rs, crates/rome_js_formatter/src/utils/conditional.rs, crates/rome_rowan/src/ast/mod.rs, crates/rome_rowan/src/macros.rs
This PR introduces a new `AstNode::cast_ref` method that takes a node by reference and only clones it if it can be cast into the `AstNode`.
Being able to pass a reference instead of the owned value can be useful if it's necessary to test against multiple nodes
```
if let Some(if_statement) = JsIfStatement::cast(node.clone()) {
..
} else if let Some(expression_stmt) = JsExpressionStatement::cast(node.clone()) {
..
} else if let Some(switch_statement) = JsSwitchStatement::cast(node) {
..
}
```
As you can see here, the `node` must be cloned `n-1` times where `n` is the number of branches (Rust may be able to optimize them away but doesn't hurt to help the compiler). Using `cast_ref` reduces the clones to at most one in the case the node matches one branch.
This PR further introduces a …
=> feat(rome_rowan): `cast_ref` and `match_ast` macro

website/playground/src/QuotePropertiesSelect.tsx, website/playground/src/QuoteStyleSelect.tsx, website/playground/src/SettingsMenu.tsx, website/playground/src/SourceTypeSelect.tsx, website/playground/src/prettierWorker.ts, website/playground/src/romeWorker.ts, website/playground/src/types.ts, website/playground/src/utils.ts
- Implemented `Quote Properties` to playground!
- Quote Type -> Quote Style
Relevant issue
- #3065
=> feat(playground): implement option quote_properties

crates/rome_formatter/src/comments.rs, crates/rome_formatter/src/lib.rs, crates/rome_js_formatter/src/context.rs, crates/rome_js_formatter/src/js/statements/block_statement.rs, crates/rome_js_formatter/src/utils/member_chain/mod.rs
`context.comments` used to return a `Rc<Comments>` so that the lifetime of `comments` isn't bound to the lifetime of the `FormatContext`. This is necessary to support writing to the formatter while holding to a reference of comments:
(Pseudo code):
```rust
let comments = f.context().comments();
for comment in comments.leading_comments(node) {
write!(f, [comment])?;
}
```
The downside of returning an `Rc` is that every code path using `comments` pays for the overhead of incrementing the `Rc` counter and using an `Rc` in the signature leaks the abstraction.
This PR changes `Comments` to use an `Rc` internally to enable cheap cloning, similar to how `SyntaxNode` works. This allows `context.comments()` to return a reference to `Comments` instead and only code paths that need to write to the …
=> refactor(rome_formatter): Return reference from `context.comments()`

crates/rome_formatter/src/builders.rs, crates/rome_formatter/src/format_element.rs, crates/rome_formatter/src/printer/mod.rs, crates/rome_js_formatter/src/utils/assignment_like.rs, crates/rome_js_formatter/src/utils/binary_like_expression.rs
This PR adds a new `indent_if_group_breaks` IR element that has the same semantics as using `if_group_breaks` with `indent` and `if_group_fits_on_line`
```rust
write!(f, [
group(&text("Head")).with_group_id(Some(id)),
if_group_breaks(&indent(&text("indented"))).with_group_id(Some(id)),
if_group_fits_on_line(&text("indented")).with_group_id(Some(id))
])
```
The advantage of the new IR is that it simplifies the debug output of the IR and removes the need to memoize the content.
I don't expect this to boost performance in a significant way. While this change reduces the number of IR elements and removes the need for memorizing, these operations by itself don't have a high enough cost to significantly affect the formatter perf.
I added new doc tests and ran `cargo test` to verify that using …
=> feat(rome_formatter): `IndentIfGroupBreaks` IR element

crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs, crates/rome_js_analyze/tests/specs/js/noUnusedVariables/noUnusedVariables.js, crates/rome_js_analyze/tests/specs/js/noUnusedVariables/noUnusedVariables.js.snap, crates/rome_js_analyze/tests/specs/js/noUnusedVariables/noUnusedVariables.ts.snap, website/src/docs/lint/rules/noUnusedVariables.md
This improves noUnusedVariables in three ways and removes the suggestion of removing the unused variables:
1 - It does not flag variables starting with "_";
2 - It does not flag React because some old codebases import React and use it only after JSX transpiling;
3 - It ignores function and class expressions (we are going to deal with these in another rule);
The suggestion was removed, because it suggested removing the first parameter of a function, and of course, completely changing the meaning of the other parameters. We need to think a little bit about what we want to suggest.
```
> cargo test -p rome_js_analuze -- no_unused
```
=> feat(rome_js_analyze): no unused starting with underscore; small hack for React and removing suggested fix

crates/rome_formatter/src/builders.rs, crates/rome_formatter/src/format_element.rs, crates/rome_formatter/src/formatter.rs, crates/rome_formatter/src/printer/mod.rs, crates/rome_js_formatter/src/js/lists/array_element_list.rs, crates/rome_js_formatter/src/jsx/lists/child_list.rs
This PR refactors `Fill` to support different separators for every item rather than one uniform separator that separates all elements in the list.
This is necessary to implement `fill` for array expressions where the separator should be a:
* soft line break or space: if there are 0 - 1 line breaks before the node
* empty line: if there are more than 1 new lines before the node.
Used in #3126
=> feat(rome_formatter): Custom separator per `Fill` item

crates/rome_js_formatter/tests/specs/js/module/prettier-differences/fill-array-comments.js, crates/rome_js_formatter/tests/specs/js/module/prettier-differences/fill-array-comments.js.snap
As discussed offline with @ematipico  Add a test that shows why Rome formats array fill elements differently than Prettier.
=> test(rome_js_formatter): Document array-fill comments difference

Cargo.lock, crates/rome_cli/src/commands/check.rs, crates/rome_cli/src/commands/ci.rs, crates/rome_cli/src/commands/format.rs, crates/rome_lsp/src/server.rs, crates/rome_lsp/src/session.rs, crates/rome_service/Cargo.toml, crates/rome_service/src/configuration/mod.rs, editors/vscode/package-lock.json, editors/vscode/package.json
Fixes #3088 
Fixes https://github.com/rome/tools/issues/3128
This PR is partial fix, where it allows the LSP to load the configuration from a `base_path`, which is provided by the client during the initialization of the server. The base path is provided via `root_uri`. (`root_path` is deprecated).
The reason why this is a partial fix, is because loading the configuration file from a custom base path diverges from how our file system works. Basically the resolution of the files should be kept in sync. 
Although this fix can be accepted because our LSP doesn't use the file system, other than when resolving the configuration.
I manually created a project with custom configuration, and checked that it's correctly loaded:
```json
{
"formatter": {
"enabled": true
},
"linter": {
"enabled": true, …
```
=> fix(rome_lsp, vscode): load config from custom base path

crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs, crates/rome_js_analyze/tests/specs/js/noUnusedVariables/noUnusedVariables.ts, crates/rome_js_analyze/tests/specs/js/noUnusedVariables/noUnusedVariables.ts.snap, crates/rome_js_semantic/src/tests/assertions.rs, crates/rome_js_semantic/src/tests/references.rs, website/src/docs/lint/rules/noUnusedVariables.md
Part of #2979 
This PR allows Typescript function overloading to not be flagged as unused.
```ts
function used_overloaded(): number;
function used_overloaded(s: string): string;
function used_overloaded(s?: string) {
return s;
}
used_overloaded();
```
```
> cargo test -p rome_js_analyze -- no_unused
```
=> feat(rome_js_analyze): no unused variables supporting ts overload

crates/rome_bin/src/service/unix.rs
This PR fixes how the domain socket file used to communicated between the daemon server and workspace clients is handled.
Specifically, since the file is left behind in the system temporary directory when the daemon process is killed, the `open_socket` needs to handle the `ConnectionRefused` error in the same way as the `NotFound` error and consider the daemon is not running.
I also extended this behavior to the `print_socket` with an additional safeguard as it will only try to connect a limited number of times before failing with the last error reported by the system.
Finally, since the server cannot bind to an existing file I added a call to `remove_file` on the domain socket file if it exists when the `run_daemon` function is called
I tested this manually using Ubuntu on WSL: I checked …
=> fix(rome_bin): improve error handling for Unix domain sockets

editors/vscode/src/commands/index.ts, editors/vscode/src/main.ts, editors/vscode/src/statusBar.ts, editors/vscode/src/status_bar.ts
Related to #3006
Currently users of the VSCode extension have little to no feedback on whether the extension is active or not for the current file, or on the status of the language server. Taking inspiration from rust-analyzer and Prettier, this PR adds a status bar item for Rome that displays different state when the server is starting up, is ready and active, is inactive because Rome doesn't support the current document (currently this is done at the extension level by checking if the document matches the language selector for the extension, in the future we may request additional information to the language server and display the status of individual features like linting or formatting), or has crashed repeatedly. Additionally, clicking on the status bar item will open the "Rome Trace" …
=> feat(vscode): add a status bar item for the language server

crates/rome_cli/src/execute.rs, crates/rome_cli/src/traversal.rs, crates/rome_js_syntax/src/source_type.rs, crates/rome_lsp/src/documents.rs, crates/rome_lsp/src/handlers/text_document.rs, crates/rome_lsp/tests/server.rs, crates/rome_service/src/file_handlers/javascript.rs, crates/rome_service/src/file_handlers/mod.rs, crates/rome_service/src/lib.rs, crates/rome_service/src/workspace.rs, crates/rome_service/src/workspace/server.rs, editors/vscode/src/commands/index.ts, editors/vscode/src/main.ts, editors/vscode/src/status_bar.ts, npm/backend-jsonrpc/src/workspace.ts
Fixes #3006
This PR adds a new `language_hint` field to the parameters of the `open_file` Workspace method. It lets clients specify a language ID as a hint for the file type resolver, for instance for files that do not have a file extension yet in the editor. To support this I've merged the `EditorLanguage` enum in `rome_lsp` into the `Language` enum in `rome_service`, and refactored error handling across the code base to make the lack of a file extension a non-fatal error in file type determination.
I've added an additional test for the LSP to verify we can correctly format files without an extension
=> feat(rome_service): allow workspace clients to provide a language hint

crates/rome_formatter/src/token.rs, crates/rome_js_formatter/src/jsx/attribute/expression_attribute_value.rs
The formatting of `JsxExpressionAttributeValue` used to special handle the case when the `}` token has a skipped token trivia attached.
```javascript
<div className={asdf asdf} />
```
The special handling ensured that the formatter inserts a whitespace between the expression and the skipped token trivia so that the above doesn't become
```javascript
<div className={asdfasdf} />
```
The problem with the old solution is that it doesn't scale. We can't add these checks in every place where some skipped token trivia may be possibler (which, could be any node).
This PR improves the skipped token trivia formatting in rome formatter to account for any trailing whitespace of the previous token and preserves if it is followed by a skipped token trivia.
Verified that the test is still passing after …
=> fix(rome_formatter): Skipped token trivia spacing

crates/rome_js_analyze/src/analyzers/ts/use_shorthand_array_type.rs, crates/rome_js_analyze/tests/specs/ts/useShorthandArrayType.ts, crates/rome_js_analyze/tests/specs/ts/useShorthandArrayType.ts.snap
1. Fixes #3111 
1. Checking newly added snapshot
=> fix(rome_js_analyze): false positive useShorthandArrayTypes

crates/rome_js_formatter/src/context.rs, crates/rome_js_formatter/src/lib.rs, crates/rome_js_formatter/src/syntax_rewriter.rs, crates/rome_js_formatter/tests/prettier_tests.rs, crates/rome_js_formatter/tests/spec_test.rs, crates/rome_js_formatter/tests/specs/ts/string/parameter_quotes.ts.snap, crates/rome_js_parser/src/lexer/tables.rs, crates/rome_wasm/build.rs, xtask/bench/src/features/formatter.rs, xtask/bench/src/lib.rs, xtask/codegen/src/generate_bindings.rs
This PR removes the `Default` implementation from `JsFormatOptions` because passing a `SourceType` that matches with the type of the AST is mandatory to get correct formatting results. Assuming a default isn't safe because the formatting may depend on the correct source type.
I noticed that we aren't always passing in the right source type when adding another test to only apply some expensive logic if the source type is JSX and it never took that branch.
See now changed prettier tests
=> test(rome_js_formatter): Remove `JsFormatOptions` `Default` implementation

crates/rome_js_formatter/src/utils/assignment_like.rs
The memoize of right is no longer necessary as it is now using the `indent_if_group_breaks` IR element
`cargo test`
=> perf(rome_js_formatter): Remove unnecessary memoize

crates/rome_cli/tests/main.rs, crates/rome_cli/tests/snap_test.rs, crates/rome_cli/tests/snapshots/main_check/should_disable_a_rule_group.snap, crates/rome_cli/tests/snapshots/main_check/upgrade_severity.snap, crates/rome_service/src/configuration/linter/rules.rs, rome.json, xtask/codegen/src/generate_configuration.rs
This PR  adds a `rome.json` file to the root of our project and fixes a bug I found.
While I was enabling the non-recommended rules in our codebase, I found out that a certain configuration was not correctly computing the rule to run. This PR applies a fix.
The reason why I added a `rome.json` file to out repository is because at the moment there are some rules that are not run by default, and in order to dogfood rome, we should be enable all the rules if possible. This will help us to find early bugs.
I verified that the updated tests are correct. I also added a new assertion. I manually verified in the VSCode extension that the enabled rules are applied, as well as the recommended rules.
=> fix(rome_service): correctly compute rules

.github/workflows/stale.yml
This PR implements a simple cron job to automatically mark PRs/issues in stale state using the 'S-Stable' label. Then, the action proceeds to close them if there's further inactivity.
PRs with the label 'PR: on hold' are exempt. 
Merge it and wait. The example was copied from the [repository of the action](https://github.com/actions/stale)
=> ci: stale workflow

.github/workflows/release_cli.yml, npm/rome/package.json
The `upload-artifact` action is stripping the `npm/` prefix from the WASM artifacts, this adds an explicit path to the corresponding `download-artifact` so the files get downloaded and unpacked to the correct directory
Run the CLI release CI workflow again
=> fix(ci): download the WASM artifacts to the correct directory in the publish job

crates/rome_cli/src/commands/format.rs, crates/rome_service/src/configuration/mod.rs, crates/rome_service/src/settings.rs, crates/rome_service/src/workspace/server.rs
This PR is a follow up of https://github.com/rome/tools/pull/3123
This PR removes all the constraints that we have inside the `WorkspaceSettings`. Now the settings are not publicly exposed anymore, so we can remove all the serde/schemars macros. This will allow to have more choice with the data structures we want to choose.
This is an internal refactor, so the existing CI should pass.
=> chore(rome_service): remove constraints from settings

Cargo.lock, xtask/coverage/Cargo.toml, xtask/coverage/src/lib.rs
Use `std::thread::available_parallelism()` over `num_cpus` in `xtask coverage`
`xtask coverage`
=> chore: Replace `num_cpus` crate with `std` call

crates/rome_cli/src/traversal.rs, crates/rome_cli/tests/main.rs, crates/rome_cli/tests/snapshots/main_check/apply_noop.snap, crates/rome_cli/tests/snapshots/main_check/apply_ok.snap, crates/rome_cli/tests/snapshots/main_check/downgrade_severity.snap, crates/rome_cli/tests/snapshots/main_check/lint_error.snap, crates/rome_cli/tests/snapshots/main_check/maximum_diagnostics.snap, crates/rome_cli/tests/snapshots/main_check/no_lint_if_linter_is_disabled_when_run_apply.snap, crates/rome_cli/tests/snapshots/main_check/parse_error.snap, crates/rome_cli/tests/snapshots/main_ci/ci_does_not_run_formatter.snap, crates/rome_cli/tests/snapshots/main_ci/ci_does_not_run_linter.snap, crates/rome_cli/tests/snapshots/main_ci/ci_lint_error.snap, crates/rome_cli/tests/snapshots/main_ci/ci_parse_error.snap, crates/rome_cli/tests/snapshots/main_ci/formatting_error.snap, crates/rome_cli/tests/snapshots/main_format/does_not_format_if_disabled.snap, crates/rome_cli/tests/snapshots/main_format/format_stdin_successfully.snap, crates/rome_cli/tests/snapshots/main_format/formatter_lint_warning.snap, crates/rome_cli/tests/snapshots/main_format/formatter_print.snap, crates/rome_cli/tests/snapshots/main_init/creates_config_file.snap, crates/rome_cli/tests/snapshots/main_reporter_json/reports_formatter_check_mode.snap, crates/rome_cli/tests/snapshots/main_reporter_json/reports_formatter_write.snap
This PR fixes #3167 
Diagnostics were pulled regardless of the capability of the workspace. I added a small condition before the pulling of diagnostics.
I created two test cases: one where the formatter is enabled and linter disabled, one where the formatter is disabled and the linter enabled
=> fix(rome_cli): do not pull diagnostics if linter is turned off

crates/rome_cli/src/commands/check.rs, crates/rome_cli/src/commands/ci.rs, crates/rome_cli/src/commands/format.rs, crates/rome_cli/tests/main.rs, crates/rome_cli/tests/snapshots/main_format/applies_custom_configuration.snap, crates/rome_cli/tests/snapshots/main_format/applies_custom_configuration_over_config_file.snap, crates/rome_cli/tests/snapshots/main_format/applies_custom_quote_style.snap, crates/rome_service/src/configuration/formatter.rs, crates/rome_service/src/configuration/mod.rs
Fixes #3175 
We were incorrectly computing a `WorkspaceSettings`, while now we should change/create a `Configuration` struct instead and then update the settings of the workspace.
This bug went undetected because we don't have tests that check that arguments passed via CLI are correctly applied.
I created two new tests, one that applies the generic configuration of the formatter and one that applies the configuration for the javascript language.
=> fix(rome_cli): correctly compute configuration

CHANGELOG.md, editors/vscode/package.json, npm/rome/package.json
To merge once https://github.com/rome/tools/issues/3175 is closed
=> release: 0.9.1

Cargo.lock, crates/rome_cli/Cargo.toml, crates/rome_cli/src/execute.rs, crates/rome_cli/src/service/mod.rs, crates/rome_cli/src/service/unix.rs, crates/rome_cli/src/service/windows.rs, crates/rome_cli/src/traversal.rs, crates/rome_cli/tests/main.rs, crates/rome_js_formatter/tests/spec_test.rs, crates/rome_lsp/src/handlers/analysis.rs, crates/rome_lsp/src/server.rs, crates/rome_lsp/src/session.rs, crates/rome_service/src/lib.rs, crates/rome_service/src/workspace.rs, crates/rome_service/src/workspace/client.rs, crates/rome_service/src/workspace/server.rs, crates/rome_wasm/src/lib.rs
This PR improves the performance of the remote daemon transport, primarily by allowing both the client and server to process more requests at the same time. The changes include:
- Refactored the `WorkspaceTransport` trait to make it aware of request IDs. This lets the transport layer send out multiple requests to the remote server at the same time and process the responses out of order (this makes use of the `dashmap` crate to store the handles of pending requests in a thread-safe hashmap)
- Use the `OwnedReadHalf` and `OwnedWriteHalf` types provided by `tokio` on Unix, and manually implemented `<Client|Server>ReadHalf` and `<Client|Server>WriteHalf` types on Windows to support "true" parallel I/O operations on the transport socket, rather than relying on the `split` function provided by …
=> perf(rome_service): increase the throughput of the remote daemon transport

Cargo.lock, crates/rome_cli/Cargo.toml, crates/rome_cli/src/termination.rs, crates/rome_cli/tests/main.rs, crates/rome_cli/tests/snap_test.rs, crates/rome_cli/tests/snapshots/main_check/apply_suggested_error.snap, crates/rome_cli/tests/snapshots/main_check/lint_error.snap, crates/rome_cli/tests/snapshots/main_check/maximum_diagnostics.snap, crates/rome_cli/tests/snapshots/main_check/parse_error.snap, crates/rome_cli/tests/snapshots/main_check/upgrade_severity.snap, crates/rome_cli/tests/snapshots/main_ci/ci_does_not_run_linter.snap, crates/rome_cli/tests/snapshots/main_ci/ci_lint_error.snap, crates/rome_cli/tests/snapshots/main_ci/ci_parse_error.snap, crates/rome_cli/tests/snapshots/main_ci/formatting_error.snap, crates/rome_cli/tests/snapshots/main_configuration/incorrect_globals.snap, crates/rome_cli/tests/snapshots/main_configuration/incorrect_rule_name.snap, crates/rome_cli/tests/snapshots/main_configuration/line_width_error.snap, crates/rome_cli/tests/snapshots/main_format/format_stdin_with_errors.snap, crates/rome_cli/tests/snapshots/main_format/indent_size_parse_errors_negative.snap, crates/rome_cli/tests/snapshots/main_format/indent_size_parse_errors_overflow.snap, crates/rome_cli/tests/snapshots/main_format/indent_style_parse_errors.snap, crates/rome_cli/tests/snapshots/main_format/line_width_parse_errors_negative.snap, crates/rome_cli/tests/snapshots/main_format/line_width_parse_errors_overflow.snap, crates/rome_cli/tests/snapshots/main_format/quote_properties_parse_errors_letter_case.snap, crates/rome_service/src/configuration/linter/rules.rs, crates/rome_service/src/configuration/mod.rs, xtask/codegen/src/generate_configuration.rs
This PR increases the coverage of the snapshots of the CLI tests, by tracking the `Termination` message emitted in case of errors. 
All the snapshots that result in errors are updated. While doing so, I found a bug in how we construct the error message of the rules and fixed it. 
Manually checked that the termination messages are printed in the snapshots
=> test(rome_cli): snap termination error

crates/rome_js_analyze/src/semantic_analyzers/js/use_camel_case.rs, crates/rome_js_analyze/src/utils.rs, crates/rome_js_analyze/tests/specs/js/useCamelCase.js, crates/rome_js_analyze/tests/specs/js/useCamelCase.js.snap, rome.json
This PR fixes a false flag of all uppercase const as an invalid non-camel case.
Fixes a lot of issues here: https://github.com/rome/tools/runs/8188485278
```
> cargo test -p rome_js_analyze -- camel_case
```
=> fix(rome_js_analyze): accept const as non camel case

website/src/_includes/docs/getting-started.md
The order of `download` and `latest` was swapped, so the command was not working.
Source: https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases
=> docs: fix link to download latest asset

crates/rome_js_analyze/src/analyzers/js.rs, crates/rome_js_analyze/src/analyzers/js/use_optional_chain.rs, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/tests/specs/js/useOptionalChain/complexLogicalAndCases.ts, crates/rome_js_analyze/tests/specs/js/useOptionalChain/complexLogicalAndCases.ts.snap, crates/rome_js_analyze/tests/specs/js/useOptionalChain/logicalAndCases.js, crates/rome_js_analyze/tests/specs/js/useOptionalChain/logicalAndCases.js.snap, crates/rome_js_analyze/tests/specs/js/useOptionalChain/nullishAndLogicalOr.ts, crates/rome_js_analyze/tests/specs/js/useOptionalChain/nullishAndLogicalOr.ts.snap, crates/rome_js_analyze/tests/specs/js/useOptionalChain/validCases.ts, crates/rome_js_analyze/tests/specs/js/useOptionalChain/validCases.ts.snap, crates/rome_js_semantic/src/semantic_model.rs, crates/rome_js_syntax/src/expr_ext.rs, crates/rome_js_syntax/src/lib.rs, crates/rome_service/src/configuration/linter/rules.rs, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/useOptionalChain.md
Resolved https://github.com/rome/tools/issues/2748
The algorithms are described in the documentation for `LogicalAndChain` and `LogicalOrLikeChain`.
Open questions:
1. This PR handles cases only with logical and expressions and logical or/nullish **separately**. 
`foo && foo.bar && foo.bar.baz` generates one warning and one fix.
`((foo || {}).bar || {}).baz` also generates one warning and one fix.
`((foo && foo.bar) || {}).baz` generates two warnings and two fixes.
2. `LogicalOrLikeChain` collects nodes which need to transform in the `action` phase.   `LogicalAndChain` collects in the `run` phase. Technically, this can be done for `LogicalAndChain` (we can compare only one sub-chain to generate warning) as well, but I'm afraid it might complicate the code. I will mark this code fragment …
=> feat(rome_js_analyze): useOptionalChain #2748

crates/rome_service/src/configuration/linter/rules.rs, crates/rome_service/src/workspace_types.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, xtask/codegen/src/generate_configuration.rs
This PR adds support for constructing the rules into the JSON schema used by our VSCode extension.
Manually packaged the extension. Here's a couple of screenshots
=> feature(vscode): add rules to the schema

crates/rome_js_analyze/src/semantic_analyzers/nursery/use_camel_case.rs, crates/rome_js_analyze/tests/specs/nursery/useCamelCase.js, crates/rome_js_analyze/tests/specs/nursery/useCamelCase.js.snap
This PR add support for non camel case function when:  
1 - They are used inside a new expression;
2 - They are exported.
```
> cargo test -p rome_js_analyze -- camel_case
```
=> feat(rome_js_analyze): useCamelCase accepts function when they are used in new or exported

crates/rome_diagnostics/src/file.rs, crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs, crates/rome_js_analyze/tests/spec_tests.rs, crates/rome_js_syntax/src/expr_ext.rs, crates/rome_rowan/src/cursor/node.rs, crates/rome_rowan/src/syntax_node_text.rs, crates/rome_rowan/src/syntax_token_text.rs, crates/rome_service/src/configuration/mod.rs, crates/rome_text_size/src/range.rs
This PR improves the performance of `SyntaxNodeText` by using the `token_at_offset` method rather than traversing over all tokens in the tree until it find the first token that has an overlapping range. Using `token_at_offset` has better performance because it only traverses into nodes that have an overlapping range.
Example: Getting the text for `+ e` in ``a + b + c + d + e`
* Old implementation: Traverses through the whole tree until it reaches the `+` token
* New: Finds the `+` on the first level, then traverses into `e`
Doing this improvement I discovered that `noShoutyConstants` uses `SyntaxNodeText` over `SyntaxTokenText`. `SyntaxTokenText` has the better performance because it isn't necessary to find the first token with an overlapping range. So, I refactored the implementation to …
=> perf(rome_rowan): `SyntaxNodeText` improvements

crates/rome_formatter/src/source_map.rs, crates/rome_js_formatter/src/builders.rs, crates/rome_js_formatter/src/syntax_rewriter.rs
This PR adds a `DeletedRanges` iterator to the `TransformedSourceMap` that allows iterating over all deleted ranges including the deleted text.
The comments refactoring needs a way to identify if a trivia piece is right before the closing `)` in the original tree because we want to keep trailing comments inside parentheses with the preceding nodes
```javascript
!(
a
// some comment
);
b
```
The comment should be a trailing comment of `a` and not become a leading comment of `b` because the transformed tree has the following shape
```javascript
!a
// Some comment
b;
```
Such an iterator requires a fast way to get the text of a deleted range. This isn't possible with `SyntaxNodeText` because resolving the text requires iterating to the token with the given offset which is `O(n)`. That's why …
=> feat(rome_formatter): Source Map iteration over deleted ranges

crates/rome_rowan/src/syntax.rs, crates/rome_rowan/src/syntax/element.rs
This PR makes the `SyntaxElementKey` public. The `key` methods already have been public but the type itself wasn't, preventing it to e.g. be used as keys in a `HashMap`.
The Comments refactoring uses `SyntaxElementKey` as `HashMap`  keys which is why it is necessary to use the type in other crates. An alternative would have been to use `SyntaxNode` and `SyntaxToken` as keys. However, this has the downside that all keys must be deallocated after formatting a file whereas the compiler may be able to optimize the drop away when using the key.
`cargo build`
=> feat(rome_rowan): Expose `SyntaxElementKey`

Cargo.lock, crates/rome_diagnostics/src/file.rs, crates/rome_diagnostics/src/suggestion.rs, crates/rome_formatter/src/lib.rs, crates/rome_rowan/src/lib.rs, crates/rome_rowan/src/serde_impls.rs, crates/rome_service/src/workspace.rs, crates/rome_service/src/workspace_types.rs, crates/rome_text_edit/Cargo.toml, crates/rome_text_edit/src/lib.rs, crates/rome_text_size/Cargo.toml, crates/rome_text_size/src/lib.rs, crates/rome_text_size/src/schemars_impls.rs, npm/backend-jsonrpc/src/workspace.ts, npm/rome/src/index.ts
This is another change extracted from #3222, this implements the `JsonSchema` trait on the `TextRange` and `TextSize` structs directly in the `rome_text_size` crate since now own it, instead relying on manual `-Schema` implementations that were actually incorrect.
This PR only change how these types are represented in the `schemars` meta-type system, the only visible side-effect for this is that the `TextRange` type is now correctly declared as `[number, number]` in the generated TypeScript bindings
=> feat(rome_text_size): implement the JsonSchema trait on TextRange and TextSize

Cargo.lock, crates/rome_formatter/Cargo.toml, crates/rome_formatter/src/comments.rs, crates/rome_formatter/src/comments/map.rs
This PR is part of the Comments refactoring (#3227)
This PR implements a multimap for storing the leading, dangling, and trailing comments for nodes.
A naive implementation using three multimaps: one to store the leading, dangling, and trailing parts of each node, requires between `nodes < allocations < nodes * 3` `vec` allocations (`nodes` = number of nodes with at least one comment). 
This purpose-built multimap uses a shared `Vec` to store all comments where this is possible (99.99% of comments) and only allocates node-specific `Vec`s for nodes appearing "out of order"
The idea behind the implementation is that comments normally remain in the same order as in the source document. That means:
* All comments for a node are inserted at "the same" time (one at a time, but before inserting …
=> feat(rome_formatter): Comments multi map

Cargo.lock, crates/rome_formatter/Cargo.toml, crates/rome_formatter/src/comments.rs, crates/rome_formatter/src/comments/builder.rs, crates/rome_formatter/src/lib.rs, crates/rome_formatter/src/token.rs
This PR is part of the Comments refactoring (https://github.com/rome/tools/pull/3227)
This PR includes the API changes to `Comments`. `Comments` is the main facade used by formatters and the implementation that extracts comments from a syntax tree. 
I implemented new test for the builder.
=> refactor(rome_formatter): Part 2: Comments API

website/playground/package.json, website/playground/pnpm-lock.yaml, website/playground/src/NurseryRules.tsx, website/playground/src/SettingsMenu.tsx, website/playground/src/romeWorker.ts, website/playground/src/types.ts, website/playground/src/utils.ts
This PR adds a new checkbox to the playground to enable nursery rules. This allows us to debug these rules that are still in development. 
I didn't bother much about where to put that checkbox... I am sure we would need an overhaul of the UI, in a separate place.
Play with the deployed background
=> feat(playground): enable nursery lint rules

Cargo.lock, crates/rome_cli/Cargo.toml, crates/rome_cli/src/main.rs, xtask/bench/Cargo.toml, xtask/bench/src/main.rs
This PR replaces the default global allocator to use `jemallocator` on **all operative systems**, exception for Windows because it's not supported.
Here's some benchmarks from my machine (I use macOS)
```block
group                                 jamalloc                               main
-----                                 --------                               ----
parser/checker.ts                     1.00     98.9±7.70ms    26.3 MB/sec    1.16    115.2±3.25ms    22.6 MB/sec
parser/compiler.js                    1.00     52.8±1.15ms    19.8 MB/sec    1.49     79.0±1.86ms    13.3 MB/sec
parser/d3.min.js                      1.00     34.2±2.76ms     7.7 MB/sec    1.22     41.9±0.96ms     6.3 MB/sec
parser/dojo.js                        1.00      3.1±0.24ms    22.2 MB/sec    1.16 …
```
=> perf(rome_cli): replace global allocator with jemalloc

crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/nullishAndLogicalOr.ts, crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/nullishAndLogicalOr.ts.snap, crates/rome_js_parser/src/syntax/expr.rs, crates/rome_js_parser/test_data/inline/err/invalid_optional_chain_from_new_expressions.rast, crates/rome_js_parser/test_data/inline/err/invalid_optional_chain_from_new_expressions.ts
1. Adding syntax error for `new A?.b()`
2. Fixes #3115 
1. Ci should pass
3. Checking the newly added snapshot
=> fix(rome_js_parser): Adding syntax error for new A?.b()

Cargo.lock, crates/rome_service/src/workspace_types.rs, xtask/bench/Cargo.toml, xtask/codegen/src/formatter.rs, xtask/codegen/src/generate_bindings.rs
This PR is part of the comments refactoring #3227.
This PR changes the binding code gen to emit leading line breaks before doc comments.
It contains a few more changes but I hope that's ok:
* The codegen changes so that `cargo codegen formatter` generates files that use the `FormatUnknownNodeRule` for unknown nodes. 
* Adds a `count` feature to `xtask bench` to easily get the counts of any type using `countme`
Generated the bindings and formatted them with the new formatter.
=> chore(xtask): Part 8: Add line breaks before doc comments

Cargo.lock, crates/rome_formatter/Cargo.toml, crates/rome_formatter/src/comments.rs, crates/rome_formatter/src/comments/map.rs, crates/rome_formatter/src/format_element.rs, crates/rome_formatter/src/lib.rs, crates/rome_formatter/src/trivia.rs, crates/rome_formatter/src/verbatim.rs
This PR adds a debug assertion to verify if all comments in a program have been formatted to prevent accidental "dropping" of comments.
I removed some comments formatting to verify that the panic is triggered.
=> feat(rome_Formatter): Assert formatting of comments

crates/rome_js_analyze/src/analyzers/correctness/use_block_statements.rs, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/tests/specs/correctness/useBlockStatements.js, crates/rome_js_analyze/tests/specs/correctness/useBlockStatements.js.snap
This PR fixes #3199
Added a new test case
=> fix(rome_js_analyzer): add newline if statement has comments in `useBlockStatements`

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/react.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_children_prop.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs, crates/rome_js_analyze/tests/specs/nursery/noChildrenProp/noChildrenPropInvalid.jsx, crates/rome_js_analyze/tests/specs/nursery/noChildrenProp/noChildrenPropInvalid.jsx.snap, crates/rome_js_analyze/tests/specs/nursery/noChildrenProp/noChildrenPropValid.jsx, crates/rome_js_analyze/tests/specs/nursery/noChildrenProp/noChildrenPropValid.jsx.snap, crates/rome_js_analyze/tests/specs/nursery/noUselessFragments/withChildren.jsx, crates/rome_js_analyze/tests/specs/nursery/noUselessFragments/withChildren.jsx.snap, rome.json, website/playground/src/romeWorker.ts
Closes #3267 
This PR also enables other nursery rules in the playground and inside our repository. While doing so, I uncovered a false positive inside `noUselessFragments` rule, which is fixed here.
Added new test cases for the new rule and the fixed case
=> feat(rome_js_analyzer): rule `noChildrenProp`

crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/validCases.ts, crates/rome_js_analyze/tests/specs/nursery/useOptionalChain/validCases.ts.snap, crates/rome_js_syntax/src/expr_ext.rs, crates/rome_js_syntax/src/lib.rs
This PR fixes #3257 
The PR add two new test cases
=> fix(rome_js_analyzer):  precedence for `useOptionalChain`

crates/rome_formatter/src/printer/mod.rs, crates/rome_js_formatter/src/jsx/tag/closing_element.rs, crates/rome_js_formatter/src/jsx/tag/opening_element.rs
This fixes the issue why the test is currently failing in #3251 
The specific snipped triggering the issue is:
```javascript
<div>
ENddddDSIIIN <div>
texttexttexttexttexttexttexttexttexttexttexttextextffg
</div>{" "}
HRS
</div>
```
That generates the following IR
```
[
group(["<div>"]),
indent([
hard_line_break,
fill([
["ENddddDSIIIN"],
[
if_group_breaks(["{" "}", soft_line_break]),
if_group_fits_on_line([" "])
],
[
best_fitting([
[
[
group(["<div>"]),
"texttexttexttexttexttexttexttexttexttexttexttextextffg",
"</div>"
]
]
[
[
group(["<div>"]),
indent([
hard_line_break,
fill([
["texttexttexttexttexttexttexttexttexttexttexttextextffg"]
])
]),
hard_line_break,
"</div>"
]
]
])
],
[
if_group_breaks(["{" "}", soft_line_break]),
if_group_fits_on_line([" "])
],
["HRS"]
]
])
]),
hard_line_break, …
```
=> fix(rome_formatter): Printer fill fits

crates/rome_formatter/src/printer/mod.rs
I noticed this when investigating how to correctly implement `fill`.
The problem with only pushing the items of the variant after the `StartEntry` is that any `FitsPredicate` that counts the start/end entries won't see the corresponding `StartEntry`.
Manually pushing the `StartEntry` onto the stack isn't even necessary because it uses the same `args` anyway
Why is it important to be fixed. A `FitsPredicate` may return a `PrintError::InvalidDocument` if it believes that it has seen an `EndEntry` without a matching `StartEntry` even for valid documents.
=> fix(rome_formatter): Best fitting start entry

website/playground/src/utils.ts
Prettier IR tab has an incorrect IR for jsx input.
[Playground](https://play.rome.tools/?code=++%3Cdiv%3E%0A++++ENddddDS+IN+%3Cdiv%3E%0A++++++text+text+text+text+text+text+text+text+text+text+text%0A++++%3C%2Fdiv%3E%7B%27+%27%7D%0A++++HRS%0A++%3C%2Fdiv%3E&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=true&jsx=true#IAAgADwAZABpAHYAPgAKACAAIAAgACAARQBOAGQAZABkAGQARABTACAASQBOACAAPABkAGkAdgA+AAoAIAAgACAAIAAgACAAdABlAHgAdAAgAHQAZQB4AHQAIAB0AGUAeAB0ACAAdABlAHgAdAAgAHQAZQB4AHQAIAB0AGUAeAB0ACAAdABlAHgAdAAgAHQAZQB4AHQAIAB0AGUAeAB0ACAAdABlAHgAdAAgAHQAZQB4AHQACgAgACAAIAAgADwALwBkAGkAdgA+AHsAJwAgACcAfQAKACAAIAAgACAASABSAFMACgAgACAAPAAvAGQAaQB2AD4A)
It seems that `printDocToString` mutates the document.
=> fix(website): incorrect IR for jsx input

crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/tests/references.rs
Closes https://github.com/rome/tools/issues/3170
```
> cargo test -p rome_js_semantic -- ok_typescript_function_type  
```
=> fix(rome_js_semantic): correctly push/pop scopes for ts function types

crates/rome_js_analyze/src/semantic_analyzers/nursery/no_unused_variables.rs, crates/rome_js_analyze/tests/specs/nursery/noUnusedVariables/noUnusedVariables.ts, crates/rome_js_analyze/tests/specs/nursery/noUnusedVariables/noUnusedVariables.ts.snap, crates/rome_js_analyze/tests/specs/nursery/noUnusedVariables/privateOrPublicConstructorParameters.ts, crates/rome_js_analyze/tests/specs/nursery/noUnusedVariables/privateOrPublicConstructorParameters.ts.snap
Closes https://github.com/rome/tools/issues/3183
```
> cargo test -p rome_js_analyze -- no_unused
```
=> fix(rome_js_analyze): no unused variables accepting ts public/private constructor parameters

crates/rome_cli/src/reports/mod.rs, crates/rome_cli/src/traversal.rs, crates/rome_diagnostics/src/emit.rs, crates/rome_diagnostics/src/v2/adapters.rs, crates/rome_diagnostics/src/v2/context.rs, crates/rome_diagnostics/src/v2/diagnostic.rs, crates/rome_diagnostics/src/v2/display.rs, crates/rome_diagnostics/src/v2/serde.rs, crates/rome_diagnostics_categories/src/lib.rs, crates/rome_diagnostics_macros/src/generate.rs, crates/rome_fs/src/fs.rs, crates/rome_fs/src/fs/memory.rs, crates/rome_fs/src/fs/os.rs, crates/rome_lsp/src/utils.rs, crates/rome_lsp/tests/server.rs, crates/rome_service/src/workspace.rs, crates/rome_service/src/workspace/server.rs, npm/backend-jsonrpc/src/workspace.ts, npm/rome/tests/daemon/__snapshots__/formatContent.test.mjs.snap, npm/rome/tests/daemon/formatContent.test.mjs, npm/rome/tests/wasm/__snapshots__/formatContent.test.mjs.snap, npm/rome/tests/wasm/formatContent.test.mjs
This PR holds a number of miscellaneous changes related to exposing the new diagnostic system to the node.js API.
The central change to enable this is replacing the `rome_diagnostics::Diagnostic` type in the result of the `pull_diagnostics` Workspace method with the new `rome_diagnostics::v2::serde::Diagnostic` type, the serializable form of the new `Diagnostic` trait.
In order to make this work I had to fix a few bugs around the serialization and lifetime of diagnostic categories.
I also updated the logic that turns Rome diagnostics into LSP diagnostics to be generic over the Diagnostic trait, and changed the error reporting in the CLI filesystem traversal logic to use the new `Error` type provided by `rome_diagnostics` instead of declaring its own `TraversalError`.
The changes in the …
=> feat(rome_diagnostics): refactor some existing diagnostics to use the new Diagnostic trait

crates/rome_analyze/src/matcher.rs, crates/rome_analyze/src/query.rs, crates/rome_analyze/src/registry.rs, crates/rome_analyze/src/syntax.rs, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_undeclared_variables.rs, crates/rome_js_analyze/src/semantic_services.rs, crates/rome_js_analyze/tests/specs/nursery/noUndeclaredVariables.js, crates/rome_js_analyze/tests/specs/nursery/noUndeclaredVariables.js.snap, crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/semantic_model.rs, crates/rome_js_semantic/src/tests/assertions.rs
This PR improves the performance of the `noUndeclaredVariables` rule by deriving the `Queryable` trait on the `SemanticServices` type. This allows individual rules to query the `SemanticModel` as a whole and "manually" traverse it to emit a sequence of signals, instead of having to match on individual AST nodes. This is particularly useful for `noUndeclaredVariables`, since it's a lot cheaper to iterate on the list of all the unresolved references in the semantic model than to match on all the identifier nodes in the syntax tree.
Side note: while it may seem useful to use this new capability to query the semantic model for other lint rules, it is primarily intended as an advanced feature for optimizations and as such should only be used if you know what you're doing. I'm currently …
=> perf(rome_js_analyze): improve the performance of noUndeclaredVariables

crates/rome_js_syntax/src/expr_ext.rs, crates/rome_js_syntax/src/import_ext.rs, crates/rome_js_syntax/src/jsx_ext.rs
This PR fixes a small bug found in https://github.com/rome/tools/pull/3336#discussion_r987789842
The `inner_string_text` functions were using the whole text, while they should use the trimmed text.
I updated the doc tests by adding some trivia, to demonstrate that the issue is fixed.
=> fix(rome_js_syntax): pick trimmed text instead the raw text

crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/semantic_model.rs, crates/rome_js_semantic/src/semantic_model/closure.rs
This PR introduces closures in the semantic model.
One interesting decision is what to do with:
```js
function f(c) {
console.log(a);
function g() {
console.log(b, c);
}
}
```
The implementations is returning that ```f``` captures ```a```, and it has a inner closure that captures ```b``` and ```c```. Which is closer to the code.
```
cargo test -p rome_js_semantic -- ok_semantic_model_closure
```
=> feat(rome_js_semantic): Semantic Model support for closures

crates/rome_cli/tests/main.rs, crates/rome_cli/tests/snapshots/main_check/fs_error_symlink.snap, crates/rome_cli/tests/snapshots/main_check/fs_error_unknown.snap, crates/rome_fs/src/fs.rs, crates/rome_fs/src/fs/memory.rs, crates/rome_fs/src/fs/os.rs, crates/rome_fs/src/lib.rs
Fixes #3329
This PR changes the rendering of the `UnhandledDiagnostic` diagnostic type, emitted by the `OsFileSystem` when an unknown file type is encountered. It adds an explicit error message and description, along with an information advices providing additional details. It also adds a specialized version of the error message when the unhandled file is a symbolic link, as that's the most common case for this error to be raised. Finally, it downgrades the severity of the diagnostic from error to warning, since this is not a "fatal" error that should cause the traversal to abort.
The diagnostic should now be printed as follow when encountering a symbolic link:
```text
..\test-link\link internalError/fs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
! Symbolic links are …
```
=> fix(rome_fs): improve the messaging of the "unhandled file type" diagnostic

crates/rome_cli/src/traversal.rs, crates/rome_cli/tests/main.rs, crates/rome_cli/tests/snapshots/main_check/file_too_large.snap, crates/rome_cli/tests/snapshots/main_ci/file_too_large.snap, crates/rome_cli/tests/snapshots/main_format/file_too_large.snap, crates/rome_console/src/fmt.rs, crates/rome_fs/src/fs/memory.rs, crates/rome_service/src/lib.rs, crates/rome_service/src/workspace/server.rs
Fixes #3330
This PR adds a maximum size threshold to the Workspace after which files are no longer parsed, analyzed or formatted. At the moment I've hard-coded this limit to 1 MiB, but it should be trivial to expose this limit in the configuration file or the CLI if users really want to process very large files.
As part of the new message for this new error, I've added a new `Bytes` utility to `rome_console` that prints a quantity in bytes using the correct binary unit (B, KiB, MiB, GiB or TiB)
I've added new test cases for the CLI that ensures files larger than the size threshold are not checked or formatted, and the correct diagnostic is emitted.
=> fix(rome_service): disallow large files from being parsed and analyzed

crates/rome_cli/tests/snapshots/main_check/upgrade_severity.snap, crates/rome_js_analyze/src/analyzers/nursery/no_unreachable.rs, crates/rome_js_analyze/src/control_flow/nodes/switch_stmt.rs, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsBreakStatement.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsContinueStatement.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsDoWhileStatement.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsForInStatement.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsForOfStatement.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsForStatement.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsIfStatement.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsLabeledStatement.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsReturnStatement.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsSwitchStatement.js, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsSwitchStatement.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsThrowStatement.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsTryFinallyStatement.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsTryStatement.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsVariableStatement.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsWhileStatement.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/MergeRanges.js, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/MergeRanges.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/SuppressionComments.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/TerminatorsPlurals.js.snap, website/src/docs/lint/rules/noUnreachable.md
Fixes #2961
This PR improves the range-merging logic of the `noUnreachable` rule to allow large sections of unreachable code to be reconstructed from many disjoint instruction-level ranges. I also took the opportunity to rework how the advices emitted in the diagnostics are sorted and worded to make better use of the new diagnostics rendering.
I've added a new `MergeRanges` test case that checks the range merging works correctly for all the supported control flow statements, and I've updated a few other snapshots that were also impacted by this change.
=> fix(rome_js_analyze): improve the diagnostics emitted by `noUnreachable`

crates/rome_lsp/src/utils.rs
There was a bug in the code handling the conversion of text diff operations to LSP text edits, where the text positions where calculated as relative to the new revision of the text when they should have been offsets in the old revision instead.
This issue was not caught in the existing test because it replaced the sequence `old` with `new`, which happened to have the same length so there was no mismatch in offset between the two revisions. I've added an additional test case to cover this.
=> fix(rome_lsp): fix the calculation of offsets in the diff to LSP text edit conversion

crates/rome_diagnostics/src/file.rs, crates/rome_wasm/src/utils.rs, npm/js-api/tests/wasm/__snapshots__/diagnosticPrinter.test.mjs.snap, npm/js-api/tests/wasm/diagnosticPrinter.test.mjs
The `DiagnosticPrinter` was broken since #3315 as it was not deserializing diagnostics from JS back into Rust with the correct type (it was using `rome_diagnostics::Diagnostic` instead of `rome_diagnostics::v2::serde::Diagnostic`). This should fix the outstanding issue of the Playground failing to print the diagnostics.
I've added a new case in the tests of the WASM API in `@rometools/js-api` to check the diagnostic printer works correctly
=> fix(rome_wasm): fix the WASM diagnostic printer

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/analyzers/nursery.rs, crates/rome_js_analyze/src/analyzers/nursery/no_auto_focus.rs, crates/rome_js_analyze/tests/specs/nursery/noAutofocus/noAutoFocusInvalid.jsx, crates/rome_js_analyze/tests/specs/nursery/noAutofocus/noAutoFocusInvalid.jsx.snap, crates/rome_js_analyze/tests/specs/nursery/noAutofocus/noAutoFocusValid.jsx, crates/rome_js_analyze/tests/specs/nursery/noAutofocus/noAutoFocusValid.jsx.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, rome.json, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/noAutofocus.md
Closes #3297 
Added test cases to test the situations according to [this docs](https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/a11y/noAutofocus.md).
=> feat(rome_js_analyzer): rule `noAutofocus`

crates/rome_js_analyze/src/utils/tests.rs, crates/rome_js_semantic/src/semantic_model.rs, crates/rome_js_semantic/src/semantic_model/closure.rs, crates/rome_service/src/file_handlers/javascript.rs
This PR implements a simple global resolution for the semantic model.
```
> cargo test -p rome_js_semantic -- ok_semantic_model_globals
```
=> feat(rome_js_semantic): simple globals resolution

crates/rome_analyze/Cargo.toml, crates/rome_analyze/src/context.rs, crates/rome_analyze/src/options.rs, crates/rome_analyze/src/registry.rs, crates/rome_analyze/src/signals.rs, crates/rome_js_analyze/Cargo.toml, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/src/utils/rename.rs, crates/rome_service/Cargo.toml
Closes https://github.com/rome/tools/issues/3343 
Closes https://github.com/rome/tools/issues/3344 
Closes https://github.com/rome/tools/issues/3345
The function `rule_options` has been renamed `rule_settings` and it's been lifted inside the `AnalyzerContext`. The `AnalyzerContext` now accepts a `RuleKey`, which is needed to retrieve and deserialize the JSON string coming from the configuration.
`serde` is not optional anymore (I thought the entity of the change was bigger).
The handling of the error has been left out on purpose for the time being, and it will be handled in a different PR
The current CI should work
=> feat(rome_analyze): use serde to deserialize rule settings

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/analyzers/nursery.rs, crates/rome_js_analyze/src/analyzers/nursery/use_valid_anchor.rs, crates/rome_js_analyze/tests/specs/nursery/useValidAnchor.jsx, crates/rome_js_analyze/tests/specs/nursery/useValidAnchor.jsx.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, website/src/docs/lint/rules/index.md, website/src/docs/lint/rules/useValidAnchor.md, xtask/lintdoc/src/main.rs
This PR closes #3303 
I tried to add some extensive documentation for this rule.
Added various test cases
=> feat(rome_js_analyze): rule `useValidAnchor`

Cargo.lock, crates/rome_formatter/Cargo.toml, crates/rome_formatter/src/printer/mod.rs, crates/rome_formatter/src/printer/queue.rs, crates/rome_formatter/src/printer/stack.rs, crates/rome_js_formatter/tests/specs/prettier/jsx/text-wrap/test.js.snap
Implements the fix for https://github.com/rome/tools/pull/3251#issuecomment-1264447408
This PR addresses an issue in the Printer where fill printed the item in flat mode even though the separator neither fits in flat nor expanded mode. In that case, it is necessary to expand the `item` to avoid overflowing the configured print width. 
See the updated snapshots.
=> fix(rome_formatter): Fill fits

crates/rome_js_parser/src/syntax/module.rs, crates/rome_js_parser/test_data/inline/err/export_named_clause_err.rast, crates/rome_js_parser/test_data/inline/ok/export_named_from_clause.js, crates/rome_js_parser/test_data/inline/ok/export_named_from_clause.rast
This PR fixes an issue in our parser where the following syntax was incorrectly rejected.
```js
export {"a"} from "b";
```
The reason why it was rejected is that Rome parses the statement as an `export {...}` statement first where `{"a"}` isn't valid and re-parses the statement when it ends at a `from` statement.
But this means that the parsing of `export {...}`  must be at least as permissive as `export {...} from` to guarantee that the parser reaches the `from` keyword.
This PR ensures that this is the case by explicitly handling the `export {"a"};` case
=> fix(rome_js_parser): Export `{"a"} from`

crates/rome_js_parser/src/state.rs, crates/rome_js_parser/test_data/inline/ok/arguments_in_definition_file.d.rast, crates/rome_js_parser/test_data/inline/ok/arguments_in_definition_file.d.ts, crates/rome_js_syntax/src/source_type.rs, xtask/codegen/src/parser_tests.rs
Ambient context has slightly different rules than parsing in a normal context. One such difference is that `arguments` and future reserved keywords are valid identifiers.
Our parser already correctly handled this case by setting the `strict_mode` to `None` when entering an ambient context. However, we initialized `strict_mode` with `Module` for `d.ts` files.
This PR correctly initializes the parser state with `strict = None` if the file is a type script definition file.
I added a new parser test and verified that the `jquery.d.ts` can now be formatted
```bash
cargo run --bin rome format ../vscode/extensions/html-language-features/server/lib/jquery.d.ts --write
```
=> fix(rome_js_parser): Allow `arguments` in `d.ts` files

crates/rome_js_formatter/src/js/expressions/arrow_function_expression.rs, crates/rome_js_formatter/tests/specs/js/module/arrow/arrow_chain_comments.js, crates/rome_js_formatter/tests/specs/js/module/arrow/arrow_chain_comments.js.snap
This PR fixes an issue where trailing comments of arrow expressions that are part of an arrow chain (arrow expressions that are the body of another arrow) were dropped.
The manual handling of comments is necessary because the arrow chain formatting doesn't call into the `FormatJsArrowFunctionExpression` of nested arrow functions.
The implementation already handles the formatting of leading comments correctly.
I added a new snapshot test and verified that running rome format on prettier yields no more "dropped comments" errors.
=> fix(rome_js_formatter): Arrow chain trailing comments

crates/rome_js_formatter/src/comments.rs, crates/rome_js_formatter/src/lib.rs, crates/rome_js_formatter/src/utils/assignment_like.rs, crates/rome_js_formatter/tests/specs/ts/assignment/assignment_comments.ts, crates/rome_js_formatter/tests/specs/ts/assignment/assignment_comments.ts.snap, crates/rome_js_formatter/tests/specs/ts/assignment/property_assignment_comments.ts, crates/rome_js_formatter/tests/specs/ts/assignment/property_assignment_comments.ts.snap
This PR fixes an issue where comments associated with initializers in variable declarators or class properties were dropped. I noticed this when formatting the `vscode` repo.
I added a bunch of new snapshot tests to verify the placement of comments for properties and variable declarators (fewer for variable declarators, because there are already many in Prettier's test suite).
I also run Rome format on the vscode repo to verify that there are no more diagnostics about dropped comments
=> fix(rome_js_formatter): Fix dropped initializer comments

crates/rome_diagnostics/src/v2/display.rs, crates/rome_js_analyze/tests/specs/correctness/noMultipleSpacesInRegularExpressionLiterals.js.snap, crates/rome_js_analyze/tests/specs/correctness/useSimplifiedLogicExpression.js.snap, website/src/docs/lint/rules/noDangerouslySetInnerHtmlWithChildren.md, website/src/docs/lint/rules/noMultipleSpacesInRegularExpressionLiterals.md, website/src/docs/lint/rules/noUnusedTemplateLiteral.md, website/src/docs/lint/rules/noVoidElementsWithChildren.md, website/src/docs/lint/rules/useSimplifiedLogicExpression.md, website/src/docs/lint/rules/useSingleCaseStatement.md, website/src/docs/lint/rules/useSingleVarDeclarator.md
Fixes #3391
The new diagnostics print a line of `━` characters at the end of the header line to fill the width up to 100 columns, but when the header line is long (for instance if the file path is very long or if the diagnostic has additional tags) this means the separators isn't displayed. This PR adds a minimal width, to force the line to be at least 10 characters wide.
I've updated a few snapshot files that were impacted by this change
=> fix(rome_diagnostics): force the diagnostics separator line to be at least 10 characters wide

crates/rome_js_formatter/src/js/bindings/parameters.rs, crates/rome_js_formatter/src/js/expressions/arrow_function_expression.rs, crates/rome_js_formatter/src/utils/test_call.rs, crates/rome_js_formatter/tests/specs/js/module/arrow/arrow_test_callback.js, crates/rome_js_formatter/tests/specs/js/module/arrow/arrow_test_callback.js.snap
Rome has special formatting for test calls that ensures that callbacks remain on the same line as the `it` or `describe` even if exceeding the configured print width. This check was missing for arrow function expression with a single binding parameter so that formatting
```javascript
it('should have the default duration when using the onClose arguments', done => {
expect(true);
done();
});
```
first resulted in 
```javascript
it('should have the default duration when using the onClose arguments', (
done,
) => {
expect(true);
done();
});
```
and ultimately in
```javascript
it('should have the default duration when using the onClose arguments', (done) => {
expect(true);
done();
});
```
This PR removes the need for a second formatting pass by picking up the test call layout in the arrow …
=> fix(rome_js_formatter): Fix arrow binding parameter in test call

crates/rome_formatter/src/arguments.rs, crates/rome_formatter/src/buffer.rs, crates/rome_formatter/src/builders.rs, crates/rome_formatter/src/format_element.rs, crates/rome_formatter/src/format_element/document.rs, crates/rome_formatter/src/lib.rs, crates/rome_formatter/src/macros.rs, crates/rome_formatter/src/printer/mod.rs, crates/rome_formatter/src/source_map.rs, crates/rome_js_formatter/src/utils/jsx.rs
This PR inlines the `Text` enum into the `FormatElement` enum to reduce the size of `FormatElement` from 32 to 24 bytes.
The largest variant of `FormatElement` is `FormatElement::Text` with a size of 24 bytes, which makes `FormatElement` 32 bytes wide because it adds one byte for the variant tag + 7 bytes of padding. 
The size of `Text` is 24 bytes:
* 1 byte for the union tag.
* 20 bytes for the largest variant `SyntaxTokenText`: 
* 16 bytes for the slice  (8 bytes for `GreenToken` + 8 bytes for the text range)
* 4 bytes for the source position
* 3 bytes of padding
This means, that we reserve 10 bytes of padding even for the largest enum variant (even worse for e.g. `LineSuffixBoundary` that has 31 bytes of padding). 
This PR inlines `Text` to avoid having to pad twice, once for `Text` …
=> perf(rome_formater): Inline `FormatElement::Text`

crates/rome_js_analyze/src/semantic_analyzers/correctness/no_dupe_args.rs, crates/rome_js_formatter/src/js/any/object_binding_pattern_member.rs, crates/rome_js_syntax/src/generated/nodes.rs, xtask/codegen/js.ungram
This PR removes the `JsIdentifierBinding` from the `JsAnyObjectBindingPatternMember` union. A single identifier is parsed as a `JsObjectBindingPatternShorthandProperty` and not as a `JsIdentifierBinding`.
I verified that the member union for `JsObjectAssignmentPattern` does not have a `JsReferenceIdentifier` variant.
=> fix(rome_js_syntax): Remove `JsIdentifierBinding` from object binding pattern member union

Cargo.lock, crates/rome_analyze/src/lib.rs, crates/rome_analyze/src/matcher.rs, crates/rome_analyze/src/registry.rs, crates/rome_analyze/src/rule.rs, crates/rome_analyze/src/syntax.rs, crates/rome_js_analyze/Cargo.toml, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/src/registry.rs, crates/rome_service/src/configuration/mod.rs, crates/rome_service/src/file_handlers/javascript.rs, xtask/codegen/Cargo.toml, xtask/codegen/src/generate_analyzer.rs, xtask/codegen/src/generate_configuration.rs, xtask/lintdoc/src/main.rs
Fixes #3406
This PR changes how the "rule registry" concept of the analyzer works by splitting its various use-case into separate types implemented at different location in the codebase through a common `RegistryVisitor` trait. This trait makes it possible to differentiate between the "static registry" containing all the rules for a given language (implemented through the new `visit_registry` function replacing `build_registry`), and various "dynamic registries" that get built on demand throughout the codebase: the analyzer holds both a fast set of all the known rules and a `RuleRegistry` containing only the active rules, the `lintdoc` tools builds a list of the lint rules only, the LSP also needs to build a list of the code action rules, ...
I've added an additional test for suppression …
=> fix(rome_diagnostics): fix unknown rule warning false positive

crates/rome_cli/src/commands/help.rs
Fixes #3415
This adds the `start` and `stop` commands to the list of commands documented in the "main" help text printed by `rome --help`. I also took the opportunity to add a short summary for the commands in the list to make it easier to see what each command is doing at a glance without having to print the full help text for each command.
N/A
=> fix(rome_cli): improve the main help text

crates/rome_js_formatter/src/js/expressions/arrow_function_expression.rs, crates/rome_js_formatter/tests/specs/jsx/arrow_function.jsx, crates/rome_js_formatter/tests/specs/jsx/arrow_function.jsx.snap
Fix https://github.com/rome/tools/issues/3376
`cargo test -p rome_js_formatter`
=> fix(rome_js_formatter): JSX Expression child closing parentheses #3376

crates/rome_diagnostics/tests/macros/unknown_field_attr.stderr, crates/rome_diagnostics_macros/src/parse.rs
The Rust Compiler already has a mechanism in place to emit an error when an unknown attribute is used in the code, so the procedural macro should simply ignore attributes it doesn't known about. Not only does this prevent a duplicate diagnostic from being emitted, but it's also important to allow attributes from the language (such as the `#[doc = ""]` attribute that doc-comments desugar to) or other proc-macros on types that derive `Diagnostic`
The "unknown attribute" case is already covered but the test suite of the macro, the snapshot has been updated to ensure that only one diagnostic is emitted by the compiler.
=> fix(rome_diagnostics_macros): correctly ignore unknown attributes

crates/rome_js_analyze/src/analyzers/nursery/use_key_with_click_events.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_key_with_mouse_events.rs
In the recent PRs there were few places where we did use the try operator, but in these places it wasn't explicit enough **why** we were using it. 
I changed the code to use `is_none` and early return.  
The CI should work
=> chore(rome_js_analyze): better use of `Option`

crates/rome_cli/src/commands/daemon.rs, crates/rome_cli/src/commands/rage.rs, crates/rome_cli/tests/commands/rage.rs, crates/rome_cli/tests/snapshots/main_commands_rage/rage_ok.snap, crates/rome_cli/tests/snapshots/main_commands_rage/with_configuration.snap, crates/rome_cli/tests/snapshots/main_commands_rage/with_malformed_configuration.snap, crates/rome_cli/tests/snapshots/main_commands_rage/with_server_logs.snap
This PR adds the server log to the output of the `rage` command. 
I initially considered implementing the LSP `trace` notification but preferred to not go with it in the end because:
* Reading the server log from the disk has the advantage that we can extract log messages that have been written **before** rage was called compared to only the log messages written when rage `rage` was run
* The other approach would probably not have worked because the notifications sent by the LSP server would be send AFTER the `rome/rage` command has completed. It would be necessary to implement some wait mechanism on the client to give the server time to send the notifications and then consume every one of them. 
I still plan to spend some time today to explore if it is possible to implement the trace …
=> feat(rome_cli): Add server logs to `rage` command

website/package.json, website/pnpm-lock.yaml
The `format` command uses the latest Rome version (main) to format the files and not the version packed with NPM. We can, therefore, safely remove the dependency on the Rome NPM package.
=> chore(website): Remove rome dependency

crates/rome_diagnostics/CONTRIBUTING.md
This PR adds a new file in `crates/rome_diagnostics/CONTRIBUTING.md` that serves as a documentation on how to write diagnostics, with both technical explanations and best practices to write good errors for the user.
N/A
=> docs(rome_diagnostics): add a contributor documentation file for diagnostics

crates/rome_cli/src/commands/format.rs, crates/rome_cli/src/execute.rs, crates/rome_cli/src/termination.rs, crates/rome_cli/src/traversal.rs, crates/rome_cli/tests/commands/format.rs, crates/rome_cli/tests/main.rs
- Resolves the issue that the error messages in `rome check` and `rome ci` incorrectly refer to the `rome format` command
```
❯ cargo run --bin rome ci --quote-style="double" 
Finished dev [unoptimized + debuginfo] target(s) in 0.08s
Running `target/debug/rome ci --quote-style=double`
Error: missing argument '<INPUT>'. Type 'rome format --help' for more information.
```
- Running `rome check` or `rome ci` with one argument missing or unsupported options and the error message should infer the subcommand
=> fix(rome_cli): print the correct subcommand in error messages

crates/rome_cli/src/commands/init.rs, crates/rome_cli/tests/snapshots/main_init/creates_config_file.snap, website/src/_includes/docs/cli-screenshots/init.md
Short fix for the stated command that should verify formatting _and_ correctness. At the moment, `rome check` does not check the formatting, you'll need to run `rome format .` separately, or just use `rome ci`. That also means `rome check . --apply-suggested` does not fix formatting errors as well. This might be obvious to some but this should avoid some confusion.
Fixes https://github.com/rome/tools/issues/3440
```
cargo insta test
...
cargo insta review
```
Approved that one change
=> fix(rome_cli): state correct command to verify code post `rome init`

crates/rome_cli/src/service/mod.rs
Makes the `open_socket` public for builds targeting windows to fix a build failure and align with builds targeting `unix`.
=> fix(rome_cli): Fix private `open_socket`

crates/rome_cli/src/commands/help.rs
- Resolves #3456
- Per `apply_format_settings_from_cli`
https://github.com/rome/tools/blob/745464fb69d048de348b31b0b28e265b9e9fe0a8/crates/rome_cli/src/commands/ci.rs#L10
`rome ci` supports the following options:
```
--indent-style <tabs|space>              Change the indention character (default: tabs)
--indent-size <number>                   If the indentation style is set to spaces, determine how many spaces should be used for indentation (default: 2)
--line-width <number>                    Change how many characters the formatter is allowed to print in a single line (default: 80)
--quote-style <single|double>            Changes the quotation character for strings (default: ")
--quote-properties <as-needed|preserve>  Changes when properties in object should be quoted (default: …
```
=> fix(rome_cli): remove unsupported options in the `ci` help text

crates/rome_analyze/src/lib.rs, crates/rome_analyze/src/signals.rs, crates/rome_cli/tests/snapshots/main_commands_check/parse_error.snap, crates/rome_cli/tests/snapshots/main_commands_ci/ci_parse_error.snap, crates/rome_diagnostics/src/v2/display/message.rs, crates/rome_js_analyze/src/analyzers/correctness/no_double_equals.rs, crates/rome_js_analyze/tests/specs/correctness/noDoubleEquals.js.snap, crates/rome_service/src/file_handlers/javascript.rs, crates/rome_service/src/file_handlers/mod.rs, crates/rome_service/src/settings.rs, crates/rome_service/src/workspace/server.rs, website/src/docs/lint/rules/noDoubleEquals.md, website/src/docs/lint/rules/useAnchorContent.md, website/src/docs/lint/rules/useValidTypeof.md, xtask/lintdoc/src/main.rs
This PR joins the refactored diagnostics of JS parser and analyzer into a single data structure, which `v2::serde::Diagnostics`.
In theory, once this PR is merged, we could start merging the code in `main`.
CLI tests passed locally. 
The command `cargo lintdoc` now works
=>  refactor(rome_service): use `serde::Diagnostic` in the workspace

crates/rome_js_analyze/src/utils/tests.rs, crates/rome_js_syntax/src/jsx_ext.rs
This PR try to simplify the API for retrieving JSX attributes.  
Unfortunately, to achieve this it needs to use unsafe, because ```JsxAttribute``` is not ```Copy```.
```
let [a, c, d] = list.find_attributes_by_name(["a", "c", "d"]);
```
```
cargo test -p rome_js_analyze -- find_attributes_by_name 
```
=> feat(rome_js_syntax): better api for picking jsx attributes

website/src/credits.md, website/src/docs/lint/rules/index.md, xtask/lintdoc/src/main.rs
* Add lint groups to the TOC
* Make `nursery` the last group (likely the least important)
* Removes `since (v...)` from the overview to reduce the noise (available on the details page)
=> doc(website): Show lint groups in TOC

crates/rome_cli/src/commands/help.rs, crates/rome_js_formatter/src/context/trailing_comma.rs, crates/rome_js_formatter/src/lib.rs, crates/rome_js_formatter/src/utils/array.rs, crates/rome_js_formatter/tests/spec_test.rs, crates/rome_js_formatter/tests/specs/js/module/array/trailing-comma/array_trailing_comma.js.snap, crates/rome_js_formatter/tests/specs/js/module/array/trailing-comma/options.json, crates/rome_js_formatter/tests/specs/js/module/export/trailing-comma/export_trailing_comma.js.snap, crates/rome_js_formatter/tests/specs/js/module/export/trailing-comma/options.json, crates/rome_js_formatter/tests/specs/js/module/import/trailing-comma/import_trailing_comma.js.snap, crates/rome_js_formatter/tests/specs/js/module/import/trailing-comma/options.json, crates/rome_js_formatter/tests/specs/js/module/object/trailing-comma/object_trailing_comma.js.snap, crates/rome_js_formatter/tests/specs/js/module/object/trailing-comma/options.json, crates/rome_js_formatter/tests/specs/ts/class/trailing_comma/class_trailing_comma.ts.snap, crates/rome_js_formatter/tests/specs/ts/class/trailing_comma/options.json, crates/rome_js_formatter/tests/specs/ts/enum/enum_trailing_comma.ts.snap, crates/rome_js_formatter/tests/specs/ts/enum/options.json, crates/rome_js_formatter/tests/specs/ts/function/function_trailing_comma.ts.snap, crates/rome_js_formatter/tests/specs/ts/function/options.json, crates/rome_js_formatter/tests/specs/ts/object/object_trailing_comma.ts.snap, crates/rome_js_formatter/tests/specs/ts/object/options.json, crates/rome_js_formatter/tests/specs/ts/type/trailing-comma/options.json, crates/rome_js_formatter/tests/specs/ts/type/trailing-comma/type_trailing_comma.ts.snap, crates/rome_service/src/configuration/javascript.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, website/playground/src/TrailingCommaSelect.tsx, website/playground/src/types.ts
Add `none` option for `TrailingComma`.
`cargo test -p rome_js_formatter`
=> feat(rome_js_formatter): trailing comma none

crates/rome_cli/src/traversal.rs, crates/rome_cli/tests/commands/format.rs, crates/rome_cli/tests/configs.rs, crates/rome_cli/tests/snap_test.rs, crates/rome_cli/tests/snapshots/main_commands_format/does_not_format_ignored_directories.snap, crates/rome_cli/tests/snapshots/main_commands_format/write_only_files_in_correct_base.snap, crates/rome_fs/src/fs/memory.rs
There was an issue in the `rome ci` command, but we couldn't see it because the `MemoryFileSystem` behaves differently when handling the files, compared to `OsFileSystem`. By default, it was accepting any kind of file and it was using the `strip_prefix` function. This results in two issues:
- couldn't simulate commands like `rome format .` (the dot)
- couldn't replicate 100% how the real traversal behaves
This PR tries to change that behaviour.
- I added a new test case for ignoring directories, and see if it works as expected.
- Once I added the `can_handle` function,  the test `ci_does_not_run_linter` was failing, because it was wrongly computing when a file is ignored. That's fixed in the `traversal.rs`
=> fix(rome_cli): correctly compute file to handle in `rome ci`

npm/rome/scripts/generate-packages.mjs
Closes #3482  
I manually checked that the updated `package.json` doesn't contain optional dependencies to wasm packages.
=> chore(rome): remove WASM pacakges from optional dependencies

crates/rome_js_parser/src/syntax/expr.rs, crates/rome_js_parser/test_data/inline/ok/optional_chain_call_less_than.rast, crates/rome_js_parser/test_data/inline/ok/optional_chain_call_less_than.ts
This PR fixes a false diagnostic for call expressions that are part of an optional chain (static member) that are then followed by a binary `<` expression.
```
String(item)?.b <aBcd;
```
The problem is that the error recovery code for `a.test?.` incorrectly kicked in which should not happen if what followed after the call expression is a valid static member expression in an optional chain.
fixes #3486
=> fix(rome_js_parser): call expression in optional member chain followed by `<`

.github/workflows/release_js_api.yml
The `update-nightly-version` script needs to be run in the `publish` job to ensure the version is correctly set in the `package.json` manifest of the `@rometools/js-api` package before it gets pushed to npm
Publish a nightly / pre-release version of the JS API
=> fix(ci): run the version update script in the publish job of the js-api release workflow

npm/js-api/scripts/update-nightly-version.mjs, npm/rome/package.json, npm/rome/scripts/update-nightly-version.mjs
This PR changes the prefix of the pre-release tag applied to nightly versions from `-next` to `-nightly`
Publish a nightly version of `@rometools/js-api` and check it has the correct tag
=> fix(ci): fix the pre-release tag for nightly versions

crates/rome_cli/src/traversal.rs, crates/rome_cli/tests/commands/ci.rs, crates/rome_cli/tests/snapshots/main_commands_ci/ci_runs_linter_not_formatter_issue_3495.snap
Closes #3495 
Added a new test case
=> fix(rome_cli): correctly compute `can_handle` in CI mode

crates/rome_lsp/src/capabilities.rs, crates/rome_lsp/src/documents.rs, crates/rome_lsp/src/handlers/text_document.rs, crates/rome_lsp/tests/server.rs
Historically our LSP implementation has been using full document sync, where the editor sends the entire content of the document on every change notification, since it's easier to get right. However sending the whole buffer is a heavy operation, so VSCode will debounce change notifications or defer them until other language server requests are sent. This has caused [issues](https://github.com/rome/tools/issues/2932) in the past with requests being deferred too much causing the document state to go out of sync between the editor and language server.
This PR implements support for the incremental document sync mode where the editor sends in individual changes as they happen, meaning updates can be processed more frequently and could generally cause the editor experience to feel more …
=> feat(rome_lsp): add support for incremental document sync in the language server

crates/rome_js_analyze/src/analyzers/style/no_negation_else.rs
Closes https://github.com/rome/tools/issues/3141
Added a new test case from the issue that was filed
=> fix(rome_js_analyze): don't check double negation in `noNegationElse`

crates/rome_cli/src/traversal.rs, crates/rome_lsp/src/session.rs, crates/rome_service/src/file_handlers/javascript.rs, crates/rome_service/src/file_handlers/mod.rs, crates/rome_service/src/workspace.rs, crates/rome_service/src/workspace/server.rs, npm/backend-jsonrpc/src/workspace.ts, npm/js-api/src/index.ts, website/playground/src/romeWorker.ts
This PR adds a new `max_diagnostics` field to `PullDiagnosticsParams` that limits how many diagnostics are emitted in the `diagnostics` field of `PullDiagnosticsResult`, and maintains a counter of `skipped_diagnostics` as well as an `has_errors` flag to allow checking if any of the skipped diagnostics had a severity of `Error` or higher. The `max_diagnostics` value is not a hard limit, and more diagnostics may be emitted by the parser. This new argument is used in the CLI since it's only printing a limited amount of diagnostics, the console thread now maintains an approximate counter of `remaining_diagnostics` that can still be printed, and the shared value of this counter is used as the value of `max_diagnostics` in the worker threads of the traversal.
This change is covered by the test …
=> feat(rome_service): add a `max_diagnostics` parameter to `pull_diagnostics`

crates/rome_cli/tests/snapshots/main_commands_check/upgrade_severity.snap, crates/rome_js_analyze/src/control_flow/nodes/for_stmt.rs, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsForStatement.js, crates/rome_js_analyze/tests/specs/nursery/noUnreachable/JsForStatement.js.snap
Fixes #3511
This PR fixes the control flow graph generation of for-statements with no `test` node by correctly generating an unconditional jump edge from the condition block to the loop block instead of not generating an edge at all.
I've added an additional test case for the `noUnreachable` rule to check this, and updated a CLI snapshot that was also triggering the rule
=> fix(rome_js_analyze): fix how control flow edges are generated in for-statements with no test node

crates/rome_js_analyze/src/analyzers/style/no_negation_else.rs, crates/rome_js_analyze/tests/specs/style/noNegationElse/issue_3141.js, crates/rome_js_analyze/tests/specs/style/noNegationElse/issue_3141.js.snap
This is a follow up of https://github.com/rome/tools/pull/3491#discussion_r1006798333
Added a new test case
=> fix(rome_js_analyze): additional check for `noNegationElse`

crates/rome_diagnostics/src/v2/display/diff.rs, crates/rome_js_analyze/tests/specs/correctness/noDebugger.js.snap, crates/rome_js_analyze/tests/specs/correctness/noUnnecessaryContinue.js.snap, crates/rome_js_analyze/tests/specs/nursery/noVoidElementsWithChildren/createElement.js.snap, website/src/docs/lint/rules/noUnnecessaryContinue.md
Fixes #3515
This PR changes how line breaks are handled in diffs, and specifically how individual lines get marked as "modified" when a line break is removed or inserted. It fixes an issue with the rendering of diffs from the formatter, but also changes when diffs are allowed to be rendered in short mode as the removal of an entire line is now shown in full mode (with the surrounding lines of context).
I've added an additional test case for this and updated the ellipsis case since it was actually being rendered incorrectly. I've also improved how markup assertion mismatches are displayed in the tests to ensure these kinds of issue are easier to notice in the future, and update a few snapshots related to the short mode changes.
=> fix(rome_diagnostics): improve the handling of newline characters in diffs

crates/rome_cli/src/commands/check.rs, crates/rome_cli/src/commands/ci.rs, crates/rome_cli/src/commands/format.rs, crates/rome_cli/src/configuration.rs, crates/rome_cli/src/lib.rs, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/commands/ci.rs, crates/rome_cli/tests/commands/format.rs, crates/rome_cli/tests/configs.rs, crates/rome_cli/tests/snapshots/main_commands_check/file_too_large.snap, crates/rome_cli/tests/snapshots/main_commands_check/file_too_large_cli_limit.snap, crates/rome_cli/tests/snapshots/main_commands_check/file_too_large_config_limit.snap, crates/rome_cli/tests/snapshots/main_commands_check/files_max_size_parse_error.snap, crates/rome_cli/tests/snapshots/main_commands_ci/file_too_large.snap, crates/rome_cli/tests/snapshots/main_commands_ci/file_too_large_cli_limit.snap, crates/rome_cli/tests/snapshots/main_commands_ci/file_too_large_config_limit.snap, crates/rome_cli/tests/snapshots/main_commands_ci/files_max_size_parse_error.snap, crates/rome_cli/tests/snapshots/main_commands_format/file_too_large.snap, crates/rome_cli/tests/snapshots/main_commands_format/file_too_large_cli_limit.snap, crates/rome_cli/tests/snapshots/main_commands_format/file_too_large_config_limit.snap, crates/rome_cli/tests/snapshots/main_commands_format/files_max_size_parse_error.snap, crates/rome_service/src/configuration/mod.rs, crates/rome_service/src/lib.rs, crates/rome_service/src/settings.rs, crates/rome_service/src/workspace/server.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts
This PR introduces a `files.maxSize` configuration to set the maximum allowed file size for the workspace. I've also reworded the error message that's emitted for skipped files to use the same messaging as Rome JS, that focuses on performance and doesn't mention parsing.
I've added additional test cases for the CLI to check that the option is correctly applied, and update existing snapshots for the tests of the default limit with the new error message.
=> feat(rome_service): add a configuration option to set the file size limit of the workspace

crates/rome_js_parser/src/syntax/binding.rs, crates/rome_js_parser/src/tests.rs, crates/rome_js_parser/test_data/inline/ok/destructuring_initializer_binding.js, crates/rome_js_parser/test_data/inline/ok/destructuring_initializer_binding.rast
Rome's parser implements a very limited check for duplicated bindings by testing if there are no duplicate bindings in the same variable declaration.
This PR fixes an issue where the parser flagged a binding with the same name inside a destructuring initializer as a duplicated binding which is incorrect.
Fixes #3521  #2960
=> fix(rome_js_parser): Ignore bindings in desctructuring initializers

crates/rome_js_formatter/src/lib.rs, crates/rome_js_parser/src/lib.rs
I noticed that the formatter documentation mentions how to create and run parser tests when reviewing #3536
This PR moves the documentation to `rome_js_parser`.
=> doc(rome_js_parser,rome_js_formatter): Move Parser Test documentation

.github/workflows/release_cli.yml, .github/workflows/release_lsp.yml, editors/vscode/.vscodeignore, editors/vscode/package-lock.json, editors/vscode/package.json
Fixes #3541 
This PR fixes an issue with our CI pipeline where it didn't set the ROME_VERSION env variable correctly. 
It took me a while to figure out the issue but the problem is that `"var=value" >> $GITHUB_ENV` doesn't work on windows builds where you must use `$Env::GITHUB_ENV` instead. 
I fixed it by:
* Moving the part where we write the version number to the *Check Version* job that always runs on linux builds
* Later only rely on `env` that works on all runners. 
This PR also removes the `node_moduels` folder from the published VS Code extension. It isn't necessary to publish `node_modules` because we pre-built the javascript file with `esbuild`. 
Downloaded the artefacts from nightly builds and installed them locally. 
* Installed the VS Code extension and verified that …
=> ci: Fix version on windows build

crates/rome_js_analyze/src/analyzers/a11y/use_anchor_content.rs, website/src/docs/lint/rules/useAnchorContent.md
There is an invalid diagnostic example for [`useAnchorContent`](https://rome.tools/docs/lint/rules/useanchorcontent/). This PR fixes the issue.
PR checks
=> docs(website): fix an invalid diagnostic example for `useAnchorContent`

crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs, crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/extraDependenciesInvalid.js, crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/extraDependenciesInvalid.js.snap, crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/missingDependenciesInvalid.js, crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/missingDependenciesInvalid.js.snap, crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/valid.js, crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/valid.js.snap, crates/rome_js_semantic/src/semantic_model.rs, crates/rome_js_semantic/src/semantic_model/is_constant.rs, crates/rome_js_semantic/src/tests/references.rs, website/src/docs/lint/rules/useExhaustiveDependencies.md
This PR extends support of useExhaustiveDependencies to consider constant captures as not needed in the dependency list.
The current implementation assumes that every expression without a reference is a constant.  
This bring us some polemic cases:
- {}
- []
- function () {}
- () => {}
- class {}
These are all considered constants, even though
- {} === {} equals false
- [] === [] equals false
- (function () {}) === (function () {}) equals false
- {} === {} equals false
- (class {}) === ( class {}) equals false
I think this is the case because JS decided to test them by reference and not by value. There are libs specially made to implement equality by value, for example: https://www.npmjs.com/package/are-equal and any assert library. I would say that equality by value is stronger than …
=> fix(rome_js_analyze): fix const dependency in react hooks

crates/rome_cli/src/commands/init.rs, crates/rome_cli/tests/snapshots/main_init/creates_config_file.snap, website/src/_includes/docs/configuration.md, website/src/_includes/docs/formatter.md, website/src/_includes/docs/getting-started.md, website/static/_redirects
This PR sets up static permalinks for the URLs used by the CLI so that changes to the website structure no longer require updating the CLI. 
This PR also slightly improves the rendering of the `rome init` command.
* I opened the permalinks from my browser and verified that they redirect me to the correct sections
=> doc(rome_cli): Use permalinks in `rome init`

crates/rome_diagnostics/CONTRIBUTING.md
and fix a link to the technical philosophy.
The main motivation behind moving the writing to the top is that I want to link from it from the blog post but it being at the bottom means the browser can't scroll to the top of the section.
The second reason is that it's probably good to know what a diagnostic should be before learning all the technical jargon and details.
=> docs(rome_diagnostics): Move Writing Diagnostics to the top

crates/rome_js_formatter/src/utils/mod.rs, crates/rome_js_formatter/tests/specs/js/module/interpreter.js.snap, crates/rome_js_formatter/tests/specs/js/module/interpreter_with_empty_line.js, crates/rome_js_formatter/tests/specs/js/module/interpreter_with_empty_line.js.snap, crates/rome_js_formatter/tests/specs/js/module/script.js.snap, crates/rome_js_formatter/tests/specs/js/script/script.js.snap
Closes #3497
I updated snapshot results by `cargo insta review`.
=> fix(rome_js_formatter): make empty line after hashbang optional

crates/rome_js_analyze/src/analyzers/nursery/no_invalid_constructor_super.rs, crates/rome_js_analyze/tests/specs/nursery/noInvalidConstructorSuper.js, crates/rome_js_analyze/tests/specs/nursery/noInvalidConstructorSuper.js.snap, website/docs/src/lint/rules/noInvalidConstructorSuper.md
- Resolves https://github.com/rome/tools/issues/3560
Added new test cases for export declarations
=> fix(rome_js_analyzer): `noInvalidConstructorSuper` false positive for class expressions

crates/rome_cli/src/execute.rs, crates/rome_cli/src/traversal.rs
This PR changes how threads are spawned during parallel traversal operations: it merges the console and report tasks into a single dedicated thread running outside of the Rayon thread pool, so that all threads in the pool are now available to process files.
I've also made the initial setup of input tasks run on the main thread (to avoid allocating an extraneous thread for this), and replaced some redundant cloning operations of the traversal state with shared references (this is made possible by using the scoped thread API of the standard library from Rust 1.63)
This is purely an internal change, it should have no noticeable side effect other than possibly improving traversal performance on multi-core systems, and the existing test suite of the CLI should ensure this is actually the case.
=> refactor(rome_cli): refactor the threading of parallel traversal to increase occupancy

editors/vscode/README.md
This PR extends the README of the VS Code extension that users see when navigating to the Rome marketplace page or opening the extension in VS Code.
[README](https://github.com/rome/tools/blob/doc/editor/editors/vscode/README.md)
=> doc: VS Code extension

.github/workflows/release_cli.yml, .github/workflows/release_js_api.yml
This PR makes a few changes to the release workflows before the stable release:
- Publish releases to the `rome` npm package under the `latest` tag instead of `next`
- Ensure the `prerelease` environment variable is correctly exported in CLI nightly builds
- Publish the `js-api` using its path instead of package name
Test run of the `release_cli` workflow: https://github.com/rome/tools/actions/runs/3418383900
Test run of the `release_js_api` workflow: https://github.com/rome/tools/actions/runs/3418397143
=> fix(ci): fix the release workflows for the stable release

.github/workflows/release_js_api.yml, npm/rome/README.md
This fixes how the Rome logo is displayed in the README when the markdown file is rendered outside of GitHub. The logo exists in two versions for dark and light mode, and the correct version to display in the readme was selected using the `gh-light-mode-only` and `gh-dark-mode-only` fragments. This logic is GitHub-specific though, and doesn't work when the readme file is rendered outside of GitHub (for instance on the `rome` npm package: https://www.npmjs.com/package/rome/v/0.10.1-nightly.a9db0f0). I've replaced the images with the standard `picture` element to automatically select the correct version of the image using the `prefers-color-scheme: dark` CSS media query.
I've also rolled up a simple fix to the `release_js_api` workflow into this, it fixes the creation of GitHub releases for …
=> fix(docs): use the standard picture element to display the logo

crates/rome_cli/src/commands/ci.rs, crates/rome_cli/tests/commands/ci.rs, crates/rome_cli/tests/snapshots/main_commands_ci/ci_does_not_run_formatter.snap, crates/rome_cli/tests/snapshots/main_commands_ci/ci_does_not_run_formatter_via_cli.snap
Fixes an issue where `rome ci` ignored the `formatter.enabled` and `linter.disabled` configuration. The issue was that the CI defaulted to `true` when the `--formater/linter-enabled` options weren't specified.
The existing integration test didn't work because Rome doesn't check the formatting for files with lint/parse errors. I changed the integration test to a file that only has incorrect formatting.
=> fix(rome_cli): Respect formatter/linter `enabled` from configuration

npm/rome/package.json
Adds a `license` field to the `rome` npm package
Closes #3628
N/A
=> chore(npm): add license

editors/vscode/README.md
Corrects how the extension resolves Rome and how to make the extension use the latest version after an update.
=> doc(editors): Clarify Rome discovery

crates/rome_js_analyze/src/analyzers/a11y/use_key_with_click_events.rs, crates/rome_js_analyze/src/utils/tests.rs, crates/rome_js_syntax/src/jsx_ext.rs, website/docs/src/lint/rules/index.md, website/docs/src/lint/rules/useKeyWithClickEvents.md
Interactive elements like `button`, `a`, `input` etc. don't need key events as they are supported by the browser.
This is a simplified implementation and the rule should also consider if the element is hidden for screen readers but that's out of the scope of this fix. See #3640
I added a new test that verifies that `button` no longer gets flagged.
This reduces the number of lint warnings and is thus, safe to land
=> fix(rome_js_analyze): False positives for interactive elements in `useKeyWithClickEvents`

crates/rome_cli/src/commands/rage.rs, crates/rome_cli/src/service/mod.rs, crates/rome_cli/src/service/unix.rs, crates/rome_cli/src/service/windows.rs
Fixes #3637
This PR changes the path of the named pipe / domain socket used to communicate between the language client and server to include the version string of `rome_service`. This ensures a given instance of the Rome CLI binary always spawns (and connects to) an instance of the Rome daemon it's compatible with.
Due to the nature of this check (using filesystem paths) the comparison between version IDs is a strict equality, however as the version string of `rome_service` is an internal value we could change it independently from the main Rome version number. We could also truncate the patch number from the version string, but for now I expect even patch release of Rome may include breaking changes to the protocol so I'm leaving the full version string.
I tested this locally by running …
=> fix(rome_cli): ensures the service only connects to compatible versions

crates/rome_cli/src/commands/daemon.rs, crates/rome_cli/src/lib.rs, crates/rome_cli/src/service/unix.rs, crates/rome_cli/src/service/windows.rs, crates/rome_lsp/src/server.rs, crates/rome_lsp/src/session.rs, editors/vscode/README.md
Fixes #3636
This change makes use of the existing session tracking code to schedule a background task once the last session is dropped from the server. After a short timeout (correctly set at 60 seconds), this task will broadcast the shutdown signal to the server if no new session was started in the meantime.
This behavior can be disabled by passing the `--no-timeout` flag to the `__run_server` internal command, this is done automatically by the `rome start` command to ensure manually started instances of the server never times out. Importantly, the timeout task is only scheduled when a client disconnects, meaning a newly started server instance will run indefinitely until at least one client connects event if it wasn't passed the `--no-timeout` flag (this should rarely happen if ever as …
=> feat(rome_lsp): stop the daemon after the last client disconnects

npm/js-api/package.json, npm/js-api/src/daemon.ts, npm/js-api/src/nodeWasm.ts
The wasm and backendjsonrpc dependencies are both marked as optional but the implementation loads packages statically, making the `js-api` fail immediately if one of the two isn't installed.
This PR moves the imports into lazy async calls.
=> fix(npm/js-api): Lazy load backend implementations

npm/js-api/src/index.ts
Imports `Diagnostic` and `Configuration` as type instead of an object
=> fix(npm/js-api): Import type from @rometools/backend-jsonrpc

website/docs/src/formatter/index.md
using `tabs` gives the following error so updating the docs:
```
Error: failed to parse argument '--indent-style': failed to parse 'tabs': Value not supported for IndentStyle
```
ran  
```
rome format --indent-style tab . 
```
and it worked
=> docs: change indent-style from tabs to tab

website/src/pages/guides/getting-started.mdx
According to https://pnpm.io/cli/install `pnpm install` is used to install a whole project and not to add a single dependency. `pnpm add` should be used instead.
I just tried to use `pnpm install` like shown here and it surprisingly worked but since this is not documented it might be better to use `pnpm add` in Rome's documentation.
=> Fix pnpm install command

website/src/pages/configuration.mdx
https://docs.rome.tools/configuration/ cannot be accessed from the sidebar.
Solution: add `category: reference` to frontmatter.
=> docs(configuration): add to sidebar

website/src/playground/Playground.tsx, website/src/playground/components/CodePane.tsx, website/src/playground/components/SettingsPane.tsx, website/src/playground/utils.ts, website/src/styles/playground.scss
This PR adds the ability to resize the playground code view and collapse settings. These settings are remembered.
https://user-images.githubusercontent.com/853712/201496160-1a60fe1f-91af-4836-93b8-9b88810922b5.mov
=> website(docs): Add ability to resize playground code view and collapse settings

netlify.toml, website/build-netlify.sh
This PR removes the `base` property from `netlify.toml`. Netlify checks if there are any changes to the base directory to decide if it needs to skip a build. Unfortunately, since we merged the playground into the docs, we should be doing a build for every playground change. After this PR the builds will no longer be skipped.
=> website(docs): Remove base property from netlify.toml

npm/js-api/README.md, npm/rome/README.md, rfcs/002-runtime-api.md, website/src/components/cli-screenshots/noUnreachable-example.md
I found that some links were broken, so I fixed them.
note: I discovered that some links referring to the https://rome.github.io/tools/ were also broken, but was unable to fix them because I did not know the proper links.
=> docs: fix broken links

xtask/contributors/src/main.rs, xtask/lintdoc/src/main.rs
lintdoc is generating md files under `website/docs` but that path has been changed.
NA
=> fix(lindoc): fix generated docs path

npm/backend-jsonrpc/package.json, npm/js-api/package.json, npm/rome/package.json
This will add a standard link to the repo in the npm registry website.
For reference: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository
After the next publish to npm, the packages on the npm website should link to the correct directory in GitHub.
=> docs: Add `repository` field in `package.json` files of published npm packages

crates/rome_js_formatter/src/jsx/attribute/expression_attribute_value.rs, crates/rome_js_formatter/src/lib.rs, crates/rome_js_formatter/tests/specs/jsx/attributes.jsx, crates/rome_js_formatter/tests/specs/jsx/attributes.jsx.snap
Fix https://github.com/rome/tools/issues/3531#issuecomment-1311698292
https://github.com/prettier/prettier/blob/ae3dd17114bfb9831b85816f927eea90dcb0968b/src/language-js/print/jsx.js#L506-L521
[Playground](https://docs.rome.tools/playground/?code=%3COtherComponent%0A%09value%3D%7B%0A%09%09new+Set%28veryLongConditionZzzzzzzzzzzzzzzzzveryLongConditionZzzzzzzzzzzzzzzzzveryLongConditionZzzzzzzzzzzzzzzzz%29%0A%09%7D%0A%2F%3E#PABPAHQAaABlAHIAQwBvAG0AcABvAG4AZQBuAHQACgAJAHYAYQBsAHUAZQA9AHsACgAJAAkAbgBlAHcAIABTAGUAdAAoAHYAZQByAHkATABvAG4AZwBDAG8AbgBkAGkAdABpAG8AbgBaAHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAdgBlAHIAeQBMAG8AbgBnAEMAbwBuAGQAaQB0AGkAbwBuAFoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB2AGUAcgB5AEwAbwBuAGcAQwBvAG4AZABpAHQAaQBvAG4AWgB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6AHoAegB6ACkACgAJAH0AC …
=> fix(rome_js_formatter): new expression attribute

crates/rome_js_parser/src/syntax/expr.rs, crates/rome_js_parser/src/syntax/function.rs, crates/rome_js_parser/test_data/inline/err/async_arrow_expr_await_parameter.js, crates/rome_js_parser/test_data/inline/err/async_arrow_expr_await_parameter.rast, crates/rome_js_parser/test_data/inline/err/await_in_module.js, crates/rome_js_parser/test_data/inline/err/await_in_module.rast, crates/rome_js_parser/test_data/inline/err/await_in_non_async_function.js, crates/rome_js_parser/test_data/inline/err/await_in_non_async_function.rast, crates/rome_js_parser/test_data/inline/err/await_in_parameter_initializer.rast, crates/rome_js_parser/test_data/inline/err/await_in_static_initialization_block_member.js, crates/rome_js_parser/test_data/inline/err/await_in_static_initialization_block_member.rast, crates/rome_js_parser/test_data/inline/err/no_top_level_await_in_scripts.rast, crates/rome_js_parser/test_data/inline/ok/reparse_await_as_identifier.js, crates/rome_js_parser/test_data/inline/ok/reparse_await_as_identifier.rast
Fixes:
* https://github.com/rome/tools/issues/2479
Added unit tests for the scenarios.
=> fix(rome_js_parser): improve await handling in non-async context

website/src/pages/formatter/index.mdx
As discussed in https://github.com/rome/tools/discussions/3698#discussioncomment-4128011 if you are new to the world of formatting it might be hard to understand at first why Rome (and Prettier) are so opinionated. Prettier has a whole philosophy page which might be overkill at this point. But adding just a few of these links add's a lot of necessary context as they will either immediately resonate or alienate people which are looking for a less opinionated tool.
=> doc(website): Add context about Romes philosophy

crates/rome_analyze/src/lib.rs, crates/rome_analyze/src/matcher.rs, crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/tests/specs/correctness/noUnreachable/SuppressionComments.js.snap, crates/rome_service/src/file_handlers/javascript.rs, npm/backend-jsonrpc/src/workspace.ts
Fixes #3655
This PR tracks whether any signal was suppressed by a suppression comment. Once all analyzer passes have completed, a warning is emitted for all line suppressions that never actually recorder any hit. While the change is mostly straightforward, it still requires some special handling in `pull_diagnostics` to ensure we don't report unused suppression diagnostics in syntax-only passes of the analyzer (were all lint rules are disabled, and thus suppression comments are never hit)
I updated the existing suppression tests to ensure the new diagnostic is correctly emitted, as well as the `SuppressionComments` snapshot test for the `noUnreachable` rule that was also impacted by this change (since it has a negative case to check that certain comment positions do not suppress the rule)
=> feat(rome_analyze): add a warning for unused suppression comments

website/src/styles/_global.scss, website/src/styles/_mixins.scss
`color-scheme` was previously set on `input`s only, while we can set it on the root/html element to affect other elements on the page, including scrollbars.
I've also added the `only` keyword to prevent user agents from applying color overrides.
I've also changed from the `html` selector to `:root`, shouldn't matter much, though I do wonder if browsers optimize it as there can only be one `:root` per document, while you are allowed to create random `html` elements and append them just about anywhere.
For reference:
https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme
https://developer.mozilla.org/en-US/docs/Web/CSS/:root
Tested in the live website with Chrome's DevTools.
Double-checked with the deploy preview.
=> website(docs): set `color-scheme` on the root element

crates/rome_lsp/src/server.rs
Fixes #3522
This change forces a diagnostic update on all open documents after a configuration update event
I tested this locally by ensuring that disabling a lint rule in the configuration cause all the corresponding diagnostics to disappear on save
=> fix(rome_lsp): update all diagnostics after a configuration change

editors/vscode/README.md, editors/vscode/package-lock.json, editors/vscode/package.json, editors/vscode/src/main.ts
Fixes #3635
This PR makes use of the `resolve` library to resolve the corresponding `@rometools/cli-*` package for the current platform from each workspace root folder. This lets the extension automatically detect and use the correct version of the language server if the workspace has an explicit dependency on the `rome` package
I built and installed the extension locally, opened a test workspace with the `rome` package installed, and checked the extension is correctly using the version of Rome loaded from npm instead of its own bundled binary
=> feat(vscode): try to resolve the rome package from the workspace root

crates/rome_cli/src/commands/help.rs, crates/rome_cli/src/lib.rs, crates/rome_cli/src/main.rs, crates/rome_cli/tests/main.rs, crates/rome_console/src/lib.rs, crates/rome_js_semantic/src/tests/assertions.rs, website/src/pages/cli.mdx, xtask/lintdoc/src/main.rs
Fixes #3623
This adds a new `--force-colors` argument to the CLI to force the `EnvConsole` to use ANSI colors event if the stream would have otherwise been determined to be incompatible (not a TTY)
I've added a few tests that ensure the `--no-colors` and `--force-colors` arguments are correctly parsed, unfortunately it's not really possible to check they actually work since this relies on using the actual `EnvConsole` instead of the `MemoryConsole` and writes directly to the stdout / stderr streams using `termcolor`, meaning it's not possible to inspect the output that got written by the CLI run (this also means the tests also circumvent the `println!` inhibiting behavior of the Rust test framework and write directly to the test output anyway)
=> feat(rome_cli): add a `--force-colors` argument

crates/rome_analyze/src/categories.rs, crates/rome_analyze/src/lib.rs, crates/rome_js_analyze/src/assists/correctness/flip_bin_exp.rs, crates/rome_js_analyze/src/assists/correctness/inline_variable.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_camel_case.rs, crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs, crates/rome_lsp/src/handlers/analysis.rs, crates/rome_lsp/src/utils.rs, crates/rome_lsp/tests/server.rs, crates/rome_service/src/file_handlers/javascript.rs, crates/rome_service/src/workspace.rs, npm/backend-jsonrpc/src/workspace.ts
This PR adds new variants and sub-enums to the `ActionCategory` enum in `rome_analyze` to allow creating code actions with other "root kinds" than `quickfix` and `refactor` (such as `source`), as well as express sub-types for refactor and source actions (such as `extract`, `inline` and `rewrite` for refactors).
In addition to this, code action kinds are now suffixed with `.rome.<rule group>.<rule name>`: this allows user to specify they want the "Fix All" action exposed by Rome instead of any fix-all action to be applied automatically on save using `"editor.codeActionsOnSave": { "source.fixAll.rome": true }`, or to explicitly request that code actions emitted by a given rule are applied automatically (again by adding entries such as `quickfix.rome.correctness.useWhile` to …
=> feat(rome_analyze): extend ActionCategory to allow expressing more code action kinds

crates/rome_js_formatter/src/jsx/lists/child_list.rs, crates/rome_js_formatter/src/lib.rs, crates/rome_js_formatter/tests/specs/jsx/element.jsx, crates/rome_js_formatter/tests/specs/jsx/element.jsx.snap
Partial fix https://github.com/rome/tools/issues/3531
```
function Component3() {
return (
<div>
{fn(data)}{' '}
<Component />
</div>
);
}
function Component4() {
return (
<div>
{fn(datadatadatadatadatadatadatadatadatadatadatadatadatadatadatadata)}{' '}
<Component />
</div>
);
}
```
Prettier transforms `{' '}` in `JSXText` which is a meaningful text.
- https://github.com/prettier/prettier/blob/ae3dd17114bfb9831b85816f927eea90dcb0968b/src/language-js/print/jsx.js#L91-L98
- https://github.com/prettier/prettier/blob/ae3dd17114bfb9831b85816f927eea90dcb0968b/src/language-js/print/jsx.js#L819-L825
- https://github.com/prettier/prettier/blob/ae3dd17114bfb9831b85816f927eea90dcb0968b/src/language-js/print/jsx.js#L135-L137
`cargo test -p rome_js_formatter`
=> fix(rome_js_formatter): jsx whitespace is meaningful jsx text

CONTRIBUTING.md
The internal documentation links are broken in contributing.md. Just update the links to the correct url.
=> docs(contributing): update internal documentation links 

.github/workflows/parser_conformance.yml
Closes https://github.com/rome/tools/issues/3682
It's weird that conformance always runs even though we have the paths in the workflow. Personally I don't know if this fixes the issue, but I noticed that the paths of this workflow are different from the workflows that work.
Merge it and see if a new PR doesn't trigger the workflow?
=> ci: fix conformance workflow

website/src/pages/configuration.mdx, website/src/pages/formatter/index.mdx
I was confused that there are language-specific config options in a section other than `formatting`, so I've added some notes to the docs. 
Issue: https://github.com/rome/tools/issues/3632
=> Add notes about language-specific config

crates/rome_js_formatter/src/js/expressions/unary_expression.rs, crates/rome_js_formatter/src/js/statements/return_statement.rs, crates/rome_js_formatter/src/utils/conditional.rs, crates/rome_js_formatter/tests/specs/js/module/expression/unary_expression_verbatim_argument.js, crates/rome_js_formatter/tests/specs/js/module/expression/unary_expression_verbatim_argument.js.snap, crates/rome_js_formatter/tests/specs/js/module/statement/return_verbatim_argument.js, crates/rome_js_formatter/tests/specs/js/module/statement/return_verbatim_argument.js.snap
… 
This PR fixes #3735 by only adding parentheses around the argument if the argument isn't suppressed. This is necessary because the verbatim formatting of the argument includes the parentheses too. Formatting the parentheses in the return/unary formatting and as part of the verbatim results in duplicating the parentheses on every save.
I added a handful of new tests covering the problematic cases.
=> fix(rome_js_formatter): Unnecessary parentheses for return/unary with verbatim argument

crates/rome_lsp/src/handlers/analysis.rs, crates/rome_lsp/src/handlers/formatting.rs, crates/rome_lsp/src/handlers/rename.rs, crates/rome_lsp/src/handlers/text_document.rs, crates/rome_lsp/src/line_index.rs, crates/rome_lsp/src/utils.rs
Fixes #3733
This PR ensures the `LineIndex` utility (used to convert between the `LineCol` and `TextSize` representations of text positions within the language server) correctly accounts for UTF-8 character boundaries by properly converting between column numbers and byte offsets instead of directly reinterpreting each value kind as the other. I've also introduced additional error checking (especially in the `line_col` method that's not failible just like `offset`) to ensure that invalid text positions properly return `None` rather than an invalid offset (or panic)
I've added new test cases for `LineIndex` to check the result of both `offset` and `line_col` with various kinds of valid or invalid input
=> fix(rome_lsp): improve the handling of UTF-8 and overflow errors in `LineIndex`

website/src/components/NavigationSidebar.astro
Currently, clicking "Blog" when in `doc.rome.tools` from mobile, results in 404. So I hard-coded the link like in https://github.com/rome/tools/blob/acffd660ebbd9b0b10d39b77ae4cd1fd305a0d8e/website/src/BaseLayout.astro#L80
=> docs(website): fix broken link to blog

crates/rome_js_analyze/src/analyzers/correctness/no_unreachable.rs, crates/rome_js_analyze/tests/specs/correctness/noUnreachable/JsTryFinallyStatement.js.snap, crates/rome_js_analyze/tests/specs/correctness/noUnreachable/issue-3654.js, crates/rome_js_analyze/tests/specs/correctness/noUnreachable/issue-3654.js.snap
Fixes #3654
This changes the analysis of exception control flow to stop at the first catch handler while visiting an exception branch instead of unwinding all the way to the function root.
I've added a new test case for check for regressions for the associated issue. I've also updated the `JsTryFinallyStatement` snapshot since the fix also improves the diagnostics emitted by `noUnreachable` in some cases.
=> fix(rome_js_analyze): improve exception control flow handling

.github/workflows/bench_cli.yml
This adds a new `!bench_cli` command similar to the existing `!bench_*` comments we can use to trigger benchmark runs of the analyzer, formatter and parser on pull requests. The CLI is special though as it's using `hyperfine` to run the actual CLI binary on the same repos used for the benchmark suite in `benchmark/` (Webpack, Prettier and ESLint), as opposed to using `criterion` to benchmark individual parts of the toolchain.
Unfortunately I don't think I can run this workflow without merging it first, hopefully it shouldn't take too many tries to get it to work correctly ...
=> feat(ci): add a new PR command to benchmark the CLI with hyperfine

.github/workflows/bench_cli.yml
This is a followup PR to #3764, I've manually run the workflow a few times to sort out all the issues so it should work correctly now
I've run the workflow manually here: https://github.com/rome/tools/actions/runs/3480835543
The resulting comment looks like this: https://github.com/rome/tools/pull/3764#issuecomment-1317230997
=> fix(ci): finish the `!bench_cli` command

crates/rome_js_analyze/src/analyzers/nursery/no_conditional_assignment.rs, crates/rome_js_analyze/tests/specs/nursery/noConditionalAssignment/invalid.js, crates/rome_js_analyze/tests/specs/nursery/noConditionalAssignment/invalid.js.snap, crates/rome_js_analyze/tests/specs/nursery/noConditionalAssignment/valid.js.snap, website/src/pages/lint/rules/noConditionalAssignment.md
Suggested fix for Conditional Assignment. (Followup from https://github.com/rome/tools/pull/3750#pullrequestreview-1182179008)
Added/Updated tests.
=> feat(rome_js_analyze): Suggested fix for Conditional Assignment

crates/rome_js_analyze/src/assists/correctness/inline_variable.rs, crates/rome_js_analyze/tests/specs/correctness/inlineVariable/doNotInline.js, crates/rome_js_analyze/tests/specs/correctness/inlineVariable/doNotInline.js.snap, crates/rome_js_analyze/tests/specs/correctness/inlineVariable/recursiveInvalid.js, crates/rome_js_analyze/tests/specs/correctness/inlineVariable/recursiveInvalid.js.snap, crates/rome_js_analyze/tests/specs/correctness/inlineVariable/valid.js, crates/rome_js_analyze/tests/specs/correctness/inlineVariable/valid.js.snap, crates/rome_js_semantic/src/tests/references.rs, crates/rome_rowan/src/ast/batch.rs
Fixes https://github.com/rome/tools/issues/3697.
Better together with https://github.com/rome/tools/pull/3740.
This PR increments the code action "inline variable" considering the type of the initializer. 
There is a chance that we may want to revisit this in the future, because some expressions do not make sense to be inlined. Example:
```js
const a = (1, (x) => {}, true);
```
Don't know why someone would write this, but this sure do not make sense to be inlined.
```
> cargo test -p rome_js_analyze -- inline_variable
```
=> fix(rome_js_analyze): inline variable considering initializer

CONTRIBUTING.md
While I am learning how to contribute to the rome project, I found that the internal link for `Analyzers and lint rules` selection was pointing to rome_js_analyzer instead of rome_analyze. This PR is for fixing that.
=> doc(contributing): fix the wrong link for analyzers and lint rules selection

crates/rome_js_formatter/src/js/declarations/function_declaration.rs, crates/rome_js_parser/src/syntax/function.rs, crates/rome_js_parser/test_data/inline/err/ts_declare_generator_function.rast, crates/rome_js_parser/test_data/inline/err/ts_declare_generator_function.ts
Add `Generators are not allowed in an ambient context.` error for generator functions in an ambient context.
[Typescript playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEBbA9sArhBByAHl+A3gFDzwg4AOyMALvKAGZQZ0NoB2YNAlsuwFTwaIAM40AFMgo8+ALnhR2ATwCU8gG7JuwIgF8i5KrXrhoceG04yBQ0RLXxN2gNxA)
For function overloading Rome has an error:
https://github.com/rome/tools/blob/4084d3e18e5d38b006e0dc99b3ce5975f9e01bf2/crates/rome_js_parser/src/syntax/function.rs#L280-L285
`cargo test`
=> feat(rome_js_parser): Improve parser error for generator function in an ambient context

crates/rome_js_analyze/tests/specs/correctness/noUndeclaredVariables.ts, crates/rome_js_analyze/tests/specs/correctness/noUndeclaredVariables.ts.snap, crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/tests/assertions.rs, crates/rome_js_semantic/src/tests/scopes.rs
Fixes:
*  #3798 
```
cargo test -p rome_js_semantic
cargo test -p rome_js_analyze -- no_undeclared_variables
```
=> fix(rome_js_semantic): include binding for type parameters

.gitattributes, Cargo.lock, crates/rome_cli/tests/commands/init.rs, crates/rome_cli/tests/commands/mod.rs, crates/rome_cli/tests/configs.rs, crates/rome_cli/tests/main.rs, crates/rome_cli/tests/snapshots/main_commands_init/creates_config_file.snap, crates/rome_cli/tests/snapshots/main_commands_init/creates_config_file_when_rome_installed_via_package_manager.snap, crates/rome_cli/tests/snapshots/main_init/creates_config_file.snap, crates/rome_fs/src/fs/memory.rs, crates/rome_service/src/configuration/linter/rules.rs, crates/rome_service/src/configuration/mod.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, npm/rome/package.json, npm/rome/schema.json, xtask/codegen/Cargo.toml, xtask/codegen/src/generate_configuration.rs, xtask/codegen/src/generate_schema.rs
Closes #3690 
- added a new `$schema` property to the configuration
- updated the `codegen-configuration` and `codegen-schema` aliases to store the first paragraph of the documentation of the rules
- updated the `rome` package to publish a new file called `configuration_schema.json`
- updated the `Default` implementation of `Configuration`, with the `$schema` value that points to `./node_modules/rome/configuration_schema.json`.
This change is very biased. I thought that it could be a nice DX improvement to have it as part of the `rome init` command. The path is hard coded, I checked on the internet and it seems that all local paths use unix paths, it don't seem to be OS dependent. 
I updated the existing CLI tests. The CI should pass for code generated files.
=> feat(rome_service): add `$schema` to configuration

npm/rome/scripts/generate-packages.mjs, npm/rome/scripts/postinstall.js
- Apply chmod at package creation time instead of doing it when running the postinstall hook.
- I did not disabled postinstall hook entirely because it can give interesting information to users, I just removed the part where it applies chmod (because it's supposed to be done before, at package creation time).
Fixes #3799 .
Testing this change is not trivial because it impacts CD pipelines. My suggestion:
1. make an alpha/beta/rc release, to avoid risking users' installations.
2. Modify your local `.npmrc` file, by adding this line: `ignore-scripts=true`
3. Install this alpha/beta/rc package version, and check that the installed binary has execution permissions, even when the `postinstall` hook has not been triggered because of our change on the `.npmrc` config file.
As a side note, it …
=> fix: apply chmod at pkg creation time

crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/commands/ci.rs, crates/rome_cli/tests/commands/format.rs, crates/rome_cli/tests/snapshots/main_commands_check/max_diagnostics.snap, crates/rome_cli/tests/snapshots/main_commands_check/max_diagnostics_default.snap, crates/rome_cli/tests/snapshots/main_commands_ci/max_diagnostics.snap, crates/rome_cli/tests/snapshots/main_commands_ci/max_diagnostics_default.snap, crates/rome_cli/tests/snapshots/main_commands_format/max_diagnostics.snap, crates/rome_cli/tests/snapshots/main_commands_format/max_diagnostics_default.snap
The tests for the `--max-diagnostics` CLI arguments are failing semi-randomly (it seems to happen mostly with macOS on CI but I managed to reproduce the failure at least once on Windows), this PR tries to improve these tests by counting the console messages emitted for diagnostics but still checking the rest of the console output against a snapshot to try and narrow down the issue
Run the new tests on CI
=> refactor(rome_cli): improve the stability of the `max_diagnostics` tests

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/analyzers/nursery.rs, crates/rome_js_analyze/src/analyzers/nursery/no_header_scope.rs, crates/rome_js_analyze/tests/specs/nursery/noHeaderScope/invalid.jsx, crates/rome_js_analyze/tests/specs/nursery/noHeaderScope/invalid.jsx.snap, crates/rome_js_analyze/tests/specs/nursery/noHeaderScope/valid.jsx, crates/rome_js_analyze/tests/specs/nursery/noHeaderScope/valid.jsx.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noHeaderScope.md
Part of https://github.com/rome/tools/issues/3739
Closes #3815 
Unit tests
=> feat(rome_js_analyze): add noHeaderScope rule

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/control_flow.rs, crates/rome_js_analyze/src/control_flow/visitor.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_var.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs, crates/rome_js_analyze/tests/specs/nursery/noVar/invalidFunctions.js, crates/rome_js_analyze/tests/specs/nursery/noVar/invalidFunctions.js.snap, crates/rome_js_analyze/tests/specs/nursery/noVar/invalidModule.js, crates/rome_js_analyze/tests/specs/nursery/noVar/invalidModule.js.snap, crates/rome_js_analyze/tests/specs/nursery/noVar/invalidScript.jsonc, crates/rome_js_analyze/tests/specs/nursery/noVar/invalidScript.jsonc.snap, crates/rome_js_analyze/tests/specs/nursery/noVar/valid.jsonc, crates/rome_js_analyze/tests/specs/nursery/noVar/valid.jsonc.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noVar.md
Implement eslint's [no-var](https://eslint.org/docs/latest/rules/no-var).
Test included.
=> feat(rome_js_analyze): `noVar`

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/analyzers/nursery.rs, crates/rome_js_analyze/src/analyzers/nursery/no_constructor_return.rs, crates/rome_js_analyze/tests/specs/nursery/noConstructorReturn/invalid.js, crates/rome_js_analyze/tests/specs/nursery/noConstructorReturn/invalid.js.snap, crates/rome_js_analyze/tests/specs/nursery/noConstructorReturn/valid.js, crates/rome_js_analyze/tests/specs/nursery/noConstructorReturn/valid.js.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noConstructorReturn.md
This implements ESLint's [no-constructor-return](https://eslint.org/docs/latest/rules/no-constructor-return).
Unit test and doc-test included.
=> feat(rome_js_analyze): `noConstructorReturn`

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/analyzers/nursery.rs, crates/rome_js_analyze/src/analyzers/nursery/no_constructor_return.rs, crates/rome_js_analyze/src/analyzers/nursery/no_setter_return.rs, crates/rome_js_analyze/tests/specs/nursery/noConstructorReturn/invalid.js, crates/rome_js_analyze/tests/specs/nursery/noConstructorReturn/invalid.js.snap, crates/rome_js_analyze/tests/specs/nursery/noConstructorReturn/valid.js, crates/rome_js_analyze/tests/specs/nursery/noConstructorReturn/valid.js.snap, crates/rome_js_analyze/tests/specs/nursery/noSetterReturn/invalid.js, crates/rome_js_analyze/tests/specs/nursery/noSetterReturn/invalid.js.snap, crates/rome_js_analyze/tests/specs/nursery/noSetterReturn/valid.js, crates/rome_js_analyze/tests/specs/nursery/noSetterReturn/valid.js.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noConstructorReturn.md, website/src/pages/lint/rules/noSetterReturn.md
This implements Deno Lint [noSetterReturn](https://lint.deno.land/?q=&all=on#no-setter-return).
Unit tests included.
=> feat(rome_js_analyze): `noSetterReturn`

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/analyzers/nursery.rs, crates/rome_js_analyze/src/analyzers/nursery/no_extra_non_null_assertion.rs, crates/rome_js_analyze/tests/specs/nursery/noExtraNonNullAssertion/invalid.ts, crates/rome_js_analyze/tests/specs/nursery/noExtraNonNullAssertion/invalid.ts.snap, crates/rome_js_analyze/tests/specs/nursery/noExtraNonNullAssertion/valid.ts, crates/rome_js_analyze/tests/specs/nursery/noExtraNonNullAssertion/valid.ts.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noExtraNonNullAssertion.md
Implement [no-extra-non-null-assertion](https://typescript-eslint.io/rules/no-extra-non-null-assertion).
Unit tests
=> feat(rome_js_analyze): add noExtraNonNullAssertion rule

crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs
- Fixes the formatting issue that causes CI to fail and a typo fix in use_exhaustive_dependencies.rs
Format Rust Files CI
=> chore: run rustfmt and typo fix

crates/rome_js_analyze/src/semantic_analyzers/correctness/no_arguments.rs, crates/rome_js_semantic/src/semantic_model/reference.rs
Small performance improvement for `noArguments`.
```
> hyperfine "~/github/tools/target/release/rome check ~/github/vscode" "~/github/toolsmain/target/release/rome check ~/github/vscode" -i
Benchmark 1: ~/github/tools/target/release/rome check ~/github/vscode
Time (mean ± σ):     661.1 ms ±   7.2 ms    [User: 8643.3 ms, System: 201.7 ms]
Range (min … max):   649.0 ms … 673.3 ms    10 runs
Warning: Ignoring non-zero exit code.
Benchmark 2: ~/github/toolsmain/target/release/rome check ~/github/vscode
Time (mean ± σ):     722.4 ms ±   9.8 ms    [User: 9576.6 ms, System: 210.6 ms]
Range (min … max):   710.3 ms … 745.3 ms    10 runs
Warning: Ignoring non-zero exit code.
Summary
'~/github/tools/target/release/rome check ~/github/vscode' ran
1.09 ± 0.02 times faster than …
```
=> feat(rome_js_analyze): faster version of noArguments

crates/rome_cli/src/traversal.rs, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/snapshots/main_commands_check/fs_error_dereferenced_symlink_unix.snap, crates/rome_cli/tests/snapshots/main_commands_check/fs_error_infinite_symlink_exapansion_unix.snap, crates/rome_cli/tests/snapshots/main_commands_check/unsupported_file.snap
I grouped two very small fixes to the CLI into this since I didn't want to open a PR for each of these:
- The first change is to use checked arithmetic when calculating the number of processed files. The CLI checks that at least one file was processed by subtracting the number of skipped files from the total number of files that were read, however in case a file fails to be read from the disk it will increment the skipped counter but not the total counter, making the subtraction panic in debug builds and to an integer underflow on release builds.
- The second change is an update to the Unix-specific snapshots of the CLI that were missed when I merged #3835, since I ran the snapshot update on Windows but not on Unix.
I've added a new test case for the first change, and the second one is …
=> fix(rome_cli): fix small CLI and test issues

crates/rome_analyze/src/diagnostics.rs, crates/rome_analyze/src/matcher.rs, crates/rome_diagnostics/src/context.rs, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/tests/spec_tests.rs, crates/rome_service/src/file_handlers/javascript.rs, website/src/playground/tabs/DiagnosticsListTab.tsx, xtask/lintdoc/src/main.rs
This PR adds a new API to `DiagnosticExt` called `with_severity`, which allows changing the severity of a diagnostic in a "native" way. 
This change allows removing an API I had to create in the `AnalyzerDiagnostic`, which is not needed anymore.
This is a "under the hoods" change, which means that the existing tests should pass.
=> feat(rome_diagnostics): add `with_severity` API

crates/rome_js_analyze/src/assists/correctness.rs, crates/rome_js_analyze/src/assists/correctness/organize_imports.rs, crates/rome_js_analyze/tests/specs/correctness/organizeImports/comments.js, crates/rome_js_analyze/tests/specs/correctness/organizeImports/comments.js.snap, crates/rome_js_analyze/tests/specs/correctness/organizeImports/directives.js, crates/rome_js_analyze/tests/specs/correctness/organizeImports/directives.js.snap, crates/rome_js_analyze/tests/specs/correctness/organizeImports/duplicate.js, crates/rome_js_analyze/tests/specs/correctness/organizeImports/duplicate.js.snap, crates/rome_js_analyze/tests/specs/correctness/organizeImports/empty-line-whitespace.js, crates/rome_js_analyze/tests/specs/correctness/organizeImports/empty-line-whitespace.js.snap, crates/rome_js_analyze/tests/specs/correctness/organizeImports/empty-line.js, crates/rome_js_analyze/tests/specs/correctness/organizeImports/empty-line.js.snap, crates/rome_js_analyze/tests/specs/correctness/organizeImports/group-comment.js, crates/rome_js_analyze/tests/specs/correctness/organizeImports/group-comment.js.snap, crates/rome_js_analyze/tests/specs/correctness/organizeImports/interpreter.js, crates/rome_js_analyze/tests/specs/correctness/organizeImports/interpreter.js.snap, crates/rome_js_analyze/tests/specs/correctness/organizeImports/non-import-newline.js, crates/rome_js_analyze/tests/specs/correctness/organizeImports/non-import-newline.js.snap, crates/rome_js_analyze/tests/specs/correctness/organizeImports/non-import.js, crates/rome_js_analyze/tests/specs/correctness/organizeImports/non-import.js.snap, crates/rome_js_analyze/tests/specs/correctness/organizeImports/remaining-content.js, crates/rome_js_analyze/tests/specs/correctness/organizeImports/remaining-content.js.snap, crates/rome_js_analyze/tests/specs/correctness/organizeImports/sorted.js, crates/rome_js_analyze/tests/specs/correctness/organizeImports/sorted.js.snap
Fixes #3462
This is an initial implementation of import sorting, exposed through the `source.organizeImports` code action. For now, the grouping of individual imports is not configurable and the rule will only reorder imports within the same "group", blocks of adjacent import nodes separated by empty lines or non-import module items (export or statement nodes). The rule also makes no attempts at merging imports from the same source (these will be preserved as individual imports and retain their original order relative to each other).
I've added a few snapshot tests that should cover everything that's currently supported by this version of the rule
=> feat(rome_js_analyze): implement the organizeImports code action

crates/rome_js_formatter/src/jsx/lists/child_list.rs, crates/rome_js_formatter/src/utils/jsx.rs, crates/rome_js_formatter/tests/specs/jsx/new-lines.jsx, crates/rome_js_formatter/tests/specs/jsx/new-lines.jsx.snap, crates/rome_js_formatter/tests/specs/prettier/jsx/fbt/test.js.snap, crates/rome_js_formatter/tests/specs/prettier/jsx/text-wrap/test.js.snap
Fix https://github.com/rome/tools/issues/3531#issuecomment-1325080671
`cargo test -p rome_js_formatter`
=> fix(rome_js_formatter): jsx punctuation

crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs, crates/rome_js_analyze/tests/specs/style/noShoutyConstants.js, crates/rome_js_analyze/tests/specs/style/noShoutyConstants.js.snap
Closes #3867
> cargo test -p rome_js_analyze -- shouty
With some new test cases which were missing:
```javascript
const Empty = "";
export const E = Empty;
const NotMatching = "DoesNotMatch";
export const F = NotMatching;
const matchingLowercase = "matchingLowercase";
export const G = matchingLowercase;
const AL = "ALPHA";
export const H = AL;
const ALPHA = "AL";
export const I = ALPHA;
```
=> fix(rome_js_analyze): fix noShoutyConstants with empty string

crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/src/semantic_analyzers/correctness/no_useless_fragments.rs, crates/rome_js_analyze/tests/specs/correctness/noUselessFragments/issue_3668.jsx, crates/rome_js_analyze/tests/specs/correctness/noUselessFragments/issue_3668.jsx.snap
Fixes #3668 
Added two new test cases.
=> fix(rome_js_analyze): false positives for `noUselessFragments` #3668

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/analyzers/nursery.rs, crates/rome_js_analyze/src/analyzers/nursery/no_const_enum.rs, crates/rome_js_analyze/tests/specs/nursery/noConstEnum.ts, crates/rome_js_analyze/tests/specs/nursery/noConstEnum.ts.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noConstEnum.md
This is an exclusive rule for Rome!
This rule disallows TypeScript `const enums`.
Const enums pitfalls are described on [TS docs](https://www.typescriptlang.org/docs/handbook/enums.html#const-enum-pitfalls).
See [my comment](https://github.com/rome/tools/pull/3849#discussion_r1032400804) for more context.
Unit test and doc-tests.
=> feat(rome_js_analyze): `noConstEnum`

crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/tests/references.rs
Fixes https://github.com/rome/tools/issues/3779.
```
> cargo test -p rome_js_semantic -- ok_class_expression
```
=> fix(rome_js_analyze): fix class expr binding

crates/rome_cli/tests/snap_test.rs, crates/rome_fs/src/fs.rs, crates/rome_fs/src/fs/memory.rs, crates/rome_fs/src/fs/os.rs
This PR adds permission checks to the `MemoryFileSystem`, so that it's no longer possible to call `read_to_string` on a file that was not open with the `read` option or `set_content` on file open with the `write` option.
I've also used the opportunity to further implement the specific behavior of the `create_new` and `truncate` flags to make sure they work the same way in both `FileSystem` implementations, and remove the `append` flag since our FileSystem API doesn't support appending content to a file anyway. 
Finally I've removed the specialized implementations of the `FileSystemExt` trait in favor of a single generic implementation over any type implementing the base trait (this is the convention for Rust extension trait as it makes it possible to use those extension methods on `&dyn …
=> feat(rome_fs): implement permission checking in the memory filesystem

npm/js-api/src/index.ts, npm/js-api/tests/__snapshots__/lintContent.test.ts.snap, npm/js-api/tsconfig.json
This fixes the tests for the JS API by removing the experimental use of `FinalizationRegistry` as it caused the test runner to hang, and updating the diagnostics snapshot to account for the changes in #3843
The JS API tests should now pass
=> fix(js-api): fix the JS API tests

Cargo.lock, crates/rome_analyze/src/lib.rs, crates/rome_analyze/src/matcher.rs, crates/rome_analyze/src/signals.rs, crates/rome_analyze/src/syntax.rs, crates/rome_cli/src/traversal.rs, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/snapshots/main_commands_check/suppression_syntax_error.snap, crates/rome_diagnostics/src/context.rs, crates/rome_diagnostics/src/diagnostic.rs, crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/lib.rs, crates/rome_js_formatter/src/comments.rs, crates/rome_js_syntax/Cargo.toml, crates/rome_js_syntax/src/suppression.rs, crates/rome_service/src/file_handlers/javascript.rs, npm/backend-jsonrpc/src/workspace.ts, website/src/frontend-scripts/index.ts, website/src/frontend-scripts/mobile.ts, website/src/frontend-scripts/toc.ts
Fixes #3841
With the existing suppression comment parsing logic, any comment that failed to parse as a suppression was simply ignored by the analyzer and formatter. I've modified the signature of the suppression parser so that any comment line that starts with `rome-ignore` (I've also changed this to be case insensitive and allow underscores so `ROME_IGNORE` would work too) is now detected as a suppression comment, and everything that comes after must parse correctly or a diagnostic will get emitted.
I expect this change to improve the developer experience of using suppression comments since incorrectly written suppression will now emit an explicit syntax error instead of being silently ignored.
I've added additional tests for the newly introduced errors to both the suppression parser in …
=> feat(rome_analyze): emit syntax error diagnostics for suppression comments

scripts/timetravel.sh
Small script to help to understand what changed through time. It will checkout, build and run rome for each commit specified and will generate a report like the one below.
* semantic model improvements
2022-11-23 11:18:13 +0000
```
Checked 1 file(s) in 609µs
```
2022-11-01 08:20:00 +0000
```
Checked 1 files in 668µs
```
2022-10-10 16:39:56 +0100
```
/home/user/github/test.ts:1:7 lint/nursery/noUnusedVariables ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
× This variable is unused.
> 1 │ const a = <T>(a: T) => console.log(a);
│       ^
i Unused variables usually are result of incomplete refactoring, typos and other source of bugs.
Checked 1 files in 956µs
Error: errors where emitted while running checks
```
* perf(rome_js_analyze): improve the performance of noUndeclaredVariables by allowing it …
=> script to analyze behaviour of rome throughout time

.github/workflows/main.yml, .github/workflows/pull_request.yml, Cargo.lock, clippy.toml, crates/rome_js_formatter/src/utils/binary_like_expression.rs, crates/rome_js_syntax/src/expr_ext.rs, crates/rome_js_syntax/src/union_ext.rs, xtask/bench/Cargo.toml, xtask/codegen/Cargo.toml, xtask/codegen/src/generate_aria.rs, xtask/libs_bench/Cargo.toml
* Enables the clippy cargo checks
* Disallows the use of `dbg` in non-test code
* Adds a check for unused dependencies
* [Run with an unused dependency](https://github.com/rome/tools/actions/runs/3572501737/jobs/6005462718)
=> ci: Add more clippy & dependency checks

Cargo.lock, crates/rome_js_analyze/Cargo.toml, crates/rome_js_analyze/src/assists/correctness/organize_imports.rs, crates/rome_js_analyze/tests/specs/correctness/organizeImports/natural-sort.js, crates/rome_js_analyze/tests/specs/correctness/organizeImports/natural-sort.js.snap
This change the sorting algorithm using by the `organizeImports` action to use natural ordering (provided by the `natord` crate) instead of alphabetical ordering.
I've added an additional test case demonstrating the new ordering.
=> feat(rome_js_analyze): sort imports using natural ordering

website/src/playground/utils.ts
This PR fixes the Source Type `Script` option on the playground.
The issue is that Rome only parses `cjs` and `cts` files as scripts and all other extensions as modules. This PR updates the playground's extension mapping to correctly use `cjs` and `cts` for scripts
=> fix(playground): Script Type

Cargo.lock, crates/rome_cli/src/execute.rs, crates/rome_cli/src/traversal.rs, crates/rome_cli/tests/snapshots/main_commands_format/does_not_format_ignored_directories.snap, crates/rome_json_formatter/src/lib.rs, crates/rome_json_parser/src/syntax.rs, crates/rome_service/Cargo.toml, crates/rome_service/src/file_handlers/javascript.rs, crates/rome_service/src/file_handlers/json.rs, crates/rome_service/src/settings.rs, crates/rome_service/src/workspace/server.rs
This PR enables the formatting capability for JSON for debug builds. 
Enabling the JSON formatter for debug builds is useful to integrate it into the prettier test suite (that uses `App`) and to test rome locally. 
Why not `rome_flags.is_unstable`: We may want to use the unstable flag shortly when at least some formatting is implemented. However, the formatter isn't doing any formatting yet.
* Ran `rome format rome.json` in the root directory: Rome reports that the file has been formatted
* Ran `rome check rome.json`: Rome emits a diagnostic that linting isn't supported
* Ran `rome ci rome.json`: Rome reports that it checked one file
* Running any of the above commands in release mode reports that the file type isn't supported
=> feat(rome_json_formatter): Enable JSON formatting for debug builds

.github/workflows/build_ci.yaml, .github/workflows/publish_container_ci.yaml, ci/publish.ps1, ci/publish.sh, ci/rome-ci-x86-64-centos7/Dockerfile
This PR creates the container need to build Rome using older glibc.
Will unblock https://github.com/rome/tools/pull/3650
Thus github action in this PR should publish a container to our container domain inside github;
And we should be able to build rome using this container on PR https://github.com/rome/tools/pull/3650
Rome binary should depend on glibc 2.17.
Rome binary should run on a standard container using CentOS.
=> chore(ci): centos7 ci container

crates/rome_cli/src/traversal.rs, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/commands/format.rs, crates/rome_cli/tests/snapshots/main_commands_check/fs_error_read_only.snap, crates/rome_cli/tests/snapshots/main_commands_format/fs_error_read_only.snap, crates/rome_service/src/configuration/mod.rs
Fixes an issue where Rome could not process files on read-only file systems during traversal, where write access to the file system was not required.
This is required to execute Rome in isolated environments (sandboxes).
Example -  Error message when running the check command on a read-only file system
```sh
$ rome check .
```
```
/test.js internalError/io ━━━━━━━━━━
× Read-only file system (os error 30)
Checked 0 file(s) in 939µs
Skipped 1 file(s)
Rome encountered an unexpected error
This is a bug in Rome, not an error in your code, and we would appreciate it if you could report it to https://github.com/rome/tools/issues/ along with the following information to help us fixing the issue:
Source Location: crates/rome_cli/src/traversal.rs:210:8
Thread Name: main
Message: attempt to subtract …
```
=> fix(rome_cli): Allow to run on read-only file systems

crates/rome_cli/src/traversal.rs
Remove `eprintln` statement that
**Before**
**After**
=> fix(rome_cli): Remove `eprintln`

crates/rome_js_analyze/src/assists/correctness/organize_imports.rs, crates/rome_js_analyze/tests/specs/correctness/organizeImports/namedSpecifiers.js, crates/rome_js_analyze/tests/specs/correctness/organizeImports/namedSpecifiers.js.snap, crates/rome_lsp/src/utils.rs, crates/rome_rowan/src/syntax/trivia.rs
This PR extends the `organizeImports` code action to not only sort whole import nodes, but also reorder the named import specifiers within a given node.
The implementation is made quite complex by the necessity of moving nodes along with the relevant comments while remaining syntactically correct, which means inserting or removing comma tokens and newline trivias as nodes get moved to different places.
The current solution correctly handles nodes that were formatted using the Rome Formatter, but the output may be formatted incorrectly when the formatting of the input get more complex (this is only formatting though, it should not result in any syntax errors).
I've also fixed a bug in the `SyntaxTrivia::first` method that was causing it to return a trivia piece with an incorrect source …
=> feature(rome_js_analyze): implement import sorting for named specifiers

crates/rome_cli/src/panic.rs, editors/vscode/src/main.ts
Fixes #3920
This is a followup to #3952 adding additional logs to the CLI and VSCode extension. Specifically, it extends the panic hook of the CLI to print the panic message to the current tracing log file in addition to stderr. This ensures that panic messages can be retrieved in the logs when they cause a background process like the language server to crash.
In addition to this, I extended the previous changes to the VSCode extension to wrap errors thrown by the `connect` function in addition to the exceptions raised by the socket itself. I also improved the `getSocket` function by collecting the content of the stderr pipe for the CLI child process in addition to stdout, and to fail with an error if the content of stdout was empty. This error will now include the exit code of the CLI as …
=> fix(rome_cli): improve the logging of panics and connection errors

crates/rome_js_analyze/tests/specs/style/noArguments.cjs, crates/rome_js_analyze/tests/specs/style/noArguments.cjs.snap, crates/rome_js_analyze/tests/suppression/correctness/noUndeclaredVariables.ts.snap, crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/tests/assertions.rs, crates/rome_js_semantic/src/tests/references.rs
Fixes https://github.com/rome/tools/issues/4003
```
> cargo test -p rome_js_analyze -- no_arguments
```
=> fix(rome_js_analyzer): correctly delegate unresolved references to its parent scope

.github/workflows/release_js_api.yml, npm/js-api/package.json
This PR fixes the `release_js_api` workflow by ensuring all the distributions of the `rome_wasm` crate (bundler, node and web) have been built before running `tsc` so the type checker can ensure all the definitions are valid and coherent.
Run the release workflow for version `0.2.0` again (I've downgraded the version number in this PR to bump it again in a followup commit and trigger the release workflow again)
=> fix(ci): fix the release workflow for the JS API

crates/rome_js_analyze/src/react/hooks.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs, crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/missingDependenciesInvalid.js, crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/missingDependenciesInvalid.js.snap, crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/valid.js, crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/valid.js.snap, crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/valid.ts, crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/valid.ts.snap, crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/semantic_model/binding.rs, crates/rome_js_semantic/src/semantic_model/import.rs, crates/rome_js_semantic/src/tests/functions.rs, crates/rome_js_semantic/src/tests/scopes.rs, website/src/pages/lint/rules/useExhaustiveDependencies.md
This PR closes https://github.com/rome/tools/issues/3727.
The main issue is that before we only considered `const` as stable if the initializer is constant. The specific example was calling a function, which we assume is never constant.
Now, all `const` declarator outside of component are considered as stable.
I also did a small refactor of the code using the new `Binding` and `.declarator()`.
This is done on top of https://github.com/rome/tools/pull/3860 and will wait for it before rebasing.
```
> cargo test -p rome_js_analyze -- use_exhaustive_dependencies
```
=> fix(rome_js_analyze): use exhaustive deps considering external const as stable

crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs, crates/rome_js_analyze/src/utils/rename.rs, crates/rome_js_analyze/src/utils/tests.rs, crates/rome_js_analyze/tests/spec_tests.rs, crates/rome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidVariables.ts, crates/rome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidVariables.ts.snap, crates/rome_js_analyze/tests/specs/correctness/noUnusedVariables/validVariables.tsx, crates/rome_js_analyze/tests/specs/correctness/noUnusedVariables/validVariables.tsx.snap, crates/rome_js_analyze/tests/specs/nursery/noVar/invalidScript.jsonc.snap, crates/rome_js_analyze/tests/specs/nursery/useConst/invalid.jsonc, crates/rome_js_analyze/tests/specs/nursery/useConst/invalid.jsonc.snap, crates/rome_js_analyze/tests/specs/nursery/useConst/valid.jsonc, crates/rome_js_analyze/tests/specs/nursery/useConst/valid.jsonc.snap, crates/rome_js_analyze/tests/specs/nursery/useConst/validPartial.js, crates/rome_js_analyze/tests/specs/nursery/useConst/validPartial.js.snap, crates/rome_js_semantic/src/tests/references.rs, crates/rome_js_syntax/src/binding_ext.rs, website/src/pages/lint/rules/useConst.md
Fixes: https://github.com/rome/tools/issues/4006
The real fix is at: `crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs`
All the other changes were using some of the examples to better test semantic model and batch mutation with the cases of `useConst`.
I also moved a lot of cases from valid to invalid and vice-versa.
The older version of `crates/rome_js_analyze/tests/specs/nursery/useConst/valid.jsonc.snap` incorrectly had some diagnostics. I also fixed that.
```
> cargo test -p rome_js_analyze -- use_const
```
=> fix(rome_js_analyze): fix useConst suggestion when some bindings cannot live inside const

crates/rome_js_analyze/src/analyzers/nursery/no_constructor_return.rs, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noConstructorReturn.md
=> docs(noConstructorReturn): fix rule description

crates/rome_service/src/file_handlers/json.rs, website/package.json, website/pnpm-lock.yaml, website/src/playground/Playground.tsx, website/src/playground/utils.ts, website/src/playground/workers/prettierWorker.ts, website/src/playground/workers/romeWorker.ts
This PR adds basic JSON support to the playground. It's not the deluxe version. 
To use JSON, it's necessary to switch to the multifile mode and change the extension to `json`. 
We should probably add a language dropdown in the future that lets you pick JavaScript, TypeScript, or JSON, similar to what Prettier has. I decided not to do this as part of this PR because it's mainly to unlock the development of the JSON formatter and not to promote the JSON formatting on the playground.
I tested the playground with a JSON, jS ,and TypeScript file
=> feat(playground): Add JSON support

crates/rome_js_analyze/src/semantic_analyzers/correctness/no_undeclared_variables.rs, crates/rome_js_analyze/tests/specs/correctness/noUndeclaredVariables.ts, crates/rome_js_analyze/tests/specs/correctness/noUndeclaredVariables.ts.snap, crates/rome_js_semantic/src/semantic_model/reference.rs, crates/rome_js_syntax/src/identifier_ext.rs, crates/rome_js_syntax/src/lib.rs
Fix a problem with `noUndeclaredVariables` regarding Typescript const assertion.
```
> cargo test -p rome_js_analyze -- no_undeclared_variables
```
=> fix(rome_js_analyze): fix ts const assertion on noUndeclaredVariables

crates/rome_cli/src/commands/rage.rs, crates/rome_cli/tests/snapshots/main_commands_rage/rage_ok.snap, crates/rome_cli/tests/snapshots/main_commands_rage/with_configuration.snap, crates/rome_cli/tests/snapshots/main_commands_rage/with_malformed_configuration.snap, crates/rome_cli/tests/snapshots/main_commands_rage/with_server_logs.snap, npm/rome/bin/rome
This PR extends the `rome rage` command to include the name and version of the JavaScript runtime that executed the `rome` wrapper script as well as the name and version of the package manager:
```
❯ npx rome rage
CLI:
Version:              0.0.0
Color support:        true
Platform:
CPU Architecture:     x86_64
OS:                   windows
Environment:
ROME_LOG_DIR:         unset
NO_COLOR:             unset
TERM:                 unset
JS_RUNTIME_VERSION:   "v16.13.2"
JS_RUNTIME_NAME:      "node"
NODE_PACKAGE_MANAGER: "npm/8.3.0"
❯ yarn rome rage
yarn run v1.22.19
$ C:\Users\Micha\git\rome-test\node_modules\.bin\rome rage
CLI:
Version:              0.0.0
Color support:        true
Platform:
CPU Architecture:     x86_64
OS:                   windows
Environment:
ROME_LOG_DIR:         unset …
```
=> feat(rome_cli): Add JS runtime and package manager information to `rage`

editors/vscode/src/main.ts
The main goal of this PR is to introduce a version check on the binary distribution that's loaded from the workspace. Versions of the `@rometools/cli-*` packages lower than `0.9.0` did not include the language server, and as such will fail to initialize when spawned by the extension. I've added a simple check against the major and minor version of the package that to ignore versions that do not meet the current requirements of the extension and fall back to the bundled version of the binary if it's available.
In addition to this, I also made a minor change to the handler of the "Restart LSP Server" command to skip trying to stop the server if its not already running and only try to start it instead. Finally, I've updated the logic of the `fileExists` function to also handle the …
=> fix(vscode): ignore incompatible versions of the binary and improve the restart logic

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, crates/rome_analyze/CONTRIBUTING.md, justfile
This PR updates the contribution guidelines.
We will create a new "release PR" at beginning of each release cycle and contributors will open PRs against it to update the documentation.
N/A
=> chore: update contribution guidelines

crates/rome_lsp/src/server.rs, crates/rome_lsp/src/session.rs
This PR refactors the initialization and configuration loading logic of the language server Session to limit the use of `Mutex` and `RwLock`:
- The `client_capabilities`, `client_information` and `root_uri` fields are only written to when the session is initialized, with all following access being read-only. I've moved these fields to a new `InitializeParams` struct stored in a `OnceCell` container (I'm using the implementation from `tokio` to avoid having to pull in another crate until `std::sync::OnceLock` is stabilized) that should provide a similar "write-once read-many" synchronization primitive at a lower performance and memory cost than `Mutex` or `RwLock`.
- The workspace configuration used to be loaded in `update_configuration` but applied to the workspace in …
=> refactor(rome_lsp): refactor the initialization and configuration loading logic

crates/rome_cli/tests/commands/format.rs, crates/rome_cli/tests/configs.rs, crates/rome_cli/tests/snapshots/main_commands_format/does_not_format_ignored_directories.snap, crates/rome_lsp/src/handlers/analysis.rs, crates/rome_lsp/src/handlers/formatting.rs, crates/rome_lsp/src/handlers/rename.rs, crates/rome_lsp/src/handlers/text_document.rs, crates/rome_lsp/src/requests/syntax_tree.rs, crates/rome_lsp/src/session.rs, crates/rome_lsp/tests/server.rs, crates/rome_service/src/matcher/pattern.rs
Fixes #3790
This PR fixes how ignore patterns are parsed and changes how paths are represented in the language server to reduce discrepancies with the CLI. For ignore patterns, the parse will now strip the `./` prefix from the input string, and prepend the pattern with a `**` group if the input string doesn't start with an absolute filesystem path. For the Language Server, the logic converting URIs into `RomePath` will now try to strip the path to the root of the workspace from the path of the file, which has the effect of making most paths relative much like they generally are on the CLI.
I've update the tests for the file ignores on the CLI to check that various forms of ignore patterns are all working correctly. I also modified the LSP tests to ensure it only constructs URIs that can …
=> fix(rome_lsp): improve the pattern matching logic for ignored files

crates/rome_lsp/src/session.rs
This PR fixes a build issue caused by a conflict between the changes of #4042 and #4044
The `rome_lsp` crate should build correctly
=> fix(rome_lsp): fix the merge conflict of #4042 and #4044

crates/rome_diagnostics_categories/src/categories.rs, xtask/codegen/src/generate_new_lintrule.rs
This PR fixes codegen for new lint rules.
```
> just new-lintrule /crates/rome_js_analyze/src/semantic_analyzers/nursery SomeRule
```
=> chore(codegen): fix codegen for new lint rule

crates/rome_formatter/src/lib.rs, crates/rome_formatter/src/separated.rs, crates/rome_js_formatter/src/prelude.rs, crates/rome_js_formatter/src/separated.rs, crates/rome_json_formatter/src/separated.rs
This PR extracts the `separated()` helper for formatting separated lists into `rome_formatter` so that it can be re-used between the different language implementations. 
It's a bit awkward because the `AsFormat` and `IntoFormat` aren't available in the `rome_formatter` crate. That's why the iterator extension trait must still be duplicated between implementations. 
`cargo test`
=> refactor(rome_formatter): Extract shared separated logic

crates/rome_aria/src/iso.rs, crates/rome_aria/src/lib.rs, crates/rome_aria_metadata/build.rs, crates/rome_aria_metadata/src/lib.rs, crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/aria_analyzers/nursery.rs, crates/rome_js_analyze/src/aria_analyzers/nursery/use_valid_lang.rs, crates/rome_js_analyze/src/aria_services.rs, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/tests/specs/nursery/useValidLang.jsx, crates/rome_js_analyze/tests/specs/nursery/useValidLang.jsx.snap, crates/rome_js_syntax/src/jsx_ext.rs, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/useValidLang.md
Closes #3948 
I added a new `AriaIso` struct that exposes some utility function to check if a country/language is valid.
The diagnostics are different from the old rule. The old rules used to do a combination of `<LANGUAGE>-<COUNTRIES>` when given possible valid suggestions. Here I decided to keep it dumber and to just suggest the correct language when it's wrong, and then the correct countries if the country isn't correct.
Added some test cast
=> feat(rome_js_analyzer): rule `useValidLang`

crates/rome_js_analyze/src/analyzers/nursery/no_self_compare.rs
This is a follow-up of #4031. When implementing #4059 I saw we already have a helper to check if the operator is used to compare the expressions.
CI tests
=> chore(rome_js_analyze): simplify comparison operator check

Cargo.lock, crates/rome_analyze/CONTRIBUTING.md, crates/rome_analyze/Cargo.toml, crates/rome_analyze/src/lib.rs, crates/rome_analyze/src/matcher.rs, crates/rome_analyze/src/query.rs, crates/rome_analyze/src/registry.rs, crates/rome_analyze/src/syntax.rs, crates/rome_analyze/src/visitor.rs, crates/rome_js_analyze/src/analyzers/correctness/no_unreachable.rs, crates/rome_js_analyze/src/aria_services.rs, crates/rome_js_analyze/src/control_flow.rs, crates/rome_js_analyze/src/control_flow/visitor.rs, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/src/semantic_services.rs, crates/rome_service/src/file_handlers/javascript.rs
This PR modifies how various types related to the `Queryable` trait are injected into the analyzer infrastructure. This includes:
- Allowing `Queryable` types to dynamically register the `Visitor` instances that emits them to the analyzer
- Replacing the `QueryMatch` enum with `TypeId` and `Box<dyn Any>` to allow any arbitrary type to be emitted as a visitor event
The main goal of this refactor is to allow individual rules to declare custom syntax tree visitors to emit the event they rely upon as an optimization opportunity instead of having to traverse the syntax tree in their `run` method. For instance the `useYield` rule could be implemented like this:
<details>
<summary>Code</summary>
```rust
impl Rule for UseYield {
type Query = MissingYield;
}
struct MissingYield(AnyFunctionLike); …
```
=> refactor(rome_analyze): refactor how Visitors, Queryables and QueryMatches are related

crates/rome_analyze/CONTRIBUTING.md, crates/rome_aria/src/macros.rs, crates/rome_aria/src/roles.rs, crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/aria_analyzers/nursery.rs, crates/rome_js_analyze/src/aria_analyzers/nursery/no_noninteractive_element_to_interactive_role.rs, crates/rome_js_analyze/tests/specs/nursery/noNoninteractiveElementToInteractiveRole/invalid.jsx, crates/rome_js_analyze/tests/specs/nursery/noNoninteractiveElementToInteractiveRole/invalid.jsx.snap, crates/rome_js_analyze/tests/specs/nursery/noNoninteractiveElementToInteractiveRole/valid.jsx, crates/rome_js_analyze/tests/specs/nursery/noNoninteractiveElementToInteractiveRole/valid.jsx.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, justfile, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noNoninteractiveElementToInteractiveRole.md, website/src/playground/Playground.tsx, website/src/playground/components/Tabs.tsx, xtask/codegen/src/generate_new_lintrule.rs
Start implementing #3816 
Closes https://github.com/rome/tools/issues/3950
In order to implement this rule, new metadata were necessary. This metadata describes **some** of the existing roles, by adding the "concepts". 
Concepts are information that tells us how an HTML can be mapped via ARIA roles, for example:
```html
<button>Hit me</button>
```
Can be mapped with ARIA roles like this:
```html
<input type="button">Hit me</input>
<span role="button">Hit me</span>
```
This kind of information will be needed for another rule.
Not only that, though. These metadata are also useful to identify whether some HTML elements are non-interactive and if some ARIA roles are interactive.
- ARIA roles are interactive if they have `"widget"` in their list of roles
- HTML elements are deemed …
=> feat(rome_js_analyzer): partial implementation for rule `noNoninteractiveElementToInteractiveRole`

crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/analyzers/a11y.rs, crates/rome_js_analyze/src/analyzers/a11y/use_html_lang.rs, crates/rome_js_analyze/tests/specs/a11y/useHtmlLang.jsx, crates/rome_js_analyze/tests/specs/a11y/useHtmlLang.jsx.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/useHtmlLang.md
Closes #3944.
Run newly added tests.
=> feat(rome_js_analyzer): rule `useHtmlLang`

crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/tests/assertions.rs, crates/rome_js_semantic/src/tests/references.rs, crates/rome_js_semantic/src/tests/scopes.rs
This PR fix a hole in the semantic model scope that was not considering static init blocks.
```
> cargo test -p rome_js_semantic -- ok_scope_static_initialization_block
> cargo test -p rome_js_semantic -- ok_reference_static_initialization_block
```
=> fix(rome_js_semantic): semantic model considering static init block as scope

crates/rome_cli/src/commands/check.rs, crates/rome_cli/src/commands/help.rs, crates/rome_cli/src/traversal.rs, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/snapshots/main_commands_check/apply_noop.snap, crates/rome_cli/tests/snapshots/main_commands_check/apply_ok.snap, crates/rome_cli/tests/snapshots/main_commands_check/apply_suggested_error.snap, crates/rome_cli/tests/snapshots/main_commands_check/should_disable_a_rule_group.snap
BREAKING CHANGE: rename `--apply-suggested` to `--apply-unsafe`
Closes #3782 
In #3782, some users expressed that the argument's name doesn't sufficiently describe its intent and result. This PR changes the name of `--apply-suggested` to `--apply-unsafe`
I updated the snapshot tests. The current CI should work.
=> feat(rome_cli): rename `--apply-suggested` to `--apply-unsafe`

crates/rome_js_analyze/src/analyzers/nursery/no_const_enum.rs, crates/rome_js_analyze/tests/specs/nursery/noConstEnum.ts, crates/rome_js_analyze/tests/specs/nursery/noConstEnum.ts.snap
This PR improves trivia handling for the quick fix of `noConstEnum`.
new unit test included
=> refactor(rome_js_anallyze): `noConstEnum` better trivia handling

crates/rome_js_formatter/src/ts/types/union_type.rs, crates/rome_js_formatter/tests/specs/ts/type/union_type.ts, crates/rome_js_formatter/tests/specs/ts/type/union_type.ts.snap
Fixes #4074
I verified the updated snapshot to ensure it matches Prettier's output.
=> fix(rome_js_formatter): Union in mapped type

crates/rome_analyze/src/matcher.rs, crates/rome_analyze/src/syntax.rs, crates/rome_cli/tests/commands/rage.rs, crates/rome_js_analyze/src/analyzers/nursery/use_enum_initializers.rs, crates/rome_js_parser/src/lexer/mod.rs, crates/rome_js_parser/src/syntax/module.rs, crates/rome_js_parser/src/syntax/typescript/ts_parse_error.rs, crates/rome_json_parser/src/lexer/mod.rs, crates/rome_lsp/src/utils.rs, crates/rome_parser/src/diagnostic.rs, crates/rome_parser/src/marker.rs, crates/rome_rowan/src/cursor/element.rs, crates/rome_rowan/src/cursor/node.rs, crates/tests_macros/src/lib.rs, rust-toolchain.toml, xtask/codegen/src/formatter.rs, xtask/codegen/src/generate_analyzer.rs, xtask/coverage/src/lib.rs, xtask/coverage/src/ts/ts_microsoft.rs
Upgrades the Rust toolchain to version [1.66.0](https://blog.rust-lang.org/2022/12/15/Rust-1.66.0.html)
`cargo build && cargo test`
=> chore: Upgrade to Rust 1.66.0

crates/rome_js_parser/src/state.rs, crates/rome_js_parser/src/syntax/class.rs, crates/rome_js_parser/src/syntax/expr.rs, crates/rome_js_parser/src/syntax/function.rs, crates/rome_js_parser/src/syntax/object.rs, crates/rome_js_parser/src/syntax/stmt.rs, crates/rome_js_parser/src/syntax/typescript.rs, crates/rome_js_parser/src/syntax/typescript/statement.rs, crates/rome_js_parser/src/syntax/typescript/types.rs
This PR moves the state tracking if conditional types are allowed from the `ParserState` into a new `TypeContext` explicitly passed as an argument to type parsing methods, similar to the `ExpressionContext` for parsing expressions.
The advantage of an passing the context as an argument over an additional flag on the state is that it is easier to reason about the state of the parser and avoids accidental "leaking" of the conditional types when switching between parsing types and expressions (as it is the case when parsing the function parameters).
I verified that the fixed regressions are intentional.
=> refactor(rome_js_parser): Inroduce TypeContext

Cargo.lock, crates/rome_lsp/Cargo.toml, crates/rome_lsp/src/documents.rs, crates/rome_lsp/src/handlers/text_document.rs, crates/rome_lsp/src/line_index.rs
This PR add a new `replace_range` method to the `Document` and `LineIndex` data structures used internally in the Language Server to track the state of an open document. This new method allows the text of an existing document and its associated line index to be updated in place, instead of having to be recreated from scratch on every change. I also took the opportunity to remove the duplicate storage of the text in both `Document` and `LineIndex`, the string is now only stored in the innermost structure (the line index).
I've added a few manual test case for the new `replace_range` method on `LineIndex`, as well as an automated "property test" that checks the function works correctly over a diverse range of values using the `proptest` crate.
=> feat(rome_lsp): add a `replace_range` method to `Document`

crates/rome_js_analyze/src/analyzers/nursery/use_is_nan.rs, crates/rome_js_analyze/tests/specs/nursery/useIsNan/invalid.js.snap, website/src/pages/lint/rules/useIsNan.md
Promote use of `Number.isNaN` instead of `isNaN`.
`Number.isNaN()` and `isNaN()` [have not the same behavior](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN#description). When the argument to `isNaN()` is not a number, the value is first coerced to a number. `Number.isNaN()` does not perform this coercion. Therefore, it is a more reliable way to test whether a value is `NaN`.
The snapshot is updated.
=> docs(useIsNan): promote `Number.isNaN` instead of `isNaN`

Cargo.lock, crates/rome_js_parser/src/parse.rs, crates/rome_json_parser/src/lib.rs, crates/rome_parser/src/tree_sink.rs, crates/rome_rowan/src/arc.rs, crates/rome_rowan/src/green.rs, crates/rome_rowan/src/green/node.rs, crates/rome_rowan/src/green/node_cache.rs, crates/rome_rowan/src/green/token.rs, crates/rome_rowan/src/green/trivia.rs, crates/rome_rowan/src/lib.rs, crates/rome_rowan/src/tree_builder.rs, crates/rome_service/src/file_handlers/javascript.rs, crates/rome_service/src/file_handlers/json.rs, crates/rome_service/src/file_handlers/mod.rs, crates/rome_service/src/workspace/server.rs, xtask/bench/Cargo.toml, xtask/bench/src/language.rs, xtask/bench/src/lib.rs
This PR aims at improving the performance of running multiple parsing session over the same document by allowing the green node cache to be stored in the workspace alongside the syntax tree and reused by each parser invocation.
As the cache is now long-lived, this requires the implementation of a cache eviction strategy to avoid having the in-memory caches of the open documents grow indefinitely. This behavior is implemented in the `TreeBuilder` with the help of a new `LiveSet` structure that tracks the set of tokens and nodes that were retrieved from the cache or inserted by a given instance of the builder, and drains the entries that have not been marked from the cache when `finish` is called on the builder. This strategy is sufficient as the workspace maintains a node cache …
=> feat(rome_service): recycle the node cache across parsing sessions

crates/rome_js_analyze/src/semantic_analyzers/correctness/no_unused_variables.rs, crates/rome_js_analyze/tests/suppression/correctness/noUnusedVariables/ts-module-export.ts, crates/rome_js_analyze/tests/suppression/correctness/noUnusedVariables/ts-module-export.ts.snap, crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/tests/scopes.rs
Fixes #4179.
This also recognize exported members of a module.
Test included.
By the way I am not sure to understand why `noUnusedVariables` is not in `tests/specs`.
=> fix(js_semantic):handle exported modules and their members

crates/rome_js_analyze/src/analyzers/style/use_single_case_statement.rs, crates/rome_js_analyze/tests/specs/style/useSingleCaseStatement.js, crates/rome_js_analyze/tests/specs/style/useSingleCaseStatement.js.snap, crates/rome_rowan/src/syntax/token.rs, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/useSingleCaseStatement.md
Closes #4068.
I also updated the diagnostic for better consistency with other rules.
By the way, the rule should certainly be renamed to `useSingleSwitchClauseStatement`.
Unfortunately, this is a stable rule.
I personally could rather deprecate the rule, once [`noSwitchDeclarations`](https://github.com/rome/tools/pull/3917) becomes merged or stable.
New Unit test for `default` switch clauses.
=> fix(rome_js_analyze): handle default clause in `useSingleCaseStetement`

crates/rome_js_analyze/src/semantic_analyzers/correctness/no_unused_variables.rs, crates/rome_js_analyze/tests/specs/correctness/noUnusedVariables/validClass.ts, crates/rome_js_analyze/tests/specs/correctness/noUnusedVariables/validClass.ts.snap
Fixes #4164
New test included.
No change.
=> fix(noUnusedVariables): ignore TypeScript property parameters

crates/rome_js_formatter/src/ts/types/mapped_type.rs, crates/rome_js_formatter/tests/specs/ts/type/mapped_type.ts, crates/rome_js_formatter/tests/specs/ts/type/mapped_type.ts.snap
Fixes #4165
Test included to avoid regression.
No change.
=> fix(rome_js_formatter): mapped type formatting

crates/rome_cli/src/commands/rage.rs, crates/rome_cli/src/configuration.rs, crates/rome_lsp/src/session.rs, crates/rome_service/src/configuration/mod.rs, crates/rome_service/src/lib.rs, website/package.json
This PR adds a way to discover `rome.json` by traversing the file system upwards. 
I manually tested the feature using the CLI in our internal repository, and tested manually the VSCode extension.
Below a recording to demonstrate the feature:
https://user-images.githubusercontent.com/602478/220338807-cb241498-807a-4bba-a8d6-2b1644e17d1e.mov
=> feat(rome_service): traverse upwards the fs to discover the config file

Cargo.lock
Fixes `warning: the following packages contain code that will be rejected by a future version of Rust: fs_extra v1.2.0` from `cargo build`.
- webdesus/fs_extra#38
Run `cargo build`.
=> chore: Update fs_extra to fix future incompatibility warning

website/src/playground/tabs/SettingsTab.tsx
The `for` attribute of these `<label>`s were incorrectly copied.
In the playground **Settings** tab, hover or click the **Semicolons** or **Lint Rules** labels.
=> fix(website): Associate labels with the right controls

crates/rome_js_factory/src/generated/node_factory.rs, crates/rome_js_factory/src/generated/syntax_factory.rs, crates/rome_js_formatter/src/js/module/export_from_clause.rs, crates/rome_js_formatter/tests/specs/ts/module/export_clause.ts, crates/rome_js_formatter/tests/specs/ts/module/export_clause.ts.snap, crates/rome_js_parser/src/syntax/auxiliary.rs, crates/rome_js_parser/src/syntax/module.rs, crates/rome_js_parser/test_data/inline/err/export_from_clause_err.js, crates/rome_js_parser/test_data/inline/err/export_from_clause_err.rast, crates/rome_js_parser/test_data/inline/ok/export_from_clause.js, crates/rome_js_parser/test_data/inline/ok/export_from_clause.rast, crates/rome_js_syntax/src/generated/nodes.rs, crates/rome_js_syntax/src/generated/nodes_mut.rs, xtask/codegen/js.ungram
Part of #4227.
This adds the support for `export type *`.
#2400 and #4227 have to be implemented before updating the TypeScript supported version on the website.
=> feat(rome_js_parser): TS 5.0 `export type *`

crates/rome_diagnostics/src/display/frame.rs
The `unsafe` blocks in this module are unnecessary, so let’s remove them.
The test suite segfaults for me (both with and without this change), so I’m relying on CI here. Clearly we’re misusing `unsafe` somewhere, and we should remove `unsafe` wherever possible. Although these particular uses of `unsafe` are among the more innocuous ones, I figured they’re a good starting point.
=> Remove unsafe from rome_diagnostics::display::frame

crates/rome_cli/src/commands/daemon.rs, crates/rome_cli/tests/snap_test.rs, crates/rome_js_analyze/src/analyzers/nursery/use_enum_initializers.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs, crates/rome_js_formatter/src/js/lists/template_element_list.rs, xtask/coverage/src/ts/ts_microsoft.rs
Run `cargo clippy --fix` with nightly Clippy.
`cargo clippy`.
=> Fix more nightly Clippy lints

crates/rome_diagnostics/src/error.rs
The stated reason for this `unsafe` code was to avoid bloating the size of `Result<T, Error>`, since `Box<dyn Diagnostic>` would be a fat pointer.  But `Box<Box<dyn Diagnostic>>`, a thin pointer to a fat pointer, acomplishes the same goal safely.  We don’t have millions of `Error`s in the common case, so this seems like a better tradeoff than maintaining `unsafe` code here.
Ran the test suite. Two of the tests in `rome_diagnostics::error::tests` make assertions about the sizes of `Error` and `Result<(), Error>`, and continue to pass.
=> Replace unsafe rome_diagnostics::Error implementation with double-Box

crates/rome_formatter/src/comments/builder.rs, crates/rome_formatter/src/lib.rs, crates/rome_formatter/src/source_map.rs, crates/rome_formatter/src/verbatim.rs, crates/rome_js_formatter/src/js/bindings/parameters.rs, crates/rome_js_formatter/src/lib.rs, crates/rome_js_formatter/src/syntax_rewriter.rs
https://github.com/rome/tools/issues/4149
This PR tries to fix several issues when we format a node with a range.
1. The transform function builds the source map by iterating over all tokens and pushing source text in the builder. This correctly builds up the source text for the sub-tree, but the offsets are incorrect if the root isn't at the start of the document.
2. The transform function can `detach` a node if it updates a tree (`splice_slots`) while a traversing. We must return transformed a node back into the original tree to correct offset and sometimes a formatting result depends on a `parent` kind.
`cargo test`
=> fix(rome_formatter): format range has incorrect source map #4149

crates/rome_analyze/src/context.rs, crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redeclaration.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs, crates/rome_js_analyze/tests/specs/nursery/noRedeclaration/invalid.jsonc, crates/rome_js_analyze/tests/specs/nursery/noRedeclaration/invalid.jsonc.snap, crates/rome_js_analyze/tests/specs/nursery/noRedeclaration/invalid.ts, crates/rome_js_analyze/tests/specs/nursery/noRedeclaration/invalid.ts.snap, crates/rome_js_analyze/tests/specs/nursery/noRedeclaration/valid.jsonc, crates/rome_js_analyze/tests/specs/nursery/noRedeclaration/valid.jsonc.snap, crates/rome_service/src/configuration/linter/rules.rs, crates/rome_service/src/configuration/parse/json/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noRedeclaration.md
implement noRedeclaration https://eslint.org/docs/latest/rules/no-redeclare. Fixes https://github.com/rome/tools/issues/3990
have run 
1. `just codegen`
2. ` just test-lintrule no_redeclaration`
3. `just documentation`
4. `just check-ready`
```bash
running 2 tests
test specs::nursery::no_redeclaration::valid_jsonc ... ok
test specs::nursery::no_redeclaration::invalid_jsonc ... ok
test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 249 filtered out; finished in 0.10s
```
+ Not handle the redeclaration of global variables and function parameters
=> feat(rome_js_analyzer): implement rule noRedeclaration, no-redeclare

crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/src/semantic_analyzers/correctness/no_unused_variables.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redeclaration.rs, crates/rome_js_semantic/src/semantic_model/binding.rs, crates/rome_js_semantic/src/semantic_model/builder.rs, crates/rome_js_semantic/src/tests/references.rs, crates/rome_js_syntax/src/binding_ext.rs, website/src/pages/lint/rules/noRedeclaration.md
When https://github.com/rome/tools/pull/4053 was merged, it unveiled an issue in our semantic model.
The CI didn't fail because it doesn't  run some script, but the command `check` was failing on such codes:
```ts
type P = {
[key in P]: D
}
```
This PR fixes the issue, where we track `key` as bindings.
Added a new test case
=> fix(rome_js_semantic): add `TsTypeParameterName` to bindings

crates/rome_js_analyze/src/semantic_analyzers/suspicious/no_duplicate_parameters.rs, crates/rome_js_analyze/tests/specs/suspicious/noDuplicateParameters.js.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noDuplicateParameters.md
Improve `noDuplicateParameters` docs
No change.
No change.
=> docs(rome_js_analyze): improve `noDuplicateParameters` docs

crates/rome_cli/src/execute.rs, crates/rome_console/src/lib.rs, xtask/lintdoc/src/main.rs
Fixes https://github.com/rome/tools/issues/4197
Tested locally
=> fix(rome_cli): don't add newline when formatting from stdin

crates/rome_analyze/src/context.rs, crates/rome_analyze/src/lib.rs, crates/rome_analyze/src/matcher.rs, crates/rome_analyze/src/registry.rs, crates/rome_analyze/src/rule.rs, crates/rome_analyze/src/signals.rs, crates/rome_analyze/src/syntax.rs, crates/rome_analyze/src/visitor.rs, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/snapshots/main_commands_check/ignore_configured_globals.snap, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/src/semantic_analyzers/correctness/no_undeclared_variables.rs
The analyzer infrastructure has had  for a while the `globals` field available in the configuration, although it wasn't documented because it wasn't used.
This PR implements the logic to read these globals and update the `noUnusedVariables` rule to consume it. 
I created a new test case to make sure the feature works.
=> feat(rome_js_analyzer): read globals from analyzer options

crates/rome_js_analyze/src/semantic_analyzers/nursery/no_parameter_assign.rs, website/src/pages/lint/rules/noParameterAssign.md
Fix the version of `noParameterAssign`.
/
/
=> docs(rome_js_analyze): `noParameterAssign` in release 12.0.0

crates/rome_analyze/CONTRIBUTING.md
This takes the review of @ematipico into account.
See [here](https://github.com/rome/tools/pull/4278#pullrequestreview-1330744634) for the review.
This also adds other minor fixes and adjustments.
=> docs(rome_js_analyze): improve CONTRIBUTING

crates/rome_cli/src/execute.rs, crates/rome_cli/src/traversal.rs, crates/rome_fs/src/fs/os.rs, crates/rome_lsp/src/server.rs, crates/rome_service/src/workspace.rs, crates/rome_service/src/workspace/client.rs, crates/rome_service/src/workspace/server.rs, rome.json, website/package.json
This PR changes how the traversal works, making the traversal more aware of the ignored paths.
At the moment, Rome tries to traverse all ignored paths, and we check if **the single file** is ignored. This is very inefficient for two reasons:
- we don't cache when a file is ignored, so we need to check it every single time;
- we end up traversing even ignored folders like `dist/`, `target/`, etc., all folders that have built artefacts;
With this PR, I added a new method to the workspace to check if the path is ignored and changed the `can_handle` function to take into consideration directories. If a directory is ignored, then we stop the traversal.
This changes how the ignored paths should be expressed. I had to change the paths in our `rome.json`. Because of that, I consider this fix a …
=> fix(rome_cli): prevent exploration of ignored directories

website/src/pages/guides/getting-started.mdx
Changing the yarn command so it actually saves it to devPackages, --save-dev is not an option (https://yarnpkg.com/cli/add)
When i used the getting started doc with yarn it installed with into my normal packages and not into the dev ones.
=> docs: Changing the yarn command

website/src/pages/cli.mdx, website/src/pages/configuration.mdx
Enhances the documentation for the new config-path option and defuses some strong wording (~Warning~ -> Important).
Related
- https://github.com/rome/tools/pull/4002
=> website(docs): Enhance the documentation for the config-path option

crates/rome_analyze/src/rule.rs, crates/rome_deserialize/src/json.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs, crates/rome_lsp/tests/server.rs, crates/rome_service/src/configuration/diagnostics.rs, crates/rome_service/src/configuration/mod.rs, crates/rome_service/src/file_handlers/json.rs, crates/rome_service/src/file_handlers/mod.rs, crates/rome_service/src/workspace/server.rs, crates/rome_service/tests/spec_tests.rs
This PR adds a minor improvement to the LSP. When the workspace requests diagnostics for a JSON file, we check if the file being analyzed is a `rome.json` file and attempt to deserialize and return additional diagnostics.
While the schema is already valuable for the majority of the cases:
- sometimes, people don't use the JSON schema, or they are not aware of it;
- there are situations where we run specific validations;
I added a new test case. I also tested locally.
=> feat(rome_lsp): pull diagnostics for `rome.json`

npm/rome/scripts/generate-packages.mjs
This PR just add the license to the autogenerated packages marked as optional dependencies of the main package.
This was causing problems with some systems that require licenses. 
This was referenced [on this issue](https://github.com/rome/tools/issues/4290).
Closes https://github.com/rome/tools/issues/4290
AFAIK, this is only executed on CI whenever a new version is deployed, so no tests are required.
=> fix: add missing license to the generated packages on CI

crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redeclaration.rs, crates/rome_js_analyze/tests/specs/nursery/noRedeclaration/invalid-declaration-merging.ts, crates/rome_js_analyze/tests/specs/nursery/noRedeclaration/invalid-declaration-merging.ts.snap, crates/rome_js_analyze/tests/specs/nursery/noRedeclaration/invalid.jsonc, crates/rome_js_analyze/tests/specs/nursery/noRedeclaration/invalid.jsonc.snap, crates/rome_js_analyze/tests/specs/nursery/noRedeclaration/valid-declaration-merging.ts, crates/rome_js_analyze/tests/specs/nursery/noRedeclaration/valid-declaration-merging.ts.snap, crates/rome_js_analyze/tests/specs/nursery/noRedeclaration/valid-duplicate.ts, crates/rome_js_analyze/tests/specs/nursery/noRedeclaration/valid-duplicate.ts.snap, crates/rome_js_syntax/src/binding_ext.rs, website/src/pages/lint/rules/noRedeclaration.md
Fixes #4287.
While I was fixing the issue, I realized that [noDuplicateParameters](https://docs.rome.tools/lint/rules/noduplicateparameters/) and `noRedeclaration` have some intersections. We could merge these two rules in another PR?
EDIT: this PR also allows duplicate parameters. To prevent duplicate parameters use `noSuplicateParameters` instead.
Extended.
Updated.
=> fix(rome_js_analyze): `noRedeclaration` declaration merging

crates/rome_formatter/src/lib.rs, crates/rome_formatter_test/src/spec.rs, crates/rome_formatter_test/src/utils.rs, crates/rome_js_formatter/src/lib.rs, crates/rome_js_formatter/tests/specs/js/module/expression/binary_range_expression.js, crates/rome_js_formatter/tests/specs/js/module/expression/binary_range_expression.js.snap, crates/rome_js_formatter/tests/specs/js/module/no-semi/semicolons_range.js, crates/rome_js_formatter/tests/specs/js/module/no-semi/semicolons_range.js.snap, crates/rome_js_formatter/tests/specs/js/module/parentheses/range_parentheses_binary.js, crates/rome_js_formatter/tests/specs/js/module/parentheses/range_parentheses_binary.js.snap, crates/rome_js_formatter/tests/specs/js/module/range/range_parenthesis_after_semicol.js, crates/rome_js_formatter/tests/specs/js/module/range/range_parenthesis_after_semicol.js.snap, crates/rome_js_formatter/tests/specs/js/module/range/range_parenthesis_after_semicol_1.js, crates/rome_js_formatter/tests/specs/js/module/range/range_parenthesis_after_semicol_1.js.snap, crates/rome_js_formatter/tests/specs/js/module/string/parentheses_token.js, crates/rome_js_formatter/tests/specs/js/module/string/parentheses_token.js.snap, crates/rome_js_formatter/tests/specs/jsx/parentheses_range.jsx, crates/rome_js_formatter/tests/specs/jsx/parentheses_range.jsx.snap
1. Fix format issues with incorrect replace rage in the source text.
- `crates/rome_js_formatter/tests/specs/js/module/range/range_parenthesis_after_semicol.js.snap`
- `crates/rome_js_formatter/tests/specs/js/module/range/range_parenthesis_after_semicol_1.js.snap`
2. Introduce `<<<ROME_RANGE_START>>>` and `<<<ROME_RANGE_END>>>` for snapshot testing.
3. Fix format the range issue if we get a token in the transformed tree.
UPD:
Let say we want to format with range ``range = 5..94`` this code: 
```
a?.b
const a = () => {sdasdsa;
kek;
dsad<<<ROME_RANGE_START>>>sa;
123;
("y̆es");
};
console.log("🚀".length);
<<<ROME_RANGE_END>>>
("Jan 1, 2018 – Jan 1, 2019");
```
We need to calculate `source` and `dest` ranges. 
- `source` range we use to find a position in the source text where we need to …
=> fix(rome_formatter): fix format range

xtask/codegen/src/generate_new_lintrule.rs
When I execute `just new-lintrule crates/rome_js_analyze/src/analyzers/nursery noNonInteractiveTabindex`, the result has an error like this:
- It seems like the pattern `<rule_name>` on the `declare_rule!` macro is invalid case: https://github.com/rome/tools/blob/9f502577b2e8711f4c6cced00f9bd1b8c42a97e7/xtask/lintdoc/src/main.rs#L390
- So I removed `<` and `>`.
This pr fixes this error.
=> fix(xtask): `just new-lintrule` document generation error

crates/rome_lsp/src/session.rs
Closes https://github.com/rome/tools/issues/4322
I manually tested that creating a new file is correctly handled.
=> fix(rome_lsp): handle untitled files

CHANGELOG.md, crates/rome_aria/src/roles.rs, crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/aria_analyzers/nursery.rs, crates/rome_js_analyze/src/aria_analyzers/nursery/no_noninteractive_element_to_interactive_role.rs, crates/rome_js_analyze/src/aria_analyzers/nursery/no_noninteractive_tabindex.rs, crates/rome_js_analyze/tests/specs/nursery/noNoninteractiveTabindex/invalid.jsx, crates/rome_js_analyze/tests/specs/nursery/noNoninteractiveTabindex/invalid.jsx.snap, crates/rome_js_analyze/tests/specs/nursery/noNoninteractiveTabindex/valid.jsx, crates/rome_js_analyze/tests/specs/nursery/noNoninteractiveTabindex/valid.jsx.snap, crates/rome_js_unicode_table/src/tables.rs, crates/rome_service/src/configuration/linter/rules.rs, crates/rome_service/src/configuration/parse/json/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noNoninteractiveTabindex.md
Closes #3817
- I reused parsing logics written in [no_positive_tabindex.rs](https://github.com/rome/tools/blob/main/crates/rome_js_analyze/src/semantic_analyzers/a11y/no_positive_tabindex.rs)
`cargo test -p rome_js_analyze -- no_noninteractive_tabindex`
- test cases: https://github.com/rome/tools/blob/archived-js/internal/compiler/lint/rules/a11y/noNoninteractiveTabindex.test.toml (file.tsx)
=> feat(rome_js_analyze): noNoninteractiveTabindex

CHANGELOG.md, Cargo.lock, crates/rome_cli/Cargo.toml, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/snapshots/main_commands_check/apply_noop.snap, crates/rome_cli/tests/snapshots/main_commands_check/apply_ok.snap, crates/rome_cli/tests/snapshots/main_commands_check/apply_unsafe_with_error.snap, crates/rome_cli/tests/snapshots/main_commands_check/should_disable_a_rule.snap, crates/rome_cli/tests/snapshots/main_commands_check/should_disable_a_rule_group.snap, crates/rome_formatter/src/diagnostics.rs, crates/rome_lsp/tests/server.rs, crates/rome_service/src/diagnostics.rs, crates/rome_service/src/file_handlers/javascript.rs, crates/rome_service/src/file_handlers/mod.rs, crates/rome_service/src/workspace/server.rs
With this PR, the code emitted by the analyzer actions is now formatted using Rome's internal formatter. After all the analyzer actions have been committed to the current code, the formatting is applied at the end. 
If the formatter is disabled, no formatting is applied.
Existing tests should be updated.
=> feat(rome_service): apply formatter to code actions

CHANGELOG.md, crates/rome_js_analyze/src/analyzers/a11y/no_blank_target.rs, crates/rome_js_analyze/src/analyzers/a11y/use_alt_text.rs, crates/rome_js_analyze/src/analyzers/a11y/use_anchor_content.rs, crates/rome_js_analyze/src/analyzers/a11y/use_html_lang.rs, crates/rome_js_analyze/src/analyzers/a11y/use_key_with_mouse_events.rs, crates/rome_js_analyze/src/analyzers/a11y/use_valid_anchor.rs, crates/rome_js_analyze/src/analyzers/correctness/no_string_case_mismatch.rs, crates/rome_js_analyze/src/analyzers/nursery/no_redundant_alt.rs, crates/rome_js_analyze/src/analyzers/nursery/no_svg_without_title.rs, crates/rome_js_analyze/src/analyzers/style/use_numeric_literals.rs, crates/rome_js_analyze/src/aria_analyzers/nursery/no_noninteractive_element_to_interactive_role.rs, crates/rome_js_analyze/src/aria_analyzers/nursery/no_noninteractive_tabindex.rs, crates/rome_js_analyze/src/aria_analyzers/nursery/no_redundant_roles.rs, crates/rome_js_analyze/src/aria_analyzers/nursery/use_aria_prop_types.rs, crates/rome_js_analyze/src/aria_analyzers/nursery/use_valid_lang.rs, crates/rome_js_analyze/src/aria_services.rs, crates/rome_js_analyze/src/semantic_analyzers/a11y/use_button_type.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_iframe_title.rs, crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs, crates/rome_js_analyze/tests/specs/style/useNumericLiterals/invalid.js.snap, crates/rome_js_syntax/src/expr_ext.rs, crates/rome_js_syntax/src/jsx_ext.rs, crates/rome_js_syntax/src/lib.rs, crates/rome_js_syntax/src/static_value.rs
This PR introduces common logic for checking expression values based on #4073 and discussion. This is useful when implementing some aria rules that checks value of the JSX attributes.
After merge in this PR, I will refactor much more in the current codebases using this methods.
I need to keep the current tests passed. I updated `useNumericLiterals/invalid.js.snap` because the previous code didn't handle empty template string correctly.
=> refactor(rome_js_anaylze): introduce StaticValue enum for checking value of the JSX attributes or JS expressions

CHANGELOG.md, crates/rome_js_analyze/src/globals/runtime.rs, crates/rome_js_analyze/tests/specs/correctness/noUndeclaredVariables/noUndeclaredVariables.js, crates/rome_js_analyze/tests/specs/correctness/noUndeclaredVariables/noUndeclaredVariables.js.snap
Fix https://github.com/rome/tools/issues/4365
`cargo test`
=> fix(rome_js_analyze): lint/correctness/noUndeclaredVariables incorrectly identifies AggregateError as an undeclared variable. #4365

CHANGELOG.md, crates/rome_js_analyze/src/analyzers/style/use_shorthand_array_type.rs, crates/rome_js_analyze/tests/specs/style/useShorthandArrayType/invalid.ts, crates/rome_js_analyze/tests/specs/style/useShorthandArrayType/invalid.ts.snap, crates/rome_js_analyze/tests/specs/style/useShorthandArrayType/valid.ts, crates/rome_js_analyze/tests/specs/style/useShorthandArrayType/valid.ts.snap, website/src/pages/lint/rules/useShorthandArrayType.md
Closes #4349 #4361 
This pr adds modification for nested `ReadonlyArray` (#4349 ) and reduce false positive (#4361 ).
Currently, our `useShorthandArrayType` follows [typescript-eslint/array-type (array-simple option)](https://typescript-eslint.io/rules/array-type/#array-simple).
And the rule should not report `TsObjectType` in a type `Array` or `ReadonlyArray`.
```ts
// issue 4349
type Before = ReadonlyArray<ReadonlyArray<T>>
type After = readonly (readonly T[])[]
// issue 4361
type AcceptedObjectType = Array<{x: string, y: string}>
```
`cargo test -p rome_js_analyze -- use_shorthand_array_type`
- ~~[ ] The PR requires a changelog line~~
- ~~[ ] The PR requires documentation~~
- ~~[ ] I will create a new PR to update the documentation~~
I updated lint rule doc a bit (describes …
=> fix(rome_js_analyze): `useShorthandArrayType` should handle nested ReadonlyArray and not report to `TsObjectType`

CHANGELOG.md, crates/rome_analyze/src/context.rs, crates/rome_analyze/src/lib.rs, crates/rome_analyze/src/matcher.rs, crates/rome_analyze/src/options.rs, crates/rome_analyze/src/registry.rs, crates/rome_analyze/src/signals.rs, crates/rome_analyze/src/syntax.rs, crates/rome_analyze/src/visitor.rs, crates/rome_js_analyze/src/lib.rs, crates/rome_js_analyze/src/semantic_analyzers/correctness/no_undeclared_variables.rs, crates/rome_js_analyze/tests/spec_tests.rs, crates/rome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalidTsInJs.js, crates/rome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalidTsInJs.js.snap, crates/rome_js_analyze/tests/specs/correctness/noUndeclaredVariables/validTsGlobals.ts, crates/rome_js_analyze/tests/specs/correctness/noUndeclaredVariables/validTsGlobals.ts.snap, crates/rome_service/src/file_handlers/javascript.rs, crates/rome_service/src/file_handlers/json.rs, crates/rome_service/src/file_handlers/mod.rs, crates/rome_service/src/workspace/server.rs, website/src/pages/lint/rules/noUndeclaredVariables.md, xtask/bench/src/language.rs, xtask/lintdoc/src/main.rs
This PR adds two new metadata to the analyzer infrastructure:
- the `file_path` of the file being analyzed; this will be useful for some other rules that like https://github.com/rome/tools/discussions/4282.
- the `SourceType`, which will allow making the rules smarter. In this PR, I updated `noUndeclaredVariables`, where the rule doesn't check TypeScript global variables if the file being analyzed is a JavaScript file. 
I created a new test case for the rule that was updated
=> feat(rome_js_analyze): analyzer metadata

CHANGELOG.md, editors/vscode/src/main.ts
Fix #4338
It seems that we are receiving two different DidOpenTextDocument events with different URI schemes. The first one has the scheme "file", which indicates that the file is being accessed directly from the file system. The second one has the scheme "git", which suggests that the file is being accessed from a Git repository. After that we're receiving an change event.
```
rome_lsp::handlers::text_document::did_open{params=DidOpenTextDocumentParams { text_document: TextDocumentItem { uri: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/lo.ts", query: None, fragment: None }, language_id: "typescript", version: 1, text: "console.log(\"before\");\n" } }}
│ ├─┐rome_lsp::handlers::text_document::did_open{params=DidOpenTextDocumen …
```
=> fix(vscode): Text duplication when using VSCode git utilities #4338

crates/rome_js_analyze/src/analyzers/a11y/no_access_key.rs, crates/rome_js_analyze/src/analyzers/a11y/no_auto_focus.rs, crates/rome_js_analyze/src/analyzers/a11y/no_blank_target.rs, crates/rome_js_analyze/src/analyzers/a11y/no_distracting_elements.rs, crates/rome_js_analyze/src/analyzers/a11y/no_header_scope.rs, crates/rome_js_analyze/tests/specs/a11y/noAccessKey/invalid.jsx, crates/rome_js_analyze/tests/specs/a11y/noAccessKey/invalid.jsx.snap, crates/rome_js_analyze/tests/specs/a11y/noAutofocus/invalid.jsx, crates/rome_js_analyze/tests/specs/a11y/noAutofocus/invalid.jsx.snap, crates/rome_js_analyze/tests/specs/a11y/noAutofocus/valid.jsx, crates/rome_js_analyze/tests/specs/a11y/noAutofocus/valid.jsx.snap, crates/rome_js_analyze/tests/specs/a11y/noBlankTarget/invalid.jsx, crates/rome_js_analyze/tests/specs/a11y/noBlankTarget/invalid.jsx.snap, crates/rome_js_analyze/tests/specs/a11y/noBlankTarget/valid.jsx, crates/rome_js_analyze/tests/specs/a11y/noBlankTarget/valid.jsx.snap, crates/rome_js_analyze/tests/specs/a11y/noDistractingElements/invalid.jsx, crates/rome_js_analyze/tests/specs/a11y/noDistractingElements/invalid.jsx.snap, crates/rome_js_syntax/src/expr_ext.rs, crates/rome_js_syntax/src/jsx_ext.rs, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noAutofocus.md, website/src/pages/lint/rules/noBlankTarget.md, website/src/pages/lint/rules/noDistractingElements.md, website/src/pages/lint/rules/noHeaderScope.md
I added more tests and docs for a11y rules through refactoring based on #4342
This is internal refactoring, so I don't update the CHAGELOG.md
=> refactor(rome_js_analyze): add more tests and docs for a11y rules through refactoring 

.github/workflows/main.yml
I fixed the failure of the CI on the main branch that occurred during the git clone.
see: https://github.com/rome/tools/actions/runs/4738153766/jobs/8411710398
```
Error: error: unable to create file tests/baselines/reference/tsserver/configuredProjects/Open-ref-of-configured-project-when-open-file-gets-added-to-the-project-as-part-of-configured-file-update-buts-its-open-file-references-are-all-closed-when-the-update-happens.js: Filename too long
```
=> chore: support long file names when cloning repositories related to Test262

crates/rome_cli/src/commands/help.rs, website/src/pages/formatter/index.mdx
The following PR https://github.com/rome/tools/pull/3657 provided an update to the copy on the website, but did not update the copy in the CLI. 
This update resolves the typo, which is hopefully the last time. 
Followed instructions in [CONTRIBUTING.md](https://github.com/rome/tools/blob/fdf2a8ccc1708374ba9156d2faaa49436e574daa/CONTRIBUTING.md)
- `cargo build`
- `cargo test`
The following screenshot shows running the help command and the `--indent-style` option resolved saying `<tab|space>`
=> docs: change "tabs" to "tab" in format help command

CHANGELOG.md, crates/rome_lsp/tests/server.rs, crates/rome_service/src/file_handlers/javascript.rs
This PR removes the `RuleCategories::ACTION` from being executed during code actions. 
The reason why I removed them from code actions is because:
- they are hidden from the user;
- some of those actions are taking a toll to big files, causing huge delays in saving a file; [relevant discussion](https://discord.com/channels/678763474494423051/1026860476749062154/1099388658336936078)
I updated a test case
=> fix(rome_lsp): remove code assists from code actions

CHANGELOG.md, crates/rome_js_analyze/src/analyzers/style/no_non_null_assertion.rs
Fix #4348.
I also added some comments and made minor refactoring.
No change.
=> fix(rome_js_analyze): #4348

CONTRIBUTING.md, Cargo.lock, crates/rome_analyze/CONTRIBUTING.md, justfile, xtask/codegen/Cargo.toml, xtask/codegen/src/lib.rs, xtask/codegen/src/main.rs, xtask/codegen/src/promote_rule.rs
This PR creates a new `just` script to automate the process of promoting the rules:
```shell
just promote-rule noConsoleLog style
```
=> chore: add script to promote rules

CHANGELOG.md, crates/rome_js_analyze/src/semantic_analyzers/a11y/use_button_type.rs, crates/rome_js_analyze/tests/specs/a11y/useButtonType/inJsx.jsx, crates/rome_js_analyze/tests/specs/a11y/useButtonType/inJsx.jsx.snap, crates/rome_js_analyze/tests/specs/a11y/useButtonType/inObject.js, crates/rome_js_analyze/tests/specs/a11y/useButtonType/inObject.js.snap, crates/rome_js_analyze/tests/specs/a11y/useButtonType/withBindingInvalid.js, crates/rome_js_analyze/tests/specs/a11y/useButtonType/withBindingInvalid.js.snap, crates/rome_js_analyze/tests/specs/a11y/useButtonType/withDefaultNamespaceInvalid.js, crates/rome_js_analyze/tests/specs/a11y/useButtonType/withDefaultNamespaceInvalid.js.snap, crates/rome_js_analyze/tests/specs/a11y/useButtonType/withRenamedImportInvalid.js, crates/rome_js_analyze/tests/specs/a11y/useButtonType/withRenamedImportInvalid.js.snap, website/src/playground/tabs/SettingsTab.tsx
Fix #4410 and make the rule more robust by handling more cases such as:
```jsx
<button type/>
```
I also made some refactoring to simplify the implementation.
New tests and regression tests included.
=> fix(rome_js_analyze): #4410

.github/workflows/bench_analyzer.yml, .github/workflows/bench_cli.yml, .github/workflows/bench_formatter.yml, .github/workflows/bench_parser.yml, .github/workflows/parser_conformance.yml, .github/workflows/pull_request.yml, .github/workflows/pull_request_js.yml, .github/workflows/release_lsp.yml, .github/workflows/runtime.yml, rust-toolchain.toml
- upgrades the rust toolchain to `1.69.0`
- removes `actions-rs` from the workflows because it's an action that is not maintained anymore. 
Current CI should pass
=> chore: new Rust version and change CI actions

CHANGELOG.md, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_camel_case.rs, crates/rome_js_analyze/tests/specs/nursery/useCamelCase/useCamelCase.jsx, crates/rome_js_analyze/tests/specs/nursery/useCamelCase/useCamelCase.jsx.snap
This is related to #3262
`useCamelCase`emits a false positive diagnostic for default exported components.
see: [playground](https://docs.rome.tools/playground/?lintRules=all&code=ZQB4AHAAbwByAHQAIABkAGUAZgBhAHUAbAB0ACAAZgB1AG4AYwB0AGkAbwBuACAASABvAGcAZQAoACkAIAB7AAoAIAAgAHIAZQB0AHUAcgBuACAAKAA8AFQAZQB4AHQAPgB0AGUAcwB0ADwALwBUAGUAeAB0AD4AKQAKAH0ACgAKAGUAeABwAG8AcgB0ACAAZgB1AG4AYwB0AGkAbwBuACAARgBvAG8AKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgADwAZABpAHYAPgBoAG8AZwBlADwALwBkAGkAdgA%2BAAoAfQAKAA%3D%3D)
I add new test cases.
=> fix(rome_js_analyzer): ignore default exported function in useCamelCase

CHANGELOG.md, crates/rome_cli/src/commands/check.rs, crates/rome_cli/src/commands/mod.rs, crates/rome_cli/src/execute/mod.rs, crates/rome_cli/src/execute/process_file.rs, crates/rome_cli/src/execute/std_in.rs, crates/rome_cli/src/lib.rs, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/snapshots/main_commands_check/check_help.snap, crates/rome_cli/tests/snapshots/main_commands_check/check_stdin_apply_successfully.snap, crates/rome_cli/tests/snapshots/main_commands_check/check_stdin_apply_unsafe_only_organize_imports.snap, crates/rome_cli/tests/snapshots/main_commands_check/check_stdin_apply_unsafe_successfully.snap, crates/rome_service/src/file_handlers/javascript.rs, crates/rome_service/src/file_handlers/json.rs, crates/rome_service/src/workspace.rs
This PR allows running the command `rome check` via standard input.
Example:
```shell
cat file.js | rome check --apply-unsafe --organize-imports-enabled=true --stdin-file-path=file.js > file.js
```
In order to make the command `rome check` more ergonomic with `stdin`, I created three new flags:
- `--formatter-enabled`
- `--linter-enabled`
- `--organize-imports-enabled`
By doing so, a user can apply the type of change to the input. These are the same flags that we have in the `rome ci` command, and they behave in the same way.
These new flags can be used even without `stdin`. 
Added new test cases to ensure the changes are applied based on the features enabled/disabled.
=> feat(rome_cli): rome check via stdin

CHANGELOG.md, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_camel_case.rs, crates/rome_js_analyze/tests/specs/nursery/useCamelCase/useCamelCase.js, crates/rome_js_analyze/tests/specs/nursery/useCamelCase/useCamelCase.js.snap
Fix false positive diagnostics that useCamelCase caused to private class members
see: https://discord.com/channels/678763474494423051/1102161432226836480/1102161432226836480
see: [playground](https://docs.rome.tools/playground/?lintRules=all&code=YwBsAGEAcwBzACAASABvAGcAZQAgAHsACgAgACAAIwBhAGIAYwBEAEUARgAgAD0AIAAxADsACgB9AA%3D%3D)
I added new test cases.
=> fix(rome_js_analyzer): Fix false positive diagnostics that useCamelCase caused to private class members

CHANGELOG.md, crates/rome_js_analyze/src/analyzers/a11y/no_header_scope.rs, crates/rome_js_analyze/tests/specs/a11y/noHeaderScope/invalid.jsx, crates/rome_js_analyze/tests/specs/a11y/noHeaderScope/invalid.jsx.snap, crates/rome_js_analyze/tests/specs/a11y/noHeaderScope/valid.jsx, crates/rome_js_analyze/tests/specs/a11y/noHeaderScope/valid.jsx.snap
Fix false positive diagnostics that noHeadeScope caused to custom components.
see: [playground](https://docs.rome.tools/playground/?lintRules=all&code=PABDAG8AbQBwAG8AbgBlAG4AdAAgAHMAYwBvAHAAZQA9AHsAIgB0AGUAcwB0ACIAfQAgAC8APgAKAA%3D%3D)
=> fix(rome_js_analyze): suppress noHeadeScope diagnostics for custom components

CHANGELOG.md, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_hook_at_top_level.rs, crates/rome_js_analyze/tests/specs/nursery/useHookAtTopLevel/invalid.ts, crates/rome_js_analyze/tests/specs/nursery/useHookAtTopLevel/invalid.ts.snap, crates/rome_js_analyze/tests/specs/nursery/useHookAtTopLevel/valid.ts, crates/rome_js_analyze/tests/specs/nursery/useHookAtTopLevel/valid.ts.snap
Fix #4463 
I add some snapshot tests
=> fix(rome_js_analyze): Fix false positive diagnostics that `useHookAtTopLevel` caused to `as` or `satisfies` expressions.

benchmark/run.js
I noticed that we were cloning whole repositories but only using parts of them to actually perform the benchmark against. This change takes advantage of [`git sparse-checkout`](https://git-scm.com/docs/git-sparse-checkout) to only pull the folders that we define in our configuration. It does not affect benchmark results, but does make the setup faster.
I don't believe this requires a changelog entry
This does not require documentation.
=> perf: improve clone speed of benchmark tool with sparse-checkout

CHANGELOG.md, crates/rome_cli/src/commands/mod.rs, crates/rome_cli/tests/commands/lsp_proxy.rs, crates/rome_cli/tests/commands/mod.rs, crates/rome_cli/tests/snapshots/main_commands_lsp_proxy/lsp_proxy_help.snap
Closes https://github.com/rome/tools/issues/4489
We didn't have tests for this command. I created a new one. The `help` output should be enough for now
=> fix(rome_cli): fix regression for `rome lsp-proxy` command

CHANGELOG.md, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/snapshots/main_commands_check/should_not_enable_all_recommended_rules.snap, crates/rome_service/src/configuration/linter/rules.rs, xtask/codegen/src/generate_configuration.rs
Closes https://github.com/rome/tools/issues/4479 and addresses https://github.com/rome/tools/issues/4488
I used the code provided by  https://github.com/rome/tools/issues/4488 because using nursery rules is too brittle.
I created a new test cases
=> fix(rome_service): correctly load recommended rules

CHANGELOG.md, editors/vscode/package.json, npm/rome/package.json
Bug fix release
Just make sure the changelog is fine
=> release: v12.1.1

CHANGELOG.md, CONTRIBUTING.md, editors/vscode/package.json, npm/rome/package.json
=> release: 12.1.2

.github/workflows/pull_request.yml, .github/workflows/pull_request_js.yml, .github/workflows/release_cli.yml, .github/workflows/release_js_api.yml, .github/workflows/runtime.yml
CI gives this warning:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16:
jetli/wasm-pack-action@v0.3.0, pnpm/action-setup@v2.1.0.
For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
Latest `pnpm/action-setup` and `jetli/wasm-pack-action` don't use Node.js 12 any more while not having breaking changes.
=> chore: Bump `pnpm/action-setup` and `jetli/wasm-pack-action` to latest

CHANGELOG.md, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/snapshots/main_commands_check/should_not_enable_nursery_rules.snap, crates/rome_service/src/configuration/linter/rules.rs, xtask/codegen/src/generate_configuration.rs
Closes https://github.com/rome/tools/issues/4479
We treat nursery rules differently from the rest of the rules. We treated them differently only when using the top `recommended: true` but not when `nursery: {}` was defined.
This PR changes the code generation of the configuration to enable recommended rules **only** when `recommended: true`.
Added the test case of the issue
=> fix(rome_service): treat nursery rules differently

.github/workflows/bench_analyzer.yml, .github/workflows/bench_formatter.yml, .github/workflows/bench_parser.yml, .github/workflows/parser_conformance.yml
https://github.com/rome/tools/pull/4541#issuecomment-1567340250
None
Ref: https://trstringer.com/github-actions-multiline-strings/
=> chore(ci): Fix new lines in github output

CHANGELOG.md, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/commands/ci.rs, crates/rome_cli/tests/commands/format.rs, crates/rome_cli/tests/snapshots/main_commands_check/check_help.snap, crates/rome_cli/tests/snapshots/main_commands_check/ignores_unknown_file.snap, crates/rome_cli/tests/snapshots/main_commands_ci/ci_help.snap, crates/rome_cli/tests/snapshots/main_commands_ci/ignores_unknown_file.snap, crates/rome_cli/tests/snapshots/main_commands_format/format_help.snap, crates/rome_cli/tests/snapshots/main_commands_format/ignores_unknown_file.snap, crates/rome_cli/tests/snapshots/main_commands_format/no_supported_file_found.snap, crates/rome_service/src/configuration/merge.rs, crates/rome_service/src/configuration/mod.rs, crates/rome_service/src/configuration/parse/json/files.rs, crates/rome_service/src/settings.rs, crates/rome_service/src/workspace.rs, crates/rome_service/src/workspace/server.rs, crates/rome_service/tests/invalid/files_extraneous_field.json.snap, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json
Closes https://github.com/rome/tools/issues/4546
Added:
- a new CLI option `--file-ignore-unknown` 
- a new configuration option `"ignoreUnknown"`
Added a test case for each command
=> feat(rome_cli, rome_service): ignore unknown files

CHANGELOG.md, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/snapshots/main_commands_check/apply_bogus_argument.snap, crates/rome_js_analyze/src/semantic_analyzers/style/no_parameter_assign.rs, crates/rome_js_analyze/tests/specs/style/noParameterAssign/valid.jsonc, crates/rome_js_analyze/tests/specs/style/noParameterAssign/valid.jsonc.snap, crates/rome_js_semantic/src/semantic_model/binding.rs, crates/rome_js_semantic/src/semantic_model/model.rs
Fix a semantic model crash when we have `JsBogusBinding`.
```
function _13_1_3_fun(arguments) { }
```
```
0: JS_FUNCTION_DECLARATION@0..44
0: (empty)
1: FUNCTION_KW@0..18 "function" [Newline("\n"), Whitespace("        ")] [Whitespace(" ")]
2: (empty)
3: JS_IDENTIFIER_BINDING@18..29
0: IDENT@18..29 "_13_1_3_fun" [] []
4: (empty)
5: JS_PARAMETERS@29..41
0: L_PAREN@29..30 "(" [] []
1: JS_PARAMETER_LIST@30..39
0: JS_FORMAL_PARAMETER@30..39
0: JS_BOGUS_BINDING@30..39
0: IDENT@30..39 "arguments" [] []
1: (empty)
2: (empty)
3: (empty)
2: R_PAREN@39..41 ")" [] [Whitespace(" ")]
6: (empty)
```
We have the crash here for the `NoParameterAssign` rule:
https://github.com/rome/tools/blob/dad13a9f6cc2a9743d5aa8c08fad0830b67e7a1c/crates/rome_js_semantic/src/semantic_model/model.rs#L330-L337
I believe …
=> fix(rome_js_analyzer): Big pack of js/ts files that crashes rome #4323

CHANGELOG.md, npm/rome/bin/rome
This adds an env var which allow users to override the path to the rome binary.
It's a way to provide a solution for running rome under nix.
See https://github.com/rome/tools/issues/4516#issuecomment-1569095669
=> Accept an environment variable to specify which binary to use

crates/rome_cli/src/diagnostics.rs, crates/rome_cli/tests/snapshots/main_commands_check/apply_unsafe_with_error.snap, crates/rome_cli/tests/snapshots/main_commands_check/shows_organize_imports_diff_on_check.snap, crates/rome_cli/tests/snapshots/main_commands_check/shows_organize_imports_diff_on_check_apply.snap
Addresses this issue:
* https://github.com/rome/tools/issues/4579
> There seems to be a typo on [this line](https://github.com/rome/tools/blob/e3d8c8b5a89ea532d95870221c52250f356f7d2e/crates/rome_cli/src/diagnostics.rs#LL202C9-L202C9).
> 
> ```
>   × Fixes applied to the file, but there a still diagnostics to address.
> ```
> 
> It seems to be wanting to say "there **_are_** still diagnostics to address".
- [-] The PR requires a changelog line
- [-] The PR requires documentation
- [-] I will create a new PR to update the documentation
=> fix typo in diagnostic message

CHANGELOG.md, crates/rome_js_analyze/src/analyzers/style/use_default_parameter_last.rs, crates/rome_js_analyze/tests/specs/style/useDefaultParameterLast/invalid.js, crates/rome_js_analyze/tests/specs/style/useDefaultParameterLast/invalid.js.snap, crates/rome_js_analyze/tests/specs/style/useDefaultParameterLast/invalid.ts.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/useDefaultParameterLast.md
This PR improves the code action and the diagnostic message of `useDefaultParameterLast`.
New test included.
No need.
=> refactor(rome_js_analyze): enhance `useDefaultParameterLast`

CHANGELOG.md, crates/rome_service/src/configuration/javascript.rs, crates/rome_service/src/configuration/parse/json/javascript.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json
Closes https://github.com/rome/tools/issues/4573
I will add tests in the next PRs
=> feat(rome_service): add parser option for unsafe decorators

CHANGELOG.md
=> docs: fix broken link in change log

CHANGELOG.md
Make it easier for people to find docs for different lint rules
mentioned in the change log by making lint rule names clickable links.
Note: The noExtraSemicolon link
(https://docs.rome.tools/lint/rules/noextrasemicolon/) is currently
broken. This link appeared elsewhere in the change log already, though.
=> docs: linkify lint rules in change log

CHANGELOG.md, crates/rome_js_analyze/src/analyzers/suspicious/no_redundant_use_strict.rs, crates/rome_js_analyze/tests/specs/suspicious/noRedundantUseStrict/validReactDirectives.tsx, crates/rome_js_analyze/tests/specs/suspicious/noRedundantUseStrict/validReactDirectives.tsx.snap
React introduce new directives "use client" and "use server".
noRedundantUseStrict rule raise false positive error about these directives, so I fixed it.
see: [playground](https://docs.rome.tools/playground/?lineWidth=120&indentStyle=space&semicolons=as-needed&lintRules=all&code=JwB1AHMAZQAgAGMAbABpAGUAbgB0ACcACgAgAAoAaQBtAHAAbwByAHQAIAB7ACAAdQBzAGUAUwB0AGEAdABlACAAfQAgAGYAcgBvAG0AIAAnAHIAZQBhAGMAdAAnAAoAIAAKAGUAeABwAG8AcgB0ACAAZABlAGYAYQB1AGwAdAAgAGYAdQBuAGMAdABpAG8AbgAgAEMAbwB1AG4AdABlAHIAKAApACAAewAKACAAIABjAG8AbgBzAHQAIABbAGMAbwB1AG4AdAAsACAAcwBlAHQAQwBvAHUAbgB0AF0AIAA9ACAAdQBzAGUAUwB0AGEAdABlACgAMAApAAoAIAAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwAZABpAHYAPgAKACAAIAAgACAAIAAgADwAcAA%2BAFkAbwB1ACAAYwBsAGkAYwBrAGUAZAAgAHsAYwBvAHUAbgB0AH0AIAB0AGkAbQBlAHMAPAAvAHAAPgAKACAAIAAgACAAIAAgAD …
=> fix(rome_js_analyze):  noRedundantUseStrict check only 'use strict' directive

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, editors/vscode/README.md, website/src/pages/vscode.mdx
Part of https://github.com/rome/tools/discussions/4585
This PR:
- update the PR template and removes the documentation part
- update the contribution guidelines
- adds some information to the VSCode extension
@rome/core-contributors I added a couple of labels. When merging a PR, use these labels for those PRs that needs some follow up for documentation and/or changelogs.
=> chore: remove changelog line and documentation parts

crates/rome_js_analyze/src/analyzers/complexity/no_useless_constructor.rs, website/src/pages/lint/rules/noUselessConstructor.md
The version was not properly set for [`noUselessConstructor`](https://docs.rome.tools/lint/rules/nouselessconstructor/) (set to next instead of 12.1).
=> refactor(rome_js_analyze): set version for noUselessConstructor

CHANGELOG.md, crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_global_is_nan.rs, crates/rome_js_analyze/tests/specs/nursery/noGlobalIsNan/invalid.js, crates/rome_js_analyze/tests/specs/nursery/noGlobalIsNan/invalid.js.snap, crates/rome_js_analyze/tests/specs/nursery/noGlobalIsNan/valid.js, crates/rome_js_analyze/tests/specs/nursery/noGlobalIsNan/valid.js.snap, crates/rome_service/src/configuration/linter/rules.rs, crates/rome_service/src/configuration/parse/json/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/components/generated/NumberOfRules.astro, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noGlobalIsNan.md
This rule recommends using `Number.isNaN` instead of the global and unsafe `isNaN` that attempts a coercion.
=> feat(rome_js_analyze): noGlobalIsNan

CHANGELOG.md, crates/rome_js_analyze/src/analyzers/correctness/no_unreachable_super.rs, crates/rome_js_analyze/tests/specs/correctness/noUnreachableSuper/missingSuper.js, crates/rome_js_analyze/tests/specs/correctness/noUnreachableSuper/missingSuper.js.snap
Fix #4520
I update snapshot tests
=> fix(rome_js_analyze): suppress false positive diagnostics to nested if statements 

CHANGELOG.md, crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_global_is_finite.rs, crates/rome_js_analyze/tests/specs/nursery/noGlobalIsFinite/invalid.js, crates/rome_js_analyze/tests/specs/nursery/noGlobalIsFinite/invalid.js.snap, crates/rome_js_analyze/tests/specs/nursery/noGlobalIsFinite/valid.js, crates/rome_js_analyze/tests/specs/nursery/noGlobalIsFinite/valid.js.snap, crates/rome_js_analyze/tests/specs/nursery/noGlobalIsNan/invalid.js.snap, crates/rome_service/src/configuration/linter/rules.rs, crates/rome_service/src/configuration/parse/json/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/components/generated/NumberOfRules.astro, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noGlobalIsFinite.md
This rule recommends using `Number.isFinite` instead of the global and unsafe `isFinite` that attempts a type coercion.
I was wondering if this could not be merged with `noGlobalIsNan`. However, I didn't find a common name... This is why I proposed two distinct rules.
=> feat(rome_js_analyze): add noGlobalIsFinite

CHANGELOG.md, crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/analyzers/nursery.rs, crates/rome_js_analyze/src/analyzers/nursery/use_arrow_function.rs, crates/rome_js_analyze/tests/specs/nursery/useArrowFunction/invalid.ts, crates/rome_js_analyze/tests/specs/nursery/useArrowFunction/invalid.ts.snap, crates/rome_js_analyze/tests/specs/nursery/useArrowFunction/valid.ts, crates/rome_js_analyze/tests/specs/nursery/useArrowFunction/valid.ts.snap, crates/rome_service/src/configuration/linter/rules.rs, crates/rome_service/src/configuration/parse/json/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/astro.config.ts, website/src/components/generated/NumberOfRules.astro, website/src/frontend-scripts/toc.ts, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/useArrowFunction.md, website/src/playground/utils.ts
=> feat(rome_js_analyze): add `useArrowFunction`

website/src/playground/Playground.tsx, website/src/playground/PlaygroundLoader.tsx, website/src/playground/components/SettingsPanel.tsx, website/src/playground/tabs/SettingsTab.tsx, website/src/playground/types.ts, website/src/playground/workers/romeWorker.ts, website/src/styles/playground/_settings.scss
Close https://github.com/rome/tools/issues/4606
Add a checkbox for playground under the  syntax setting tab
=> feat(playground): Implement playground option #4606

CHANGELOG.md, Cargo.lock, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/snapshots/main_commands_check/check_json_files.snap, crates/rome_deserialize/src/json.rs, crates/rome_diagnostics/Cargo.toml, crates/rome_service/Cargo.toml, crates/rome_service/src/configuration/parse/json.rs, crates/rome_service/src/file_handlers/json.rs, justfile
Closes https://github.com/rome/tools/issues/4444
As for now I just limited myself to implement the `lint` function because we don't have actions for JSON lint rules.
Added a new test case to make sure we get diagnostics.
=> feat(rome_service): add support for JSON linter in the workspace

CHANGELOG.md, crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/analyzers/nursery.rs, crates/rome_js_analyze/src/analyzers/nursery/no_void.rs, crates/rome_js_analyze/tests/specs/nursery/noVoid/invalid.js, crates/rome_js_analyze/tests/specs/nursery/noVoid/invalid.js.snap, crates/rome_js_analyze/tests/specs/nursery/noVoid/valid.js, crates/rome_js_analyze/tests/specs/nursery/noVoid/valid.js.snap, crates/rome_js_syntax/src/expr_ext.rs, crates/rome_service/src/configuration/linter/rules.rs, crates/rome_service/src/configuration/parse/json/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/components/generated/NumberOfRules.astro, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noVoid.md
Implements the rule [`noVoid`](https://eslint.org/docs/latest/rules/no-void)
Added few test cases
=> feat(rome_js_analyze): rule `noVoid`

crates/rome_js_analyze/src/analyzers/style/no_comma_operator.rs, website/src/pages/lint/rules/noCommaOperator.md
Fix an erroneous example of `noCommaOperator`
No change.
=> docs: fix `noCommaOperator` example

CHANGELOG.md, crates/rome_js_analyze/src/analyzers/correctness/no_invalid_constructor_super.rs, crates/rome_js_analyze/tests/specs/correctness/noInvalidConstructorSuper/invalid.js.snap, crates/rome_js_analyze/tests/specs/correctness/noInvalidConstructorSuper/valid.ts, crates/rome_js_analyze/tests/specs/correctness/noInvalidConstructorSuper/valid.ts.snap
Fixes #4624.
This PR should prevent future related bugs.
Regression tests included.
=> No invalid constructor super/4624

justfile
I just ran `just install-tools` as the `CONTRIBUTING.md` guide told me to, but it didn't work for me, because it appears to install the wrong `binstall` crate. The one it installed was this unmaintained crate: https://crates.io/crates/binstall, but the one it should install (to make `cargo binstall` work) is this one: https://crates.io/crates/cargo-binstall
If you want to reproduce it, make sure no `binstall` crate is installed:
```sh
cargo uninstall binstall
cargo uninstall cargo-binstall
cargo binstall # This should error now.
```
Then you can rerun `just install-tools`, and with this PR it should install the correct one.
=> Install correct binstall crate

crates/rome_js_analyze/src/semantic_analyzers/correctness/no_undeclared_variables.rs, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/pnpm-lock.yaml, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noUndeclaredVariables.md
[Context](https://discord.com/channels/678763474494423051/678763474930761739/1124355556036055150)
=> docs: better documentation for rule

Cargo.lock, Cargo.toml, crates/rome_analyze/Cargo.toml, crates/rome_cli/Cargo.toml, crates/rome_cli/src/diagnostics.rs, crates/rome_cli/src/lib.rs, crates/rome_console/Cargo.toml, crates/rome_deserialize/Cargo.toml, crates/rome_diagnostics/Cargo.toml, crates/rome_diagnostics/src/adapters.rs, crates/rome_diagnostics/src/diagnostic.rs, crates/rome_diagnostics_categories/Cargo.toml, crates/rome_formatter/Cargo.toml, crates/rome_formatter_test/Cargo.toml, crates/rome_fs/Cargo.toml, crates/rome_js_analyze/Cargo.toml, crates/rome_js_formatter/Cargo.toml, crates/rome_js_parser/Cargo.toml, crates/rome_js_syntax/Cargo.toml, crates/rome_json_formatter/Cargo.toml, crates/rome_lsp/Cargo.toml, crates/rome_rowan/Cargo.toml, crates/rome_service/Cargo.toml, crates/rome_text_edit/Cargo.toml, crates/rome_text_size/Cargo.toml, crates/rome_wasm/Cargo.toml, justfile
Updated dependencies and did some housekeeping inside our crates.
Current CI should pass
=> chore: update dependencies and housekeeping

CHANGELOG.md, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_hook_at_top_level.rs, crates/rome_js_analyze/tests/specs/nursery/useHookAtTopLevel/invalid.js, crates/rome_js_analyze/tests/specs/nursery/useHookAtTopLevel/invalid.js.snap, crates/rome_js_analyze/tests/specs/nursery/useHookAtTopLevel/valid.js, crates/rome_js_analyze/tests/specs/nursery/useHookAtTopLevel/valid.js.snap
Fix #4637 
I added some snapshot tests
=> fix(rome_js_analyze): suppress useHookAtTopLevel's false positive when accessing properties directly from a hook

.github/workflows/main.yml, .github/workflows/parser_conformance.yml
We don't need to install `cargo-cache` when cleaning the cache because `moonrepo/setup-rust` action already done it in advance.
I've already checked it in other pull request on my fork. A `Documentation` job failed, but this is not related to changes in this pull request. The reason is that my fork doesn't have an appropriate GitHub token.
https://github.com/TaKO8Ki/tools/pull/1
CI should pass.
=> ci: avoid installing `cargo-cache` twice

.editorconfig, crates/rome_cli/src/execute/mod.rs, crates/rome_cli/src/execute/process_file.rs, crates/rome_cli/src/execute/process_file/format_file.rs, crates/rome_cli/src/execute/process_file/lint_file.rs, crates/rome_cli/tests/snapshots/main_commands_format/file_too_large.snap, crates/rome_cli/tests/snapshots/main_commands_format/file_too_large_cli_limit.snap, crates/rome_cli/tests/snapshots/main_commands_format/file_too_large_config_limit.snap, crates/rome_cli/tests/snapshots/main_commands_lint/file_too_large.snap, crates/rome_cli/tests/snapshots/main_commands_lint/file_too_large_cli_limit.snap, crates/rome_cli/tests/snapshots/main_commands_lint/file_too_large_config_limit.snap
Part of the refactoring of the process of files.
As you can see, a few bugs were caught in the process:
- fixed the emitted diagnostics
- fixed the processed files
=> refactor(rome_cli): format file in different flow

crates/rome_js_analyze/src/analyzers/nursery/no_nonoctal_decimal_escape.rs, crates/rome_js_analyze/src/options.rs, crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/malformedOptions.js.snap, crates/rome_service/src/configuration/parse/json/linter.rs, crates/rome_service/src/configuration/parse/json/rules.rs, crates/rome_service/tests/invalid/hooks_incorrect_options.json, crates/rome_service/tests/invalid/hooks_incorrect_options.json.snap, crates/rome_service/tests/invalid/naming_convention_incorrect_options.json, crates/rome_service/tests/invalid/naming_convention_incorrect_options.json.snap, website/src/pages/lint/rules/noNonoctalDecimalEscape.md, xtask/codegen/src/generate_configuration.rs, xtask/lintdoc/src/main.rs
This PR refactors the way we deserialize the options of the lint rules.
I wasn't delighted with the diagnostic messages, there were very unclear and we were showing suggestions that didn't belong to the rule we were scanning.
I created ad-hoc functions to pass down the rule name and use it to emit correct diagnostics. This involves a bit more code, but it gives the user a better message.
Added new test cases and updated the current ones
=> refactor(rome_service): better messaging for rule options

CHANGELOG.md, crates/rome_js_analyze/src/semantic_analyzers/complexity/no_useless_fragments.rs, crates/rome_js_analyze/tests/specs/complexity/noUselessFragments/issue_4639.jsx, crates/rome_js_analyze/tests/specs/complexity/noUselessFragments/issue_4639.jsx.snap
Fix #4639
see: https://docs.rome.tools/playground/?lintRules=all&code=ZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIABTAG8AbQBlAEMAbwBtAHAAbwBuAGUAbgB0ACgAKQAgAHsACgAgACAAcgBlAHQAdQByAG4AIAA8AGQAaQB2ACAAeAAtAHMAbwBtAGUALQBwAHIAbwBwAD0AewA8AD4ARgBvAG8APAAvAD4AfQAgAC8APgA7AAoAfQAKAAoAZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIABTAG8AbQBlAEMAbwBtAHAAbwBuAGUAbgB0AEEAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgADwAZABpAHYAIAB4AC0AcwBvAG0AZQAtAHAAcgBvAHAAPQAiAEYAbwBvACIAIAAvAD4AOwAKAH0A
I update some snapshot tests and I checked the issue was resolved by using https://github.com/fubhy/rome-bug-repro.
=> fix(rome_js_analyze): noUselessFragments use JsxString node when replacing JsxText

crates/rome_js_analyze/src/analyzers/nursery/no_nonoctal_decimal_escape.rs, crates/rome_js_analyze/tests/specs/nursery/noNonoctalDecimalEscape/invalid.js.snap, website/src/pages/lint/rules/noNonoctalDecimalEscape.md
Addresses https://discord.com/channels/678763474494423051/978209399120216076/1126496823587115018
This PR modifies the noNonoctalDecimalEscape rule and narrows the scope of its fixes. This change eliminates the unusual circumstance of multiple diagnostics being performed on behalf of the user and also rectifies issues with the `cargo lintdoc` command.
If I understand correctly, the current analyzer should only be able to return one action for each diagnostic.
In this rule, below example `\0\8` should have multiple diagnoses and suggest multiple fixes.
```javascript
const x = "\0\8";
// `\0\8` should be reported and fixed to `\u00008` 
// `\8` should be reported and fixed to `\0\u0038`
// `\8` should be reported and fixed to `\0\\8` (this fix will be removed by this PR because of diagnostic …
```
=> fix(rome_js_analyze): noNonoctalDecimalEscape returns single diagnostic

CHANGELOG.md, crates/rome_js_analyze/src/semantic_analyzers/correctness/no_undeclared_variables.rs, crates/rome_js_analyze/tests/specs/correctness/noUndeclaredVariables/noUndeclaredVariables.ts, crates/rome_js_analyze/tests/specs/correctness/noUndeclaredVariables/noUndeclaredVariables.ts.snap, crates/rome_js_semantic/src/events.rs
Fix #4642 
I update some snapshot tests.
=> fix(rome_js_analyze): skip `this` reference identifier in the semantic analyzer

CHANGELOG.md, crates/rome_js_parser/src/syntax/module.rs, crates/rome_js_parser/test_data/inline/err/export_default_expression_broken.js, crates/rome_js_parser/test_data/inline/err/export_default_expression_broken.rast
Fix https://github.com/rome/tools/issues/4670
`cargo test`
=> fix(rome_js_parser): Crash at empty default export #4670

Cargo.lock, Cargo.toml, crates/rome_css_parser/Cargo.toml, crates/rome_css_parser/LICENSE, crates/rome_css_parser/README.md, crates/rome_css_parser/src/lexer/mod.rs, crates/rome_css_parser/src/lexer/tests.rs, crates/rome_css_parser/src/lib.rs, crates/rome_css_parser/src/prelude.rs, crates/rome_css_syntax/Cargo.toml, crates/rome_css_syntax/src/generated/kind.rs, crates/rome_js_formatter/Cargo.toml, crates/rome_js_parser/Cargo.toml, crates/rome_json_parser/Cargo.toml, crates/rome_json_parser/src/lexer/mod.rs, crates/rome_rowan/Cargo.toml, xtask/codegen/src/css_kinds_src.rs
Lexes string literal and comments 
https://drafts.csswg.org/css-syntax/#consume-string-token
https://github.com/swc-project/swc/blob/main/crates/swc_css_parser/src/lexer/mod.rs
https://github.com/servo/rust-cssparser/blob/master/src/tokenizer.rs
`cargo test -p rome_css_parser`
=> feat(rome_css_parser): CSS lexer #4682

CHANGELOG.md, crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/analyzers/nursery.rs, crates/rome_js_analyze/src/analyzers/nursery/no_useless_empty_export.rs, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/invalid_with_default_export.js, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/invalid_with_default_export.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/invalid_with_empty_export.js, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/invalid_with_empty_export.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/invalid_with_export.js, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/invalid_with_export.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/invalid_with_export_from.js, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/invalid_with_export_from.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/invalid_with_import.js, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/invalid_with_import.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/invalid_with_sideeffect_import.js, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/invalid_with_sideeffect_import.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/valid_empty_export.js, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/valid_empty_export.js.snap, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/valid_export.js, crates/rome_js_analyze/tests/specs/nursery/noUselessEmptyExport/valid_export.js.snap, crates/rome_service/src/configuration/linter/rules.rs, crates/rome_service/src/configuration/parse/json/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/components/generated/NumberOfRules.astro, website/src/frontend-scripts/mobile.ts, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noUselessEmptyExport.md
This implements [no-useless-empty-export](https://typescript-eslint.io/rules/no-useless-empty-export/) with a minor improvement: we also report the case where several empty exports compete. In this case, we preserve the last empty export.
=> feat(rome_js_analyze): noUselessEmptyExport

CHANGELOG.md, crates/rome_js_analyze/src/analyzers/nursery/no_fallthrough_switch_clause.rs, crates/rome_js_analyze/tests/specs/nursery/noFallthroughSwitchClause/valid.js, crates/rome_js_analyze/tests/specs/nursery/noFallthroughSwitchClause/valid.js.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noFallthroughSwitchClause.md
This PR fixes an issue with `noFallthroughSwitchClause` that reported code with block statements:
```js
switch x {
// this case was reported by the rule
case 0: {
f();
break;
}
case 1:
f();
}
```
New test included.
=> refactor(rome_js_analyze): noFallthroughSwitchClause handle block statements

CHANGELOG.md, crates/rome_js_analyze/src/analyzers/correctness.rs, crates/rome_js_analyze/src/semantic_analyzers/correctness.rs, crates/rome_js_analyze/src/semantic_analyzers/correctness/no_new_symbol.rs, crates/rome_js_analyze/tests/specs/correctness/noNewSymbol/invalid.jsonc, crates/rome_js_analyze/tests/specs/correctness/noNewSymbol/invalid.jsonc.snap, crates/rome_service/src/configuration/linter/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noNewSymbol.md
This PR improves `noNewSymbol` by handling `globalThis` and `window` global namespaces.
I also moved the rule to the correct location (`analyzers` to `semantic_analyzers`).
I noted that other rules are in the wrong location.
I think we should merge `semantic_analyzers` into `analyzers`. The separation seems confusing for most of the contributors...
Test added.
=> refactor(rome_js_analyze): handle globalThis for `noNewSymbol`

crates/rome_cli/tests/commands/format.rs, crates/rome_js_formatter/src/js/expressions/arrow_function_expression.rs, crates/rome_js_formatter/tests/quick_test.rs, crates/rome_js_formatter/tests/specs/ts/arrow/arrow_parentheses.ts, crates/rome_js_formatter/tests/specs/ts/arrow/arrow_parentheses.ts.snap, crates/rome_js_formatter/tests/specs/ts/arrow/options.json
I missed a few cases in #4667 that lead to syntax errors in some arrow function parameters when `arrow_parentheses` is set to `asNeeded`
Added a new test file `arrow_parentheses.ts`
=> fix(rome_js_formatter): improve handling of arrow parentheses

CHANGELOG.md, crates/rome_js_analyze/src/analyzers/style/use_enum_initializers.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_naming_convention.rs, crates/rome_js_analyze/src/utils.rs, crates/rome_js_analyze/tests/specs/suspicious/noDuplicateCase/valid.js, crates/rome_js_analyze/tests/specs/suspicious/noDuplicateCase/valid.js.snap, crates/rome_js_syntax/src/lib.rs
Fix #4706
Regression test included.
=> fix(rome_js_analyze): fix a false positive for `noDuplicateCase`

crates/rome_cli/src/execute/traverse.rs, crates/rome_cli/tests/commands/check.rs, crates/rome_cli/tests/snapshots/main_commands_check/applies_organize_imports_from_cli.snap
There was a bug where the "organize imports" feature wasn't correctly checked.
Added a new test case. No need for changelog line because this is part of a previous refactor.
=> fix(rome_cli): correctly check for organize imports support

crates/rome_js_formatter/src/js/expressions/arrow_function_expression.rs
The `arrow_parentheses` option currently removes parentheses to the body that would otherwise be added to avoid confusion. Since this is probably not expected to anyone using the option (considering prettier doesn't remove them), this PR reverts this behavior
`cargo t`
=> fix(rome_js_formatter): properly retain parentheses in body

CHANGELOG.md, crates/rome_js_analyze/src/analyzers/nursery/use_literal_enum_members.rs, crates/rome_js_analyze/tests/specs/nursery/useLiteralEnumMembers/invalid.ts, crates/rome_js_analyze/tests/specs/nursery/useLiteralEnumMembers/invalid.ts.snap, crates/rome_js_analyze/tests/specs/nursery/useLiteralEnumMembers/valid.ts, crates/rome_js_analyze/tests/specs/nursery/useLiteralEnumMembers/valid.ts.snap, crates/rome_js_syntax/src/expr_ext.rs, website/src/pages/lint/rules/useLiteralEnumMembers.md
This PR relaxes `useLiteralEnumMembers` to allow referencing to previous enum members. This is commonly used in enum flags (it is used multiple times in the TypeScript Compiler source code). For example:
```ts
enum FileAccess {
None = 0,
Read = 1,
Write = 1 << 1,
All = Read | Write,
}
```
A wide range of references are recognized (`Write`, `FileAccess.Write`, `FileAccess["Write"]` ``FileAccess[`Write`]``) 
To be more consistent, the rule is also relaxed to allow arbitrary numeric and string expressions that involve string and number literals.
I wonder if the rule should be renamed to `useConstantEnumMembers` to better reflect the new implementation.
Tests updated and extended.
=> feat(rome_js_analyze): relax `useLiteralEnumMembers`

crates/rome_deserialize/src/json.rs, crates/rome_formatter/src/builders.rs, crates/rome_formatter/src/format_element.rs, crates/rome_formatter/src/format_element/document.rs, crates/rome_formatter/src/printer/mod.rs, crates/rome_formatter/src/source_map.rs, crates/rome_formatter/src/trivia.rs, crates/rome_js_analyze/src/analyzers/nursery/use_import_restrictions.rs, crates/rome_js_analyze/src/assists/correctness/organize_imports.rs, crates/rome_js_formatter/src/utils/jsx.rs, crates/rome_js_formatter/src/utils/test_call.rs, crates/rome_js_semantic/src/events.rs, crates/rome_js_semantic/src/semantic_model/scope.rs, crates/rome_js_syntax/src/directive_ext.rs, crates/rome_js_syntax/src/import_ext.rs, crates/rome_json_syntax/src/member_ext.rs, crates/rome_json_syntax/src/string_ext.rs, crates/rome_rowan/src/cursor/token.rs, crates/rome_rowan/src/lib.rs, crates/rome_rowan/src/syntax/token.rs, crates/rome_rowan/src/token_text.rs
This PR follows the discussion in https://github.com/rome/tools/pull/4721#issuecomment-1648213843
I renamed `SyntaxTokenText` to `TextToken` to communicate the fact that it is not related to `SyntaxToken`: there is no reference to parent nodes, and there is no way to get the absolute range of the text.
Following this renaming, I also renamed `SyntaxTokenTextSlice` to `LocatedTokenText`.
All test passed.
=> refactor(rome_rowan): rework SyntaxTokenText into TokenText

Cargo.lock, crates/rome_css_factory/src/generated/node_factory.rs, crates/rome_css_factory/src/generated/syntax_factory.rs, crates/rome_css_factory/src/lib.rs, crates/rome_css_parser/Cargo.toml, crates/rome_css_parser/src/lexer/mod.rs, crates/rome_css_parser/src/lib.rs, crates/rome_css_parser/src/parser.rs, crates/rome_css_parser/src/syntax.rs, crates/rome_css_parser/src/token_source.rs, crates/rome_css_parser/tests/css_test_suite/ok/empty.css.snap, crates/rome_css_parser/tests/spec_test.rs, crates/rome_css_parser/tests/spec_tests.rs, crates/rome_css_syntax/src/generated/kind.rs, crates/rome_css_syntax/src/generated/macros.rs, crates/rome_css_syntax/src/generated/nodes.rs, crates/rome_css_syntax/src/generated/nodes_mut.rs, crates/rome_css_syntax/src/lib.rs, crates/rome_json_syntax/src/lib.rs, crates/rome_rowan/src/syntax/trivia.rs, xtask/codegen/css.ungram, xtask/codegen/src/css_kinds_src.rs
Initial implementation of `CssTokenSource` and `CssParser` for the CSS parser. 
Added `CssParserOptions` which has an `allow_single_line_comments` option. This allows the writing of single line comments in CSS syntax.
`cargo test`
=> feat(rome_css_parser): CSS parser #4682

CHANGELOG.md, crates/rome_lsp/src/diagnostics.rs, crates/rome_lsp/src/handlers/formatting.rs, crates/rome_lsp/src/lib.rs, crates/rome_lsp/src/server.rs, crates/rome_service/src/diagnostics.rs, crates/rome_service/src/snapshots/file_ignored.snap
Closes https://github.com/rome/tools/issues/4564
I created a function to handle errors coming from the single query operations of the LSP, in this way we can pass the `Client` and send messages if we see fit.
I tested locally and manually on my VSCode extension.
=> feat(rome_lsp): send message to the client

crates/rome_js_analyze/src/analyzers/a11y/no_blank_target.rs, crates/rome_js_analyze/src/analyzers/a11y/use_alt_text.rs, crates/rome_js_analyze/src/analyzers/nursery/no_control_characters_in_regex.rs, crates/rome_js_analyze/src/analyzers/nursery/no_self_assign.rs, crates/rome_js_analyze/src/analyzers/nursery/use_literal_enum_members.rs, crates/rome_js_analyze/src/analyzers/nursery/use_literal_keys.rs, crates/rome_js_analyze/src/analyzers/style/use_enum_initializers.rs, crates/rome_js_analyze/src/analyzers/suspicious/no_duplicate_class_members.rs, crates/rome_js_analyze/src/analyzers/suspicious/no_duplicate_object_keys.rs, crates/rome_js_analyze/src/analyzers/suspicious/no_prototype_builtins.rs, crates/rome_js_analyze/src/aria_services.rs, crates/rome_js_analyze/src/react.rs, crates/rome_js_analyze/src/react/hooks.rs, crates/rome_js_analyze/src/semantic_analyzers/correctness/no_global_object_calls.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_naming_convention.rs, crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs, crates/rome_js_analyze/src/utils.rs, crates/rome_js_factory/src/make.rs, crates/rome_js_formatter/src/js/expressions/call_arguments.rs, crates/rome_js_syntax/src/directive_ext.rs, crates/rome_js_syntax/src/expr_ext.rs, crates/rome_js_syntax/src/import_ext.rs, crates/rome_js_syntax/src/jsx_ext.rs, crates/rome_js_syntax/src/lib.rs, crates/rome_js_syntax/src/static_value.rs, crates/rome_json_syntax/src/lib.rs, crates/rome_json_syntax/src/member_ext.rs, crates/rome_json_syntax/src/string_ext.rs
This PR improves the concistency of the code-base. It introduces several changes:
- Remove `QuotedString` and `StaticStringValue` in favor of `TokenText` and `StaticValue`.
This removes a bug in the implementation of `QuotedString` that was not reported yet.
- Remove unused functions related to these types
- Simplify `StaticValue` by replacing `TemplateChunk` with `String` and `EmptyString`
- I removed dead (and misleading) code (comparison against `-0` and `+0` has no sense because we only handle positive numbers...)
- I removed recognition of template string such as "`${1}`" because this leads to erroneous string values (for instance `${1n}` is converted to the string `1n` instead of the string `1`).
There is more refactoring to do (maybe removing `StaticValue` in favor of an union of …
=> refactor(rome_syntax): improve `inner_string_text`

website/src/layouts/BaseLayout.astro
The image meta tags urls in the rome tools website are broken and link to https://rome.toolsimg/social-logo.png instead of https://rome.tools/img/social-logo.png
```html
<meta content="https://rome.toolsimg/social-logo.png" property="og:image">
```
The site url in the astro.config.ts is set to https://rome.tools, so a slash needs to be added for it to work properly
```js
site: "https://rome.tools",
```
The fix is to add a slash to a broken URL, I made sure that the updated url works and navigates to the social-logo.png image.
=> fix: image urls are broken in meta tags

CHANGELOG.md, crates/rome_diagnostics_categories/src/categories.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/no_unsafe_declaration_merging.rs, crates/rome_js_analyze/tests/specs/nursery/noUnsafeDeclarationMerging/invalid.ts, crates/rome_js_analyze/tests/specs/nursery/noUnsafeDeclarationMerging/invalid.ts.snap, crates/rome_js_analyze/tests/specs/nursery/noUnsafeDeclarationMerging/valid.ts, crates/rome_js_analyze/tests/specs/nursery/noUnsafeDeclarationMerging/valid.ts.snap, crates/rome_js_semantic/src/events.rs, crates/rome_service/src/configuration/linter/rules.rs, crates/rome_service/src/configuration/parse/json/rules.rs, editors/vscode/configuration_schema.json, npm/backend-jsonrpc/src/workspace.ts, npm/rome/configuration_schema.json, website/src/components/generated/NumberOfRules.astro, website/src/pages/lint/rules/index.mdx, website/src/pages/lint/rules/noUnsafeDeclarationMerging.md
Implements [no-unsafe-declaration-merging](https://typescript-eslint.io/rules/no-unsafe-declaration-merging/) with a minor difference: we accept declaration merging between an interface and an ambient class because it is not unsafe.
_ESlint_ tests included and extra tests.
=> feat(rome_js_analyze): noUnsafeDeclarationMerging

crates/rome_js_semantic/src/events.rs
Deduplicate a function from the rome_js_semantic crate.
No change.
=> refactor(rome_js_semantic): deduplicate code

.github/workflows/pull_request.yml, .github/workflows/release_cli.yml, .github/workflows/release_js_api.yml, .github/workflows/release_lsp.yml, .github/workflows/runtime.yml, npm/backend-jsonrpc/pnpm-lock.yaml, npm/js-api/pnpm-lock.yaml
I update Node.js to v18 (v14 is EOL) and pnpm to v8.
=> chore: update node-version and pnpm in CI

.github/workflows/pull_request.yml, Cargo.toml, crates/rome_cli/src/configuration.rs, crates/rome_cli/tests/commands/format.rs, crates/rome_cli/tests/snapshots/main_commands_format/format_jsonc_files.snap, crates/rome_cli/tests/snapshots/main_commands_format/treat_known_json_files_as_jsonc_files.snap, crates/rome_cli/tests/snapshots/main_commands_format/treats_typescript_json_like_jsonc.snap, crates/rome_css_parser/Cargo.toml, crates/rome_deserialize/src/json.rs, crates/rome_js_analyze/Cargo.toml, crates/rome_js_transform/Cargo.toml, crates/rome_json_analyze/Cargo.toml, crates/rome_json_syntax/src/file_source.rs, crates/rome_service/src/configuration/diagnostics.rs, crates/rome_service/src/configuration/mod.rs, crates/rome_service/src/file_handlers/json.rs, crates/rome_service/src/file_handlers/mod.rs, crates/rome_service/tests/spec_tests.rs, crates/rome_test_utils/Cargo.toml, crates/rome_test_utils/src/lib.rs, justfile
This PR adds support for parsing `.jsonc` files.
Additionally, I added some "known files" that should be parse as `jsonc` files. The list of files was copied from the VSCode repository: https://github.com/microsoft/vscode/blob/67d7cbc82247f6695854ebe70a66d275ebd5f479/extensions/json/package.json#L47-L69
I added new test cases
=> feat: add support for `.jsonc` files

CHANGELOG.md, crates/rome_js_analyze/src/analyzers/style/use_enum_initializers.rs, crates/rome_js_analyze/tests/specs/style/useEnumInitializers/invalid.ts, crates/rome_js_analyze/tests/specs/style/useEnumInitializers/invalid.ts.snap, crates/rome_js_analyze/tests/specs/style/useEnumInitializers/valid.ts, crates/rome_js_analyze/tests/specs/style/useEnumInitializers/valid.ts.snap, website/src/pages/lint/rules/useEnumInitializers.md
The rule now reports all uninitialized members of an enum in a single diagnostic.
This reduces the noise produced by the rule.
This also simplifies the implementation of the quick-fix.
Moreover, ambient enum declarations are now ignored.
This avoids reporting ambient enum declarations in _TypeScript_ declaration files.
```
declare enum Weather {
Rainy,
Sunny,
}
```
New tests included.
=> refactor(rome_js_analyze): improve `useEnumInitializers`

xtask/codegen/src/generate_new_lintrule.rs
Improve the generation of new lint rule, directly using `range()`.
Manually tested.
=> Generate new lintrule

crates/rome_cli/tests/configs.rs, crates/rome_cli/tests/snapshots/main_commands_check/deprecated_suppression_comment.snap, crates/rome_cli/tests/snapshots/main_commands_check/file_too_large.snap, crates/rome_cli/tests/snapshots/main_commands_check/file_too_large_cli_limit.snap, crates/rome_cli/tests/snapshots/main_commands_check/file_too_large_config_limit.snap, crates/rome_cli/tests/snapshots/main_commands_ci/file_too_large.snap, crates/rome_cli/tests/snapshots/main_commands_ci/file_too_large_cli_limit.snap, crates/rome_cli/tests/snapshots/main_commands_ci/file_too_large_config_limit.snap, crates/rome_cli/tests/snapshots/main_commands_init/creates_config_file.snap, crates/rome_cli/tests/snapshots/main_commands_init/creates_config_file_when_rome_installed_via_package_manager.snap, crates/rome_cli/tests/snapshots/main_commands_rage/with_configuration.snap, crates/rome_cli/tests/snapshots/main_commands_rage/with_malformed_configuration.snap, crates/rome_service/src/configuration/organize_imports.rs, editors/vscode/configuration_schema.json, npm/rome/configuration_schema.json
This PR enables import sorting by default and goes out of the experimental phase.
I updated test cases. I will update the changelog and documentation in the release PR.
=> feat: enable organize imports by default

crates/rome_js_analyze/src/analyzers/style/use_single_var_declarator.rs, crates/rome_js_analyze/src/semantic_analyzers/nursery/use_naming_convention.rs, crates/rome_js_formatter/src/js/declarations/for_variable_declaration.rs, crates/rome_js_formatter/src/js/declarations/variable_declaration.rs, crates/rome_js_syntax/src/stmt_ext.rs
Fix #4646 
This PR is to update linter logic for using declaration.
All tests that already exist are now passed.
=> feat(rome_js_analyze): update linter logic for using declaration

crates/rome_js_analyze/tests/specs/suspicious/noRedeclare/valid-declaration-merging.ts, crates/rome_js_analyze/tests/specs/suspicious/noRedeclare/valid-declaration-merging.ts.snap, crates/rome_js_syntax/src/binding_ext.rs
fixes #4771
Note: [`tsc` doesn't always allow merging namespaces and variables](https://github.com/microsoft/TypeScript/issues/55190#issuecomment-1684904258). Either way, checking this shouldn't fall under the linter - either it's a type error or it's a declaration merge, but it's never a shadow.
=> fix(noRedeclare): allow merging namespace + variable
