.github/CONTRIBUTING.md

Contributing doc had a link to `romejs/rome` instead of `facebookexperimental/rome`.

Fix dead link

---

README.md

The logo used to have an `alt` attribute from a previous project.
The new `alt` attribute includes the name of the project and a description of the logo taken from the history section of the README.md.

Updated the logo `alt` attribute on README.md

---

packages/@romejs/core/master/Master.ts

Hi i try run `rome start` and get error
```✔ Connected to daemon
✔ Started daemon!
Done in 0.26s.
[Error: The server->client event "reporterRemoteToLocalMessage" cannot be subscribed by a client bridge
Failed to generate stacktrace: ENOENT: no such file or directory, open '/Users/User/Downloads/sa/rome.cjs.map'] Promise {
<rejected> [Error: The server->client event "reporterRemoteToLocalMessage" cannot be subscribed by a client bridge
Failed to generate stacktrace: ENOENT: no such file or directory, open '/Users/User/Downloads/sa/rome.cjs.map']```

Fix error: The server->client event "reporterRemoteToLocalMessage"

---

packages/@romejs/cli-flags/Parser.ts

Was browsing and saw a redundant `if` statement. Perhaps this had been intended to log when a flag was set twice but most CLIs don't seem to worry about this and as such this method _appears_ to be an unnecessary indirection for the time being 🤷‍♂

Remove redundant method

---

packages/@romejs/core/master/linter/CompilerLinter.ts

I've tried `./scripts/dev-rome lint` command, and then I got this error message on console.
But json syntax must be double quote key string like `{"enabled": true}`.
I added escaped double quotes at the key string.
```js
"Files excluded from linting as it's not enabled. Add `lint: {\"enabled\": true}`"
```
Thanks 🤗

[@romejs] CompilerLinter.ts: fix invalid json syntax in message

---

packages/@romejs/codec-js-manifest/dependencies.ts

This PR adds a pattern to parse NPM aliases eg `npm:@hapi/joi@15.x.x` which were throwing an error when bundling.
@sebmck from our discussion on discord I can't figure out where I need to `parseSemverRange` on the version. Just returning the version as I did won't work?

[WIP/HOLD] Adds a pattern to parse NPM aliases

---

packages/@romejs/js-parser/__rtests__/__rfixtures__/jsx/basic/22/input.mjs
packages/@romejs/js-parser/__rtests__/__rfixtures__/jsx/basic/22/output.txt
packages/@romejs/js-parser/__rtests__/index.ts
packages/@romejs/js-parser/tokenizer/index.ts

fixes #33 
In a .mjs file (or other ESModules compatible file) if there is a `@jsx` pragma at the top, enable jsx syntax. This is similar to what happens for flow with `@flow`
The tests are failing due to the .mjs file extension. Thinking about the best way to solve that, currently I added .mjs as a valid fixture extension but it seems there is some code that's "forcing" it to be read as a script instead of a module for the test purposes

Enable jsx with pragma

---

packages/@romejs/core/master/linter/CompilerLinter.ts

As described in #69, rome instructs the user to run `rome config enable lint` when no linting configuration is present. To generate a valid linting configuration, `rome config enable-category lint` should be run instead. This updates the CLI output to reflect that.

Update error message for missing lint config (#69)

---

README.md

In future I assume the readme will link to a hosted website, but in the meantime just this just updates the deep link to the markdown file.
Note the tests were failing on master when I cloned and this change didn't add any failures, so I'm presuming it's ok.

Fix broken link from main readme to "getting started"

---

.github/CONTRIBUTING.md
website/docs/community/contributing.md

This fixes two more broken "Getting Started" links in the contributing-related files.
It also might make sense to remove `CONTRIBUTING.md` since it has been added to the `website` folder (or vice versa)?

Fix broken "Getting Started" link in CONTRIBUTING

---

packages/@romejs/string-markup/__rtests__/__rsnapshots__/parse.ts.rsnap
packages/@romejs/string-markup/__rtests__/parse.ts
packages/@romejs/string-markup/parse.ts

This is not necessary and prevents Windows paths from being used as attribute values. #39

string-markup: Remove string escaping

---

.github/CONTRIBUTING.md
README.md
website/docusaurus.config.js
website/src/pages/index.js

Simple PR to unify the various "Getting Started" links to point to the website instead of the repo's Markdown file.

Point "Getting Started" links to website

---

packages/@romejs/js-compiler/__rtests__/lint.ts
packages/@romejs/js-compiler/transforms/lint/index.ts
packages/@romejs/js-compiler/transforms/lint/noLabelVar.ts

Adds `no-label-var` check for #94 
Maybe also check for `BROWSER` / `NODE` / `JEST` - Variables?

adds noLabelVar to linter

---

packages/@romejs/codec-js-manifest/convert.ts
packages/@romejs/codec-js-manifest/index.ts
packages/@romejs/codec-js-manifest/types.ts
packages/@romejs/consume/Consumer.ts
packages/@romejs/consume/types.ts
packages/@romejs/core/master/fs/Resolver.ts
packages/@romejs/core/master/fs/resolverSuggest.ts
packages/@romejs/js-compiler/lib/Context.ts
packages/@romejs/parser-core/index.ts
packages/@romejs/path/__rtests__/index.ts
packages/@romejs/path/collections.ts
packages/@romejs/path/index.ts

This PR adds support for Node Package Exports to the module resolver https://nodejs.org/api/esm.html#esm_package_exports

Resolver: Add support for Node exports manifest field

---

packages/@romejs/js-compiler/__rtests__/lint.ts
packages/@romejs/js-compiler/transforms/lint/index.ts
packages/@romejs/js-compiler/transforms/lint/noDeleteVars.ts

Address item `noDeleteVars ` on issue #94 
- Includes a test for `noDeleteVars`, assumes the parser mode is `modern`
ps: uses ES Lint `noDeleteVars` as reference

add noDeleteVars lint rule

---

packages/@romejs/codec-js-manifest/index.ts

I should add tests but we don't really have any for any of this package. I'll add this condition when writing them later.

Add default name for people when normalizing loose manifests

---

packages/@romejs/js-compiler/__rtests__/lint.ts
packages/@romejs/js-compiler/transforms/lint/index.ts
packages/@romejs/js-compiler/transforms/lint/noTemplateCurlyInString.ts

Add no template curly in string for #94

Add noTemplateCurlyInString lint rule

---

packages/@romejs/fs/index.ts
scripts/vendor/rome.cjs

This fixes an issue reported that's likely due to a race condition when deleting cache files.
I can't imagine any scenarios in Rome where we use `unlink` where we care if the file no longer exists, so this change suppresses them.

fs: Make unlink safe from file deletion

---

packages/@romejs/js-compiler/transforms/lint/index.ts

Easy PR to sort the lint imports in alphabetical order so that it reduces the chance of merge conflicts and also makes visual scanning of certain imports easier.
@sebmck As a follow up, what do you think about making one directory per lint rule and co-locating the tests within each directory? `packages/@romejs/js-compiler/__rtests__/lint.ts` is growing pretty rapidly in size.

js-compiler: sort lint imports

---

packages/@romejs/cli-reporter/Reporter.ts
packages/@romejs/core/client/commands.ts

```
cli-reporter: Add informative prompts for key usage on all select calls
cli-reporter: In select, when pressing escape, kill the process
cli-reporter: In select, when we kill the process, also output a warning message
local init command: Add support for tests component
local init command: Error when a project already exists in the cwd
```
Resolves #161 and #162

Interactive CLI and init command fixes

---

packages/@romejs/codec-js-regexp/index.ts
packages/@romejs/diagnostics/categories.ts
packages/@romejs/js-analysis/evaluators/modules/ExportLocalDeclaration.ts
packages/@romejs/js-ast-utils/isStatement.ts
packages/@romejs/js-compiler/transforms/lint/__rtests__/noDuplicateCase.ts
packages/@romejs/js-compiler/transforms/lint/index.ts
packages/@romejs/js-compiler/transforms/lint/noDuplicateCase.test.ts
packages/@romejs/js-compiler/transforms/lint/noDuplicateCase.ts

Implements `no-duplicate-case` for the linter as part of work on issue #94

Checks for duplicate switch case declarations

---

website/docs/community/contributing.md

The current `Code of Conduct` link is broken. I was initially going to move back directories and navigate to `CODE_OF_CONDUCT.md` but I felt that linking `https://github.com/facebookexperimental/rome/blob/master/.github/CODE_OF_CONDUCT.md` would be a better solution
Let me know if there's any preference! 👍

Fixing Code of Conduct link

---

package.json

Added requirements node version based on below doc.
[CONTRIBUTING.md getting-started](https://github.com/facebookexperimental/rome/blob/master/.github/CONTRIBUTING.md#getting-started)
I guess this is effective on common projects prevent any annoying issue report come from older node environment.  
But Rome is special about `node_modules`, don't need run `yarn install` though. 😅
```
// run yarn install with node v10.15.3
ryota.murakami@ryotas-MacBook-Pro ~/f/rome> yarn install
yarn install v1.22.0
[1/5] 🔍  Validating package.json...
error rome-root@0.0.2: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.15.3"
error Found incompatible module.
```
Anyway I think better than nothing this is, thanks! 🙏

package.json: add "engines": {"node": ">=12.0.0"}

---

packages/@romejs/core/master/bundler/BundleRequest.ts
packages/@romejs/core/master/linter/Linter.ts
packages/@romejs/diagnostics/DiagnosticsProcessor.ts
packages/@romejs/diagnostics/categories.ts

Didn't notice that #168 removed the `addSuppressions` call. I've added it back since those suppressions could be used to hide compiler/parser diagnostics etc.
Instead, it's now possible to signal to `DiagnosticsProcessor` to ignore certain diagnostic category prefixes. We also do this to allow bundler suppressions, which would have otherwise been triggered in the linter etc.

Add ability for DiagnosticsProcessor to ignore the unused suppression s of certain category prefixes

---

website/docusaurus.config.js

Currently, Logo is not displayed at Twitter card.
This adds `og:image`.

Add og:image

---

website/docs/community/contributing.md
website/docs/introduction/getting-started.md
website/docs/introduction/installation.md

The installation guide and getting started guide on the website created copy-able code block that started with `$`. When actually using the docusaurus copy button, the `$` would also be copied, resulting in the user either ignoring the copy button completely or having to remove the first character of the command after pasting it in.
This change removes the `$` from the code blocks so users can copy it and directly paste it in a shell.
Quick GIF of a screencast showing the copy differences between current and this change.

[website] Removed bash command $ prefix in code blocks 

---

website/src/css/custom.css
website/src/pages/index.js
website/src/pages/styles.module.css

Hi !
I made small improvements for the accessibility of the website :
- "Get Started" btn
- Now has a `:focus` state which change based on the current theme
- Changed the text color to black because of the contrast
- Changed the Hero banner subtitle to a `<h2>` for a better HTML structure
Before the page jumped from a `<h1>` to a `<h3>`
The current contrast : 
The new one : 
I hope these changes are relevant 😄 
Keep up the great work 👍

feat(website): improve accessibility

---

packages/@romejs/core/common/types/analyzeDependencies.ts
packages/@romejs/core/master/bundler/BundleRequest.ts
packages/@romejs/core/master/dependencies/DependencyGraph.ts
packages/@romejs/core/master/dependencies/DependencyNode.ts
packages/@romejs/diagnostics/descriptions.ts
packages/@romejs/js-compiler/api/analyzeDependencies.test.md
packages/@romejs/js-compiler/api/analyzeDependencies.test.ts
packages/@romejs/js-compiler/api/analyzeDependencies/index.ts

This PR adds a new `topLevelLocalBindings` property to `analyzeDependencies`. When importing from a module and we can't find the import, we check if there's a local binding with the same name and hint that they may have forgotten to export it.
I also took the liberty of cleaning up some confusing property names in `DependencyNode`.
Full credit goes to @aweary who came up with this in [this tweet](https://twitter.com/aweary/status/1240386993839730688/) about a new language he's working on.

Provide a hint when we can't find an export that exists as a local binding

---

packages/rome/package.json

This PR adds a `postinstall` method to the, currently unreleased, `rome` npm package. Right now it's just a placeholder.
One of the tenants I listed in the README when I wrote it was:
> **Set clear expectations.** Make project intent and decisions known well in advance. Nothing should be a surprise.
This is one of the things I was thinking about when writing it. In the future we may want to advertise a link to the Rome OpenCollective if we end up having one. A lot of people evidentially hate having advertisements blasted at them in their terminal, and others may also argue the efficacy of it in the first place.
I would rather us be in the position to remove it later than not being able to add it at all.
I think having this ability is important because while I don't think I'd ever …

Add postinstall message

---

packages/@romejs/js-ast-utils/isTypeExpressionWrapperNode.ts
packages/@romejs/js-generator/generators/typescript/TSNonNullExpression.ts
packages/@romejs/js-generator/generators/typescript/TSTypeAssertion.ts

We were bailing out when `typeAnnotations: false` when we should special case them as they're actual value wrappers.

Fix code gen for TSTypeAssertion and TSNonNullExpression

---

website/docs/introduction/installation.md

On Windows the ```cd rome; ./scripts/build-release dist``` does not work. The following works on Windows; ```cd rome && node scripts/build-release dist```. This requires PowerShell 7 just for the && to work.

Instructions for building on Windows 10.

---

packages/@romejs/codec-js-regexp/index.ts
packages/@romejs/js-compiler/transforms/lint/noReferenceToNonExistingGroup.test.md
packages/@romejs/js-compiler/transforms/lint/noReferenceToNonExistingGroup.test.ts

In this PR: 
* I refactored the octal parsing code used in my previous PR https://github.com/facebookexperimental/rome/pull/197 to fill out the `// TODO octal` that was left out for octal parsing (`\0` case). 
* I also discovered and fixed a `Reference to non-existent group` case that the previous PR was not catching.
Thanks

Octal escape parsing

---

packages/@romejs/diagnostics/descriptions.ts
packages/@romejs/js-parser/tokenizer/index.ts

In https://github.com/facebookexperimental/rome/pull/192, we reverted the dangling backlash lint rule https://github.com/facebookexperimental/rome/pull/181 since it was being checked during the lint phases rather than during parsing.
This PR performs the check in the parser instead.
PS: I wasn't sure how to add tests. If I should, can you point me where/how to add them? I saw `@romejs/js-parser/test-fixtures`, but I wasn't sure if that's where to add them
Thanks

Dangling backslash

---

website/docusaurus.config.js

Fix the following meta header:
```
<meta data-react-helmet="true" property="og:image" content="https://romejs.devhttps://romejs.dev/img/rome-logo.png">
<meta data-react-helmet="true" property="twitter:image" content="https://romejs.devhttps://romejs.dev/img/rome-logo.png">
```

Fix Docusaurus theme image config

---

packages/@romejs/vcs/index.ts

Before this change, any new files wouldn't be picked. The reason behind this change is to be able to run `rome lint --fix --changed` on the entire changeset.

Add new files to the VCS's modified files

---

packages/@romejs-integration/vscode/package.json

`repository` and `bugs` are optional fields which let users easily navigate to the repository and submit bugs from the vscode marketplace.
Slightly unrelated: Also I registered the `rome` and `romejs` namespace for vscode extensions and I recently updated the extension to be whats on master with your recent rewrite. I don't mind donating the namespace to you or if thats not possible I'll just update it whenever there is a version bump to the extension. The extension can be found [here](https://marketplace.visualstudio.com/items?itemName=rome.rome).

add repository & bugs field for vscode extension

---

packages/@romejs/js-formatter/builders/jsx/JSXElement.ts

Right now it's possible to manipulate the children of a `JSXElement` and if it's `selfClosing` then it's children will not be output. This adds a check to the code generator to only output it that way when it has no children.
I considered getting rid of the `selfClosing` property all together, and just leaving in the `children.length === 0` case, but if that's used with the formatter then as someone is developing they'll have go back and constantly readd the end tag. This way we preserve the original intent.

Check for children.length when printing a selfClosing JSXElement

---

packages/@romejs/js-formatter/builders/expressions/CallExpression.ts

Prior this change, the output for `OptionalCallExpression` was wrong:
```js
f<T>?(...xs)
```
Correct output is:
```js
f?.<T>(...xs)
```

Fix OptionalCallExpression formatting

---

packages/@romejs/codec-js-regexp/index.ts
packages/@romejs/js-parser/test-fixtures/es2015/uncategorised/196/output.txt
packages/@romejs/js-parser/test-fixtures/esprima/expression-primary-literal-regular-expression/u-flag-surrogate-pair/output.txt
packages/@romejs/js-parser/test-fixtures/esprima/expression-primary-literal-regular-expression/u-flag-valid-range/output.txt

Before this PR Rome would return `Unexpected end of file` instead of the proper regex error.

fix regex diagnostics

---

packages/@romejs/cli-flags/Parser.ts

It looks like `<pad>` was missing a closing tag

Add closing tag

---

packages/@romejs/cli-reporter/Reporter.ts
packages/@romejs/core/master/WorkerQueue.ts
packages/@romejs/core/master/bundler/BundleRequest.ts
packages/@romejs/core/master/dependencies/DependencyGraph.ts
packages/@romejs/core/master/fs/FileAllocator.ts
packages/@romejs/core/master/linter/Linter.ts

This PR optimizes the worker queueing abstraction we use throughout Rome.
When we want to do things like compile files, we assign them to workers, and in parallel dispatch one request each to each worker. We do this to prevent sending all the requests to all workers at the same time. However this lead to idle time in the workers between the requests from the master process. This changes it so that we always dispatch at least 2 requests, which fill that idle time.
The command I used for the benchmark was:
```
./scripts/dev-rome bundle packages/rome /tmp/rome-bundle-test --profile
```
The `--profile` flag produces a profile containg all Rome processes. You can then load it into Chrome, making it super easy to do these sorts of performance investigations.
**Before** 9.6 seconds
**After** 5 …

Make bundler 2x faster

---

packages/@romejs/cli-flags/Parser.ts
packages/@romejs/codec-js-manifest/convert.ts
packages/@romejs/codec-js-manifest/index.ts
packages/@romejs/consume/Consumer.ts

This PR adds support for fallback exports arrays to our manifest validation.
This was tricky as it required catching diagnostics when validating each element, and returning the first valid one.
Possible improvements:
- Adding in lossless serialization, since we lose all the intermediate fallbacks
- What do we do if none of them are valid?
Documentation:
- https://github.com/jkrems/proposal-pkg-exports#validations-and-fallbacks
- https://nodejs.org/api/esm.html#esm_package_exports_fallbacks

Add support for manifest exports fallback arrays

---

packages/@romejs/js-compiler/api/compile.ts
packages/@romejs/js-formatter/Printer.ts

This fixes source maps generation which was also prevent --coverage option to work 
This was the easiest fix, but I wasn't sure if it was the right one. I also considered refactoring 
https://github.com/facebookexperimental/rome/blob/d95a3a7aab90773c9b36d9c82a08c8c4c6b68aa5/packages/%40romejs/js-formatter/Printer.ts#L214-L234
to increment `generatedColumn` even if `lineWrap` is false, but wasn't sure. 
Let me know what you think

fix sourcemaps generation

---

packages/@romejs/core/master/Cache.ts
packages/@romejs/core/master/bundler/BundleRequest.ts
packages/@romejs/core/master/bundler/Bundler.ts

Turns out our in-memory caching in the master was broken. This basically meant when we were bundling test files we were compiling every single file, which is why it was so slow.
While weren't hitting the master cache, we were hitting the worker memory cache. We still incurred considerable overhead marshalling this data back and forth, especially with the size of the individual file mappings array, which is huge. We should also look into minimizing the size of it.
I also noticed that there could be race conditions since we sometimes bundle files in parallel, meaning we could be compiling multiple times at one point in time, so I added a lock so we wait, and hopefully hit the cache when the lock is released.

Fix caching and add bundle compile lock

---

packages/@romejs/cli-reporter/Progress.ts
packages/@romejs/cli-reporter/ProgressBase.ts
packages/@romejs/cli/bin/rome.ts
packages/@romejs/cli/cli.ts
packages/@romejs/codec-source-map/SourceMapConsumer.ts
packages/@romejs/codec-source-map/SourceMapConsumerCollection.ts
packages/@romejs/codec-source-map/SourceMapGenerator.ts
packages/@romejs/codec-source-map/index.ts
packages/@romejs/codec-source-map/types.ts
packages/@romejs/core/client/commands.ts
packages/@romejs/core/common/bridges/TestWorkerBridge.ts
packages/@romejs/core/common/types/bundler.ts
packages/@romejs/core/common/types/client.ts
packages/@romejs/core/common/utils/executeMain.ts
packages/@romejs/core/master/MasterRequest.ts
packages/@romejs/core/master/bundler/BundleRequest.ts
packages/@romejs/core/master/bundler/Bundler.ts
packages/@romejs/core/master/commands/bundle.ts
packages/@romejs/core/master/commands/run.ts
packages/@romejs/core/master/commands/test.ts
packages/@romejs/core/master/dependencies/DependencyNode.ts
packages/@romejs/core/master/testing/TestRunner.ts
packages/@romejs/core/master/testing/types.ts
packages/@romejs/core/test-worker/TestWorkerRunner.ts
packages/@romejs/diagnostics/DiagnosticsProcessor.ts
packages/@romejs/js-formatter/Printer.ts
packages/@romejs/v8/CoverageCollector.ts
packages/@romejs/v8/sourceMapManager.ts
packages/rome/index.ts

This PR improves bundler performance when bundling multiple files even more. The focus of this was to make `rome test` even faster. There was a lot of low hanging fruit. I've done the following improvements.
- We allow passing in markup to progress bars. This markup is then stripped to just plain text. The display of a progress bar is debounced, so we were doing some unnecessary work for progress bar text that ever even made it to the console.
- Deferred the creation of source maps. This made it so we don't have any overhead of source maps until we've actually.
- Allowed a `SourceMapConsumer` to be constructed with raw mappings
- Cached `DependencyNode#resolveImports`.
- Disabled coverage by default for `rome test`. Still enabled for `rome ci`. You can explicitly use `rome test …

Improve multiple bundle performance even more

---

packages/@romejs/cli-flags/Parser.ts
packages/@romejs/cli-flags/serializeCLIFlags.ts
packages/@romejs/codec-json/parse.ts
packages/@romejs/consume/Consumer.ts
packages/@romejs/consume/types.ts
packages/@romejs/core/master/Master.ts
packages/@romejs/core/master/MasterRequest.ts

Before we allowed `rome test --updateSnapshots` but this now errors and tells you to use `--update-snapshots`.
This also fixes a bug where you weren't allowed a trailing argument after a boolean flag. eg.
```
rome test --update-snapshots packages/@romejs-compiler
```
Would throw an error about an invalid argument index.

Enforce kebab casing for CLI flags

---

packages/@romejs/cli-reporter/ProgressBase.ts
packages/@romejs/cli/testWorker.ts
packages/@romejs/consume/Consumer.ts
packages/@romejs/core/common/utils/fork.ts
packages/@romejs/core/master/testing/TestRunner.ts
packages/@romejs/core/test-worker/TestWorker.ts

So I forgot that the test runner supports multiple test workers but it was hardcoded to one. So I just set the worker count to the same max worker count for regular server workers.
The only tricky part of this was adding in some logic that selects a random inspector port. There's a V8 inspector connection for all test workers from the master so it can elegantly handle timeouts. By default there's only one port that it uses.
**Before** 20s
**After** 14s

Enable multiple test workers

---

packages/@romejs/codec-js-regexp/index.ts

This is a PR that escapes `\b` in regular expressions which allows it to get parsed as `RegExpWordBoundaryCharacter` which previously wasn't happening.

escape `\b` in regular expressions

---

packages/@romejs-runtime/rome/test.ts
packages/@romejs/cli-flags/Parser.test.ts
packages/@romejs/codec-js-manifest/dependencies.test.ts
packages/@romejs/codec-semver/parse.test.ts
packages/@romejs/core/test-worker/SnapshotManager.ts
packages/@romejs/core/test-worker/TestAPI.ts
packages/@romejs/core/test-worker/TestWorkerRunner.ts
packages/@romejs/js-ast-utils/getCompletionRecords.test.ts
packages/@romejs/js-compiler/api/analyzeDependencies.test.ts
packages/@romejs/js-compiler/api/lint.test.ts
packages/@romejs/js-compiler/suppressions.test.ts
packages/@romejs/js-parser/index.test.ts
packages/@romejs/path-match/parse.test.ts
packages/@romejs/string-markup/parse.test.ts

This PR changes the `t.snapshot` methods to be async. In the process I cleaned up the current snapshot manager code to support n snapshots.

Async snapshots

---

packages/rome/package.json

This PR fix #313. Just add version number to `/packages/rome/package.json` so **npm** could install dist folder.

Fix npm can't install dist folder as missing package version

---

packages/@romejs/core/test-worker/SnapshotManager.ts

`parser.input` will have removed the carriage returns

Use parser.input rather than the raw file content in SnapshotManager

---

packages/@romejs/cli-flags/Parser.ts
packages/@romejs/cli/cli.ts
packages/@romejs/core/client/commands/lsp.ts
packages/@romejs/core/common/commands.ts

This PR adds an `ignoreFlags` array you can specify on a command, or on the root flag parser options.
This marks the flag as used, and ignores it when checking for incorrect casing and shorthand usage. This is used in the `rome lsp` command as there's some default flags passed by `vscode-languageclient`.
cc @KevinKelbie

Add ignoreFlags option to cli-flags

---

packages/@romejs/diagnostics/descriptions.ts
packages/@romejs/js-ast/utils.ts
packages/@romejs/js-compiler/types.ts
packages/@romejs/js-formatter/builders/types/IntersectionTypeAnnotation.ts
packages/@romejs/js-formatter/builders/typescript/TSMappedType.ts
packages/@romejs/js-formatter/builders/typescript/TSTypeParameterDeclaration.ts
packages/@romejs/js-parser/tokenizer/state.ts
packages/@romejs/messages/index.ts
packages/@romejs/project/load.ts
packages/@romejs/project/types.ts
packages/@romejs/typescript-helpers/index.ts

Before the change, a `TSMappedType` node was not wrapping when its line width with exceeded the print width.
Before:
```ts
type ProjectConfigJSONObjectReducer<Object> = { [PropertyKey in keyof Object]: ProjectConfigJSONPropertyReducer<Object[PropertyKey]> };
type JustNodeKeys<T> = ExcludeCoreNodeKeys<{[K in keyof T]: JustNodeKeysProp<K, NonNullable<T[K]>>}[keyof T]>;
```
After:
```ts
type ProjectConfigJSONObjectReducer<Object> = {
[PropertyKey in keyof Object]: ProjectConfigJSONPropertyReducer<
Object[PropertyKey]
>
};
type JustNodeKeys<T> = ExcludeCoreNodeKeys<
{[K in keyof T]: JustNodeKeysProp<K, NonNullable<T[K]>>}[keyof T]
>;
```

Fix TSMappedType formatting

---

packages/@romejs/diagnostics/descriptions.ts
packages/@romejs/js-formatter/builders/comments.ts
packages/@romejs/js-formatter/builders/expressions/ConditionalExpression.ts
packages/@romejs/js-formatter/builders/typescript/TSConditionalType.ts
packages/@romejs/js-parser/parser/lval.ts

Nested conditional expressions were indented twice.
This change fixes 2 use cases:
- Over indentation of nested conditional expressions
- Break propagation for nested conditional expressions
**Before:**
```ts
type ProjectConfigJSONPropertyReducer<Type> = Type extends AbsoluteFilePath
? string
: Type extends Array<AbsoluteFilePath>
? Array<string>
: Type extends AbsoluteFilePathSet
? Array<string>
: Type extends Map<string, any> ? Dict<MapValue<Type>> : Type;
```
**After:**
```ts
type ProjectConfigJSONPropertyReducer<Type> = Type extends AbsoluteFilePath
? string
: Type extends Array<AbsoluteFilePath>
? Array<string>
: Type extends AbsoluteFilePathSet
? Array<string>
: Type extends Map<string, any>
? Dict<MapValue<Type>>
: Type;
```

Fix nested conditional expression formatting

---

packages/@romejs/cli-flags/Parser.ts
packages/@romejs/cli-reporter/Reporter.ts
packages/@romejs/cli/cli.ts
packages/@romejs/consume/Consumer.ts
packages/@romejs/consume/types.ts
packages/@romejs/project/load.ts

This PR cleans up the cli-flags parser and adds a new `--generate-autocomplete` flag. The `generateAutocomplete` is currently empty and includes some instructions on what values to use for generation.
cc @danteissaias

Clean up built-in cli-flags flags, and add empty method for shell autocomplete generation

---

packages/@romejs/cli-flags/Parser.ts
packages/@romejs/cli/cli.ts
packages/@romejs/consume/Consumer.ts
packages/@romejs/consume/types.ts
packages/@romejs/core/client/Client.ts
packages/@romejs/ob1/index.ts

This PR cleans up a bunch of the `Consumer` methods and adds `inputName`.

Clean up Consumer methods

---

packages/@romejs/js-compiler/lint/rules/sortImportExportSpecifiers.ts

This rule was removing the node locations to bypass a formatting issue. This is no longer needed by the new formatter.
Even worst, it was _eating_ leading new lines:
```js
/* BLOCK */
import {B, A} from 'a';
```
was transformed into:
```js
/* BLOCK */ import {B, A} from 'a';
```
This is now fixed.
cc @diokey

Fix sortImportExportSpecifiers rule

---

packages/@romejs/js-compiler/lint/rules/noMultipleSpacesInRegularExpressionLiterals.test.md
packages/@romejs/js-compiler/lint/rules/noShadowRestrictedNames.test.md
packages/@romejs/string-markup/Grid.ts

See snapshot for trailing space removal.

Grid: Don't output trailing space when next word will overflow

---

packages/@romejs/cli-diagnostics/DiagnosticsPrinter.ts
packages/@romejs/core/master/linter/Linter.ts
packages/@romejs/core/master/testing/TestRunner.ts
packages/@romejs/core/test-worker/SnapshotManager.ts
packages/@romejs/core/test-worker/TestWorkerRunner.ts

- Fix snapshot update count, and gross console formatting
- If a file has test failures then don't mark all snapshots as used
- Don't output "No known problems!" alongside "All tests passed"

Test footer error cleanup and misc test improvements

---

packages/@romejs/cli-reporter/Reporter.ts
packages/@romejs/diagnostics/descriptions.ts
packages/@romejs/string-markup/Grid.ts
packages/@romejs/string-markup/escape.ts
packages/@romejs/string-markup/parse.ts
packages/@romejs/string-markup/types.ts

`reporter.list` now just emits `ul`, `ol` and `li` tags. I just want to note again, that the markup we use is not HTML. It looks like HTML for familiarity but we have attribute whitelists, and try to have semantic markup for colored formatting etc.
I also made it enforced in the parser that elements like `li` can only exist inside of `ul`. I extended this to the table elements too.
The new grid rendering allows this to be implemented very easily, with soft line wrapping around bullets. eg.

Add ul, ol, li markup tags, restrict tags to specific positions

---

packages/@romejs/core/master/MasterRequest.ts
packages/@romejs/core/master/commands/test.ts
packages/@romejs/core/master/fs/Resolver.ts

I found myself running commands like:
```
$ ./scripts/dev-rome test packages/@romejs/cli-flags/Parser.ts
```
Note the lack of `.test.ts`. With this PR, we will alternatively try arguments without `.test.ts` with the added extension. This would also allow something like "Run tests for this file" in an IDE where an editor can just send us the source file path and we deal with the resolution.

Allow omitting .test from `rome test` args

---

packages/@romejs/core/master/linter/Linter.ts

Previously when running `rome lint --review` we would apply recommended fixes and formatting. The main motivation behind this was that there was no way for us to apply fixes to a file that had no lint errors but only pending formatting changes. That is no longer relevant because:
1. There's the `--format` flag to only apply formatting
2. The "pending fixes" diagnostic now has an action that will be displayed
cc @hzoo

Don't apply formatting or fixes when running `lint --review`

---

packages/@romejs/cli-reporter/select.ts
packages/@romejs/cli-reporter/types.ts
packages/@romejs/core/client/review.ts
packages/@romejs/core/master/commands/lint.ts
packages/@romejs/core/master/linter/Linter.ts
packages/@romejs/diagnostics/descriptions.ts
packages/@romejs/diagnostics/types.ts
packages/@romejs/js-compiler/lib/CompilerContext.ts
packages/@romejs/js-compiler/lint/decisions.ts
packages/@romejs/js-compiler/lint/suppressions.ts
packages/@romejs/js-compiler/types.ts

This PR allows you to run:
```
$ rome lint --decisions global:suppress:lint/camelCase
```
This is different to the way other lint decisions are specified as it's not bound to a file.
This will allow us to add a diagnostic action that says "Apply this fix to all files" or "Apply this fix to all occurrences in this file". The wording will be tricky and I'm not sure how many options we'll want to have.
Note that it's unlikely that a user will actually be running this command. It will be done under the hood by `--review`.
In the process I cleaned up a lot of the lint decision code that powers the selective fixes/suppressions.
The only remaining part of this PR is actually adding the actions which is easy, and then testing it.

Add global lint decisions

---

packages/@romejs/cli-diagnostics/DiagnosticsPrinter.ts
packages/@romejs/cli-reporter/Reporter.ts
packages/@romejs/cli-reporter/select.ts
packages/@romejs/cli-reporter/util.ts
packages/@romejs/core/client/review.ts
packages/@romejs/diagnostics/DiagnosticsProcessor.ts

Previously, when reviewing a diagnostic and a decision was made, if the file was outdated then the command would most likely be out of date. Lines may have changed, and we could insert suppression comments in the wrong places.
Now there's a warning that appears that waits for you acknowledge the message before asking you to try again.
Under the hood this uses the same outdated detection logic that's inside of the diagnostic printer. Between when a diagnostic has been emitted and we actually print it to the console it may have been changed, and we print a warning. Instead we just refresh that internal outdated map and check again. This way we'll be reusing the existing `dependencies` field on a diagnostic and it will work even with any future changes.

Warn on file changes while reviewing a diagnostic

---

packages/@romejs/cli-reporter/Reporter.ts

Previously if you did something like `rome lint >save.txt` then we would line wrap everything to the terminal width.

Don't specify columns when formatting to non-ansi

---

packages/@romejs/core/master/linter/Linter.ts

Previously we were showing the file count of all files seeded to the dependency graph, which weren't necessarily all linted.

Fix lint total count

---

packages/@romejs/core/master/commands/test.ts
packages/@romejs/js-formatter/Builder.ts
packages/@romejs/js-formatter/builders/expressions/ArrayExpression.ts
packages/@romejs/js-formatter/builders/objects/ObjectExpression.ts
packages/@romejs/js-formatter/builders/utils.ts
packages/@romejs/project/types.ts
packages/@romejs/string-diff/index.ts
packages/@romejs/typescript-helpers/index.ts

This PR inspects empty lines between nodes to keep them when it makes sense.
This change applies to:
- `ArrayExpression`
- `ObjectExpression`
- `TSInterfaceBody`
- `TSTypeLiteral`
- `TSEnumDeclaration`

Keep empty lines when formatting nodes

---

packages/@romejs/core/test-worker/SnapshotManager.ts
packages/@romejs/core/test-worker/TestAPI.ts
packages/@romejs/core/test-worker/TestWorkerRunner.ts
packages/@romejs/core/test-worker/utils.ts
packages/@romejs/core/worker/WorkerAPI.ts
packages/@romejs/diagnostics/DiagnosticsProcessor.ts
packages/@romejs/diagnostics/types.ts
packages/@romejs/js-ast-utils/createMemberProperty.ts
packages/@romejs/js-ast-utils/createPropertyKey.ts
packages/@romejs/js-ast-utils/doesNodeMatchPattern.test.ts
packages/@romejs/js-ast-utils/index.ts
packages/@romejs/js-ast-utils/valueToNode.ts
packages/@romejs/js-ast/literals/NumericLiteral.ts
packages/@romejs/js-ast/utils.ts

If the `received` value is a boolean, number, null, or undefined, then we just reconstruct it instead of the formatted string.

Avoid strings if possible for inline snapshots

---

packages/@romejs/cli-diagnostics/DiagnosticsPrinter.ts
packages/@romejs/cli-diagnostics/buildMessageCodeFrame.ts
packages/@romejs/cli-diagnostics/buildPatchCodeFrame.ts
packages/@romejs/cli-diagnostics/constants.ts
packages/@romejs/cli-diagnostics/printAdvice.ts
packages/@romejs/cli-diagnostics/utils.ts
packages/@romejs/core/test-worker/TestAPI.ts
packages/@romejs/diagnostics/derive.ts
packages/@romejs/v8/sourceMapManager.ts

This adds better tab support to `buildMessageCodeFrame`. Hard tabs are displayed as two soft spaced tabs. Maybe we could possibly allow configuration but I would rather avoid it. This is necessary so we can switch to hard tabs in the formatter.
#425

Better tab support in buildMessageCodeFrame

---

.github/CONTRIBUTING.md
website/docs/community/contributing.md

This pull request updates contributor installation instructions by clarifying that the `dist` directory should be removed before running any development commands. This mitigates potential confusion for users who follow the user-specific [installation instructions](https://romejs.dev/docs/introduction/installation/#cloning-and-building) followed by the contributor-specific [getting started](https://github.com/romejs/rome/blob/master/.github/CONTRIBUTING.md#getting-started) instructions, which results in two `package.json` files and a duplicate package name warning for `rome`.
Resolves #404

fix: clarify contributor installation instructions

---

packages/@romejs/js-ast-utils/doesNodeMatchPattern.ts

This allows `doesNodeMatchPattern` to be used with single parts and have comparable performance to checking `name` yourself except that you can pass around patterns.

Fast path for single part matching in doesNodeMatchPattern

---

.editorconfig

This is a holdout from when Rome was written with Flow and used the `.js` extension.
Thanks @RReverser for noticing! https://twitter.com/RReverser/status/1261841111498326021

Update .editorconfig with correct extensions

---

scripts/ast/add.cjs
scripts/lint/add.cjs

This pull request updates generation scripts related to linting and the AST by removing the Facebook copyright header.
Resolves #463

chore: remove FB copyright from newly-generated files

---

packages/@romejs/cli/cli.ts
packages/@romejs/core/common/bridges/MasterBridge.ts
packages/@romejs/core/master/Master.ts
packages/@romejs/core/master/MasterRequest.ts

Right now when there are lint or test failures we do not emit the correct exit code. This causes GitHub actions to pass when they should not.
What's happening here is that the CLI is passing `noData` to the server. This is to save on bridge transport in daemon mode because the CLI doesn't care about the request return values. This also causes `diagnostics` to be set to an empty array.
So to correct this there's a separate `hasDiagnostics` property that will always be correct.

Add hasDiagnostics and fix CLI exit code

---

scripts/_utils.cjs
scripts/lint/add.cjs

This pull request updates the generation script for adding new lint rules by camel casing generated filenames in the same way that internal linting does.
Resolves #456

fix: camel case generated lint rule names

---

packages/@romejs/diagnostics/descriptions.ts

small update from a comment in https://github.com/romejs/rome/pull/472#discussion_r426724266. @bitpshr 
Since you pointed that out, I figure I would make this update to this rule message as well.

wrap emphasis in the message of noDidUpdateSetState

---

packages/@romejs/cli-diagnostics/printAdvice.ts
packages/@romejs/diagnostics/descriptions.ts
packages/@romejs/js-compiler/lint/rules/react/jsxA11yLang.test.md
packages/@romejs/js-compiler/lint/rules/react/jsxA11yLang.test.ts
packages/@romejs/js-compiler/lint/rules/react/jsxA11yLang.ts

This PR adds suggestions to the `jsxA11yLang` lint rule:
```
✖ The lang attribute must have a valid value.
<html lang="aa-zz"></html>
^^^^^^^^^^^^^^^^^^^^^^^^^^
ℹ Did you mean aa-AF?
- aa-zz
+ aa-AF
ℹ Or one of these?
- aa-AL
- aa-DZ
- aa-AS
- aa-AD
- aa-AO
- aa-AI
- aa-AQ
- aa-AG
- aa-AR
- aa-AM
and 222 others...
```
The suggestion advice builder can be improved to limit these suggestion since 222 is... excessive.
cc @ematipico

Add jsxA11yLang suggestions

---

.git-blame-ignore-revs

This enables individuals to blame back files ignoring large scale
project changes that impact blames.
Example:
git blame packages/@romejs/core/master/bundler/Bundler.ts  --ignore-revs-file=.git-blame-ignore-revs  | grep bundlebu
BUG=#425

Add an ignore-revs file

---

website/src/pages/index.js

Updates to the website in preparation for release, ref #496
This PR checks off the following items from [this list](https://github.com/romejs/rome/issues/496#issue-622253571):

chore: update website for release

---

packages/@romejs/compiler/lint/rules/ariaHelpers.ts
packages/@romejs/compiler/lint/rules/jsx-a11y/ariaUnsupportedElements.ts
website/src/pages/styles.module.css

This pull request includes minor cleanup:
- Rename `aria-helpers.ts` to `ariaHelpers.ts`
- Remove unnecessary object key quotes from the `ariaPropsMap`
- Fix `allowUndefined` casing
- Remove newly-unused website class after #498

chore: clean up ariaHelpers and website CSS

---

packages/@romejs/cli-diagnostics/DiagnosticsPrinter.ts
packages/@romejs/core/master/Master.ts
packages/@romejs/core/master/MasterRequest.ts
packages/@romejs/core/master/bundler/BundleRequest.ts
packages/@romejs/core/master/bundler/Bundler.ts
packages/@romejs/core/master/fs/MemoryFileSystem.ts

This PR adds the following:
- Adds locks to all worker file requests. This eliminates race conditions caused by simultaneous requests. This should utilize our caches more effectively.
- Reattempts a worker request if the file changed while it was running.

Add locks when dispatching a worker request

---

packages/@romejs/compiler/lint/rules/jsx-a11y/noOnChange.test.md
packages/@romejs/compiler/lint/rules/jsx-a11y/noOnChange.ts
packages/@romejs/compiler/lint/rules/react/noStringRefs.test.md
packages/@romejs/compiler/lint/rules/react/noStringRefs.ts

Follow-up to: https://github.com/romejs/rome/pull/501#discussion_r428777239
Sorry for missing this! Updates my previous two contributions so that the added diagnostic messages point to the JSX attributes that cause lint errors. Before, the diagnostic was highlighting the entire JSX Element.

Makes the diagnostic message more specific to the JSX attribute that flags an error.

---

packages/@romejs/js-parser/parser/typescript.ts

Regression from #440 where we were previously going through some shared code paths that were asserting Flow/TS was enabled.

Add typescript syntax enabled assertions - fixes #514

---

scripts/lint/add.cjs

small add of the category to the test description. #520 adds `react` or `jsx-a11y` so this saves having to remember to add that text after you run the add script

add category to test description in script

---

packages/@romejs/cli-reporter/Reporter.ts
packages/@romejs/string-markup/format.ts
packages/@romejs/string-markup/index.ts
packages/@romejs/string-markup/types.ts

Reporter was importing directly from string-markup/types and string-markup/format so I cleaned it up a bit.

Rearrange string-markup exports

---

packages/@romejs/compiler/lint/rules/js/noCondAssign.test.md
packages/@romejs/compiler/lint/rules/js/noCondAssign.test.ts
packages/@romejs/compiler/lint/rules/js/noCondAssign.ts

I think the `test` node in `ternary` should be checked :)
* invalid
```
(foo = bar) ? foo() : baz();
``` 
CI failed cause #548.

feat add conditional expression in noCondAssign

---

packages/@romejs/compiler/transforms/compile/transpile/enums.ts
packages/@romejs/compiler/transforms/index.ts
packages/@romejs/diagnostics/categories.ts
packages/@romejs/diagnostics/descriptions/compiler.ts
packages/@romejs/js-ast-utils/index.ts
packages/@romejs/js-ast-utils/tryStaticEvaluation.ts

This pull request adds a new module to transpile TypeScript enums. Functionality matches the TypeScript compiler and the related Babel transform.
Resolves #534
Supersedes #536
**Examples:**
Input:
```ts
enum Test1 {a, b}
enum Test2 {a = 3, b = 10}
enum Test3 {a = "foo", b = "bar"}
enum Test4 {a = 7, b = "bar"}
enum Test5 {a = 5 + 5, b}
enum Test6 {a = 5 + 5, b = a}
````
Output:
```ts
function(Test1) {
Test1[Test1["a"] = 0] = "a"
Test1[Test1["b"] = 1] = "b"
}(Test1 || (Test1 = {}))
function(Test2) {
Test2[Test2["a"] = 3] = "a"
Test2[Test2["b"] = 10] = "b"
}(Test2 || (Test2 = {}))
function(Test3) {
Test3["a"] = "foo"
Test3["b"] = "bar"
}(Test3 || (Test3 = {}))
function(Test4) {
Test4[Test4["a"] = 7] = "a"
Test4["b"] = "bar"
}(Test4 || (Test4 = {}))
function(Test5) {
Test5[Test5["a"] = 10] = …
```

fix: transpile typescript enums

---

packages/@romejs/events/Event.ts

If an existing subscription becomes the `rootSubscription`, it needs to be removed from the `subscriptions` Set to avoid being invoked twice per message.

Fix Event unsubscribe

---

README.md

The readme still says to initialize `rome.json` with `{}` but it seems like you should probably be using `rome init` for that.

docs: use `rome init` instead of empty config

---

packages/@romejs/compiler/transforms/compile/transpile/enums.ts
packages/@romejs/js-ast-utils/index.ts
packages/@romejs/js-ast-utils/tryStaticEvaluation.ts
packages/@romejs/js-ast-utils/tryStaticEvaluationPath.ts

This PR makes the following changes to `tryStaticEvaluatiuon`:
- Add `const` resolution to `tryStaticEvaluation` allow variable references to be resolved
- Add full support for `JSTemplateLiteral`
- Allows `undefined` to be returned
- Adds caching
This makes it a lot more versatile and should allow for better linting capabilities.
`tryStaticEvaluationPath` is available to just pass a `Path` instance into it for easier usage.
If we have a prefer const lint rule and autofix then this it would be a lot more powerful. There's not really a way for us to compute if a binding is only assigned once as a pseudo-constant without recursing deep which would kill our scope performance.

Refactor tryStaticEvaluation

---

packages/@romejs/js-ast-utils/index.ts
packages/@romejs/js-ast-utils/resolveIndirection.ts
packages/@romejs/js-ast-utils/tryStaticEvaluation.ts

This util method is used to attempt to resolve the value of an expression. This includes:
- Following `const` values
- Collapsing type expression containers

Add resolveIndirection to js-ast-utils

---

packages/@romejs/compiler/lint/rules/js/noShadowRestrictedNames.test.md
packages/@romejs/compiler/lint/rules/js/noShadowRestrictedNames.test.ts
packages/@romejs/compiler/lint/rules/js/noShadowRestrictedNames.ts

If it's intentional that `path.scope.node !== path.node` for `JSFunctionDeclaration` nodes, then this fixes a bug with the `noShadowRestrictedNames` lint rule.
If that's not intentional, then this is just a symptom of a different problem.
Closes #547

Fix noShadowRestrictedNames lint rule

---

packages/@romejs/compiler/lint/rules/testHelpers.ts

Removed the string-handling behavior from `testLint`. And since `testLintExpect` no longer needs an optional `expect` parameter, I figured it should just be an `expectValid` boolean.

Refactor testLint and remove testLintMultiple

---

packages/@romejs/core/test-worker/TestAPI.ts

Fixed a couple typos in the messages you see for failing tests. One of them was throwing me off.
I also improved the `()` consistency between messages (by making the choices that required the fewest changes). Let me know if a different choice would be clearer.

Fix typos in TestAPI messages

---

packages/@romejs/events/Bridge.ts
packages/@romejs/events/Event.ts

This fixes the Event#clear method so that it also removes the rootSubscription.
That revealed a problem with the Bridge constructor, which was calling `this.clear()` after creating and subscribing to the heartbeatEvent. Since Event#clear was ignoring the rootSubscription, clearing the heartbeatEvent had no effect prior to this change.
I don't think the call to `this.clear()` is currently doing anything in the constructor, so I just removed it. If it's intended as a hook or it's doing something I don't understand, please let me know and I'll put it back before the subscription.

Fix Event clear and Bridge constructor

---

packages/@romejs/core/master/fs/MemoryFileSystem.ts

This changes MemoryFileSystem handleDeletion to call `deletedFileEvent` before deleting the `files` entry, so that subscribers don't throw an error when they try to get the file stats in response to the event.
I wasn't sure about the correct position for the event call relative to the other effects of the `handleDeletion` function. Does this look right?
This is related to #389 but doesn't close the issue because rome will still crash for a different reason.

Move deletedFileEvent call in handleDeletion

---

packages/@romejs/compiler/lint/rules/js/caseSingleStatement.test.md
packages/@romejs/compiler/lint/rules/js/confusingLanguage.test.md
packages/@romejs/compiler/lint/rules/js/doubleEquals.test.md
packages/@romejs/compiler/lint/rules/js/duplicateImportSource.test.md
packages/@romejs/compiler/lint/rules/js/negationElse.test.md
packages/@romejs/compiler/lint/rules/js/noDebugger.test.md
packages/@romejs/compiler/lint/rules/js/noDelete.test.md
packages/@romejs/compiler/lint/rules/js/noMultipleSpacesInRegularExpressionLiterals.test.md
packages/@romejs/compiler/lint/rules/js/noShorthandArrayType.test.md
packages/@romejs/compiler/lint/rules/js/preferBlockStatements.test.md
packages/@romejs/compiler/lint/rules/js/preferFunctionDeclarations.test.md
packages/@romejs/compiler/lint/rules/js/preferTemplate.test.md
packages/@romejs/compiler/lint/rules/js/preferWhile.test.md
packages/@romejs/compiler/lint/rules/js/singleVarDeclarator.test.md
packages/@romejs/compiler/lint/rules/js/sortImportExportSpecifiers.test.md
packages/@romejs/compiler/lint/rules/js/sparseArray.test.md
packages/@romejs/compiler/lint/rules/js/unsafeNegation.test.md
packages/@romejs/compiler/lint/rules/jsx-a11y/ariaProps.test.md
packages/@romejs/compiler/lint/rules/jsx-a11y/noAccessKey.test.md
packages/@romejs/compiler/lint/rules/jsx-a11y/noAutofocus.test.md
packages/@romejs/compiler/lint/rules/jsx-a11y/noRedundantRoles.test.md
packages/@romejs/compiler/lint/rules/jsx-a11y/noTargetBlank.test.md
packages/@romejs/compiler/lint/rules/jsx-a11y/scope.test.md
packages/@romejs/compiler/lint/rules/jsx-a11y/tabindexNoPositive.test.md
packages/@romejs/compiler/lint/rules/react/jsxFragments.test.md
packages/@romejs/compiler/lint/rules/react/jsxNoCommentText.test.md
packages/@romejs/compiler/lint/rules/react/noUselessFragment.test.md
packages/@romejs/compiler/lint/rules/react/voidDomElementsNoChildren.test.md
packages/@romejs/core/master/commands/lint.test.md
packages/@romejs/string-markup/Grid.ts

`<hr>` trailing separator has incorrect width if `inverse` tag is present. This happens because padding is added at the formatting phase so the cursor position is not adjusted accordingly.
Before:
After:

fix: adjust cursor position by <inverse> tag padding

---

packages/@romejs/core/server/WorkerManager.ts
packages/@romejs/core/server/dependencies/DependencyGraph.ts
packages/@romejs/core/server/fs/FileAllocator.ts
packages/@romejs/core/server/linter/Linter.ts

This addresses some issues that were still causing crashes when files were deleted during a lint.
It adds handling for `FileNotFound` when `LintRunner` pushes paths onto the worker queue. It also adds a couple `try-finally` blocks to make sure that locks get released after a `FileNotFound` error is thrown.
Otherwise, deleted files would cause Rome to freeze when the `onChanges` handler is called for those deleted `evictedPaths`.
I removed the `console.error` from `WorkerManager#getNextWorker` so that I could use `getFileStatsAssert` to throw the `FileNotFound` error, but I can put it back if it’s still useful.

Fix file deletion handling during lint

---

packages/@romejs/core/server/ServerRequest.ts
packages/@romejs/core/server/fs/MemoryFileSystem.ts
scripts/vendor/rome.cjs

In the LSP when there is a document change we notify workers of the new "file contents" that is used instead of getting it from disk. This works great, except that we'd hit the cache before we even get there and since the mtime matched what was in the cache then we would never update until there was an actual file save.
Well this fixes that!

[MemoryFileSystem] Hijack mtime for set buffers 

---

packages/@romejs/events/Bridge.test.ts
packages/@romejs/events/BridgeEvent.ts

These methods are inherited from the Event class, but they shouldn't be used on a BridgeEvent.

Disable callSync and callOptional for BridgeEvent

---

packages/@romejs/compiler/lint/rules/react/jsxPascalCase.test.md
packages/@romejs/string-utils/toCamelCase.test.ts
packages/@romejs/string-utils/toCamelCase.ts

this is from conversations in : https://github.com/romejs/rome/pull/551#issuecomment-636415303
I have questions around some of the test cases:
```
{input: "RoMe TeSt", expected: "RoMeTeSt"},
{input: "ROME TEST", expected: "ROMETEST"},
```
Should these actually be?
```
{input: "RoMe TeSt", expected: "RomeTest"},  // this one I could see as staying RoMeTeSt
{input: "ROME TEST", expected: "RomeTest"},
```
What updated functionality would be good for toCamelCase? We could change the the second parameter to be an object of different options. @sebmck if you have specifics in mind, I can incorporate into this pr and apply updates.

add test cases for toCamelCase for forceCapitalization param

---

website/src/_includes/docs/Getting started.md
website/src/styles/_content.scss
website/src/styles/_variables.scss

This pull request updates the new documentation site with a quick note about RJSON vs JSON and adds initial `blockquote` styling.
Replaces #602

fix: update docs with note about RJSON

---

website/static/js/index.js

If the user has switched the docs to dark mode and refreshes the page, the text still shows "Dark Mode" when the page is refreshed:

Fix mode switch text when themeInStorage === 'dark'

---

packages/@romejs/core/common/utils/Locker.test.ts
packages/@romejs/core/common/utils/Locker.ts

This adds a Locker method that wraps a callback in a lock that is automatically released even if the callback throws an error.

Add Locker wrapLock method

---

packages/@romejs/compiler/transforms/compile/transpile/enums.ts
packages/@romejs/diagnostics/categories.ts
packages/@romejs/diagnostics/descriptions/compiler.ts
packages/@romejs/js-ast-utils/tryStaticEvaluation.ts

This pull request updates the TypeScript enum transform to more-closely match TypeScript compiler pragmatics. Specifically, initializers that resolve to values other than numbers that also use variable references are now considered errors.
Resolves #572
The following cases now fail:
```ts
const str = "str";
const bool = true;
enum Test1 {a = str}
enum Test2 {a = bool}
```

fix: disallow non-numeric computed enum values

---

packages/@romejs/core/server/lsp/LSPServer.ts

This prevents the LSP server from crashing due to a format request producing diagnostics. It's related to #618 but it doesn't close it because the LSP server still crashes when invalid syntax is typed. I was only able to observe the effect of these changes by temporarily disabling the `linter.watch()` in `watchProject` so that invalid syntax wouldn't cause a crash before I could format-on-save.
This also adds a `window/logMessage` helper to output the caught diagnostics. We could filter diagnostics if we don't want to display certain types, or I could remove it entirely if we don't want to log anything at all.

Catch diagnostics for requestWorkerFormat in LSPServer

---

packages/@romejs/core/test-worker/SnapshotManager.ts

This adds a `try-finally` block so that `SnapshotManager#loadSnapshot` releases its lock if it throws an error.

Use wrapLock in SnapshotManager loadSnapshot

---

packages/@romejs/node/errors.ts
packages/@romejs/v8/errors.ts

Where we would previously emit `FileNotFound`, the `code` would not be present and so it would just be thrown as a regular error.

Inherit NodeJS.ErrnoException props in better node errors

---

packages/@romejs/events/Bridge.ts

This removes the dreaded "Bridge is dead" errors that can sometimes occur. Instead we rethrow the error that resulted in the bridge being ended in the first place. This will usually be more specific with the reason for the bridge dying.

Rethrow bridge end error in assertAlive

---

package.json

Removing this field so that the VS Code extension uses `dev-rome` instead of `vendor-rome`. The extension will still look for rome in `node_modules` before looking for the dev folder.
This field can still be added locally to `package.json` to force the extension to use a different path for the rome LSPServer.

Remove romeLSPBin field from package.json

---

website/src/_includes/layouts/base.njk

The navigation bar has repeated ids called `site-navigation`. This causes issue to assistive technologies. 
This PR makes them unique

[Website] Make IDs unique

---

website/src/index.md

On the homepage "Getting Started" is a call to action so "Get Started" reads better.

"Getting Started" -> "Get Started" on the homepage

---

README.md
website/src/_includes/layouts/base.njk
website/src/_includes/layouts/sections/head.njk
website/src/_includes/layouts/sections/hero.njk
website/src/contributing/governance.md
website/src/contributing/index.md
website/src/contributing/team.md
website/src/docs/check/rules/camel-case.md
website/src/docs/check/rules/index.md
website/src/index.md

This updates the website and README to move from the term "JavaScript Toolchain" to "Frontend Toolchain". We have long term plans to support HTML and CSS. We should set appropriate expectations at launch.
I was considering "Web Toolchain" but it may carry a web server/backend connotation.
We may be ostracizing backend Node.js engineers until we have established ourselves more, but I don't think there's an appropriate term that covers everything.
"Frontend" is still regularly used to JavaScript related software engineering, including React Native and other alternate web stacks.

JavaScript Toolchain -> Frontend Toolchain

---

website/src/_includes/layouts/base.njk

The "Linting" link on the side is giving a 404 because we changed the command from `lint` to `check` bug I forgot to update the href of the navigation bar.
This PR fixes that

Fixed link to the check command

---

packages/@romejs/core/client/Client.ts
packages/@romejs/core/server/Server.ts

I can't remember why I did it but previously called `client.end()` would cause the server to be shutdown. This was fine when the server was running inside the process, but if it was ran with a connected daemon then it would shutdown the server but the process would still hang around.
This PR makes it so that `client.end()`, when connected to daemon, just kills the socket. There is now a separate `client.shutdownServer`.
NOTE: If you want to communicate with the daemon then you CANNOT run `scripts/dev-rome` or else it will encounter a race condition where during the daemon tries to start a worker but we've cleared `/tmp/rome-dev` so it will not be able to fork a worker.
```
scripts/dev-rome start
node $TMPDIR/rome-dev/index.js status
```

Fix Client#end causing issues with daemon

---

packages/@romejs/core/server/lsp/LSPServer.ts

This is a quick fix to prevent the LSP server from sometimes hanging when someone attempts to format a document while the project’s initial `Linter#watch` is running. I think I'll be able to implement a better solution once I've spent some more time working with the LSP server.
Closes #651

Prevent requestWorkerFormat during LSP project init

---

packages/@romejs/core/common/constants.ts
scripts/_utils.cjs
scripts/assert-generated
scripts/run-vscode-extension

This makes local daemon development much nicer by making `dev-rome` reuse an old build if a daemon is running. The CLI and daemon build need to match exactly or else you'll get really weird bugs.
This now allows the following commands to be executed one after the other:
```
$ scripts/dev-rome start
$ scripts/dev-rome status
$ scripts/dev-rome stop
```

Don't let vendor-rome connect to dev-rome daemon and skip trunk build if dev daemon running

---

packages/@romejs/core/server/ServerRequest.ts

This fixes `ServerRequest#watchFilesFromArgs` so that it doesn't stop working if there's ever a `refreshFileEvent` called with a path that it's ignoring.
Previously, `flush()` would return before setting `timeout = undefined` when there were no pending paths,  so the `refreshFileEvent` subscription would never be able to set a new `flush` timeout.
This is one of the reasons that the LSP server would suddenly stop publishing diagnostics.

Fix watchFilesFromArgs flush timeout

---

website/src/styles/_global.scss

currently, the padding in inline code elements causes stacked code spans to overlap:
this PR fixes the styles to fix this:

Fix overlap of stacked inline code elements

---

packages/@romejs/cli-flags/Parser.test.md
packages/@romejs/cli-flags/Parser.test.ts
packages/@romejs/cli-flags/Parser.ts

Adds a `noProcessExit` option to Parser so that the `--help` test doesn't kill the test worker.
Adds a `preInit` callback to the `testParser` utility so that commands can be added before `parser.init()`
Closes #686

Fix `rome --help` and add test case

---

website/src/_includes/layouts/sections/footer.njk

Replaced broken "Code of Conduct" link in the footer section with the current working link

Minor: Replaced broken Code of Conduct link in the footer section

---

packages/@romejs/core/server/ServerRequest.ts
packages/@romejs/core/server/lsp/LSPServer.ts

This fixes a problem with `requestWorkerUpdateBuffer` and `requestWorkerClearBuffer`. They both cause a file's (fake) `mtime` to change, but `wrapRequestDiagnostic` normally retries requests if the `mtime` for a file changes while a request is processing.
For reasons that I didn't fully explore, this usually resulted in a nondeterministic number of retries as opposed to an infinite loop, but I think this was the main problem causing the LSP server to hang in some situations.
This also removes the "quick fix" for formatting requests because it's no longer necessary.

Add noRetry option to wrapRequestDiagnostic

---

packages/@romejs/ast/html/attributes/HTMLAriaAttribute.ts
packages/@romejs/ast/html/attributes/HTMLAttribute.ts
packages/@romejs/ast/html/attributes/HTMLDataAttribute.ts
packages/@romejs/ast/html/core/HTMLCommentBlock.ts
packages/@romejs/ast/html/core/HTMLRoot.ts
packages/@romejs/ast/html/core/HTMLText.ts
packages/@romejs/ast/html/tags/HTMLDoctypeTag.ts
packages/@romejs/ast/html/tags/HTMLTag.ts
packages/@romejs/ast/html/tags/HTMLXmlTag.ts
packages/@romejs/ast/html/unions.ts
packages/@romejs/ast/index.ts
packages/@romejs/formatter/builders/html/attributes/HTMLAriaAttribute.ts
packages/@romejs/formatter/builders/html/attributes/HTMLAttribute.ts
packages/@romejs/formatter/builders/html/attributes/HTMLDataAttribute.ts
packages/@romejs/formatter/builders/html/core/HTMLCommentBlock.ts
packages/@romejs/formatter/builders/html/core/HTMLRoot.ts
packages/@romejs/formatter/builders/html/core/HTMLText.ts
packages/@romejs/formatter/builders/html/tags/HTMLDoctypeTag.ts
packages/@romejs/formatter/builders/html/tags/HTMLTag.ts
packages/@romejs/formatter/builders/html/tags/HTMLXmlTag.ts
packages/@romejs/formatter/builders/index.ts

This PR creates the initial HTML AST nodes.
For now I just created few nodes that should describe the HTML tree but probably I missed something, so I'd like to have some feedback before actually merging it.
I tried to divide the nodes in `core`, `tags` and `attributes`
- core => root and comments
- tags => normal tags, xml tag (old, should we support it? e.g. `<?xml version="1.0" ?>`) and doctype tag (e.g. `<!DOCTYPE html>`)
- attributes => aria attributes, data attributes and attributes (class, style, etc.)
Is there something that I am missing or some information we'd want to have?
cc @sebmck

HTML ast nodes

---

packages/@romejs/core/common/bridges/WorkerBridge.ts
packages/@romejs/core/server/WorkerManager.ts
packages/@romejs/core/worker/Worker.ts

This transfers buffers to the newly spawned worker when it replaces the internal server worker.

Transfer buffers in WorkerManager replaceOwnWorker

---

packages/@romejs/core/server/Server.ts

I think this could be the cause of the macOS CI timeout we see pretty often. @yassere flagged this before in a previous review but I never bothered to add this. We'll see what happens.

Add timeout to Server#writeFiles

---

packages/@romejs/css-parser/index.ts
packages/@romejs/css-parser/parse.test.ts
packages/@romejs/css-parser/parse.ts
packages/@romejs/css-parser/types.ts
packages/@romejs/css-parser/utils.ts
packages/@romejs/diagnostics/categories.ts
packages/@romejs/diagnostics/descriptions/cssParser.ts
packages/@romejs/diagnostics/descriptions/index.ts

This pull request adds a new `css-parser` package that exposes a tolerant CSS tokenizer for the complete [CSS3 specification](https://www.w3.org/TR/css-syntax-3/#tokenization).
**TODO:**
1. Implement parser.
1. Add exhaustive tests.
1. Further verify spec compliancy.

feat: CSS tokenizer

---

packages/@romejs/codec-js-regexp/index.ts
packages/@romejs/codec-json/parse.ts
packages/@romejs/codec-semver/parse.ts
packages/@romejs/codec-spdx-license/parse.ts
packages/@romejs/core/server/fs/MemoryFileSystem.ts
packages/@romejs/core/test-worker/SnapshotManager.ts
packages/@romejs/core/test-worker/SnapshotParser.ts
packages/@romejs/css-parser/parse.ts
packages/@romejs/css-parser/utils.ts
packages/@romejs/html-parser/index.ts
packages/@romejs/js-parser/test-fixtures/core/uncategorised/441/input.test.md
packages/@romejs/js-parser/test-fixtures/esprima/invalid-syntax/migrated_0157/input.test.md
packages/@romejs/js-parser/tokenizer/index.ts
packages/@romejs/parser-core/index.ts
packages/@romejs/path-match/parse.ts
packages/@romejs/string-markup/parse.ts

`tokenize` no longer has an `input` parameter which was just passing in `this.input` anyway. There's no `getInputChar`, `getInputCharOnly` and `getInputRange` to help with getting characters from an index, including adding an offset etc.

Remove `input` parameter from ParserCore#tokenize and add getInputChar method

---

README.md

Change URL to https://romefrontend.dev/docs/getting-started - fix #722

Fix URL of broken 'Getting Started' link in README.md file

---

packages/@romefrontend/core/integrationTestHelpers.ts
packages/@romefrontend/core/server/Server.ts

This function is incorrectly named. It turns a `PartialServerQueryRequest` into a full `ServerQueryRequest`.

Rename partialServerQueryResponseToFull function

---

packages/@romefrontend/compiler/suppressions.test.md
packages/@romefrontend/compiler/suppressions.test.ts
packages/@romefrontend/compiler/suppressions.ts
packages/@romefrontend/diagnostics/categories.ts
packages/@romefrontend/diagnostics/descriptions/suppressions.ts

this is related to #729 
- updated the tests to do some simple checks against the diagnostics and suppressions in addition to generating snapshots (existing tests). this way we don't just update the snapshots and not notice something changing (though a diff might make it glaring that something changed)
- added a quick check for the suppressions that overlap (pretty much just if a line is great then startLine and under endLine of the previous suppression.
unrelated:
- the snapshots aren't in the order that they are in the test file. I imagine it has something to do with the way it is stored in a map before turning back into a list of testNames, but I didn't investigate farther.

add diagnostics for overlap suppressions and update tests

---

packages/@romefrontend/core/common/bridges/WorkerBridge.ts
packages/@romefrontend/core/server/ServerRequest.ts
packages/@romefrontend/core/server/lsp/LSPServer.ts
packages/@romefrontend/core/server/lsp/utils.ts
packages/@romefrontend/core/worker/Worker.ts
packages/@romefrontend/core/worker/utils/applyWorkerBufferPatch.test.ts
packages/@romefrontend/core/worker/utils/applyWorkerBufferPatch.ts

This PR adds incremental `textDocument` syncing to `LSPServer` by adding buffer patching capabilities to workers.
I added a `WorkerBufferPatch` type that resembles the LSP `TextDocumentContentChangeEvent` because I didn't want to use LSP-specific types in `Worker`.
Currently, `patchBuffer` returns the entire buffer over the `WorkerBridge` so that it can be passed to `memoryFs.addBuffer()` and also returned by `requestWorkerPatchBuffer`
If we don't think we'll need the return value, it might make sense to change `MemoryFileSystem#addBuffer` to accept a `size` instead of `content` and then we can just return the new size from `Worker#patchBuffer`
The `applyWorkerBufferPatch` utility handles unicode characters according to the LSP spec (I think) but the LSP server still has a formatting …

Add incremental sync to LSPServer with buffer patching

---

GOVERNANCE.md

This pull request updates the  `GOVERNANCE.md` document to specify a new protocol for voting on potential contributors. Votes would now be cast by privately messaging a project steward to allow for anonymity when discussing assenting or dissenting opinions.
cc @romefrontend/core-contributors 
Resolves #770

chore: update new contributor voting protocol

---

packages/@romefrontend/cli-reporter/Reporter.ts
packages/@romefrontend/cli/cli.ts
packages/@romefrontend/core/client/Client.ts
packages/@romefrontend/core/common/utils/Logger.ts
packages/@romefrontend/core/integrationTestHelpers.ts
packages/@romefrontend/core/server/Server.ts
packages/@romefrontend/core/server/ServerReporter.ts
packages/@romefrontend/core/server/ServerRequest.ts
packages/@romefrontend/core/server/WorkerManager.ts
packages/@romefrontend/core/server/fs/FileAllocator.ts
packages/@romefrontend/core/server/fs/MemoryFileSystem.ts
packages/@romefrontend/core/server/lsp/protocol.test.md
packages/@romefrontend/core/worker/Worker.ts
packages/@romefrontend/string-markup/format.ts
packages/@romefrontend/string-markup/grid/Grid.ts

This PR does the following:
- Server logs are now buffered until the first connected client. After that we stop buffering logs. When a client connects and enables logs then we send the init buffer. This is cheap for us to buffer because we do so little during init before a client connects. We can put some critical debug information in there.
- Server/workers now send logs in raw markup. It's then up to the client to decide if they want to format or strip it. This allows `--logs` when ran in the terminal to have colors!

Buffer server logs before first connected client

---

packages/@romefrontend/cli-diagnostics/buildCodeFrame.ts
packages/@romefrontend/cli-diagnostics/buildPatchCodeFrame.ts
packages/@romefrontend/compiler/lint/rules/js/noDuplicateGroupNamesInRegularExpressions.test.md
packages/@romefrontend/compiler/lint/rules/react/noDangerWithChildren.test.md
packages/@romefrontend/core/client/Client.ts
packages/@romefrontend/core/server/fs/MemoryFileSystem.ts
packages/@romefrontend/core/server/lsp/protocol.test.md
packages/@romefrontend/diagnostics/errors.ts
packages/@romefrontend/string-markup/escape.ts
packages/@romefrontend/string-markup/format.test.md
packages/@romefrontend/string-markup/format.ts
packages/@romefrontend/string-markup/grid/Grid.ts
packages/@romefrontend/string-markup/tags.ts
packages/@romefrontend/string-markup/types.ts

This is now how the code frames look.
**Path**
**Pointer/Message**

Split up view tags, add custom indentation gutter, and custom additional soft line indentation

---

packages/@romefrontend/cli-diagnostics/DiagnosticsPrinter.ts
packages/@romefrontend/cli-diagnostics/buildCodeFrame.ts
packages/@romefrontend/cli-diagnostics/buildPatchCodeFrame.test.ts
packages/@romefrontend/cli-diagnostics/utils.ts
packages/@romefrontend/cli-reporter/Reporter.ts
packages/@romefrontend/cli/bin/rome.ts
packages/@romefrontend/cli/cli.ts
packages/@romefrontend/core/client/Client.ts
packages/@romefrontend/core/client/commands/lsp.ts
packages/@romefrontend/core/common/bridges/ServerBridge.ts
packages/@romefrontend/core/server/Server.ts
packages/@romefrontend/core/server/commands/noop.ts
packages/@romefrontend/core/server/lsp/LSPServer.ts
packages/@romefrontend/core/server/lsp/protocol.test.md
packages/@romefrontend/core/server/lsp/utils.ts
packages/@romefrontend/string-markup/format.test.ts
packages/@romefrontend/string-markup/format.ts
packages/@romefrontend/string-markup/grid/Grid.ts
packages/@romefrontend/string-markup/index.ts
packages/@romefrontend/string-markup/tags.ts
packages/@romefrontend/string-markup/types.ts

This PR does the following:
- Fixes the `rome rage` and `rome logs` commands. They were previously not functional.
- Fixes `rome lsp --logs`. Two issues. The client reporter was being teardown and `LSPTransport` was trying to write raw JSON which can contain markup looking strings like `Array<string>`.
- Moved indentation handling from `Reporter` into `Grid`.
- Changed `string-markup` range application that hopefully resolves the ANSI code overflow issues
- Renamed various methods

rage and logs command polish

---

website/src/styles/_global.scss

Some screenshot to give a look and feel of the result. Feedback welcome!

Update breadcrumbs styles to be consistent with website coloring

---

packages/@romefrontend/cli-environment/index.ts
packages/@romefrontend/cli-environment/package.json
packages/@romefrontend/cli-layout/ansi.ts
packages/@romefrontend/cli-layout/grid/Grid.ts
packages/@romefrontend/cli-layout/grid/formatANSI.ts
packages/@romefrontend/cli-layout/types.ts
packages/@romefrontend/cli-reporter/Progress.ts
packages/@romefrontend/cli-reporter/Reporter.ts
packages/@romefrontend/cli-reporter/types.ts
packages/@romefrontend/cli/cli.ts
packages/@romefrontend/core/client/Client.ts
packages/@romefrontend/core/common/bridges/ServerBridge.ts
packages/@romefrontend/core/common/constants.ts
packages/@romefrontend/core/common/types/client.ts
packages/@romefrontend/core/common/userConfig.ts
packages/@romefrontend/core/common/utils/Logger.ts
packages/@romefrontend/core/server/Cache.ts
packages/@romefrontend/core/server/commands/check.test.md
packages/@romefrontend/core/server/web/index.ts
packages/@romefrontend/path/index.ts
packages/@romefrontend/test-helpers/integration.ts

This PR does the following:
- Renames the `color` property of `TerminalFeatures` to `colorDepth`.
- Uses `tty.WriteStream` `getColorDepth` to infer supported terminal colors.
- Adds `background` property to `TerminalFeatures` that is sniffed from `env.COLORFGBG`. It can be set to `"dark"`, `"light"`, or `"unknown"`.
- Disables default syntax highlighting theme if we aren't 100% sure the user has a dark background. If a user has set their own syntax theme then it will be enabled again.
- Adds color conversion for `rgb` values in a 4/16 bit terminal.
- Inserts reset color codes within grid formatting ranges.
- Adds terminal features to `rome rage` - closes #811.
These changes result in a much better cross-terminal experience by gracefully handling coloring. The heuristics used are reliable.

More robust ANSI formatting

---

scripts/generated-files/lint-rules.cjs
website/src/docs/lint/rules/index.md
website/src/styles/_content.scss

Closes #798 
Switched to an ordered list to show the rules. I changed a bit the styles of the list to allow some gutter between list item and other, this way it's more readable.
@EduardoLopes  would you mind take a look please?

Switch to dotted list for showing list of rules inside website

---

website/src/_includes/layouts/base.njk
website/src/styles/_sidebar.scss

This PR fix algolia dropdown hidden by `overflow-x: auto` and add styles for the search input.
Now, only the menus of the sidebar are scrollable. This is essential for mobile. On desktop, the scrollbar doesn't look good and as the menu grows, it will show all the time.
I made the sticky sidebar at first, because we were going towards make a single giant page and a sticky sidebar would be handy in that case. Now that we will not have pages that big, we should think about don't have a sticky left sidebar on desktop. c/c @sebmck

Website: Add search input styles

---

.github/ISSUE_TEMPLATE/01_bug.md
.github/ISSUE_TEMPLATE/02_misc.md
.github/ISSUE_TEMPLATE/02_question.md
.github/ISSUE_TEMPLATE/03_support.md
.github/ISSUE_TEMPLATE/03_task.md
.github/ISSUE_TEMPLATE/04_task.md
.github/ISSUE_TEMPLATE/04_umbrella.md
.github/ISSUE_TEMPLATE/05_discussion.md
.github/ISSUE_TEMPLATE/06_umbrella.md
.github/ISSUE_TEMPLATE/07_other.md
.github/ISSUE_TEMPLATE/config.yml

This PR updates our issue templates. They are now only four that I considered to be the most relevant:
- 🐛 Bug Report: "Report a possible bug or regression"
- 💭 Miscellaneous: "Feature proposals, project meta discussion and questions, and anything else!"
- 🚀 Task: "Specific actionable task. Typically opened by existing contributors. If you aren't sure then use the "Miscellaneous" template."
- ☔  Umbrella: "Discuss and track high level goals for a collection of other issues. Should only be opened with prior discussion."
I wanted to make these concise and general to avoid information overload. The last two are only relevant for contributors (including those not core). While the top two are aimed at general users.
I also included these links under these the issue templates:
- [🗣️ …

Update issue templates

---

packages/@romefrontend/cli/cli.ts
packages/@romefrontend/core/client/Client.ts
packages/@romefrontend/core/common/userConfig.ts

This PR adds `--summary` flag to `rome rage`. We will require all bug reports to contain the output of `rome rage --summary` so we can better triage and address them.
When ran, the command will output environmental information that will be useful in figuring out if a bug is specific to someones system and configuration.
We will also populate `summary.txt` with the same output in an archive when ran with `rome rage` without the `--summary` flag.
```
$ ./rome rage --summary
Environment Variables
Object {
COLORFGBG: "15;0"
COLORTERM: "truecolor"
PATH: "/Users/sebastianmckenzie/.nvm/versions/node/v14.2.0/bin:/Users/sebastianmckenzie/bin:/Users/sebastianmckenzie/.cargo/bin:./node_modules/.bin:/Applications/Visual
Studio Code.app/Contents/Resources/app/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin: …
```

Add `rome rage --summary`

---

website/src/_includes/layouts/base.njk

Defer internal script to avoid blocking the rendering
I really don't like how the docsearch.js from algolia is set up. They don't provide any async way to set up their script. The every moment we try to make the loading of the script async, it breaks

Defer internal script

---

website/static/js/index.js

On mobile, when clicking a link in the toc, the navigation sidebar was opening. This PR fixes the issue, and the toc sidebar closes when a toc link is clicked.
N/A

Website: Fix table of contents

---

website/src/index.md

I was clicking through the homepage at https://romefrontend.dev/ and noticed the `team of volunteers` link points to a page, `https://romefrontend.dev/contributing/team`, that does not exist:
I noticed the link in the `README` points to the correct URL, and updated the website link accordingly. 
New link worked locally via website build steps at https://github.com/romefrontend/rome/blob/main/CONTRIBUTING.md#website.

Update Rome volunteers link on homepage

---

internal/compiler/lint/rules/js/confusingLanguage.test.md
internal/compiler/lint/rules/js/confusingLanguage.test.rjson
internal/compiler/lint/rules/js/confusingLanguage.ts
website/src/docs/lint/rules/js/confusingLanguage.md

This pull request updates the `js/confusingLanguage` lint rule in preparation for a release to use lint suggestions instead of auto-fixes when working with object properties and member expressions. This allows `check --apply` to be used safely since unsafe property auto-fixes will no longer be applied.
I realize that the words detected in this rule and where their source of truth will change as part of #793, and I'm happy to take on the work of updating this rule once the required configuration changes land (cc @sebmck).
Resolves #760
```sh
./rome test
```

feat: lint suggestions for properties for js/confusingLanguage

---

scripts/changelog.ts

This pull request minimally updates the internal (and at some point, possibly external) `changelog` script with improved formatting.
```sh
./rome run scripts/changelog
```

fix: update changelog formatting

---

website/src/styles/_global.scss
website/src/styles/index.scss

Improve ability to discern `inline-code` elements in docs.
PR adds and uses a CSS variable for the same.
Also adds `border-radius` and `padding`.

style: inline code background color for better distinction

---

README.md

This is a quick fix to the `Getting Started` documentation which currently redirect to a "Page Not Found".
Chicking that's the correct link that I set

Fixes link to Getting Started documentation

---

website/src/_includes/docs/cli-commands.md
website/src/_includes/docs/linting.md
website/src/_includes/docs/project-config.md

This PR fixes docs links that pointed to `/docs` (like https://romefrontend.dev/docs/rjson) while it should point to current document's IDs.
For example, you can go to https://romefrontend.dev/#project-configuration and click on **RJSON** or **`rome config`** to reproduce (404 page)
Even though I just changed `.md` files, I couldn't run tests because it has thrown errors, as you can see in #999

Fix documentation 404 links

---

internal/js-ast-utils/isBinary.test.ts

Part of #1023 
This PR adds test cases for the `isBinary` utility checking binary and non-binary expressions (unary, arrays). 
Note: I wasn't sure if the copyright header was needed but I saw it in other tests I used as samples, so I kept it. Please let me know if it needs to change.
It runs and passes with  `./rome test internal/js-ast-utils/isBinary.test.ts`
No changes to other tests, so `./rome test` still passes (I've verified)

Test cases for js-ast-utils/is-binary

---

GOVERNANCE.md

Fixes links to Discord that were pointing to the repo instead of the channel.

chore: fix Discord links

---

internal/cli-flags/Parser.ts

`rome --log-shell-completions fish` prints the fish shell completion, but the output includes the meaningless subcommand description as below.
```console
> rome --log-shell-completions fish
complete -c rome -f
complete -c rome -n '__fish_use_subcommand' -a 'start' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'develop' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'stop' -d '[object Object]'
...
```
This PR makes the output meaningful.
```console
> rome --log-shell-completions fish
complete -c rome -f
complete -c rome -n '__fish_use_subcommand' -a 'start' -d 'start daemon (if none running)'
complete -c rome -n '__fish_use_subcommand' -a 'develop' -d 'TODO'
complete -c rome -n '__fish_use_subcommand' -a 'stop' -d 'stop a running daemon if one …
```

fix: subcommand description construction in fish shell completion

---

internal/core/server/ServerRequest.ts

This fixes the `clearBuffer` method name used in logs and markers. Looks like this was just a copy/paste mistake.

chore: Fix clearBuffer name in ServerRequest

---

README.md
website/src/_includes/docs/intro.md
website/src/blog/posts/2020-08-08_introducing_rome.md

**webpack** brand is well documented on their website.
see: https://webpack.js.org/branding/#the-name
That's the reason why I'm opening this Pull Request in order to spell it correctly in all `*.md` files.
Uses this following command:
```sh
$ git grep -l 'Webpack' | xargs sed -i '' 's/Webpack/webpack/g'
```
Hope you'll find this contribution helpful.
Thank you!

docs: fixes misspelling webpack words

---

internal/codec-spdx-license/index.ts
internal/codec-spdx-license/parse.ts
internal/diagnostics/descriptions/parsers/spdx.ts

License identifiers are case insensitive, per:
https://spdx.github.io/spdx-spec/appendix-IV-SPDX-license-expressions/#case-sensitivity
This package uses uppercase "APACHE-2.0", for example:
https://github.com/invertase/cluster-key-slot/blob/579d4a5f11cd3f63092286474a993350d6c7ca6d/package.json#L46
Depending on that package gave these results.
Before:
```
✖ Unknown license APACHE-2.0
44 │     "url": "http://github.com/Salakar/"
45 │   },
> 46 │   "license": "APACHE-2.0",
│               ^^^^^^^^^^
47 │   "bugs": {
48 │     "url": "https://github.com/Salakar/cluster-key-slot/issues"
ℹ Did you mean APSL-2.0?
- APACHE-2.0
+ APSL-2.0
```
After:
Pages and pages of JS lint output :)

Match license identifiers case-insensitively

---

internal/codec-source-map/base64.test.ts

Part of #1023 
Adds test for codec-source-map/base64.ts

Added test for codec-source-map/base64.ts

---

internal/codec-source-map/ArraySet.test.ts

Part of #1023 
I'm happy to close this, given @sebmck's comment [here](https://github.com/romefrontend/rome/issues/1023#issuecomment-673688408) - seems like this is largely around the ast/isX methods, but just want to make sure.
This just adds tests for asserts around indexOf, since adding to sets is relatively known.
` ./rome test internal/codec-source-map/ArraySet.test.ts`
Specifically, I tested that sets add to the underlying array, that adding duplicates would result in `indexOf` only knowing the first element, and errors thrown on indexOf in certain conditions.

Add tests for codec-source-map/ArraySet

---

internal/js-ast-utils/isJSXElement.test.ts

part of  #1023 
added tests for `isJSXElement` function in `js-ast-utils`
`./rome test` --all tests passed

test: added tests for isJsxElement in ast-js-utils

---

internal/path-match/stringify.test.ts

Related to #1023 , tests for `path-match/stringify.ts`

test: add missing test for path-match/stringify.ts

---

internal/js-ast-utils/isValidIdentifierName.test.ts

Part of #1023 
Adds test for js-ast-utils/isValidIdentifierName.ts

Added test for js-ast-utils/isValidIdentifierName.ts

---

internal/js-ast-utils/createMemberProperty.test.ts

Part of #1023 
Adds test for js-ast-utils/createMemberProperty.ts

Added test for js-ast-utils/createMemberProperty.ts

---

internal/codec-source-map/SourceMapGenerator.test.ts
internal/codec-source-map/SourceMapGenerator.ts

Part of #1023 
Adds test for codec-source-map/SourceMapConsumer.ts
Changes deprecated use of `new Buffer()` to `Buffer.from()` in SourceMapConsumer#toComment

Added test for codec-source-map/SourceMapGenerator.ts

---

internal/vcs/index.test.ts
internal/vcs/index.ts

(Ref #1023)
As the code here is mostly dependent on `git`, I only added a test for `extractFileList` for the moment. 
- testing `VCSClient` would require mocking `childProcess.spawn` or spawning a real process with a predetermined output
- testing `GitVCSClient` would require creating a new directory, initializing a new repository and doing a few commits/edits on some temporary files
In both cases, I don't feel that it would worth the effort, as the code is mostly based on external dependencies with a very small chance of getting broken.
I'm waiting for further guidance.

test: Add tests for internal/vcs (#1023)

---

internal/js-ast-utils/tryStaticEvaluation.test.ts
internal/js-ast-utils/tryStaticEvaluation.ts
internal/js-ast-utils/tryStaticEvaluationPath.test.ts

Part of #1023 
I've added test cases for interal/js-ast-utils/tryStaticEvaluation and tryStaticEvaluationPath. I noticed that boolean negation isn't supported in the unary expression case. ~~I wasn't sure if that was intentional, but I added tests to assert that `!true` would bail.~~ I added support for that after this [Discord message](https://discordapp.com/channels/678763474494423051/678763474930761739/745358222797439076)
`./rome test` works with more passing tests

Add tests for js-ast-utils/tryStaticEvaluation(path)

---

scripts/changelog.ts

This pull request updates the existing change log script by adding support for a version argument, allowing a specific version (pre-release or otherwise) to be used instead of the version that's determined internally based on commit history.
This will allow change logs to be generated and tags to be created for future betas by running the script with the correct pre-release specified, e.g. `./rome run scripts/changelog 10.0.5-beta` (cc @sebmck).
```
./rome run scripts/changelog <some_version>
```

feat: add specific version support to changelog script

---

.gitignore
internal/cli/server.ts
internal/core/client/Client.ts
internal/core/common/constants.ts
internal/core/common/userConfig.ts

This PR fixes the path that's used for named pipes on Windows, which is what we use for IPC communication between the CLI and a running server. Named pipes aren't supported on file descriptors which I didn't realize until I carefully read the docs. This will address #1017.
I also took the liberty of improving the locations of the various directories we use, making them align more with their appropriate operating system location. Where possible we always use the value derived from the XDG environment variables, regardless of operating system. See inline comments for additional references and explanation.
**Cache**
XDG/Linux: `~/.cache/rome`
Windows: `~/AppData/Local/Temp/Rome`
Mac: `~/Library/Caches/Rome`
**Config**
XDG/Linux: `~/.config/rome`
Windows: `~/AppData/Local/Rome/Config`
Mac: …

Fix named pipes path and use better locations for cache, config, data, and runtime directories

---

internal/codec-js-manifest/dependencies.test.md
internal/codec-js-manifest/dependencies.test.ts
internal/codec-js-manifest/dependencies.ts
internal/diagnostics/descriptions/manifest.ts

Add support for `workspace:` dependency pattern prefix and add specific error when we're provided with something that looks like an unsupported prefix instead of parsing it as semver.
Added test

Add support for `workspace:` dependency pattern prefix

---

internal/async/lockers.ts
internal/child-process/index.ts
internal/cli-reporter/Reporter.ts
internal/cli-reporter/types.ts
internal/codec-js-manifest/convert.ts
internal/codec-js-manifest/dependencies.ts
internal/codec-js-manifest/index.ts
internal/consume/Consumer.ts
internal/core/server/ServerRequest.ts
internal/core/server/commands/init.ts
internal/core/server/fs/MemoryFileSystem.ts
internal/core/server/fs/RecoveryStore.ts
internal/core/server/fs/glob.ts
internal/core/server/project/ProjectManager.ts
internal/diagnostics/categories.ts
internal/diagnostics/types.ts
internal/events/EventQueue.ts
internal/fs/index.ts
internal/typescript-helpers/index.ts
scripts/changelog.ts

This PR makes `rome init` automatically add itself as a dependency to `package.json` when ran in a folder without installed. This allows `npx rome init` to function as a single safe command.
In the process of doing this I had to fix numerous long-standing race conditions around `package.json` updates, which was necessary here as we are modifying `package.json` to include `rome` in an already created project. (#751) I did this by adding a global memory file system lock that we wait on in strategic places.
Manually tested, ran test suite.

Automaticaly add `rome` to `dependencies` when running `rome init`

---

internal/fs/index.ts
scripts/_utils.ts
scripts/ast-create-node.ts

This makes the previous output of non existent languages and categories created with `scripts/ast-create-node.ts` more clear.
See #1058 for more.
Output before this change:
`./rome run scripts/ast-create-node js JSDecorator statement`
```
unknown internalError/fs  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✖ /home/dibenso/source/repos/rome/internal/ast/js/statement/JSDecorator.ts does not exist
⚠ No stacktrace available for this error. This is a Node.js limitation: https://github.com/nodejs/node/issues/30944
ℹ Try setting the ROME_FS_ERRORS=1 envvar to capture stacktraces for fs calls.
File stats for internal/ast/js
Object {
atime: 2020-08-12T16:11:18.887Z
atimeMs: 1_597_248_678_887.1875
birthtime: 2020-08-12T16:10:14.200Z …
```

better errors for non existent languages and categories

---

internal/ast/js/expressions/JSUnaryExpression.ts
internal/js-analysis/evaluators/expressions/JSUnaryExpression.ts

[While writing unit tests for `isUnaryLike`, throw wasn't a UnaryExpression.](https://github.com/romefrontend/rome/issues/1023#issuecomment-673769870) 
Remove it from the UnaryExpression definitions!
Related to [Missing Tests #1023](https://github.com/romefrontend/rome/issues/1023)  
This PR has not been made with contextual knowledge, just what seems correct from a narrow look at the code in `internal/ast/js/expressions/JSUnaryExpression.ts`. 
I've depended on the existing test suite for testing. I'm happy to do more but will need direction.

"throw" is type JSThrowStatement, not UnaryExpression

---

internal/codec-spdx-license/parse.ts

Closes #1064
Matches the separator words in the license (such as `or` or `and`) in a case insensitive manner.
- **/rome** *(Rome's repository)*
- **/dom-storage.js** *(https://git.coolaj86.com/coolaj86/dom-storage.js/)* 
- **/xmldom** *https://github.com/xmldom/xmldom/()*
- `cd dom-storage.js`
- `../rome/rome init`
```
Welcome to Rome! Let's get you started... 
Files created ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- .config/rome.rjson: Your project configuration. Documentation: https://romefrontend.dev/#project-configuration
- .editorconfig: Sets editor formatting and indentation options. Documentation: …
```

fix: match case insensitive license word (#1064)

---

internal/js-ast-utils/getTSQualifiedBaseFromEntityName.test.ts

Part of #1023 
Adds test for js-ast-utils/getTSQualifiedBaseFromEntityName.ts

Added test for js-ast-utils/getTSQualifiedBaseFromEntityName.ts

---

scripts/ast-create-node.ts

I've noticed if one uses the `ast-create-node` script the interface is not exported which causes an error in `internal/ast/js/unions.ts` file. This PR fixes it.
To check that the error is valid, run the `ast-create-node` script to create a new expression node and then check for errors with `./node_modules/.bin/tsc`. After adding this change the error is no longer present.

fix: export AST interface

---

internal/markup-syntax-highlight/index.test.ts
internal/markup-syntax-highlight/utils.test.ts
internal/markup-syntax-highlight/utils.ts

Test and fixes for internal/markup-syntax-highlight

---

scripts/generated-files/lint-rules-docs.ts
website/src/docs/lint/rules/ts/useInterfaces.md

This pull request updates the `lint-rules-docs` generation script to support TSLint rule references, and updates the documentation and referenced rule for the `ts/useInterfaces` rule to prevent confusion.
Resolves #1130
```sh
./rome test
```

feat: support tslint rule references

---

website/src/_includes/docs/intro.md

This is part of a series of PRs concerning **📎 Website accessibility audit** (https://github.com/romefrontend/rome/issues/839#issuecomment-672338554)
This PR fixes: 
Language support table: empty cells are confusing even for non-impaired readers and the ones with emojis are not correctly read by screen readers.
There are not too many visual changes, but I've included some images to illustrate.

fix(website): a11y language support table

---

internal/core/server/fs/MemoryFileSystem.ts
internal/core/server/project/ProjectManager.ts
internal/diagnostics/categories.ts
internal/diagnostics/descriptions/projectManager.ts

Closes #979 
I don't know if the **diagnostic message** is correct for what we want to display to the user.
Maybe we could do something similar to the `DUPLICATE_PACKAGE` diagnostic by telling the user **which files are in conflict**.
Like so:
<p align="center">
</p>
- Create a new Rome project with `rome init`.
- Add a new config file `.config/rome.json`.
- Run any rome command (e.g `rome check`)
- It should find the following problem
<p align="center">
</p>

[projectManager] Warn when multiple configs

---

website/src/_includes/scripts/index.js

close #1170
The event from TOC link click is stoped the default browser behavior of updating URL hash by calling `event.preventDefault()`. Added manually URL hash update after it.

fix(website): update url hash when click TOC links

---

website/src/styles/_sidebar.scss

Hello,
This correction aims to correct an existing problem (#1162), the sidebar overflow.
> Look at the item `dependencies.exceptions.invalidLicenses`

fix(website): Sidebar list items width (#1162)

---

CONTRIBUTING.md
scripts/ast-create-node.ts

Closes #1161 
You can now create new `AST` nodes by following how the folders and files are currently structured in the `ast/` folder.
To create a new AST node by the name of `TSSomeNode.ts`, now you can run
`scripts/ast-create-node js/typescript/TSSomeNode`

fix: reformated ast-create-node for better readability

---

scripts/lint-create-rule.ts

current `create-lint-rule` script breaks the documentation of that rule in the website by default because of indentation and it doesn't export lint message correctly. this PR fixes those.
`./rome test`

fix: create-lint-rule script

---

website/src/_includes/scripts/index.js

Scrolling over the headings on the website feels very choppy and the browser history gets filled with entries for each and every heading element. [History.replaceState()](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState) fixes both issues.
If populating the browser history for each scrolled over heading is the intended behavior, this can be changed to use [History.pushState()](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState) instead.

fix(website): Janky scrolling

---

internal/js-ast-utils/isEmptyTemplateLiteral.test.ts

Part of #1023 
Adds test for js-ast-utils/isEmptyTemplateLiteral.ts

test: js-ast-utils/isEmptyTemplateLiteral

---

internal/js-ast-utils/inheritLoc.test.ts

Part of #1023 
Adds test for js-ast-utils/inheritLoc.ts

test: js-ast-utils/inheritLoc

---

website/src/_includes/action-links.liquid

The link to open collective is actually: romefrontend.
This PR fix to opencollective.com/rometools.

fix: opencollective link

---

scripts/generate-all-files.ts
website/src/_includes/scripts/funding.js

- Fixes a typo with "uncommitted"
- Returns early when git status returns an empty string
`./rome test`
`./rome check --apply`
Additional testing included modifying an existing lint rule, running this script and verifying the exit code of 1, and running this script without any modifications and verifying an exit code of 0.

fix: Typo on "uncommitted", updates file to return early

---

internal/core/common/file-handlers/index.ts

Ignore scss, sass and less as they make rome crash.
Better strategy should be used instead later.

chore: ignore scss, sass and less

---

internal/core/server/commands/init.ts

fixes #1245 
```
yarn rome init
```
Checks generated `.editorconfig`
```
[{*.js,*.json,*.rjson}]
...
```

fix(init): remove space between ext in generated editorconfig

---

internal/compiler/lint/rules/js/noExtraBooleanCast.test.md
internal/compiler/lint/rules/js/noExtraBooleanCast.test.rjson
internal/compiler/lint/rules/js/noExtraBooleanCast.ts
website/src/docs/lint/rules/js/noExtraBooleanCast.md

I made a pr improving `noExtraBooleanCase` rule.
First, I made it fix problems automatically
```js
while (!!foo) {}
// autofixed
while (foo) {}
```
Second, I made it report some problems even if it's not in a boolean context (`if`, `for`...).
- For example, in the current version, these are lint-free
```js
let a = 1;
const foo = {};
a += !Boolean(foo); // lint-free
``` 
- In this PR, these are reported and auto fixed
```js
let a = 1;
const foo = {};
a += !Boolean(foo); // Error and it's fixed to "a += !foo"
``` 
test cases

feat(lint): add autofix in noExtraBooleanCast

---

internal/compiler/lint/rules/js/noTemplateCurlyInString.test.md
internal/compiler/lint/rules/js/noTemplateCurlyInString.test.rjson
website/src/docs/lint/rules/js/noTemplateCurlyInString.md

Correct test case.
There is an incorrect syntax test case in `noTemplateCurlyInString`.
```js
const helloUser = 'Hello, ${user};
^ missing quote
```
test case

test(lint): correct test case in noTemplateCurlyInString

---

internal/js-ast-utils/renameBindings.test.ts

Part of #1023 
Adds test for js-ast-utils/renameBindings.ts

test: add test for js-ast-utils/renameBindings.ts

---

internal/js-ast-utils/resolveIndirection.test.ts

Part of #1023 
Adds test for js-ast-utils/resolveIndirection.ts

test: add test for js-ast-utils/resolveIndirection.ts

---

internal/formatter/node/parentheses.ts
internal/formatter/test-fixtures/js/parentheses/input.test.md
internal/formatter/test-fixtures/js/parentheses/input.ts

The checking logic in `isClassExtendsClause ` function is incorrect with the current at structure.
so rome formatter makes incorrect result (syntax error).
* target.js
```ts
class Foo extends (+Bar) {}
class Bar extends (Baz ?? Qux) {}
const foo = class extends (Bar ?? Baz) {}
```
```
$ ./rome format target.js
class Foo extends +Bar {} // syntax error
class Bar extends Baz ?? Qux {} // syntax error
const foo = class extends Bar ?? Baz {}; // syntax error
``` 
I made a pr handle it
test case

fix(formatter): correct checking extends clause

---

internal/compiler/lint/rules/react/useKey.test.md
internal/compiler/lint/rules/react/useKey.test.rjson
internal/compiler/lint/rules/react/useKey.ts
website/src/docs/lint/rules/react/useKey.md

`useKey` rule didn't report the below case even if there is no key props
```jsx
const a = foo?.map((x) =>
<div> {/*missing key props*/}
{x}
</div>
);
```
I made a pr handle it.
test case

fix(lint): handle optional call expression in useKey

---

internal/js-ast-utils/isTypeNode.ts
scripts/vendor/rome.cjs

Flow syntax support has been removed since #440 , and all ast nodes no longer has a `Flow` prefix.
This pr removes Flow from `isTypeNode`
verified in `ast/index.ts` that no ast node starts with `Flow`

feat: remove Flow from TypeNode

---

internal/ast/html/attributes/HTMLAttribute.ts
internal/compiler/lint/rules/html/useHtmlLang.ts
internal/compiler/lint/rules/html/useValidLang.ts
internal/formatter/builders/html/attributes/HTMLAttribute.ts
internal/formatter/builders/html/tags/HTMLElement.ts
internal/formatter/test-fixtures/html/attributes/input.html
internal/formatter/test-fixtures/html/attributes/input.test.md
internal/html-parser/index.ts
internal/html-parser/test-fixtures/attributes/input.html
internal/html-parser/test-fixtures/attributes/input.test.md

Rome fails to parse the boolean attribute.
- target.html
```html
<input checked>
```
```
./rome parse target.html
```
I made a PR handle it.
test case

fix(html-parser, formatter): handle boolean attribute

---

internal/cli-flags/Parser.ts

Some of the fish shell completions were emitting descriptions of `[object Object]` due to using the wrong markup functions.
```fish
complete -c rome -n '__fish_use_subcommand' -a 'start' -d '[object Object]'
```
[![Discord transcript](https://user-images.githubusercontent.com/7608555/103423965-ad36f080-4b5e-11eb-9c19-81471cc939a7.png)](https://discord.com/channels/678763474494423051/714237988145594428/794284536082202641)
I just used the `rome --write-shell-completions` command to emit new completions and observed the output by hand.
Unit tests should be written to prevent regressions.
After the changes the command is now producing the expected output
```fish
complete -c rome -n '__fish_use_subcommand' -a 'start' -d 'start daemon (if none running)'
```

fix(cli-flags): fix shell completions

---

internal/compiler/lint/rules/react/noAccessStateInSetState.test.md
internal/compiler/lint/rules/react/noAccessStateInSetState.test.rjson
internal/compiler/lint/rules/react/noAccessStateInSetState.ts
website/src/docs/lint/rules/react/noAccessStateInSetState.md

Rome throws error on below codes
- tagetr.js
```js
class MyComponent extends Component {
increment() {
this.setState();
}
}
```
```
$ ./rome check ./target.js 
✖ Cannot read property 'type' of undefined
```
I add an array length checking logic.
test case

fix(lint): check argument length in noAccessStateInSetState

---

internal/compiler/lint/index.test.ts
internal/compiler/lint/rules/harness.test.ts
internal/compiler/lint/suppressions.ts

This PR fixes the case when there's a suppression and we attempt to add a new one.
The previous code was generating a comment that is not correct for Rome. This PR fixes this case.
Created a new test case.

fix(lint): add suppression to exiting ones

---

internal/js-ast-utils/isInTypeAnnotation.test.ts

Part of #1023 
Adds test for js-ast-utils/isInTypeAnnotation.ts

test: js-ast-utils/isInTypeAnnotation

---

public-packages/vscode-extension/index.ts
scripts/run-vscode-extension.ts

Fixes #1039
And also fixes execution of `code` in `scripts/run-vscode-extension` on Windows OS

fix(vscode-extension): correct finding rome on windows os

---

internal/formatter/builders/css/core/CSSDeclaration.ts
internal/formatter/test-fixtures/css/basic/input.css
internal/formatter/test-fixtures/css/basic/input.test.md

Current CSS 
```css
a {
transition: background-color 0.3s ease-in-out;
}
```
Was formatted like this
```css
a {
transition: background-color0.3sease-in-out;
}
```
This PR fixes the issue
Added a new example to the current test fixtures

fix(formatter): add space to multiple declarations

---

internal/css-parser/index.ts
internal/css-parser/test-fixtures/values/input.css
internal/css-parser/test-fixtures/values/input.test.md
internal/formatter/test-fixtures/css/values/input.css
internal/formatter/test-fixtures/css/values/input.test.md

In CSS, The final semicolon in a set of statements is optional. 
But current parser did not handle it well
- test.css
```css
h1 {
color: red
}
```
```
$ ./rome parse ./test.css
✖ AST diagnostics aren't allowed
project-rome/test.css:3:1 parse(css)  OUTDATED  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✖ Invalid declaration
⚠ This file has been changed since the diagnostic was produced and may be out of date
```
This PR will handle it
test cases

fix(css-parser): handle optional semi

---

internal/formatter/node/parentheses.ts
internal/formatter/test-fixtures/js/parentheses/input.test.md
internal/formatter/test-fixtures/js/parentheses/input.ts

Rome formatter remove parentheses around unary in unary..
- target.ts
```ts
+(+foo);
```
```
$ ./rome format target.ts
++foo;
```
It's a pr for handle it.
```
$ ./rome format target.ts
+(+foo);
```
test cases

fix(formatter): handle parentheses around nested unary

---

internal/cli-reporter/Reporter.ts
internal/cli-reporter/types.ts
internal/cli/cli.ts
internal/core/client/Client.ts
internal/core/common/bridges/ServerBridge.ts
internal/core/common/bridges/WorkerBridge.ts
internal/core/common/types/client.ts
internal/core/common/utils/Logger.ts
internal/core/server/Server.ts
internal/core/server/ServerCache.ts
internal/core/server/ServerRequest.ts
internal/core/server/WorkerManager.ts
internal/core/worker/Worker.ts
internal/events/utils.ts
internal/test-helpers/integration.ts
website/src/_includes/docs/cli.md

This PR closes #1331. It completely rewrites the way we transport logs across process boundaries. You may not have known before but we do a lot of optimizations to ensure that logs were only sent from workers to the server when necessary. We also skip a lot of markup processing so that when you use an internal logger without a subscriber, it's very cheap so we can use them as we like.
I added some warning and error logs that would be helpful when debugging issues. Previously we just had a bunch of info messages that are verbose but amazing for debugging.
So I split the flag into `--logs all` and `--logs error`. Where `all` will include info and error logs, and `error`... will only include errors.
Ran `./rome ci`

Add `--logs all` and `--logs error`

---

internal/core/common/file-handlers/index.ts
internal/core/server/ServerRequest.ts
internal/core/server/fs/FileAllocator.ts
internal/core/server/fs/MemoryFileSystem.ts
internal/core/server/fs/glob.ts
internal/core/server/fs/resolverSuggest.ts
internal/diagnostics/categories.ts
internal/diagnostics/descriptions/files.ts
internal/diagnostics/descriptions/flags.ts
internal/diagnostics/descriptions/index.ts
internal/path/index.ts
internal/project/load.ts
internal/project/types.ts

This issue closes #1328 and #1315. It changes two error conditions that we had as runtime exceptions to diagnostics.
Specifying a file that we don't have a handler for now provides a suggestion to add it as an asset extension:
And trying to perform an operation on a file that exceeds the max file size limit now provides multiple suggestions on how to allow it and why we have that limit in the first place:
Ran `./rome ci` and manually ran commands to trigger the above screenshots.

Improve max file size and missing file handler errors

---

internal/cli/cli.ts
internal/core/client/commands.ts
internal/core/common/bridges/ServerBridge.ts
internal/core/common/commands.ts
internal/core/index.ts
internal/core/server/commands.ts
internal/core/server/lsp/LSPServer.ts
internal/diagnostics/descriptions/files.ts
internal/diagnostics/types.ts
internal/test-helpers/integration.ts

This PR adds a type union of all valid command names and switches all the appropriate callsites that use `string` to it. Thanks @ematipico for flagging in #1334! I put a subcommand name in `args` instead of `command`.
Ran TS.

Strongly type command names

---

scripts/_utils.ts

Adds additional file types support to modifyGeneratedFile which currently only supports js/ts & html.
Supports `js`, `ts`, `rjson`, `sh`, `yml` (`yaml`), `toml` and defaults to `html` like syntax.
New `CommentDelimiter` type & `determineDelimiter()`.
To merge after #1339.
`rome check`

feat: modifyGeneratedFile additional file types support

---

internal/css-parser/index.ts
internal/css-parser/test-fixtures/comment/input.css
internal/css-parser/test-fixtures/comment/input.test.md

CSS parser fails to parse multiline comments. This PR will fix it
- test.css
```css
/*
* comments
*/
```
```
./rome parse test.css
```
- result
```
✖ Expected a left curly bracket {.
1 │ /*
2 │  * comments
> 3 │  */
│   ^
```
test cases

fix(css-parser): handle multiline comments

---

internal/markdown-parser/index.ts
internal/markdown-parser/parser/paragraph.ts
internal/markdown-parser/test-fixtures/smoke/input.md
internal/markdown-parser/test-fixtures/smoke/input.test.md
internal/markdown-parser/utils.ts

Currently, text with a single newline is handled as separated paragraphs. This PR makes them handled as same paragraph with `\n` text.
**input**
```markdown
first line
second line
```
**main branch**
```
MarkdownRoot {
comments: Array []
corrupt: false
diagnostics: Array []
integrity: Object {hash: "73621482ff083eca9ea88880393298f7d3f53402200780b0c16354a9beb0535a"}
path: UIDPath<project-rome/test.md>
body: Array [
MarkdownParagraph {children: Array [MarkdownText {value: "first line"}]}
MarkdownParagraph {children: Array [MarkdownText {value: "second line"}]}
]
}
```
**This PR**
```
MarkdownRoot {
comments: Array []
corrupt: false
diagnostics: Array []
integrity: Object {hash: "73621482ff083eca9ea88880393298f7d3f53402200780b0c16354a9beb0535a"}
path: UIDPath<project-rome/test.md>
body: …
```

fix(markdown-parser): handle text with single newline as same paragraph

---

internal/browser-features/Browser.ts
internal/browser-features/index.ts
internal/core/server/ServerRequest.ts
internal/core/server/lsp/LSPServer.test.ts
internal/core/server/project/ProjectManager.ts
internal/v8/InspectorClient.ts
scripts/generated-files/browsers-db.ts

Replaces `consumer.get("one").get("two")` calls to `consumer.getPath(["one", "two"])`.
CI

chore: update usages of chained consumer get to getPath

---

internal/markdown-parser/parser/inline.ts
internal/markdown-parser/parser/paragraph.ts
internal/markdown-parser/parser/reference.ts
internal/markdown-parser/parser/text.ts
internal/markdown-parser/test-fixtures/headings/input.test.md
internal/markdown-parser/test-fixtures/lists/input.test.md
internal/markdown-parser/test-fixtures/reference/input.test.md
internal/markdown-parser/test-fixtures/smoke/input.test.md

Currently, `MarkdownText`'s ending position is the same as starting position. This PR fixes it.
See snapshot

fix(markdown-parser): fix markdown text ending position

---

internal/core/server/lsp/LSPProgress.ts

Rome LSP uses `type` field for LSPProgress which breaks Neovim's builtin LSP client. It should be `method` instead of `type` according to [the LSP spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#progress)
I tried to run the test *before* and *after* my PR to make sure I didn't mess up. Some tests are failing after 10s (`Test worker was unresponsive for 10 seconds. We tried to collect some additional metadata but we timed out again trying to fetch it...`), so I don't think they're caused by my changes

fix: use method instead of type for LSPProgress

---

CONTRIBUTING.md
internal/compiler/transforms/compile/css-handler/prefix/index.ts
internal/path/classes/AbsoluteFilePath.ts
scripts/_utils.ts
scripts/compiler-create-prefix.ts
scripts/generated-files/css-prefix.ts
scripts/lint-create-rule.ts
website/src/_includes/layouts/prefix.liquid
website/src/docs/css-handler/index.md

This PR does the following:
- create a new script called `compiler-create-prefix` that creates the main boilerplate of prefix and updates the main entry point `prefix/index.ts`. We don't have documentation yet but I think we should start creating the files, what we need later is to call the compiler and automatically print the result inside the documentation. This has basically two perks: automation and using the compiler for real;
- updates the `CONTRIBUTING.md` file with the new file;
- fixes a small issue around `AbsolutePath.createDirectory` where a folder should be created only when it doesn't exist;
- fixes an existing issue inside `generated-files/css-prefix` where a property should be converted to camel case, in case the file contains a dash, e.g. `box-shadow.ts`
- creates a basic …

chore: script file to generate prefix

---

internal/core/server/lsp/LSPProgress.ts
internal/core/server/lsp/LSPServer.ts
internal/core/server/lsp/protocol.ts
internal/core/server/lsp/types.ts

LSP is built atop the JSON-RPC specification [1]. This specification
requires messages to have a key "jsonrpc" with a value of "2.0" (as a
string). Rome's LSP server does not include a "jsonrpc" key in its
messages. This protocol violation causes some LSP clients to reject
Rome's messages.
Include the required key, fixing Rome for these clients.
[1] https://www.jsonrpc.org/specification

fix(lsp): adhere to JSON-RPC specification

---

internal/core/server/lsp/LSPServer.ts

The LSP specification requires window/logMessage notifications to
include a "type" key and a "message" key. Rome's LSP server omits the
required "type" key. This protocol violation causes problems with some
LSP clients.
Adhere to the LSP by adding the missing "type" key.

fix(lsp): fix malformed window/logMessage messages

---

internal/ast/css/media/CSSMediaQueryList.ts
internal/css-parser/parser/media/index.ts
internal/css-parser/parser/rules.ts
internal/css-parser/test-fixtures/invalid/media/feature-value-missing/input.test.md
internal/css-parser/test-fixtures/invalid/media/feature/input.test.md
internal/css-parser/test-fixtures/invalid/media/type/input.test.md
internal/css-parser/test-fixtures/media/condition/input.css
internal/css-parser/test-fixtures/media/condition/input.test.md
internal/css-parser/test-fixtures/media/feature/input.test.md
internal/css-parser/test-fixtures/media/type/input.test.md
internal/formatter/builders/css/media/CSSMediaQueryList.ts
internal/formatter/test-fixtures/css/media/condition/input.css
internal/formatter/test-fixtures/css/media/condition/input.test.md
internal/formatter/test-fixtures/css/media/features/input.test.md
internal/formatter/test-fixtures/css/media/smoke/input.test.md

This PR fixes #1460 
The issue was that I wrongly parsed the block after the media query, assuming they were declarations. Instead, there are supposed to be rules.
Hence, I changed the structure of the media query AST to mimic what we already have: `prelude` and `block`.
- `prelude` is the media query list
- `block` is a list of rules
This PR updates existing snapshots and adds new test cases

fix(css-parser, formatter): rules inside media

---

CONTRIBUTING.md
internal/core/server/commands/ci.ts
internal/core/server/commands/test.ts
internal/core/server/testing/types.ts
internal/core/worker/test/TestWorkerFile.ts

This PR adds support for `--no-suppress-logs` flag for `rome test` so that logs can be viewed in all cases.
Thanks to @sebmck for the help.
`./rome ci`
`./rome test`
`./rome test --no-suppress-logs`

feat(cli): add `suppressLogs` flag for `rome test`

---

website/src/styles/_sidebar.scss

The default padding on `button` elements isn't even on all sides, so it makes sense to remove it completely, since it looks like it was meant to be this way.
look at the website and verify the new alignment.
before|after
---|---

docs(theme): correctly align theme toggle switch

---

internal/compiler/lint/rules/jsx/noCommentText.test.md
internal/js-parser/parser/jsx.ts
internal/js-parser/test-fixtures/jsx/basic/10/input.test.md
internal/js-parser/test-fixtures/jsx/basic/empty-expression-container/input.test.md
internal/js-parser/test-fixtures/jsx/errors/attribute-empty-expression/input.test.md
internal/js-parser/test-fixtures/jsx/errors/unclosed-jsx-element/input.test.md

Rome parser does not properly handle the JSXEmptyExpresssion's position. So the comments in JSXExptyExpression attached in `trailingComments`. (But I think it should be in `innerComments`).
- test.jsx
```js
const Foo = () => {
return <>
{/* comment */}
</>
}
```
- AST (`rome parse test.jsx`)
```text
// ...
JSXExpressionContainer {
expression: JSXEmptyExpression {trailingComments: ["1"]}
}
//...
```
It's the reason why #1484 occured. The Formatter prints comment at the outside of JSXContainer (`{..}`). 
```
const Foo = () => {
return <>
{} /* comment */
</>;
};
```
There was already test case (wrong, but will be fixed in this PR). see [internal/compiler/lint/rules/jsx/noCommentText.test.md](https://github.com/rome/tools/blob/main/internal/compiler/lint/rules/jsx/noCommentText.test.md#4-form …

fix(js-parser): handle JSXEmptyExpression position

---

.gitblameignore

This is useful for ignoring commits like "Switch to hard tabs (https://github.com/rome/tools/pull/443)" which are almost never what you are looking for
```ignore
#
#
#
#
#
```

chore: add .gitblameignore file for ignore revisions from git blame

---

.rgignore

```
scripts/vendor/rome.cjs
scripts/vendor/rome.cjs.map
```
These two files show up in almost every search you could make in the rome repo. Adding them to `.rgignore` makes ripgrep (`rg`) ignore them when searching through files. ripgrep is also used by vscode so it cleans up the results you see there as well.
Search for something in vscode, you shouldn't find anything in these files.
Also note that you can toggle this button to turn the ignore files on/off.

chore: Add .rgignore file

---

internal/core/client/commands/init.ts
internal/core/common/file-handlers/index.ts
internal/core/server/commands/init.ts
internal/diagnostics/descriptions/files.ts

Fixes #1515 
There were few issues that I fixed here:
- the check on arguments is now dropped, because it's not needed;
- fixed the check `hasProject.data`;
- handled the case where the user inserts `0` as value for the tab size;
- add manually the project to the `ProjectManager`;
- changed the way the manifest of the project is retrieved. Before, we were interrogating the file system, although now we can't retrieve anymore from there (probably it changed recently). We now retrieve the manifest manually as we already have all the information we need;
- defaulting some values inside the `.editorconfig`. This fixes the case where we have empty a project with no files at all, Rome would create an empty file, which is not what we want. So, in case we don't have any extension, we set some …

fix(cli): init command

---

internal/cli/server.ts
internal/core/client/Client.ts
internal/core/server/commands/stop.ts
internal/resources/factories.ts

Closes #1528 
- Adds the socketServer as a resource so that it gets cleaned up when the server ends. 
- Adds a `safeProcessExit(0)` to the server stop command. (Is this the right approach?)
- Prevents a started daemon from inheriting stdio from the client.
Manually tested.
`./rome start`
```
ℹ No running daemon found. Starting one...
✔ Connected to daemon
✔ Started daemon!
```
`./rome stop`
```
✔ Connected to daemon
✔ Stopped server.
```
`./rome status`
```
✖ Server not running.
```

fix: exit server process when daemon is stopped

---

internal/core/common/constants.ts
scripts/dev-rome.cjs

This is an attempt to fix the socket path in dev-rome.cjs so that `./rome` commands can be run without rebuilding trunk if there's a running daemon. I haven't tested this on Windows. (I'll get setup for Windows testing at some point)
Manually tested on macOS.
` ./rome start`
```
Building trunk 
ℹ No running daemon found. Starting one...
✔ Connected to daemon
✔ Started daemon!
```
`./rome status`
```
!!!! A dev daemon is currently running. Skipping new build. !!!!
If you want to run new code and stop the daemon you can stop the daemon with:
$ ./rome stop
✔ Connected to daemon
{
projects: [{id: 0}, {id: 1}]
workers: [{astCacheSize: 0, heapTotal: 348_872_704, ownedBytes: 0n, ownedFileCount: 0, pid: 16_808, uptime: 6.303427065}]
server: {heapTotal: 348_872_704, pid: 16_808, uptime: …
```

fix(scripts): correct daemon socket path in dev-rome

---

internal/compiler/lib/VisitorState.ts

`getOptional` was throwing an error instead of returning `undefined`.
`./rome ci`

fix(compiler): correct return in getOptional

---

internal/core/server/bundler/BundleRequest.ts

Currently when bundling, the sourceMappingURL is incorrect because the bundle filename is hard-coded as 'index.js' but the sourceMappingURL is coming from the name of the entry file. This makes it harder for the debugger to find source maps.
As a temporary quick fix, is it reasonable to hard-code `index.js` here to match?

fix: match sourceMappingURL to bundler hard-coded output filename

---

internal/cli-flags/Parser.test.md
internal/cli-flags/Parser.test.ts
internal/cli-flags/Parser.ts
internal/cli-reporter/Reporter.ts
internal/string-utils/findClosesMatchingStrings.test.ts
internal/string-utils/findClosestMatchingStrings.ts
internal/string-utils/findClosestStringMatch.ts

This pr resolves #974. 
1. `rome chekc` suggests the following and the user can interactively select one
```
❯ Unknown command. Found matching commands: 
ℹ Use arrow keys and then enter to select an option
◉ check
◯ cache dir
◯ cache clear
```
2. `rome losg` suggests `rome logs` and the user can choose to execute `rome logs` or not
```
❯ Did you mean logs
ℹ Use arrow keys and then enter to select an option
◉ No (shortcut n)
◯ Yes (shortcut y)
```
3. throws error if it can't find a relevant match.
```
argv:1:9 flags/invalid  FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✖ Unknown command kjsahdaslkjdlkasjdlksajldjkaslkdjalskjda
dev-rome kjsahdaslkjdlkasjdlksajldjkaslkdjalskjda …
```

feat(cli): interactive yes/no and suggestion selection for cli commands

---

internal/diagnostics/DiagnosticsProcessor.ts

Diagnostic categories can be serialized over the bridge, so they should be compared by their contents not their identity. This was preventing the elimination filter in the LSP server from working.

fix(diagnostic): compare diagnostic filter category by contents

---

internal/core/server/ServerRequest.ts
internal/core/server/lsp/LSPServer.ts

Closes #1540 
There are still problems with the LSP server that I’ll follow up on in separate issues, but this addresses three bugs related to publishing diagnostics.
1. The LSP server only published diagnostics for AbsoluteFilePaths but was receiving UIDPath instances.
2. The LSP server was attempting to mutate an immutable DiagnosticsProcessor.
3. And then the tricky one:
The CheckRunner was adding diagnostics to its processor keyed by UIDPath. When a file changes, it should remove old diagnostics for that path because they’re about to be recomputed. But it was attempting that with an AbsoluteFilePath, which didn’t remove the UIDPath-keyed diagnostics. So diagnostics were accumulating for the lifetime of the CheckRunner, and if you fixed a problem in an open file in VS Code, the …

fix(lsp): publish diagnostics from LSP server

---

internal/project/constants.ts
internal/project/load.ts

This PR adds support for ignore files from `.eslintignore` and `.prettierignore` sources.
Manually checked on a project

feat(project): support ignore files for eslint and prettier

---

internal/core/common/IntegrationLoader.ts
internal/core/worker/integrations/eslint.ts
internal/core/worker/integrations/prettier.ts
internal/project/constants.ts
internal/project/integrations/loadEslint.ts
internal/project/integrations/loadPrettier.ts
internal/project/load.ts
internal/project/types.ts
website/src/_includes/docs/project-config.md

Part of #1570 
This PR does two things:
- adds few more options that can be passed to `eslint`;
- possibility to add these options via Rome's configuration file or via `.eslintrc.json`;
- extended the integration loader, by passing a typed `opts` object
Current CI

feat(integrations, project): new options for eslint integration

---

internal/core/server/commands/init.ts

Part of #1570 
Changes the `init` command, by disabling the `format` by default.
Current CI

chore: disable formatter by default

---

internal/compiler/lib/CompilerPath.ts
internal/compiler/lint/suppressions.ts
internal/core/client/review.ts
internal/numbers/indexed.ts

Closes #1579 
- Include `verboseAdvice` options when reviewing diagnostics
- Display the diagnostic that the user is being asked to review
- Fix `less` option so that it toggles back to original options
- Prevent injecting multiple duplicate suppression comments

fix: regressions in decisions and review command

---

internal/core/server/fs/MemoryFileSystem.ts

Closes #1437
Awaiting the `refreshFileEvent` push allows paths to be batched [in this subscription](https://github.com/rome/tools/blob/0c870f6fb6bf4f35033afabc4dbd44eeafdc2e97/internal/core/server/fs/glob.ts#L252) before this [promise](https://github.com/rome/tools/blob/0c870f6fb6bf4f35033afabc4dbd44eeafdc2e97/internal/core/server/fs/glob.ts#L283) resolves, preventing an initial checker run with zero paths.
Previously, the `newFileEvent` push had been awaited there. Was that await intentionally removed, or was that just a mistake?

fix: await refreshFileEvent when adding new files

---

internal/core/server/dependencies/DependencyGraph.ts

From node 15/16 is now possible to use the `node:` prefix to import node internals. For example `require("node:fs")` should now be accepted.
I am not sure if we should check also against the current node version where the application is running. 
UPDATE
Node check not needed, this feature has been added also to previous node versions:
> Added in: v14.13.1, v12.20.0
Manually checked

feat(core): add support for `node:` prefix for externals

---

internal/binary-transport/index.ts
internal/compiler/lint/rules/js/noUndeclaredVariables.test.md
internal/compiler/lint/rules/js/noUndeclaredVariables.test.toml
internal/compiler/lint/rules/js/noUndeclaredVariables.ts
internal/core/server/commands/config.ts
internal/core/worker/test/TestWorkerFile.ts
website/src/docs/lint/rules/js/noUndeclaredVariables.md

This is a hotfix to add `ReadonlyArray` to the list of variables to exclude from the rule. It's a temporary fix while we come up for a better solution to handle TS global interfaces.
Fixed some grammar too.
Added a new test

fix(lint): add to undeclered vars

---

internal/core/common/FatalErrorHandler.ts

The `unhandledRejection` listener is passed the rejected promise as the second argument, but the `FatalErrorHandler` handler has an optional `overrideSource?: StaticMarkup` as the second parameter.
This was causing a runtime TypeError when attempting to convert an unhandled rejection into a normalized diagnostic for printing:
```
TypeError: item is not iterable
at item (project-rome/@internal/markup/escape.ts:206:21)
at parseMarkup (project-rome/@internal/markup/parse.ts:444:10)
at normalizeMarkup (project-rome/@internal/markup/normalize.ts:212:2)
at diagnostics.normalizeMarkup (project-rome/@internal/diagnostics/DiagnosticsNormalizer.ts:307:10)
at diagnostics.normalizeDiagnostic (project-rome/@internal/diagnostics/DiagnosticsNormalizer.ts:521:22)
at normalizeDiagnostic …
```

fix(core): prevent TypeError when handling unhandledRejection

---

internal/core/server/lsp/LSPProgress.ts
internal/core/server/lsp/LSPServer.ts
internal/core/server/lsp/messages/general.ts
internal/core/server/lsp/messages/index.ts
internal/core/server/lsp/messages/textDocument.ts
internal/core/server/lsp/messages/types.ts
internal/core/server/lsp/messages/workspace.ts
internal/core/server/lsp/protocol.ts
internal/core/server/lsp/types.ts

This PR addresses a handful of issues related to the LSP Server. There are still some bugs and stability issues affecting LSP that I’ll continue to work though.
- Add `exit` notification handler to avoid accumulating `rome-cli` processes.
- Prevent sending messages from server until receiving `initialized` notification
- Partially fix handling of `workspace/didChangeWorkspaceFolders` notification. TODO: Bugs related to changing workspace folders. Will track separately.
- Allow tearing down project sessions if workspace changes while initial check watch is being performed.
- Fix labels on code actions and inserted suppression comments.
- Disable `$/progress` notifications for now because they have a significant performance impact. TODO: Fix this.
- Extract LSP message handlers into …

fix(lsp): improve LSP message handling

---

.github/workflows/autopublish.yml

Restricts the auto-publish workflow to 5 days a week.

chore(workflows): restrict days for autopublish

---

internal/core/client/commands/autoConfig.ts
internal/core/server/commands/autoConfig.ts

There were two `auto-config` queries to the server. They are unnecessary and the same job could be done with only one. I discussed this with @ematipico on Discord.

refactor(core): remove unnecessary auto-config double call

---

internal/core/server/checker/Checker.ts

Part of #1570 , this PR temporary disables the check of dependencies during `rome check`.
This is a temporary change and it will be turned on again under a flag in the next release, after we figure out what's the correct flow for users.
Existing CI

feat(core, lsp): disable dependency graph

---

internal/core/server/commands/lsp.ts
internal/core/server/fs/FileAllocator.ts
internal/core/server/lsp/LSPServer.ts
internal/core/server/lsp/messages/general.ts
internal/core/server/lsp/messages/textDocument.ts
internal/core/server/lsp/types.ts

This PR allows the LSP server to publish diagnostics for editor-synced `textDocument` paths without a dependence on `Checker#watch`, which has been a source of instability.
This temporarily restricts the LSP server to only operating on documents that are open in the editor. Later, project-wide checking through LSP can be restored when it can be made more stable.
This PR also prevents projects from being evicted/reloaded when a manifest is being modified unsaved in the editor. Saving a modified project manifest to disk can still cause the server to hang, which isn't addressed here.
Closes #1608

fix(lsp): lint without unstable project-wide check watching

---

internal/core/server/commands/config.ts

`rome config enable` and `rome config disable` commands were not correctly apply the change.
They were just applying a simple boolean.
Now it correctly change the `enabled` keyword, which is a standard key to enable/disable various features inside Rome.
Manually run the command on a different project

fix(cli): correctly apply disable/enable commands

---

internal/compiler/lib/CompilerPath.ts

The `ancestryPaths` array should be built with the [direct parent first](https://github.com/rome/tools/blob/86abd12e6ec6fc72c997407ee870c7abd9d8e810/internal/compiler/methods/reduce.ts#L251)

fix(compiler): build correct ancestryPaths in getChildPath

---

internal/core/client/commands/autoConfig.ts

Diagnostic categories were changed from strings to arrays, so the `category.asString()` was throwing a fatal error if there were any diagnostics when running the auto-config command:
```
unknown:18:20 parse(json)  FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✖ Expected a string at lint.diagnostics[0].description.category
```

fix(core): update category check in auto-config command

---

internal/core/server/Server.ts
internal/core/server/ServerRequest.ts
internal/core/server/fs/FileAllocator.ts
internal/core/server/fs/MemoryFileSystem.ts
internal/core/server/project/ProjectManager.ts

This allows the LSP server to handle `textDocument` sync notifications without crashing for files that aren't on disk (e.g. a file was deleted but is still open in VS Code).
This also closes #1165 by preventing symlinked files from crashing the server and allowing them to be formatted through LSP, but this doesn't add handling for symlinks in general.

fix(core): allow buffers for nonexistent files

---

.github/ISSUE_TEMPLATE/01_bug.yml

Version info is included in `rome rage --summary` so this dropdown is unnecessary, and not having any dev or nightly versions listed might make people think we don’t want them opening issues for those versions.

chore: remove version dropdown from bug issue template

---

website/src/_includes/docs/getting-started.md

Remove trailing `:`s from the headings in the getting started file.
They look weird on the sidebar:

docs(website): remove trailing punctuation from headings

---

internal/codec-config/retrieveConfigHandler.ts

The logic in the `retrieveConfigHandler` seemed messy and kinda weird.
This is a tiny change to use a `switch` statement instead, which will make it a bit nicer to add other config formats in the future.

refactor(codec-config): clean up `retrieveConfigHandler` implementation

---

internal/core/server/project/ProjectManager.ts
internal/diagnostics/descriptions/projectManager.ts
website/src/_includes/docs/getting-started.md
website/src/_includes/docs/project-config.md

Following [previous PR](https://github.com/rome/tools/pull/1655), this PR:
- updates the website by remove the mention of `.config` folder
- removes an old diagnostic from the `ProjectManager` that is not needed anymore
Current CI

fix(project): remove old diagnostic, not needed anymore

---

internal/core/worker/integrations/prettier.ts
internal/core/worker/workerLint.ts

This PR fixes a small bug inside the prettier integration, where we now pass the formatted content instead of reading the file from the file reference.
CI

fix(integrations): use formatted content instead of content from file

---

Cargo.lock
crates/formatter/Cargo.toml
crates/formatter/src/format_token.rs
crates/formatter/src/lib.rs
crates/formatter/src/printer.rs

Adds support for different line endings to the formatter's printer so that it emit's the users preferred line ending. 
Rome uses line feeds internally to push the complexity of having different line endings to the `Printer`, that then converts the line feeds to the user preferred ending.
Added a unit test.

feat(formatter): Support different line endings

---

crates/cli/examples/input.json
crates/formatter/src/format_json.rs

This PR fixes a small bug in printing a JSON where a trailing comma was added at the end of the last property.
Updated current tests

fix: trailing comma in JSON formatter

---

crates/formatter/src/format_json.rs

Adds support for formatting JSON arrays.
Added a unit test for the tokenization of JSON arrays.
Added an array to the `input.json` and ran `cargo run --example run_cli format .\crates\cli\examples\input.json`. It properly formatted the array.
Creating integration tests is something else I'm investigating but shouldn't block this PR.

feat(formatter): Format JSON Arrays

---

.cargo/config.toml
crates/cli/tests/main.rs
crates/formatter/src/format_token.rs
crates/formatter/src/format_token_macro.rs
crates/formatter/src/format_tokens_macro.rs
crates/formatter/src/lib.rs
crates/formatter/src/printer.rs

This PR implements a `format_tokens` declarative macro. The name of the macro is still up in the air and needs to be consolidated because we have APIs that have similar names.
For example, we have the API called `format_token` (singular) which is the main function exposed by the `rome_formatter` crate. 
I think we can consolidate the name of the APIs later, once this crate becomes more stable.
I created documentation and doc test, which helped to unveil some bug around some struct that were not exposed by default.
I created an alias called `cargo lint` which basically runs `cargo clippy` with all the arguments we have in the CI. This should help the local development.
```
cargo test
cargo doc
cargo lint
```

feat: format macro

---

Cargo.lock
crates/formatter/Cargo.toml
crates/formatter/src/format_json.rs
crates/formatter/src/format_tokens_macro.rs
crates/formatter/src/lib.rs
crates/formatter/src/printer.rs
crates/formatter/tests/specs/json/int1.expected.json

A hacky implementation that uses the rs-lint parser to parse a JSON string to a CST.
Our current JSON parser uses serde for parsing, which works well enough but isn't lossless. For example, the parsing doesn't retain the exact number formats. We also want to get more experience working with CST's and do profiling which requires us to work with a CST. 
That's why this PR swaps the serde parser with the rslint JavaScript parser. Using a JS parser isn't ideal because it parses files that are valid JS but not JSON. I believe that's OK for now to have something to play around with CST and figure out multi-language support until we build our own JSON parser. 
Tests are still passing. Parsed and formatted a large (+10 MB) JSON file

Parse JSON to CST

---

Cargo.lock
crates/tests_macros/Cargo.toml
crates/tests_macros/Readme.md
crates/tests_macros/src/lib.rs

Automatically generate unit tests from files. 
First argument: glob that will passed to https://github.com/gilnaa/globwalk. Crate's cargo.toml will be the base directory.  
Second argument: method that will be called.
```rust
tests_macros::gen_tests!{"tests/*", run_test}
fn run_test<S: AsRef<str> + std::fmt::Debug>(a: S, b: S) {
println!("{:?} {:?}", a, b);
}
```
this will generate the following for each file:
Test name is the "snake case" version of the file name.
```rust
#[test]
pub fn sometest()
{
let test_file = "<SOMEDIR>/tests/sometest.txt";
let test_expected_file = "<SOMEDIR>/tests/sometest.expected.txt";
run_test(test_file, test_expected_file);
}
```

feat: macro to automatically generate expected/snapshot tests from files

---

crates/formatter/src/formatter.rs
crates/rome_rowan/src/api.rs
crates/rome_rowan/src/cursor.rs
crates/rome_rowan/src/green.rs
crates/rome_rowan/src/green/element.rs
crates/rome_rowan/src/green/node.rs
crates/rome_rowan/src/green/token.rs
crates/rome_rowan/src/lib.rs
crates/rome_rowan/src/syntax_text.rs
crates/rome_rowan/src/tree_builder.rs
crates/rslint_parser/src/ast/stmt_ext.rs
crates/rslint_parser/src/lossless_tree_sink.rs
crates/rslint_parser/src/lossy_tree_sink.rs
crates/rslint_parser/src/parse.rs
crates/rslint_parser/src/parser.rs
crates/rslint_parser/src/syntax_node.rs

Changes the visibility of the `Green*` and `cursor::Syntax*` types to `pub(crate)` from previously `pub`. 
The motivation behind changing the visibility is that the `Green*` types are an internal optimisation of our CST to reduce memory usage by reusing identical nodes and tokens. The cursor types are also just internal representations that help navigate through a tree and is used by the public `Syntax*` types.
This PR has to remove the `replace_with` methods for now as they used to operate on `GreenNode`s. We should revisit the exact signature and behaviour when working on the mutation API. I may even suggest that the functionality should be super limited because mutating with `SyntaxNode`s directly voids all guarantees that the mutations will form a valid CST tree. Ideally, mutations …

Change the visibility of green nodes to internal

---

crates/rslint_lexer/src/lib.rs
crates/rslint_lexer/src/tests.rs
crates/rslint_parser/src/ast/stmt_ext.rs
crates/rslint_parser/test_data/inline/err/binding_identifier_invalid.rast
crates/rslint_parser/test_data/inline/err/export_decl_not_top_level.rast
crates/rslint_parser/test_data/inline/err/import_decl_not_top_level.rast
crates/rslint_parser/test_data/inline/err/invalid_method_recover.rast
crates/rslint_parser/test_data/inline/err/method_getter_err.rast
crates/rslint_parser/test_data/inline/ok/async_method.rast
crates/rslint_parser/test_data/inline/ok/class_expr.rast
crates/rslint_parser/test_data/inline/ok/continue_stmt.rast
crates/rslint_parser/test_data/inline/ok/function_decl.rast
crates/rslint_parser/test_data/inline/ok/method_getter.rast
crates/rslint_parser/test_data/inline/ok/method_setter.rast
crates/rslint_parser/test_data/inline/ok/object_expr_async_method.rast
crates/rslint_parser/test_data/inline/ok/object_expr_getter_setter.rast
crates/rslint_parser/test_data/inline/ok/object_expr_getter_setter_computed.rast
crates/rslint_parser/test_data/inline/ok/object_expr_method.rast
crates/rslint_parser/test_data/inline/ok/return_stmt.rast
crates/rslint_parser/test_data/inline/ok/static_method.rast
crates/rslint_parser/test_data/inline/ok/switch_stmt.rast
crates/rslint_parser/test_data/inline/ok/yield_expr.rast

Fixing lexer breaking newline. Now newline is always in the leading trivia.
```rust
> cargo test -p rslint_lexer
> cargo test -p rslint_parser
> cargo xtask coverage
```
Coverage has not improved.

Lexer trivia newline

---

crates/rslint_parser/src/ast.rs
crates/rslint_parser/src/ast/expr_ext.rs
crates/rslint_parser/src/ast/generated/nodes.rs
crates/rslint_parser/src/lib.rs
crates/rslint_parser/src/syntax/util.rs
xtask/js.ungram
xtask/src/codegen/ast.rs
xtask/src/codegen/generate_nodes.rs
xtask/src/codegen/kinds_src.rs

Implements an AST view for lists that contain nodes separated by tokens, for example an array expression where the elements are separated by commas. 
The PR introduces the new `AstSeparatedList`, changes the code gen to recognise the `T (',' T)* ','?` and `T (',' T)*` patterns, and uses the new separated list in the js grammar. 
The PR doesn't  use the new list yet for:
* arrays because this would require defining a new `JsArrayHole` type as well. 
* Import clauses, because not all of them must be separated by a ','
We can address these issues when changing our Ast Facade.
Part of #1725 
Passing / failing / panics stay the same
```
┌───────────┬────────┬────────┬────────┬──────────┐
│ Tests ran │ Passed │ Failed │ Panics │ Coverage │
├───────────┼────────┼────────┼────────┼──────────┤
│ …
```

AST Separated List

---

xtask/src/codegen/ast.rs

Changes the syntax codegen to respect the label for single tokens, for example, `optional: '?.'` and to create a single field for an optional token union, for example, `operator: ('a' | 'b')?`
Part of #1725 
Ran the codegen on the grammar proposed in #1719 and the codegen correctly generated the union types & and no longer failed on the `?.` token.

feat(codegen): Respect label for tokens & support optional token unions

---

.github/workflows/ci.yml

This PR adds Windows and macOS operative systems to the CI, in particular when we run the coverage for `test262` 
Current CI

ci: add windows and macos on coverage test

---

crates/rslint_parser/src/ast/generated/nodes.rs
xtask/js.ungram
xtask/src/codegen/ast.rs
xtask/src/codegen/generate_nodes.rs
xtask/src/codegen/kinds_src.rs

Part of https://github.com/rome/tools/issues/1725
Closes https://github.com/rome/tools/issues/1733
This PR improves the codegen by forcing to use labels when writing ungrammar.
```
cargo test
cargo check
cargo lint
```

feat: strip prefix from methods in code generation

---

crates/rome_rowan/src/api.rs
crates/rome_rowan/src/cursor.rs
crates/rome_rowan/src/green.rs
crates/rome_rowan/src/green/element.rs
crates/rome_rowan/src/green/node.rs
crates/rome_rowan/src/green/node_cache.rs
crates/rome_rowan/src/tree_builder.rs

Our goal is to use fixed offsets to get a specific child instead of iterating and trying to match the child by its type. 
This PR extends the rowan `*Node` types to support empty slots, a slot for a child that wasn't present in the tree either because it's an optional child or because of a syntax error. 
The proposed implementation renames the `GreenChild` enum to `Slot` and adds an `Empty` variant. This isn't the most space-efficient representation if nodes have many optional children / sparse nodes (requires 16 bytes for every empty slot). But I believe it's sufficient for now and we can research more efficient sparse array data structures in the future if this turns out to be a problem measuring with real-world programs. 
Part of #1724 
Added new tests for siblings and children. Ran …

Add support for empty slots to nodes

---

crates/rome_rowan/src/api.rs
crates/rome_rowan/src/cursor.rs
crates/rslint_parser/src/event.rs
crates/rslint_parser/src/lib.rs
crates/rslint_parser/src/lossless_tree_sink.rs
crates/rslint_parser/src/lossy_tree_sink.rs
crates/rslint_parser/src/parser.rs
crates/rslint_parser/src/tests.rs

Changes the parser to generate a `missing` event if it expected a specific token that isn't present in the source code. Tracking the missing children of a node is required to implement fixed offsets for children. 
It's probably best to only review the second commit as the first commit is part of #1761 
Part of #1724 
Verified that coverage isn't changing.

Parser: Create empty slots for expected tokens

---

crates/rome_rowan/src/api.rs
crates/rome_rowan/src/cursor.rs

Calling `siblings_with_tokens` should return the siblings but not the node/token itself on which the method is called.
This is also ensures that `siblings_with_tokens` matches the behavior of `next_sibling_or_token` and `prev_sibling_or_token` so that `n.next_sibling_or_token() == n.siblings_with_tokens(Direction::Next).next()`
This PR changes the `siblings_with_tokens` impl to return the first element before/after the node the method is called on
I added a test verifying the behaviour.

fix(rome_rowan): Ensure `siblings_with_tokens` skip start node

---

Cargo.lock
crates/rome_rowan/Cargo.toml
crates/rome_rowan/src/api.rs
crates/rome_rowan/src/cursor.rs
crates/rome_rowan/src/green/node_cache.rs
crates/rome_rowan/src/green/token.rs
crates/rome_rowan/src/lib.rs
crates/rome_rowan/src/serde_impls.rs
crates/rome_rowan/src/syntax_text.rs
crates/rome_rowan/src/tree_builder.rs

part of: #1720
Improved changes of #1738
- Now the GreenToken "slice" contains all its trivia.
- To trim this trivia we have to ask leading().text_len() and trailing().text_len() and compute where the token text actually is.
- Given that ```GreenToken``` already has its trivia, we ignore the trivia when hashing and caching. Advantage: faster; Disadvantage: dangerous. At least in theory, two equal strings can come from two different parsers and end up with two different trivia.
- GreenToken now is 32 bytes bigger (16 bytes for each trivia). Hard to improve here because ```Box<>``` wants to be aligned.
```rust
pub enum GreenTokenTrivia {
None,
One(Trivia),
Many(Box<Vec<Trivia>>),
}
print-type-size type: `GreenTokenTrivia`: 16 bytes, alignment: 8 bytes
print-type-size     discriminant: 8 …
```

trivia attached to GreenTokens

---

.github/workflows/test262.yml
crates/rslint_parser/src/parser.rs
crates/rslint_parser/src/syntax/decl.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/src/syntax/pat.rs
crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/src/syntax/typescript.rs
xtask/src/compare/mod.rs
xtask/src/compare/results.rs
xtask/src/coverage/files.rs
xtask/src/coverage/mod.rs
xtask/src/main.rs

First PR that implements #1759 
This change is very simple, every time we need to mark error inside the tree, we explicitly pass the `SyntaxKind::ERROR` as parameter instead of having it hardcoded. 
This change will make things much easier and smoother when applying specific errors during the parsing phase.
Existing CI

feat: pass error kind via parameter

---

.github/workflows/test262.yml

Removes macos-latest from OS's for test262 coverage workflow. Now it targets only ubuntu-latest and windows-latest.
Closes #1792.

fix: remove macos from test262 coverage workflow

---

.github/workflows/test262.yml

Noticed another bug introduced by https://github.com/rome/tools/pull/1795, we need to add the `${{ matrix.os }}` inside `body-includes`so the CI can update the correct message, related to the correct OS.
Current CI

ci: add matrix.os to body inlcudes

---

crates/rome_rowan/src/api.rs
crates/rome_rowan/src/cursor.rs
crates/rome_rowan/src/green/node_cache.rs
crates/rome_rowan/src/green/token.rs
crates/rome_rowan/src/lib.rs
crates/rome_rowan/src/tree_builder.rs

part of: #1720
Improved changes of #1738
```rust
> cargo test -p rome_rowan
> cargo xtask coverage
```
```rust
#[test]
pub fn syntax_trivia_pieces() {
use crate::*;
let node = TreeBuilder::<RawLanguage>::wrap_with_node(SyntaxKind(0),|builder| {
builder.token_with_trivia(
SyntaxKind(1),
"\n\t /**/let \t\t",
vec![Trivia::Whitespace(3), Trivia::Comments(4)],
vec![Trivia::Whitespace(3)],
);
});
let pieces: Vec<_> = node.first_leading_trivia().unwrap().pieces().collect();
assert_eq!(2, pieces.len());
assert_eq!("\n\t ", pieces[0].text());
assert_eq!(TextSize::from(3), pieces[0].text_len());
assert_eq!(TextRange::new(0.into(), 3.into()), pieces[0].text_range());
assert!(pieces[0].as_whitespace().is_some());
assert_eq!("/**/", pieces[1].text());
assert_eq!(TextSize::from(4), …
```

typed api access to each piece of the trivia

---

Cargo.lock
crates/rslint_parser/Cargo.toml
crates/rslint_parser/src/parser.rs
crates/rslint_parser/src/syntax/class.rs
crates/rslint_parser/src/syntax/decl.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/src/syntax/object.rs
crates/rslint_parser/src/syntax/pat.rs
crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/src/syntax/typescript.rs
crates/rslint_parser/src/tests.rs
crates/rslint_parser/test_data/inline/err/block_stmt_in_class.rast
crates/rslint_parser/test_data/inline/err/class_decl_err.rast
crates/rslint_parser/test_data/inline/err/object_expr_error_prop_name.rast

This PR adds a drop bomb to the Parser's `Marker` implementation to ensure we always call either `abandon` or `complete` on every marker. 
I was stunned to see that the parser is able to produce a valid tree even with nodes in the tree that were never completed, and, therefore, don't have a `SyntaxKind` set. 
The reason why this works is that the parser sets the kind to `TOMBSTONE` when starting a new node and these get skipped when building the final tree. The problem is, skipped means the children of the `TOMBSTONE`d node get attached to the parent. 
This "bubbling up" of children is problematic, because let's say we have a node that calls into `expr`. The expectation would be that `expr` either produces a `UnknownExpression` or doesn't add any nodes to the parse tree. However, this …

Implement Drop for Marker

---

Cargo.lock
xtask/Cargo.toml
xtask/src/lib.rs
xtask/src/libs/libs.txt
xtask/src/libs/mod.rs
xtask/src/main.rs

The current version is as simple as possible. Download and parse every file at ```xtask\src\libs\libs.txt```. If the file is already downloaded, just use the cache, which is at ```target``` folder.
Currently we can't parse ```jquery``` and ```vue```. The only two examples I pre-selected.
```
cargo xtask  coverage-libs
Compiling xtask v0.0.0 (C:\github\rome\tools\xtask)
Finished dev [unoptimized + debuginfo] target(s) in 3.17s
Running `target\debug\xtask.exe coverage-libs`
jquery.min.js - using target\jquery.min.js
thread 'main' panicked at 'Marker must either be `completed` or `abandoned` to avoid that children are implicitly attached to a markers parent.', C:\Users\xunil\.cargo\registry\src\github.com-1ecc6299db9ec823\drop_bomb-0.1.5\src\lib.rs:113:13
note: run with `RUST_BACKTRACE=1` …
```

xtask to download and parse js libs

---

Cargo.lock
crates/rslint_parser/src/syntax/typescript.rs
xtask/Cargo.toml
xtask/src/libs/libs.txt
xtask/src/libs/mod.rs
xtask/src/main.rs

Some files were panicking because ```Marker```s were being dropped without being abandoned/completed. We may have more bombs lurking. I fixed only those necessary to make all the libs below to be parsed.
We may also discuss what we want to do with this new ```xtask```.
I prefer to run as ```--release``` so files are parsed faster.
```
>cargo run -p xtask --release -- coverage-libs                                 
Finished release [optimized] target(s) in 45.25s
Running `target\release\xtask.exe coverage-libs`
[jquery.min.js] - using [target\jquery.min.js]
tokenizer took 3.5149ms
parser took 135.0601ms
tree sink took 8.1032ms
total: 149.6376ms
[vue.global.prod.js] - using [target\vue.global.prod.js]
tokenizer took 7.5291ms
parser took 381.4876ms
tree sink took 16.3364ms
total: 411.0224ms …
```

fixing parser marker bombs for some js libs

---

.github/workflows/main.yml
.github/workflows/pul_request.yml
.github/workflows/test262.yml

This PR puts some order to our workflows:
- `pull_request.yml` is the workflow where we run on pull requests. This is where we might have some bot that does some fancy stuff, like the coverage;
- `main.yml` is the workflow that we trigger when something is pushed on `main` branch. It does usual checks like in the PR. It also run the coverage and prints it in the command line (different behaviour from the PR workflow). This will also set the foundation for other jobs that we want to run only in certain occasions, specifically those jobs that take long time;
- `test262.yml` stays the same that runs on pull requests only. I plan to merge it into `pull_request.yml` but only when I figure out a wait to save artifacts between workflows
Current CI

ci: split workflows for PRs and `main` branch

---

crates/rslint_parser/src/syntax/decl.rs
crates/rslint_parser/src/syntax/pat.rs
crates/rslint_parser/test_data/inline/err/formal_params_invalid.rast
crates/rslint_parser/test_data/inline/err/formal_params_no_binding_element.rast
crates/rslint_parser/test_data/inline/err/object_expr_setter.rast
crates/rslint_parser/test_data/inline/err/paren_or_arrow_expr_invalid_params.rast
crates/rslint_parser/test_data/inline/err/setter_class_member.rast

#1829 introduced a bug where the parser now is recursing forever for some libraries like `Vue`.
The problem seems to be from the change from `SingleTokenParseRecovery` in `pat` to use `ParseRecovery` instead. However, this change is necessary because parameter lists may otherwise contain two elements that are not separated by a comma.
This PR adds a somewhat hacky fix since I'm rewriting `patterns` anyway. It reverts `pat` to use `SingleTokenParseRecovery` but takes a snapshot in `parse_formal_param_pat` and rewinds if `pattern` returned `None`.
This fixes most recursing forever issues. There are still some more but they aren't specific to #1829

fix(rslint_parser): some recursing forever

---

crates/rslint_parser/src/syntax/class.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/src/syntax/js_parse_error.rs
crates/rslint_parser/src/syntax/object.rs
crates/rslint_parser/src/syntax/pat.rs
crates/rslint_parser/src/syntax/program.rs
crates/rslint_parser/test_data/inline/err/assert_expression.js
crates/rslint_parser/test_data/inline/err/assert_expression.rast

This PR refactors the method `object_expr` to use the new `ParsedSyntax`:
- renamed the method  to `parse_object_expression`
- added error handling
- added new test
- renamed functions inside `object.rs` with prefix `parse_*`
Current CI

refactor: parse object expression

---

crates/rslint_parser/src/parser.rs
crates/rslint_parser/src/syntax/assignment_target.rs
crates/rslint_parser/src/syntax/class.rs
crates/rslint_parser/src/syntax/decl.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/src/syntax/object.rs
crates/rslint_parser/src/syntax/pat.rs
crates/rslint_parser/src/syntax/program.rs
crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/src/syntax/typescript.rs

RSLint used an `oferflow_check` inside of the parser that verified if the parser did less than 50 000 000 steps to parse the current file and otherwise panics, saying that the parser is recursing forever. 
The nicety about this approach is that it doesn't require explicit checks during parsing. However, it has a few downsides:
* It panics for very large file 
* Overflow checks are only necessary in while loops
* The panic happens anytime, but not necessarily in the loop that stopped progressing and the parser goes on and on for a long time until it reached the step limit
This PR introduces a `ParseProgress` struct that allows asserting whatever the parser is making progress. This new struct must be used in every `while` loop. 
This gives us nice stack traces:
```
Parser
thread 'main' …
```

Parser Progressing Assertion

---

crates/rslint_parser/src/lossless_tree_sink.rs
crates/rslint_parser/src/lossy_tree_sink.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/test_data/inline/ok/binary_expressions.js
crates/rslint_parser/test_data/inline/ok/binary_expressions.rast

The parser allows grouping multiple lexer-tokens into a single "parsed" token using `bump_multiple`. However, this path wasn't yet updated to account for leading/trailing trivia.
This PR ensures that trivia is also handled for the multiple token case by unifying the `do_token` implementation.
Fixes #1842
Added a new test case for bin op.

fix(rslint_parser): Fix parsing of multiple tokens

---

crates/rslint_parser/src/parser.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/src/syntax/typescript.rs
crates/rslint_parser/src/token_source.rs
xtask/src/libs/mod.rs

@xunilrj analysis showed that cloning the whole parser considerably reduces the parsing performance. 
The two places where we cloned the parser now have been in
`try_parse_ts` and inside `paren_or_arrow_expr`. 
* `try_parse_ts`: `rewind` used to panic but it seems that the bindings refactoring removed the code that caused the panic. It's now safe to use `rewind`.
* `paren_or_arrow_expr`: No idea what that code was doing. Removing it doesn't regress coverage, nor any test. I also compared the errors when parsing the libraries and there's no difference as well. Let's re-add it when we now what it is used for (with proper tests and such)
Some parse time goodies
* `vue.global.prod`: From 291ms to 12.4ms
* `react.production`: From 754us to 355us
* `dojo`: From 12ms to 2ms
* `d3.min` from 3s to …

performance: Remove cloning of parser

---

crates/rslint_parser/src/parser.rs
crates/rslint_parser/src/parser/parsed_syntax.rs
crates/rslint_parser/src/syntax/assignment_target.rs
crates/rslint_parser/src/syntax/binding.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/src/syntax/function.rs
crates/rslint_parser/src/syntax/pattern.rs
crates/rslint_parser/test_data/inline/err/binding_identifier_invalid.rast
crates/rslint_parser/test_data/inline/err/break_stmt.rast
crates/rslint_parser/test_data/inline/err/continue_stmt.rast
crates/rslint_parser/test_data/inline/err/debugger_stmt.rast
crates/rslint_parser/test_data/inline/err/directives_err.rast
crates/rslint_parser/test_data/inline/err/formal_params_invalid.rast
crates/rslint_parser/test_data/inline/err/formal_params_no_binding_element.rast
crates/rslint_parser/test_data/inline/err/function_broken.rast
crates/rslint_parser/test_data/inline/err/function_decl_err.rast
crates/rslint_parser/test_data/inline/err/identifier_err.rast
crates/rslint_parser/test_data/inline/err/rest_property_binding_err.rast
crates/rslint_parser/test_data/inline/ok/async_function_expr.rast
crates/rslint_parser/test_data/inline/ok/await_expression.rast
crates/rslint_parser/test_data/inline/ok/directives.rast
crates/rslint_parser/test_data/inline/ok/function_decl.rast
crates/rslint_parser/test_data/inline/ok/function_declaration_script.rast
crates/rslint_parser/test_data/inline/ok/function_expr.rast
crates/rslint_parser/test_data/inline/ok/parameter_list.rast
crates/rslint_parser/test_data/inline/ok/semicolons.rast
crates/rslint_parser/test_data/inline/ok/with_statement.rast
crates/rslint_parser/test_data/inline/ok/yield_expr.rast

`ParsedSyntax<ConditionalSyntax>` currently offered no helpers to mark the result as missing and adding an error. This resulted in quite some cumbersome code.
This PR adds the `or_missing` and `or_missing_with_error` helpers and uses the new helpers on the call sites.
This PR also renames `InvalidParsedSyntax` to `InvalidSyntax` to align it with `ConditionalSyntax`
The tests output changes because it now adds the "missing" markers for parameter types and return types.

`or_missing*` helpers for `ParsedSyntax<ConditionalSyntax>`

---

crates/rome_rowan/src/api.rs

This PR adds text-related methods for `SyntaxTriviaPieceWhitespace` and `SyntaxTriviaPieceComments` that delegate to the inner `SyntaxTriviaPiece`

feat: add text methods for syntax trivia piece wrappers

---

crates/rslint_parser/src/lib.rs
crates/rslint_parser/src/syntax/class.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/test_data/inline/ok/dot_expr.js
crates/rslint_parser/test_data/inline/ok/dot_expr.rast

Class fields have been standardised. Let's remove the syntax error.
This PR further removes the `decorators` flag because we don't support decorators.
We'll likely need to redo this (especially file kind). For example, TypeScript is a dialect that supports script or module.
Added a static member expression test

Enable class field support

---

crates/rome_rowan/src/api.rs
crates/rome_rowan/src/cursor.rs
crates/rslint_parser/src/ast.rs
crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/src/tests.rs
crates/rslint_parser/test_data/inline/err/export_decl_not_top_level.rast
crates/rslint_parser/test_data/inline/err/import_decl_not_top_level.rast

The node list had to gracefully handle the case where a list could contain trivia nodes or errors.
This is no longer needed because trivia is now stored inside of tokens and (most) error nodes have been replaced with `Unknown*` nodes that can be casted to `N`. That's why this PR removes the workarounds

chor(rslint_parser): Remove list workarounds for trivia/error nodes

---

crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/test_data/inline/ok/for_stmt.js
crates/rslint_parser/test_data/inline/ok/for_stmt.rast

Remap the `of` identifier to the `of` keyword if used inside an `for(.. of ..)` loop (and it isn't a variable name).
Fixes #1862
Added a new test case verifying that the `of` keyword gets remapped correctly

fix(rslint_parser): Remap `of` keyword in `for` of loops

---

crates/rome_rowan/LICENSE-APACHE
crates/rome_rowan/LICENSE-MIT
crates/rslint_errors/LICENSE
crates/rslint_lexer/LICENSE
crates/rslint_parser/LICENSE
crates/rslint_regex/LICENSE
crates/rslint_syntax/LICENSE
crates/rslint_text_edit/LICENSE

When we locally copied the code from `rowan` and `rslint`, we forgot to copy over their licenses.
This PR:
- adds the license files of the [`rowan` repo](https://github.com/rust-analyzer/rowan) (they are two);
- adds the [license file of `rslint` project](https://github.com/rslint/rslint/blob/master/LICENSE); the same very file was copied inside the internal forks that we intentionally selected;
None

chore: add license for internal forks

---

xtask/src/coverage/files.rs

closes #1891
It's safe to enable all test262 tests, we aim to pass them all 🏆 
```
cargo run -p xtask --release -- coverage
```

test(xtask): Enable all test262 tests for parser coverage

---

crates/rslint_parser/src/ast.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/src/syntax/typescript.rs
crates/rslint_parser/test_data/inline/err/binding_identifier_invalid.rast
crates/rslint_parser/test_data/inline/err/function_decl_err.rast
crates/rslint_parser/test_data/inline/err/identifier.rast
crates/rslint_parser/test_data/inline/err/identifier_err.js
crates/rslint_parser/test_data/inline/err/identifier_err.rast
crates/rslint_parser/test_data/inline/ok/ts_keyword_assignments.js
crates/rslint_parser/test_data/inline/ok/ts_keyword_assignments.rast
crates/rslint_parser/test_data/inline/ok/ts_keywords_assignments_script.js
crates/rslint_parser/test_data/inline/ok/ts_keywords_assignments_script.rast

declare, abstract, namespace, type, enum, module, global, interface, private, protected, and public are typescript keywords but valid identifiers in JS.
This PR removes the TS parsing logic for now and ensures these identifiers are correctly parsed.
`compiler.js` no longer reports any errors.

fix(rslint_parser): Fix parsing of TS keywords

---

crates/rslint_parser/src/syntax/assignment.rs
crates/rslint_parser/src/syntax/pattern.rs
crates/rslint_parser/test_data/inline/err/array_assignment_target_err.rast
crates/rslint_parser/test_data/inline/ok/array_or_object_member_assignment.js
crates/rslint_parser/test_data/inline/ok/array_or_object_member_assignment.rast

The tests added in #1893 revealed that our parser incorrectly parses the inner assignment target (`[1, 2][0]`) in `[[1,2][0] = 42] = [23]` as an array assignment target instead of a computed member expression. The same is true when using an object as the left-hand side of a member expression inside an assignment pattern.
This diff fixes this by first parsing the expression and only converting it to an assignment if it is an `array` or `object` expression

Fix assignment to array or object expression members

---

crates/rslint_parser/src/ast/generated/nodes.rs
crates/rslint_parser/src/ast/generated/syntax_factory.rs
crates/rslint_parser/src/syntax/assignment.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/src/syntax/object.rs
crates/rslint_parser/test_data/inline/err/property_assignment_target_err.rast
crates/rslint_parser/test_data/inline/ok/array_or_object_member_assignment.rast
crates/rslint_parser/test_data/inline/ok/assign_expr.rast
crates/rslint_parser/test_data/inline/ok/object_assignment_target.rast
crates/rslint_parser/test_data/inline/ok/property_assignment_target.js
crates/rslint_parser/test_data/inline/ok/property_assignment_target.rast
crates/rslint_parser/test_data/inline/ok/rest_property_assignment_target.rast
xtask/js.ungram

Object assignment patterns allow for any valid member name. RSlint's grammar defines that correctly for bindings but not for assignment targets.
This PR changes the definition of `JsObjectAssignmentPatternProperty` to allow any valid member name and fixes the parsing.
Added new tests covering computed and literal member names.

fix(rslint_parser): Fix object assignment property to allow for non identifier member names

---

Cargo.lock
xtask/Cargo.toml
xtask/src/libs/mod.rs
xtask/src/main.rs

How to run
```
cargo run -p xtask --release -- coverage-libs --filter=jquery
```
Result
```
[jquery.min.js] - using [target/jquery.min.js]
Gnuplot not found, using plotters backend
Benchmarking https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js
Benchmarking https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js: Warming up for 3.0000 s
Benchmarking https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js: Collecting 100 samples in estimated 6.1669 s (500 iterations)
Benchmarking https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js: Analyzing
https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js
time:   [11.744 ms 11.977 ms 12.241 ms]
change: [-2.3855% -0.0651% +2.6054%] (p = 0.97 > 0.05)
No change in performance detected.
Found 3 outliers among 100 …
```

xtask coverage-libs using criterion to better assess performance

---

crates/rslint_parser/src/syntax/module.rs
crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/test_data/inline/err/break_stmt.js
crates/rslint_parser/test_data/inline/err/break_stmt.rast
crates/rslint_parser/test_data/inline/err/continue_stmt.js
crates/rslint_parser/test_data/inline/err/continue_stmt.rast
crates/rslint_parser/test_data/inline/err/import_assertion_err.rast
crates/rslint_parser/test_data/inline/ok/break_stmt.js
crates/rslint_parser/test_data/inline/ok/break_stmt.rast
crates/rslint_parser/test_data/inline/ok/continue_stmt.js
crates/rslint_parser/test_data/inline/ok/continue_stmt.rast
crates/rslint_parser/test_data/inline/ok/labeled_statement.js
crates/rslint_parser/test_data/inline/ok/labeled_statement.rast
crates/rslint_parser/test_data/inline/ok/scoped_declarations.js
crates/rslint_parser/test_data/inline/ok/scoped_declarations.rast
xtask/src/libs/mod.rs

This PR fixes the remaining diagnostic when parsing the `coverage-libs` libs.
The parser tracked all defined labels but never removed them when leaving the labeled statement. That's why the parser reported diagnostics for eligibly duplicated label declarations if any label was re-used anywhere in the program
```js
a: {
a: {} // not ok
}
a: {} // ok
```
The parser generates diagnostics if a `let` or `const` declaration defines the same identifier twice. However, re-declaring the same identifier inside of the initializer is totally fine:
```js
let a = () => { let a = 10; } // this is ok
let a, a; // this isn't
```
Parse the libs with `script` to avoid the warning that the `use strict` directive is redundant.
This seems to slightly improve perf (a few ms, up to 10ms). My guess is that this …

fix(rslint_parser): libs parse diagnostics

---

xtask/src/compare/results.rs

On PowerShell the default behavior for pipes it to output an UTF-16 encoded file, so `cargo xtask coverage --json > results.json` will create a file that can't be decoded directly by `cargo xtask compare` since serde_json and Rust in general assumes an UTF-8 encoding.
This adds a simple encoding detection logic to the loading of test results file that detects (and skips over) Unicode Byte Order Mark, and re-encodes UTF-16 content into UTF-8 before handing it to serde_json

feature(xtask): add encoding detection to compare

---

crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/test_data/inline/err/for_in_and_of_initializer_loose_mode.js
crates/rslint_parser/test_data/inline/err/for_in_and_of_initializer_loose_mode.rast
crates/rslint_parser/test_data/inline/err/for_in_and_of_initializer_strict_mode.js
crates/rslint_parser/test_data/inline/err/for_in_and_of_initializer_strict_mode.rast
crates/rslint_parser/test_data/inline/ok/for_in_initializer_loose_mode.js
crates/rslint_parser/test_data/inline/ok/for_in_initializer_loose_mode.rast

~`for..in` and `for..of` loops declarators are not allowed to have an initializer in strict mode except in `for(var ... in ...)` statements~
Edit: While writing the test cases I realized my wording was wrong (although the code is correct): initializers are never allowed in strict mode, and loose mode only allows `for(var ... in ...)` but none of the others

feat(rslint_parser): add an error diagnostic to for loops initializer

---

crates/rslint_parser/src/ast/stmt_ext.rs

Fixes `JsVariableDeclarations::is_var`. Looks like just a copy/paste mistake.

fix(rslint_parser): fix JsVariableDeclarations is_var method

---

crates/rslint_lexer/src/lib.rs

This PR adds the d flag to regex, explanation of the d flag can be found here:
https://github.com/tc39/proposal-regexp-match-indices#why-use-d-for-the-regexp-flag
Local run:
| Test result | `main` count | This PR count | Difference |
| :---------: | :----------: | :-----------: | :--------: |
| Total | 44951 | 44951 | 0 |
| Passed | 42892 | 42907 | ✅ ⏫ **+15** |
| Failed | 2058 | 2043 | ✅ ⏬ **-15** |
| Panics | 1 | 1 | 0 |
| Coverage | 95.42% | 95.45% | **+0.03%** |
<details><summary><b>:tada: Fixed (15):</b></summary>
```
xtask/src/coverage/test262/test/built-ins/RegExp/match-indices/indices-array-element.js
xtask/src/coverage/test262/test/built-ins/RegExp/match-indices/indices-array-matched.js
xtask/src/coverage/test262/test/built-ins/RegExp/match-indices/indices-array-non-unicode-match. …
```

feat(rslint_lexer): add d flag to regex

---

crates/rslint_parser/src/lib.rs
crates/rslint_parser/src/parser.rs
crates/rslint_parser/src/state.rs
crates/rslint_parser/src/syntax/binding.rs
crates/rslint_parser/src/syntax/class.rs
crates/rslint_parser/src/syntax/decl.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/src/syntax/function.rs
crates/rslint_parser/src/syntax/module.rs
crates/rslint_parser/src/syntax/object.rs
crates/rslint_parser/src/syntax/program.rs
crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/src/syntax/typescript.rs

The parser has a neat `with_state` function that takes a snapshot of the parser state and restores the state to its previous state when it goes out of scope. However, the downside is that it copies the state at least twice, once inside the `with_state` function and once in the call-site, when constructing the new state which results in a serious performance penalty. 
This PR introduces a new `ChangeParserState` trait that allows making specific changes to the `ParserState` that can later be undone, only keeping a copy of the data they changed (and need to be restored later). Ideally, these changes would have semantic names. However, this PR re-uses the name of the fields. 
I hope to be able to reduce a lot of the boilerplate by introducing generic fields, for example if we're inside a …

feat(rslint_parser): Avoid cloning parser state

---

crates/rslint_parser/src/parser.rs

@MichaReiser  pointed out that ```drop_bomb``` already compiles to nothing on release; but only if we use the ```DebugDropBomb```
Before
```
ttps://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js
time:   [13.214 ms 13.346 ms 13.483 ms]
https://cdn.jsdelivr.net/npm/three@0.134.0/build/three.min.js
time:   [76.430 ms 77.113 ms 77.814 ms]
```
After
```
https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js
time:   [13.318 ms 13.412 ms 13.521 ms]
https://cdn.jsdelivr.net/npm/three@0.134.0/build/three.min.js
time:   [71.329 ms 71.884 ms 72.578 ms]
```
Summary
```
jquery.min.js,Total Time,15.8501ms,tokenization,1.2743ms,parsing,7.3124ms,tree_sink,7.2634ms
vue.global.prod.js,Total Time,21.6517ms,tokenization,1.8166ms,parsing,9.9708ms,tree_sink,9.8643ms
react.production.min.js,Total …
```

using DebugDropBomb

---

.github/workflows/test262.yml

* speed up Test262 by fetching less
* remove windows build as its slower, and performances the same as linux
* now down to ~2 mins

ci: speed up and remove windows build

---

Cargo.lock
crates/rome_analyze/Cargo.toml
crates/rome_formatter/Cargo.toml
crates/rome_lsp/Cargo.toml
crates/rome_rowan/Cargo.toml
crates/rslint_errors/Cargo.toml
crates/rslint_lexer/Cargo.toml
crates/rslint_parser/Cargo.toml
crates/rslint_regex/Cargo.toml
crates/tests_macros/Cargo.toml
rust-toolchain.toml
xtask/Cargo.toml
xtask/src/compare/results.rs
xtask/src/coverage/files.rs
xtask/src/coverage/mod.rs

While we are at it, I have updated dependencies so we don't have to wait another around of build time on dependency upgrades.
Commands ran:
```
cargo upgrade --workspace
cargo update
cargo update -p clap:3.0.7 --precise 3.0.0-beta.4
cargo update -p pico-args --precise 0.3.4
cargo update -p lexical --precise 5.2.0
```
Removed two unused dev-dependencies from rome_rowan:
* m_lexer
* serde_json
`cargo outdated`:
<details>
```
xtask:
Upgrading syn v1.0.39 -> v1.0.85
Upgrading anyhow v1.0.26 -> v1.0.52
Upgrading yastl v0.1 -> v0.1.2
Upgrading convert_case v0.4.0 -> v0.5.0
Upgrading quote v1.0.2 -> v1.0.14
Upgrading unindent v0.1.6 -> v0.1.7
Upgrading walkdir v2.3.1 -> v2.3.2
Upgrading proc-macro2 v1.0.19 -> v1.0.36
Upgrading pico-args v0.3.4 -> v0.4.2
Upgrading once_cell v1.4.1 -> v1.9.0 …
```

chore: Rust v1.58.0

---

Cargo.lock
crates/rome_analyze/src/analysis_server.rs
crates/rome_analyze/src/analyzers.rs
crates/rome_analyze/src/analyzers/no_double_equals.rs
crates/rome_analyze/src/analyzers/no_var.rs
crates/rome_analyze/src/analyzers/use_single_case_statement.rs
crates/rome_analyze/src/analyzers/use_while.rs
crates/rome_analyze/src/assists.rs
crates/rome_analyze/src/lib.rs
crates/rome_analyze/src/signals.rs
crates/rome_analyze/src/suppressions.rs
crates/rome_lsp/Cargo.toml
crates/rome_lsp/src/handlers.rs
crates/rome_lsp/src/server.rs
crates/rome_lsp/src/url_interner.rs
crates/rome_lsp/src/utils.rs

- An `AnalyzeDiagnostic` now uses an `rslint_errors::Diagnostic` internally. That `Diagnostic` format may not perfectly match our needs, but it makes sense to unify around a single core diagnostics type for all of our crates. We can either modify it incrementally or replace it later, as needed.
- Analyzers now return `Option<Analysis>` instead of `Result<Analysis>`.
- As analyzers are meant to inspect the syntax tree of an entire file, it’s often not ideal for them to bail early using `?` on fallible functions (e.g. when attempting to access the children of an AST node). It’s preferable for errors to be collected and included as part of the normal return value (similar to how our parser works). TODO: Add error-handling infrastructure for `Analysis`
- The return type is an `Option` as an …

feat: use rslint_errors Diagnostic in rome_analyze

---

crates/rslint_parser/src/syntax/class.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/test_data/inline/err/block_stmt_in_class.rast
crates/rslint_parser/test_data/inline/err/private_member_name_with_space.js
crates/rslint_parser/test_data/inline/err/private_member_name_with_space.rast
crates/rslint_parser/test_data/inline/err/private_name_with_space.js
crates/rslint_parser/test_data/inline/err/private_name_with_space.rast

Trivia isn't allowed between a `#` token and the private name identifier. This PR changes the
*private member name* and *private name* implementation to emit an error if there's a whitespace between the `#` and identifier name.
Added two new parser tests that handle whitespace between private member names

fix(rslint_parser): Fix private name with whitespace

---

crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/test_data/inline/ok/do-while-asi.js
crates/rslint_parser/test_data/inline/ok/do-while-asi.rast
crates/rslint_parser/test_data/inline/ok/do_while_statement.rast

Fix the automatic semicolon insertion rule for `do`...`while`
>   1. When, as the source text is parsed from left to right, a token (called the offending token) is
encountered that is not allowed by any production of the grammar, then a semicolon is
automatically inserted before the offending token if one or more of the following conditions is
true:
...
>  - The previous token is ) and the inserted semicolon would then be parsed as the terminating
semicolon of a do-while statement (13.7.2).
Fixes a coverage test, added new parser test

fix(rslint_parser): Do-while ASI

---

crates/rslint_parser/src/syntax/class.rs
crates/rslint_parser/test_data/inline/ok/static_generator_constructor_method.js
crates/rslint_parser/test_data/inline/ok/static_generator_constructor_method.rast

Static methods called `constructor` are valid JS, thus, these methods can be generators or async.
Verified that it fixes the 262 tests, added a new parser test

fix(rslint_parser): Static `constructor` member

---

Cargo.lock
crates/rome_cli/Cargo.toml
crates/rome_cli/src/lib.rs

This PR updates clap to the latest version. It removed some dependencies, saving a bit of compile time and disk space.
--- 
Note: Clap currently accounts for 9.6% of the binary size, which should be triaged at some point.
`cargo bloat -p rome_cli --release --crates`
```
File  .text     Size Crate
24.6%  37.7% 758.5KiB rslint_parser
11.1%  17.0% 342.2KiB rslint_lexer
9.6%  14.7% 295.4KiB clap  <---- wow
9.1%  14.0% 281.1KiB std
8.4%  12.9% 258.9KiB rome_formatter
```

chore(rome_cli): Update to clap@3.0.9

---

.github/workflows/main.yml
.github/workflows/pull_request.yml

Main branch is failing with release build, this PR adds release build check.
This PR is failling with 
```
no field `printed_tokens` on type `&formatter::Formatter`
```
@leops

ci: add `cargo check --release` to lint stage

---

Cargo.lock
crates/rslint_parser/Cargo.toml
crates/rslint_parser/src/lib.rs
crates/rslint_parser/src/parser.rs
crates/rslint_parser/src/state.rs
crates/rslint_parser/src/syntax/assignment.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/src/syntax/typescript.rs

#1929 revealed that rewinding a checkpoint isn't a guarantee that our parser is in its previous state, because it doesn't restore the state as well.
This isn't an issue for most of our state variables because most changes are scoped, automatically restored when exiting the parsing of a section.
However, the `hoisted` and `scoped` variables changes aren't scoped. A variable gets added when its first seen and the change is only undone when entering a new function or block (or class). Thus, re-parsing the same binding after a restore triggers a re-declaration error.
This PR is a preparation for #1929. It adds a `ParserStateCheckpoint` that ensures the `Parser` and its state are correctly rewinded when using checkpoints. The current implementation only adds debug assertions because the …

feat(rslint_parser): Parser State Checkpoint

---

Cargo.lock
crates/rslint_parser/Cargo.toml
crates/rslint_parser/src/numbers.rs

Number parsing is incomplete at the moment. This is the first part of on going effort to improve number parsing.
Previously rslint used the `lexical` library to parse any number into f64 without checking, and has a double parsing issue when parsing numbers with leading zeroes.
This PR only removes `lexical`, and uses
* `f64` to parse numbers with radix 10
* `i64` to parse other radix 2, 8 and 16, since JavaScript does not have floating point binary/octal/hex numbers. 
Correctness checking and other improvements will be submitted in other PRs.
All tests pass.

refactor(rslint_parser): Use `f64` and `i64` to parse numbers, remove lexical

---

.github/workflows/pull_request.yml
xtask/src/libs/mod.rs
xtask/src/main.rs

This PR adds 
* criterion groups, which enables throughput
* the `--save-baseline` option from criterion, which enables [critcmp](https://github.com/BurntSushi/critcmp) tool for comparing results
* ci pipeline with bot comment
Use Case:
```
on pr branch, run
git checkout main
cargo run -p xtask --release -- coverage-libs --save-baseline main
git checkout -
cargo run -p xtask --release -- coverage-libs --save-baseline pr
critcmp main pr # (cargo install critcmp)
```
Output using the `remove-lexical` branch
```
group                                 main                                    pr
-----                                 ----                                    --
parser/compiler.js                    1.05    98.1±26.02ms    10.7 MB/sec     1.00     93.4±7.47ms    11.2 MB/sec …
```

ci: benchmark with bot comment

---

xtask/src/coverage/mod.rs

> `raw` The test source code must not be modified in any way, files from the harness/ directory must not be evaluated, and the test must be executed just once (in non-strict mode, only).
But there are a few tests with flags `[raw, module]`. It's important that we parse these as modules. The `raw` flag has no effect because modules are "strict" by default.

fix(coverage): Fix [raw, module] flag combination of t262

---

crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/test_data/inline/ok/do-while-asi.js
crates/rslint_parser/test_data/inline/ok/do-while-asi.rast
crates/rslint_parser/test_data/inline/ok/do_while_statement.rast

#1954 fixed the ASI rule for `do...while` statements so that it no longer errors if the semicolon is missing after the `do ...while ()`.
However, the parser should still eat the semi in case one is present.
Fixes the parse errors with `d3.min.js`
Adds a new test with an optional semi.

fix(rslint_parser): Fix `do-while` optional semi

---

crates/rslint_lexer/src/state.rs
crates/rslint_lexer/src/tests.rs
crates/rslint_syntax/src/generated.rs

Fixes the remaining 262 tests that incorrectly fail parsing a valid program containing a regex literal.
The lexer uses the `in_expr` state to determine whatever a regexp is valid. This requires, that the lexer correctly tracks in which places an expression is valid. This hasn't been the case for
```
{
}
function // <- smt
```
and some keywords that I added to `before_expr` list.
Added additional tests to the lexer

fix(rslint_lexer): Fix lexing of regex literals

---

crates/rome_formatter/src/cst.rs
crates/rome_formatter/src/formatter.rs
crates/rome_formatter/src/ts/assignment/any_assignment.rs
crates/rome_formatter/src/ts/assignment/object_assignment_pattern.rs
crates/rome_formatter/src/ts/bindings/any_binding.rs
crates/rome_formatter/src/ts/bindings/object_binding_pattern.rs
crates/rome_formatter/src/ts/class/class_member.rs
crates/rome_formatter/src/ts/class/constructor_class_member.rs
crates/rome_formatter/src/ts/directives.rs
crates/rome_formatter/src/ts/expressions/expression.rs
crates/rome_formatter/src/ts/mod.rs
crates/rome_formatter/src/ts/object_members/object_member.rs
crates/rome_formatter/src/ts/parameter_list.rs
crates/rome_formatter/src/ts/statements/mod.rs
crates/rome_formatter/src/ts/statements/statement.rs
crates/rome_formatter/src/ts/unknown/assignment.rs
crates/rome_formatter/src/ts/unknown/binding.rs
crates/rome_formatter/src/ts/unknown/expression.rs
crates/rome_formatter/src/ts/unknown/import_assertion_entry.rs
crates/rome_formatter/src/ts/unknown/member.rs
crates/rome_formatter/src/ts/unknown/mod.rs
crates/rome_formatter/src/ts/unknown/named_import_specifier.rs
crates/rome_formatter/src/ts/unknown/parameter.rs
crates/rome_formatter/src/ts/unknown/statement.rs

Part of #1726 
This PR:
- changes the API `format_raw` to `format_verbatim`
- implements all `Unknown*` nodes we have in the formatter so far. While we wait on a decision on to attempt to format them, they all do call the API `format_verbatim`
- implements `ToFormatElement` for all `Unknown*` nodes
- adds formatting of `Unknown*` nodes to `cst.rs`
Existing tests

feat(rome_formatter): format_verbatim and unknown nodes

---

crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/test_data/inline/err/subscripts_err.js
crates/rslint_parser/test_data/inline/err/subscripts_err.rast
crates/rslint_parser/test_data/inline/err/template_after_optional_chain.js
crates/rslint_parser/test_data/inline/err/template_after_optional_chain.rast

Template string is not allowed to be passed to tail position of optional chain.
| Test result | `main` count | This PR count | Difference |
| :---------: | :----------: | :-----------: | :--------: |
| Total | 44951 | 44951 | 0 |
| Passed | 43841 | 43845 | ✅ ⏫ **+4** |
| Failed | 1109 | 1105 | ✅ ⏬ **-4** |
| Panics | 1 | 1 | 0 |
| Coverage | 97.53% | 97.54% | **+0.01%** |
<details><summary><b>:tada: Fixed (4):</b></summary>
```
xtask/src/coverage/test262/test/language/expressions/optional-chaining/early-errors-tail-position-null-optchain-template-string-esi.js
xtask/src/coverage/test262/test/language/expressions/optional-chaining/early-errors-tail-position-null-optchain-template-string.js
xtask/src/coverage/test262/test/language/expressions/optional-chaining/early-errors-tail-position-optc …
```

feat(rslint_parser): Ban template literal after optional chain

---

.github/workflows/bench.yml

Fix bench bot not creating a comment on PRs, from 
@driimus https://github.com/driimus/tools/compare/main...driimus-patch-1?diff=split in discord.

ci: fix bench bot not creating a comment on PRs

---

.github/workflows/bench.yml
.github/workflows/main.yml
.github/workflows/pull_request.yml
.github/workflows/test262.yml

FIx github action to enable long paths.
More details at: https://github.com/rome/tools/pull/1982

ci: enable longpaths on github actions

---

crates/rslint_errors/src/file.rs
crates/rslint_lexer/src/lib.rs
crates/rslint_lexer/src/state.rs
crates/rslint_lexer/src/tests.rs

Invalid unicode escape sequences are valid inside of tagged template literals, but not template literals. 
This PR suppresses the escape sequence diagnostics for tagged template literals. 
It further fixes an issue with escaped sequences where `validate_escape_sequence` progressed the current position and so did `read_str_literal`. 
It also fixes the span of a diagnostic to be a valid range (and not from pos to 1).
Added new lexer tests. The `invalid_escape_sequence.js` test is now passing.

fix(rslint_lexer): Invalid unicode escape sequence in tagged template literal

---

crates/rome_analyze/src/analysis_server.rs
crates/rome_core/src/file_handlers/javascript.rs
crates/rome_core/src/file_handlers/json.rs
crates/rome_core/src/file_handlers/unknown.rs
crates/rome_formatter/src/lib.rs
crates/rome_formatter/src/ts/mod.rs
crates/rome_formatter/tests/spec_test.rs
crates/rome_lsp/src/handlers.rs
crates/rslint_parser/src/ast/stmt_ext.rs
crates/rslint_parser/src/numbers.rs
crates/rslint_parser/src/parse.rs
crates/rslint_parser/src/tests.rs
crates/rslint_parser/src/util.rs
xtask/src/coverage/test262.rs
xtask/src/coverage/typescript.rs
xtask/src/libs/mod.rs

Adds a method that allows parsing a file with the provided syntax. This is useful because in many cases all we want to do is to parse the root of a program and enable certain syntax features. 
It's likely that the `Syntax` struct will change in the future. It's just what already existed.
This PR also adds a way to run TypeScript codegen tests by writing `// TYPESCRIPT`. We probably want to have a more elaborated approach of doing this in the codegen but it unblocks me from working on parsing typescript types. 
`cargo test`

feat(rslint_parser): Add `parse` method

---

.github/workflows/release.yml
.gitignore
Cargo.lock
editors/vscode/.gitignore
editors/vscode/.vscodeignore
editors/vscode/package-lock.json
editors/vscode/package.json
editors/vscode/src/extension.ts

This add a "release" GitHub Actions workflow triggered by publishing a new release on GitHub. It builds the `rome_lsp` binary for all supported OS and architectures (window/macos/linux and x86_64/aarch64 respectively) and bundles it with the VSCode extension. It then pushes the resulting packages to the VSCode Marketplace either as a normal or pre-release depending on based on the GitHub release that triggered the workflow.
As part of the release workflow, the crates.io and npm dependencies are audited for any known security issue with `cargo audit` and `npm audit` (via `npm ci`). To make this work I removed `package-lock.json` from the `.gitignore` list to ensure the npm dependencies of the extension are locked, and updated the crates.io dependencies as the `thread_local` crate was …

feat: add a release workflow

---

editors/vscode/package.json
editors/vscode/src/extension.ts

When I added a new extension locally for `rome_lsp`, I used the `rome-dev` name and had the word "Dev" all over the place so that I wouldn't mix it up with the published version. This changes the name to match what's on the marketplace and updates the version to `"0.0.4"`.
Although I noticed that the extension name is `vscode-rome` in the `archived-js` branch and I don't remember why that's the case or if we should do the same thing here. @sebmck?
@leops Also, feel free to close this PR if its easier to incorporate these changes into your #1995 PR.

chore: change vscode extension name and version

---

Cargo.lock
crates/rome_formatter/Cargo.toml
crates/rome_formatter/src/lib.rs
crates/rslint_parser/Cargo.toml
crates/rslint_parser/src/ast.rs

Use the procedural `Error` macro from the `thiserror` crate to automatically derive the `std::error::Error` and `std::fmt::Display` trait for the `FormatError` and `SyntaxError` types

refactor(error): use thiserror to implement the Error trait on FormatError and SyntaxError

---

crates/rome_formatter/src/format_element.rs
crates/rome_formatter/src/formatter.rs
crates/rome_rowan/src/api.rs
crates/rome_rowan/src/cursor.rs
crates/rome_rowan/src/green/token.rs

Iterating over trivia pieces backward is required for a number of algorithms in the formatter, for instance when emitting leading comments or determining the indentation level of a token. This adds an implementation of DoubleEndedIterator for SyntaxTriviaPiecesIterator (and its internal iterator type) to make this process more efficient than having to collect all the pieces into a vector first

feat(rome_rowan): implement DoubleEndedIterator for SyntaxTriviaPiecesIterator

---

.gitignore

Visual Studio creates a .vs directory when opening the repo with it (for instance to run a profiling session), but much like other editors we don't want that to be committed

chore(git): add .vs to the list of ignored IDE directories

---

.github/workflows/parser_conformance.yml

The conformance tests are failing because the TS submodule doesn't get cloned (seems to be missing since it got moved).
This PR re-adds the TypeScript submodule.

CI: Fix conformance tests

---

xtask/coverage/src/typescript.rs

The `baselines/reference` directory contains the expected outcome for every test.
Extend the TypeScript test case runner to check the reference directory to determine whether a test is expected to fail or not.

chor: TS Conformance expected errors

---

crates/rome_formatter/src/cst.rs
crates/rome_formatter/src/format_element.rs
crates/rome_formatter/src/format_elements.rs
crates/rome_formatter/src/formatter.rs
crates/rome_formatter/src/lib.rs
crates/rome_formatter/src/printer.rs
crates/rome_formatter/src/ts/class/property_class_member.rs
crates/rome_formatter/src/ts/directives.rs
crates/rome_formatter/src/ts/expressions/literal_expression.rs
crates/rome_formatter/src/ts/mod.rs
crates/rome_formatter/src/ts/statements/break_statement.rs
crates/rome_formatter/src/ts/statements/continue_statement.rs
crates/rome_formatter/src/ts/statements/debugger_statement.rs
crates/rome_formatter/src/ts/statements/do_while_statement.rs
crates/rome_formatter/src/ts/statements/expression_statement.rs
crates/rome_formatter/src/ts/statements/return_statement.rs
crates/rome_formatter/src/ts/statements/throw_statement.rs
crates/rome_formatter/src/ts/statements/variable_declaration_statement.rs
crates/rome_formatter/tests/spec_test.rs
crates/rome_lsp/src/capabilities.rs
crates/rome_lsp/src/handlers.rs
crates/rome_lsp/src/server.rs

This is an initial implementation of the range formatting API. It works by tracking the location of tokens between the input and output of the formatter, and use that information to remap the location of the formatting range from the source document to the result and slice the resulting code accordingly. I consider this an initial baseline implementation since it still reformats the entire document: the next step would be to find the lowest common ancestor for the start and end of the formatting range and reformat only that node, with the printer initialized to the correct indentation level.
This change introduce a layout modification of the `Token` type in the formatter: I added source location information alongside the text content, and took the opportunity to change its type from a …

feat(rome_formatter): add a baseline version of range formatting

---

crates/rome_formatter/src/formatter.rs
crates/rome_formatter/src/formatter_traits.rs
crates/rome_formatter/src/lib.rs
crates/rome_formatter/src/ts/statements/continue_statement.rs
crates/rome_formatter/src/ts/statements/return_statement.rs
crates/rome_formatter/src/ts/statements/try_statement.rs

Part of #2002 
This PR propose the usage of traits to format tokens and reducing the use of the try operator. The try operator has been replaced with the use of `.expect()` inside the traits  themselves.
One thing to notice is that these traits now return `FormatElement`. I thought that there was not point into returning `FormatResult<FormatElement>`, otherwise we need to keep using the try operator somewhere else.
I didn't want to put the new traits inside `formatter.rs` because they are not related.
New APIs for tokens/nodes:
- `.format(formatter)`
- `.format_with(formatter, |node_or_token| { ... })`
New APIs for optional tokens/nodes:
- `.format_or_empty()`
- `.format_or`
- `.format_with_or_empty`
- `.format_with_or` 
Do you think I should rename `or`  in `or_else`? 
The idea is to …

feat(rome_formatter): traits for tokens

---

.cargo/config.toml
.github/workflows/bench_formatter.yml
.github/workflows/bench_parser.yml
CONTRIBUTING.md
Cargo.lock
crates/rome_formatter/src/ts/expressions/literal_expression.rs
crates/rome_formatter/src/ts/expressions/mod.rs
crates/rome_formatter/src/ts/expressions/regex_literal.rs
xtask/bench/Cargo.toml
xtask/bench/README.md
xtask/bench/src/features/formatter.rs
xtask/bench/src/features/mod.rs
xtask/bench/src/features/parser.rs
xtask/bench/src/lib.rs
xtask/bench/src/main.rs
xtask/bench/src/utils.rs

This PR is part of #1996 
Closes #2030 
I creates a new workflow to run the formatter against the libraries that we use to bench the parser. 
I changed the key comments to trigger the benchmarks:
- `!bench_parser` will trigger  the parser benchmarks
- `!bench_formatter` will trigger the formatter benchmarks 
- the old alias `cargo benchmark` has been removed
- new cargo alias called `cargo bench_parser`
- new cargo alias called `cargo bench_formatter`
Existing CI and run locally the new command.

ci: formatter benchmarks

---

.gitattributes
crates/rome_formatter/src/cst.rs
crates/rslint_parser/src/ast/generated.rs
crates/rslint_parser/src/ast/generated/macros.rs
crates/rslint_parser/src/ast/generated/nodes.rs
xtask/codegen/src/ast.rs
xtask/codegen/src/generate_macros.rs
xtask/codegen/src/generate_nodes.rs
xtask/codegen/src/lib.rs

This PR adds a `map_syntax_node` macro with the following syntax: `map_syntax_node!(<SyntaxNode expression>, <AstNode> => <expression>, <JsSyntaxKind> => <expression>)`. The macros expands to a match on the kind of the SyntaxNode in the first argument, and for each JsSyntaxKind that implements AstNode duplicates the second argument as a match branch that casts the SyntaxNode to the appropriate AstNode type before executing the expression. For all JsSyntaxKind that do not implement AstNode the third argument is expanded as a fallback branch in the match expression.
As it stands this is only used to implement `ToFormatElement` for `SyntaxNode`, but I chose to implement this as a macro so that it can be eventually leveraged in other algorithms that implement a tree traversal and may need to …

feat: add a macro for executing an expression on all AST node types

---

crates/rome_formatter/src/formatter.rs
crates/rome_formatter/src/formatter_traits.rs
crates/rome_formatter/src/lib.rs
crates/rome_formatter/src/ts/assignment/array_assignment_pattern.rs
crates/rome_formatter/src/ts/assignment/assignment_with_default.rs
crates/rome_formatter/src/ts/assignment/computed_member_assignment.rs
crates/rome_formatter/src/ts/assignment/identifier_assignment_target.rs
crates/rome_formatter/src/ts/assignment/object_assignment_pattern.rs
crates/rome_formatter/src/ts/assignment/parenthesized_assignment.rs
crates/rome_formatter/src/ts/assignment/static_member_assignment.rs
crates/rome_formatter/src/ts/auxiliary/any_function.rs
crates/rome_formatter/src/ts/auxiliary/initializer_clause.rs
crates/rome_formatter/src/ts/auxiliary/name.rs
crates/rome_formatter/src/ts/auxiliary/reference_identifier.rs
crates/rome_formatter/src/ts/auxiliary/spread.rs
crates/rome_formatter/src/ts/bindings/binding_pattern_rest_element.rs
crates/rome_formatter/src/ts/bindings/binding_pattern_with_default.rs
crates/rome_formatter/src/ts/bindings/identifier_binding.rs
crates/rome_formatter/src/ts/bindings/object_binding_pattern.rs

This is part #1996 
This is a first batch of changes where we start using the new traits. While doing so I uncovered two new cases which now implement the new traits.
The changes should be applied to all the nodes but I decided to start small in order to not make the PR too overwhelming.
No tests should fail

refactor(rome_formatter): new format API

---

crates/rome_formatter/src/format_element.rs
crates/rome_formatter/src/formatter.rs
crates/rome_formatter/src/ts/expressions/template_chunk_element.rs

Per the ECMAScript specification there is no semantic difference between `\r`, `\n` and `\r\n` in template literals (they all get normalized to `\n`). This means the formatter doesn't need to preserve these and can normalize them all to `\n`, which will get replaced with an OS-appropriate line ending sequence in the printer.

feat(rome_formatter): normalize line terminators in template literals

---

crates/rslint_parser/src/ast/generated/nodes.rs
crates/rslint_parser/test_data/inline/ok/ts_array_type.rast
crates/rslint_parser/test_data/inline/ok/ts_call_signature_member.rast
crates/rslint_parser/test_data/inline/ok/ts_conditional_type.rast
crates/rslint_parser/test_data/inline/ok/ts_construct_signature_member.rast
crates/rslint_parser/test_data/inline/ok/ts_constructor_type.rast
crates/rslint_parser/test_data/inline/ok/ts_function_type.rast
crates/rslint_parser/test_data/inline/ok/ts_getter_signature_member.rast
crates/rslint_parser/test_data/inline/ok/ts_import_type.rast
crates/rslint_parser/test_data/inline/ok/ts_index_signature_member.rast
crates/rslint_parser/test_data/inline/ok/ts_indexed_access_type.rast
crates/rslint_parser/test_data/inline/ok/ts_inferred_type.rast
crates/rslint_parser/test_data/inline/ok/ts_intersection_type.rast
crates/rslint_parser/test_data/inline/ok/ts_literal_type.rast
crates/rslint_parser/test_data/inline/ok/ts_mapped_type.rast
crates/rslint_parser/test_data/inline/ok/ts_object_type.rast
crates/rslint_parser/test_data/inline/ok/ts_parenthesized_type.rast
crates/rslint_parser/test_data/inline/ok/ts_predefined_type.rast
crates/rslint_parser/test_data/inline/ok/ts_property_or_method_signature_member.rast
crates/rslint_parser/test_data/inline/ok/ts_reference_type.rast
crates/rslint_parser/test_data/inline/ok/ts_return_type_annotation.rast
crates/rslint_parser/test_data/inline/ok/ts_setter_signature_member.rast
crates/rslint_parser/test_data/inline/ok/ts_template_literal_type.rast
crates/rslint_parser/test_data/inline/ok/ts_this_type.rast
crates/rslint_parser/test_data/inline/ok/ts_tuple_type.rast
crates/rslint_parser/test_data/inline/ok/ts_type_operator.rast
crates/rslint_parser/test_data/inline/ok/ts_type_predicate.rast
crates/rslint_parser/test_data/inline/ok/ts_typeof_type.rast
crates/rslint_parser/test_data/inline/ok/ts_union_type.rast
xtask/codegen/js.ungram

This PR fixes a small bug in our grammar. Now the `type_parameters` in `TsTypeAliasStatement` are marked as optional.
We already have tests for these cases. I updated the current RAST files

fix(rslint_parser): mark optional type parameters is alias statement

---

crates/rome_formatter/src/format_element.rs
crates/rome_formatter/src/intersperse.rs
crates/rome_formatter/src/ts/auxiliary/function_body.rs
crates/rome_formatter/src/ts/class/getter_class_member.rs
crates/rome_formatter/src/ts/class/method_class_member.rs
crates/rome_formatter/src/ts/statements/for_of_statement.rs
crates/rome_formatter/tests/specs/js/module/class/class.js
crates/rome_formatter/tests/specs/js/module/class/class.js.snap
crates/rome_formatter/tests/specs/js/module/function/function.js
crates/rome_formatter/tests/specs/js/module/function/function.js.snap
crates/rome_formatter/tests/specs/js/module/newlines.js
crates/rome_formatter/tests/specs/js/module/newlines.js.snap
crates/rome_formatter/tests/specs/js/module/statement/for_of.js
crates/rome_formatter/tests/specs/js/module/statement/for_of.js.snap

This fixes a number of issues that were caught when running our formatter on the prettier test suite:
- Directive lists in function bodies were not printed
- The `static` token on class getters was not printed
- The `async` token on class methods was not printed
- The `static` token on class getters was not printed
- The `await` token on for-of statements was not printed
- The debug assertions in `get_lines_between_nodes` were raised when empty statements were being filtered
Most of these are fixed by formatting the missing tokens. For the last point, instead of filtering out empty statements from the iterator they are left in, but the `join_elements_with` function now skips emitting a line break before an empty element.

fix(rome_formatter): various minor corrections to the formatter

---

.gitattributes

Our windows build is failing because `ts` line endings are converted to windows line endings by git on check out. 
This PR changes the line ending to LF for all files in the test data directory
https://github.com/rome/tools/actions/runs/1807656578
Test in prod?

Windows: inline test file ending

---

.gitattributes

Our list of exceptions inside the `gitattributes` file when to use `LF` ending is ever-growing #2060, #2054.
Let's use the `LF` ending for all our files to solve this problem once and for all. This also aligns the configuration with our `.editorconfig`.
https://github.com/rome/tools/blob/a38b515dd1b3db064cf8778c004e18926d49a997/.editorconfig#L3-L4
CI

chor: Use `LF` endings for all files

---

CONTRIBUTING.md
editors/vscode/README.md

The `README.md` for the VS Code extension will appear in the Marketplace and when viewing installed extensions, so it shouldn't include development instructions. This PR moves those instructions to the `CONTRIBUTING.md` file.
The `cargo install --path crates/rome_lsp` option was removed because the current extension no longer supports it.

docs: move extension development instructions

---

.gitattributes

Changes to the AST create changes in many generated files. These changes can be distracting from the real changes made by the author.
This PR sets the `linguist-generated=true` attribute for the files generated by the codegen so that they are hidden in diffs by default and no longer count to the repo's statistics.
[Source](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github)
You can see in #2072 that the generated files are hidden by default.

chore: hide generated code

---

crates/rslint_parser/src/parser/single_token_parse_recovery.rs
crates/rslint_parser/src/state.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/src/syntax/typescript.rs
crates/rslint_parser/src/syntax/typescript/types.rs
crates/rslint_parser/src/tests.rs
crates/rslint_parser/test_data/inline/err/template_literal.js
crates/rslint_parser/test_data/inline/err/template_literal.rast
crates/rslint_parser/test_data/inline/err/ts_template_literal_error.rast
crates/rslint_parser/test_data/inline/err/ts_template_literal_error.ts
crates/rslint_parser/test_data/inline/ok/template_literal.js
crates/rslint_parser/test_data/inline/ok/template_literal.rast
crates/rslint_parser/test_data/inline/ok/type_arguments_no_recovery.rast
crates/rslint_parser/test_data/inline/ok/type_arguments_no_recovery.ts

The following typescript test panicked.
```ts
for (let i = 0 ; i < 3; ++i) {
verify.completions({
marker: `${i + 1}`,
exact: [
{ name: "foo", replacementSpan: test.ranges()[i] },
{ name: "bar", replacementSpan: test.ranges()[i] },
]
});
}
```
It revealed two problems:
1. The `parse_conditional_expr` tried to parse the `<` as a call expression with type arguments. The problem was that `parse_type_arguments` performed error recovery when it wasn't able to parse a valid type name. Thus, `parse_ts_type_parameters` ended up parsing the `${i + 1}` as a typescript template literal type
2. `${i + 1}` isn't a valid TypeScript template literal. The parser recognised the template element and then tried to parse `i + 1` as a type. This consumed the `i` but left the `+ 1` tokens. Now, the parser …

fix(rslint_parser): Template literal error recovery

---

crates/rome_formatter/src/js/lists/export_named_from_specifier_list.rs
crates/rome_formatter/src/js/lists/export_named_specifier_list.rs
crates/rome_formatter/src/js/module/export_named_from_specifier.rs
crates/rome_formatter/tests/specs/js/module/export/named_from_clause.js.snap
crates/rome_formatter/tests/specs/prettier/babel-plugins/module-string-names.js.snap
crates/rome_formatter/tests/specs/prettier/export/same-local-and-exported.js.snap
crates/rome_formatter/tests/specs/prettier/exports/test.js.snap
crates/rome_formatter/tests/specs/prettier/module-string-names/module-string-names-export.js.snap

This changes the printing order of named exports from `export { as bar foo } from "module"` to `export { foo as bar } from "module"`

fix: correct JsExportNamedFromSpecifier printing order

---

crates/rome_formatter/src/js/auxiliary/expression_snipped.rs

Besides lists (being handled in #2096) this is the last JavaScript node not having a proper implementation of `ToFormatElement`

fix: implement ToFormatElement for JsExpressionSnipped

---

crates/rslint_parser/src/syntax/class.rs
crates/rslint_parser/src/syntax/typescript/ts_parse_error.rs
crates/rslint_parser/test_data/inline/err/typescript_abstract_classes_invalid_static_abstract_member.rast
crates/rslint_parser/test_data/inline/err/typescript_abstract_classes_invalid_static_abstract_member.ts

Errors:
```
error[SyntaxError]: static members cannot be abstract
┌─ typescript_abstract_classes_invalid_static_abstract_member.ts:1:20
│
1 │ abstract class A { abstract static fn1(); }
│                    ^^^^^^^^
--
error[SyntaxError]: static members cannot be abstract
┌─ typescript_abstract_classes_invalid_static_abstract_member.ts:2:27
│
2 │ abstract class B { static abstract fn1(); }
│                           ^^^^^^^^
```

fix(rslint_parser): error on static abstract members

---

Cargo.lock
xtask/codegen/Cargo.toml
xtask/codegen/src/formatter.rs

This is a followup to #2031 and QoL improvement related to #1997:
- It removes the now-unused migration code from the old folder structure to the new
- The formatter codegen is now integrated with git and will automatically stage modified files, as well as avoid to overwrite files that have uncommitted modifications by default (can be overridden with the `--allow-staged` and `--allow-dirty` CLI flags)
- Rust files that are no longer imported into the auto-generated module tree are now automatically removed

feature(xtask): git integration for formatter codegen

---

crates/rslint_parser/src/ast/generated/nodes.rs
crates/rslint_parser/src/ast/generated/syntax_factory.rs
crates/rslint_parser/src/syntax/js_parse_error.rs
crates/rslint_parser/src/syntax/module.rs
crates/rslint_parser/test_data/inline/err/import_as_identifier_err.rast
crates/rslint_parser/test_data/inline/err/import_assertion_err.rast
crates/rslint_parser/test_data/inline/err/import_decl_not_top_level.rast
crates/rslint_parser/test_data/inline/err/import_err.rast
crates/rslint_parser/test_data/inline/err/ts_export_syntax_in_js.rast
crates/rslint_parser/test_data/inline/err/ts_named_import_specifier_error.rast
crates/rslint_parser/test_data/inline/err/ts_named_import_specifier_error.ts
crates/rslint_parser/test_data/inline/ok/import_as_as_as_identifier.rast
crates/rslint_parser/test_data/inline/ok/import_as_identifier.rast
crates/rslint_parser/test_data/inline/ok/import_assertion.rast
crates/rslint_parser/test_data/inline/ok/import_decl.rast
crates/rslint_parser/test_data/inline/ok/import_default_clause.rast
crates/rslint_parser/test_data/inline/ok/import_named_clause.rast
crates/rslint_parser/test_data/inline/ok/module.rast
crates/rslint_parser/test_data/inline/ok/ts_import_clause_types.rast
crates/rslint_parser/test_data/inline/ok/ts_import_clause_types.ts
crates/rslint_parser/test_data/inline/ok/ts_named_import_specifier_with_type.rast
crates/rslint_parser/test_data/inline/ok/ts_named_import_specifier_with_type.ts
xtask/codegen/js.ungram

Adds support for TypeScript's `import` extensions:
```ts 
import { type A, type b as C } from "./mod";
import type foo from "./mod";
import type * as foo2 from "./mod";
import type { foo3 } from "mod";
```
Added new parser tests

feat(rslint_parser): TypeScript `import` extensions

---

crates/rslint_parser/src/syntax/typescript/types.rs
crates/rslint_parser/test_data/inline/ok/ts_conditional_type_call_signature_lhs.rast
crates/rslint_parser/test_data/inline/ok/ts_conditional_type_call_signature_lhs.ts

TypeScript allows call signatures as the left-hand side of conditional types:
```ts
type X<V> = V extends (...args: any[]) => any ? true : false;
```
The parser used to call into `parse_ts_union_type_or_higher` to avoid parsing out another conditional type as the left-hand sie. However, this means the parser doesn't try to parse out function or constructor types.
This PR correctly parses function and constructor types as the left-hand side of conditional types.
part of #2113
Added new parser tests. Verified that the regressions are tests that test for the presence of type checker errors.

fix(rslint_parser): function types in conditional type lhs

---

crates/rslint_parser/src/syntax/class.rs
crates/rslint_parser/src/syntax/typescript/types.rs
crates/rslint_parser/test_data/inline/ok/ts_extends_generic_type.rast
crates/rslint_parser/test_data/inline/ok/ts_extends_generic_type.ts

The parser incorrectly parsed `B<A>` in `class T extends B<A>` as the start of a call expression with type arguments (assumed it would be `B<A>()`) instead of an identifier with type arguments.
This PR adds a check when speculatively parsing the type arguments of a call expression to only eat them if they're followed by a token that is valid coming after type arguments (either a template literal or `(`.
We may need to extend the list of valid tokens in the future to get better error recovery.
* Added a new parser test 
* Verified that the regressions are tests that should fail with errors emitted by a type checker
closes #2122

fix(rslint_parser): Type-arguments in `extends` heritage clause

---

crates/rome_formatter/src/lib.rs

Not sure what to name this tbh. `to_format_element` seems logical but it's specifically the root, so we could call it `root_to_format_element`. Thoughts?

feat(rome_formatter): add function for converting file to format_element

---

crates/rome_formatter/tests/specs/prettier/babel-plugins/record-tuple-record.js.snap
crates/rome_formatter/tests/specs/prettier/babel-plugins/v8intrinsic.js.snap
crates/rome_formatter/tests/specs/prettier/decorators/comments.js.snap
crates/rome_formatter/tests/specs/prettier/record/destructuring.js.snap
crates/rome_formatter/tests/specs/prettier/record/record.js.snap
crates/rome_formatter/tests/specs/prettier/record/spread.js.snap
crates/rome_formatter/tests/specs/prettier/record/syntax.js.snap
crates/rome_formatter/tests/specs/prettier/template-literals/css-prop.js.snap
crates/rome_formatter/tests/specs/prettier/test-declarations/angular_async.js.snap
crates/rome_formatter/tests/specs/prettier/v8_intrinsic/intrinsic_call.js.snap
crates/rslint_parser/src/syntax/module.rs
crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/test_data/inline/err/module_closing_curly.rast
crates/rslint_parser/test_data/inline/err/module_closing_curly.ts
crates/rslint_parser/test_data/inline/err/statements_closing_curly.js
crates/rslint_parser/test_data/inline/err/statements_closing_curly.rast

Example:
```
{
"name": "troublesome-lib",
"typings": "lib/index.d.ts",
"version": "0.0.1"
}
```
The parser tries to parse this as a block statement but then fails because of the `"name":`. The existing error recovery incorrectly eats away all tokens including `}` which then results in a parse error that the closing `}` is missing.
Before:
```
error[SyntaxError]: Expected a semicolon or an implicit semicolon after a statement, but found none
┌─ statements_closing_curly.js:3:7
│
3 │ "name": "troublesome-lib",
│ ------^
│ │     │
│ │     An explicit or implicit semicolon is expected here...
│ ...Which is required to end this statement
--
error[SyntaxError]: expected `'}'` but instead the file ends
┌─ statements_closing_curly.js:7:1
│
7 │
│ ^ the file ends here
```
After:
``` …
```

fix(rslint_parser): Stop statement and module recovery before `}`

---

crates/rslint_parser/src/ast/generated/nodes.rs
crates/rslint_parser/src/ast/generated/syntax_factory.rs
crates/rslint_parser/src/syntax/typescript/types.rs
crates/rslint_parser/test_data/inline/ok/ts_import_type.rast
crates/rslint_parser/test_data/inline/ok/ts_import_type.ts
xtask/codegen/js.ungram

TypeScript's import type can have type arguments:
```ts
type A = import("./test")<string>;
type B = import("./test").X<string>;
```
This PR adds the type arguments field to the `TsImportType` and changes the parser as well.
Added new parser tests.
```
cargo coverage --filter importUsedInGenericImportResolves
```
now passes.

fix(rslint_parser): Add type-arguments to `TsImportType`

---

Cargo.lock
xtask/codegen/Cargo.toml

This disables all default features of `libgit2` since they are not being used and removes a unneeded dependency on OpenSSL

fix(xtask): disable the ssh and https features of libgit2

---

crates/rslint_parser/src/ast/generated/nodes.rs
xtask/codegen/src/generate_nodes.rs

This PR adds a new `as_slots` method to all generated AST nodes. This method calls all the accessor methods of the node its implemented for, and return their results in an associated `<node>Slots` struct that consumers of this API are expected to bind to a destructuring pattern. For example:
```rust
let JsObjectExpressionSlots { l_curly_token, members, r_curly_token } = expr.as_slots();
```
This is primarily aimed at the formatter to help statically ensure that no child node or token is skipped when formatting an ASTNode, as Rust will emit an error if a field is missing in a destructuring pattern, and a warning if the resulting binding is unused

feat: implement destructuring for AST nodes

---

crates/rslint_parser/src/syntax/typescript/types.rs
crates/rslint_parser/test_data/inline/err/ts_tuple_type_cannot_be_optional_and_rest.rast
crates/rslint_parser/test_data/inline/err/ts_tuple_type_cannot_be_optional_and_rest.ts

fixing https://github.com/rome/tools/issues/2135
The code below would parse fine.
```ts
type A = [ ...name?: string[] ]
```
```
error[SyntaxError]: A tuple member cannot be both optional and rest.
┌─ ts_tuple_type_cannot_be_optional_and_rest.ts:1:12
│
1 │ type A = [ ...name?: string[] ]
│            ^^^^^^^^^^^^^^^^^^
```

fix(rslint_parser): error when tutple type is rest and optional

---

crates/rome_formatter/src/js/statements/if_statement.rs
crates/rome_formatter/tests/specs/js/module/arrow/arrow_nested.js.snap
crates/rome_formatter/tests/specs/js/module/invalid/if_stmt_err.js.snap
crates/rome_formatter/tests/specs/js/module/statement/if_chain.js
crates/rome_formatter/tests/specs/js/module/statement/if_chain.js.snap
crates/rome_formatter/tests/specs/prettier/classes/ternary.js.snap
crates/rome_formatter/tests/specs/prettier/comments/if.js.snap
crates/rome_formatter/tests/specs/prettier/do/do.js.snap
crates/rome_formatter/tests/specs/prettier/empty-statement/body.js.snap
crates/rome_formatter/tests/specs/prettier/if/comment_before_else.js.snap
crates/rome_formatter/tests/specs/prettier/if/else.js.snap
crates/rome_formatter/tests/specs/prettier/if/expr_and_same_line_comments.js.snap
crates/rome_formatter/tests/specs/prettier/if/if_comments.js.snap
crates/rome_formatter/tests/specs/prettier/no-semi/no-semi.js.snap
crates/rome_formatter/tests/specs/prettier/sloppy-mode/function-declaration-in-if.js.snap
crates/rome_formatter/tests/specs/prettier/tab-width/class.js.snap

This improves the formatting of `if(...) ... else if(...) ...` chains by flattening them and formatting them as a single group: this means the entire chain will either be printed on a single line if it fits, or each branch will be broken into a different line with an indent block
```js
if (1) 1; else if (2) 2; else 3;
if (very_long_condition_1)
very_long_statement_1();
else if (very_long_condition_2)
very_long_statement_2();
else
very_long_statement_3();
```

feat(rome_formatter): improve the formatting of if-else chains

---

xtask/coverage/README.md
xtask/coverage/src/lib.rs
xtask/coverage/src/main.rs
xtask/coverage/src/reporters.rs
xtask/coverage/src/results.rs
xtask/coverage/src/runner.rs
xtask/coverage/src/test262.rs
xtask/coverage/src/typescript.rs

A TypeScript test file can define multiple files:
```
// @Filename: tsconfig.json
{
"compilerOptions": {
"allowJs": true,
"outDir": "foo",
"isolatedModules": true,
}
}
// @Filename: index.js
module.exports = {}
var x = 1
```
This test defines 2 files, a `tsconfig.json` and an `index.js`.
This PR adds support for multiple files to our test runner and extracts the different files for the TypeScript test suite. The test runner parses each individual file and aggregates the diagnostics when asserting the outcome.
This will enable us to extract more metadata in the future, for example, respect the `@declaration` flag once the parser supports a TypeScript declaration file kind.
These are tests that are expected to fail and used to fail because they contain a `.json` file (that our parser can't …

chore(coverage): Support multiple test files per test case

---

crates/rome_formatter/tests/specs/prettier/js/babel-plugins/private-fields-in-in.js.snap
crates/rome_formatter/tests/specs/prettier/js/babel-plugins/record-tuple-record.js.snap
crates/rome_formatter/tests/specs/prettier/js/babel-plugins/record-tuple-tuple.js.snap
crates/rome_formatter/tests/specs/prettier/js/record/computed.js.snap
crates/rome_formatter/tests/specs/prettier/js/record/destructuring.js.snap
crates/rome_formatter/tests/specs/prettier/js/record/record.js.snap
crates/rome_formatter/tests/specs/prettier/js/record/shorthand.js.snap
crates/rome_formatter/tests/specs/prettier/js/record/spread.js.snap
crates/rome_formatter/tests/specs/prettier/js/record/syntax.js.snap
crates/rome_formatter/tests/specs/prettier/js/tuple/destructuring.js.snap
crates/rome_formatter/tests/specs/prettier/js/tuple/tuple.js.snap
crates/rome_formatter/tests/specs/prettier/typescript/private-fields-in-in/basic.ts.snap
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/test_data/inline/err/private_name_presence_check_recursive.js
crates/rslint_parser/test_data/inline/err/private_name_presence_check_recursive.rast
crates/rslint_parser/test_data/inline/ok/binary_expressions.js
crates/rslint_parser/test_data/inline/ok/binary_expressions.rast

Fixes the precedence of private names. Rome's parser incorrectly parsed `this && #name in this` as
```
BinaryExpression(
BinaryExpression(this && #name),
'in'
`this`
)
```
instead of
```
BinaryExpression(
this,
'&&'
BinaryExpression(#name in this)
)
```
It further fixes an issue where the parser incorrectly emitted a diagnostic for `true && #name in this` that `#name` is only allowed on the left-hand side of a binary expression.
Part of #2113 
Added new parser tests

fix(rslint_parser): Private name precedence

---

crates/rome_formatter/src/js/declarations/catch_declaration.rs
crates/rome_formatter/tests/specs/prettier/typescript/catch-clause/type-annotation.ts.snap
crates/rslint_parser/src/ast/generated/nodes.rs
crates/rslint_parser/src/ast/generated/syntax_factory.rs
crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/test_data/inline/err/ts_catch_declaration_non_any_unknown_type_annotation.rast
crates/rslint_parser/test_data/inline/err/ts_catch_declaration_non_any_unknown_type_annotation.ts
crates/rslint_parser/test_data/inline/ok/try_stmt.rast
crates/rslint_parser/test_data/inline/ok/ts_catch_declaration.rast
crates/rslint_parser/test_data/inline/ok/ts_catch_declaration.ts
xtask/codegen/js.ungram

TS supports annotating the type in a catch declaration with either `any` or `unknown`.
This PR adds the optional type annotation to the grammar and
fixes the implementation to call `parse_ts_type_annotation` instead of `parse_ts_type_parameters`
Part of #2113
Added new parser tests
Regressions. This is a bit surprising but `useUnknownInCatchVariables01` actually tests for many other compile errors but it's now failing because the parser correctly parsing the catch declaration.

fix(rslint_parser): TS type annotation in `catch` declaration

---

crates/rome_formatter/tests/specs/prettier/js/babel-plugins/record-tuple-record.js.snap
crates/rome_formatter/tests/specs/prettier/js/babel-plugins/record-tuple-tuple.js.snap
crates/rome_formatter/tests/specs/prettier/js/record/computed.js.snap
crates/rome_formatter/tests/specs/prettier/js/record/destructuring.js.snap
crates/rome_formatter/tests/specs/prettier/js/record/record.js.snap
crates/rome_formatter/tests/specs/prettier/js/record/shorthand.js.snap
crates/rome_formatter/tests/specs/prettier/js/record/spread.js.snap
crates/rome_formatter/tests/specs/prettier/js/record/syntax.js.snap
crates/rome_formatter/tests/specs/prettier/js/tuple/destructuring.js.snap
crates/rome_formatter/tests/specs/prettier/js/tuple/tuple.js.snap
crates/rslint_parser/src/parser.rs
crates/rslint_parser/src/parser/parsed_syntax.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/src/syntax/function.rs
crates/rslint_parser/src/syntax/js_parse_error.rs
crates/rslint_parser/src/syntax/pattern.rs
crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/src/syntax/typescript/types.rs
crates/rslint_parser/test_data/inline/err/optional_chain_call_without_arguments.rast
crates/rslint_parser/test_data/inline/err/optional_chain_call_without_arguments.ts
crates/rslint_parser/test_data/inline/err/private_name_presence_check_recursive.js
crates/rslint_parser/test_data/inline/err/private_name_presence_check_recursive.rast
xtask/coverage/src/typescript.rs

#2163 fixed the precedence of private names in `in` expressions, but it doesn't catch the case where a private name is used as the left-hand side of any binary expression other than `in`.
This PR adds a check to verify that the operator is the `in` operator
This PR also fixes an issue with the TypeScript test runner. TypeScript supports running a test for different targets. The name of the `errors` file is then called `<test-case>(target=<target>).errors.txt` and a test is expected to fail if it is present. Our runner doesn't support running tests with different targets but we should assert that a test is expected to fail if an `.errors` file exists for any target (same as we currently do for `module`). This isn't perfect but works reasonably well. 
Added a new parser test
The regressions …

fix(rslint_parser): Allow private name only in `in` expessions

---

crates/rome_formatter/tests/specs/prettier/typescript/definite/asi.ts.snap
crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/test_data/inline/ok/ts_type_variable_annotation.rast
crates/rslint_parser/test_data/inline/ok/ts_type_variable_annotation.ts

Respect ASI rules when parsing definite assignment assertions of variables
```
let a!: string; // definite assignment
let b//ASI
!function test() {} // unary expression
```
Added new parser tests, reviewed the formatter snapshot changes

fix(rslint_parser): Respect ASI when parsing TS's definite assignment

---

crates/rome_formatter/src/js/any/call_argument.rs
crates/rome_formatter/src/js/any/mod.rs
crates/rome_formatter/tests/specs/prettier/js/comments/issues.js.snap
crates/rome_formatter/tests/specs/prettier/js/optional-chaining/chaining.js.snap
crates/rome_formatter/tests/specs/prettier/js/preserve-line/parameter-list.js.snap
crates/rome_formatter/tests/specs/prettier/typescript/conformance/classes/mixinClassesAnnotated.ts.snap
crates/rome_formatter/tests/specs/prettier/typescript/conformance/classes/mixinClassesAnonymous.ts.snap
crates/rome_formatter/tests/specs/prettier/typescript/conformance/expressions/functionCalls/callWithSpreadES6.ts.snap
crates/rslint_parser/src/ast/generated/nodes.rs
crates/rslint_parser/src/ast/generated/syntax_factory.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/test_data/inline/err/invalid_arg_list.js
crates/rslint_parser/test_data/inline/err/invalid_arg_list.rast
crates/rslint_parser/test_data/inline/ok/call_arguments.js
crates/rslint_parser/test_data/inline/ok/call_arguments.rast
xtask/codegen/js.ungram

Call expressions can contain any number of spread arguments:
```
let a, b, c, d;
function test(...args) { console.log(args); }
test(...a, ...b, c, ...d);
```
The parser already parse these correctly but the grammar didn't allow `JsSpread` nodes in the argument position.
This PR introduces a new `JsAnyCallArgument` that is either a `JsAnyExpression` or a `JsSpread`.
Fixes #2169
Added new parser tests

fix(rslint_parser): Fix spread call expression arguments

---

Cargo.lock
crates/rome_formatter/tests/specs/prettier/js/strings/strings.js.snap
crates/rome_formatter/tests/specs/prettier/typescript/import-export/type-modifier.ts.snap
crates/rslint_lexer/src/errors.rs
crates/rslint_lexer/src/lib.rs
crates/rslint_parser/src/syntax/module.rs
crates/rslint_parser/src/syntax/object.rs
crates/rslint_parser/test_data/inline/err/ts_object_getter_type_parameters.rast
crates/rslint_parser/test_data/inline/err/ts_typed_default_import_with_named.rast
crates/rslint_parser/test_data/inline/err/ts_typed_default_import_with_named.ts
xtask/coverage/Cargo.toml
xtask/coverage/src/runner.rs
xtask/coverage/src/test262.rs
xtask/coverage/src/typescript.rs

Extends the coverage tests to assert that the parsed result contains no `Unknown` nodes for tests that are expected to pass. 
This revealed that our Unicode escape sequence parsing is too strict. The validation if Unicode escape sequences are valid (form a valid character) is only necessary in export-name positions (see T262 regressions) but not any others. This check was added in #1938 and is reverted in this PR because I believe it's more important that we parse valid files correctly. We can correctly implement the check once the work on #2035 is done. 
This PR further fixes the parsing of `getter` object members to parse out a normal type annotation and not a return type annotation.
Verified that the regressions are specific to the revert of the Unicode verification.

chore(coverage): assert no unknown in coverage

---

crates/rslint_parser/src/tests.rs
crates/rslint_parser/src/util.rs

Our `SyntaxNodeExt::contains_comments` was still using an old check to detect comments.
I stumbled across this bug while working on something else, so I wanted to fix it separately to avoid too much jargon.
Created a new test and checked that the test failing before the change of code.

fix(rslint_parser): comments detection on nodes

---

crates/rslint_parser/src/syntax/typescript/types.rs
crates/rslint_parser/test_data/inline/ok/ts_return_type_asi.rast
crates/rslint_parser/test_data/inline/ok/ts_return_type_asi.ts

TypeScript supports `: <ident> is <condition>` and `asserts <ident>` predicates on function return types.
This PR ensures that our Parser correctly respects ASI if there's a line break right before the `is` or `asserts` token:
```ts
interface I {
foo(callback: (a: any, b: any) => void): I
is(): boolean;
bar(test: string): I
asserts(): boolean
}
```
`is` and `asserts` are both methods in this example and shouldn't be parsed as return type predicates (`I is...` or `I asserts...`).
Added a new parser test with the above example.

fix(rslint_parser): Fix ASI for return type `is`/`assert` predicates

---

crates/rome_formatter/tests/specs/prettier/typescript/declare/declare-get-set-field.ts.snap
crates/rslint_parser/src/syntax/class.rs
crates/rslint_parser/test_data/inline/ok/ts_property_class_member_can_be_named_set_or_get.rast
crates/rslint_parser/test_data/inline/ok/ts_property_class_member_can_be_named_set_or_get.ts

I am creating the Typescript bench and searching for holes in our implementation. This fixes the problem I found at https://github.com/PanayotCankov/nativescript-big-dts/blob/master/ios.d.ts
```
error[SyntaxError]: expected an identifier, a string literal, a number literal, a private field name, or a computed name but instead found ':'
┌─ ios.d.ts:2270:5
│
2270 │     set: NSSet;
│        ^ Expected an identifier, a string literal, a number literal, a private field name, or a computed name here
```

feat(rslint_parser): allow ts property named get and set

---

crates/rome_formatter/tests/specs/prettier/typescript/class/constructor.ts.snap
crates/rome_formatter/tests/specs/prettier/typescript/comments/type-parameters.ts.snap
crates/rome_formatter/tests/specs/prettier/typescript/error-recovery/generic.ts.snap
crates/rslint_parser/src/syntax/auxiliary.rs
crates/rslint_parser/src/syntax/typescript/types.rs
crates/rslint_parser/test_data/inline/err/ts_export_type.rast
xtask/coverage/src/jsx/jsx_babel.rs
xtask/coverage/src/ts/ts_babel.rs

Not all tests in the `typescript` directory are expected to pass. A test is expected to fail if the `options.json` has a `throws` property or the `output.json` contains any `SyntaxError`
This PR infers the expected outcome by matching the content of the `options.json` and `output.json` (parsing the JSON feels overkill).
There are still plenty of tests that should pass but fail. However, these tests do contain syntax errors. I'm not sure if it's worth keeping this test set (example; modifiers-override)
Verified that some tests now reported "Incorrectly passed"

chore(coverage): Infer should error for ts/babel tests

---

crates/rslint_parser/src/tests.rs
crates/rslint_syntax/src/generated.rs
xtask/codegen/src/generate_syntax_kinds.rs

Currently we have a problem with RegExp. Sometimes we are not expecting them and endup parse regexp literals as multiple operators. For example:
```js
a=/a/
a==/a/
a===/a/
a!=/a/
a!==/a/
```
Although these expressions do not always make sense, we are totally getting lost:
```
error[SyntaxError]: Expected an expression for the right hand side of a `==`, but found an operator instead
┌─ parser_smoke_test:1:4
│
1 │ a==/a/
│  --^ But this operator was encountered instead
│  │
│  This operator requires a right hand side value
error[SyntaxError]: expected an expression but instead found ''
┌─ parser_smoke_test:1:7
│
1 │ a==/a/
│       ^ Expected an expression here
```
This PR solves this specifically for "==", "===", "!=" and "!==".
Another example is that this PR allows us to correctly parse …

feat(rslint_parser): eq2, eq3, neq and neq2 in is_before_expr

---

.github/workflows/release.yml

When releasing the VS Code extension in `nightly` mode, we change version/tag to: `pre-release-{YYYY}-{MM}-{DD}`, e.g: `pre-release-2022-03-04`

ci: change version name for pre-release

---

Cargo.lock
xtask/bench/Cargo.toml
xtask/coverage/Cargo.toml

From `cargo audit`
```block
Run cargo audit
Fetching advisory database from `[https://github.com/RustSec/advisory-db.git`](https://github.com/RustSec/advisory-db.git%60)
Loaded 401 security advisories (from /home/runner/.cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (235 crate dependencies)
error: 1 vulnerability found!
Crate:         regex
Version:       1.5.4
Title:         Regexes with large repetitions on empty sub-expressions take a very long time to parse
Date:          2022-03-08
ID:            RUSTSEC-2022-0013
URL:           [rustsec.org/advisories/RUSTSEC-2022-0013](https://rustsec.org/advisories/RUSTSEC-2022-0013)
Solution:      Upgrade to >=1.5.5
```

chore: fix vulnerability

---

crates/rome_rowan/src/api.rs
crates/rome_rowan/src/green/node_cache.rs
crates/rome_rowan/src/green/token.rs
crates/rslint_lexer/src/highlight.rs
crates/rslint_lexer/src/lib.rs
crates/rslint_lexer/src/tests.rs
crates/rslint_lexer/src/token.rs
crates/rslint_parser/src/event.rs
crates/rslint_parser/src/lossless_tree_sink.rs
crates/rslint_parser/src/lossy_tree_sink.rs
crates/rslint_parser/src/parser.rs
crates/rslint_parser/src/parser/parse_error.rs
crates/rslint_parser/src/parser/parsed_syntax.rs
crates/rslint_parser/src/state.rs
crates/rslint_parser/src/syntax/assignment.rs
crates/rslint_parser/src/syntax/auxiliary.rs
crates/rslint_parser/src/syntax/binding.rs
crates/rslint_parser/src/syntax/class.rs
crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/src/syntax/function.rs
crates/rslint_parser/src/syntax/js_parse_error.rs
crates/rslint_parser/src/syntax/module.rs
crates/rslint_parser/src/syntax/object.rs
crates/rslint_parser/src/syntax/pattern.rs
crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/src/syntax/typescript.rs
crates/rslint_parser/src/syntax/typescript/statement.rs
crates/rslint_parser/src/syntax/typescript/ts_parse_error.rs
crates/rslint_parser/src/syntax/typescript/types.rs
crates/rslint_parser/src/token_source.rs

Streamlines the Parser API by:
* Merging `token_src`, `span_text` and `source` into a single `source` method
* Removing `cur_tok` and replacing the calls with `cur_range`.
* Removing `nth_tok` and `nth_src` by rewriting the two usages to no longer need it
* Removing `marker_range` and `marker_vec_range` (unused)
... and uses `TextSize` and `TextRange` consistently throughout the code base (simplifies a few calls). We may want to fork `text-size` in the future to add some more helper methods or consider contributing to it.
Using `TextRange` instead of `Range<usize>` results in a small performance win:
```
group                                 main                                   text-range
-----                                 ----                                   ---------- …
```

refactor: Streamline `Parser` API and use `TextSize/Range`

---

crates/rome_lsp/src/config.rs
crates/rome_lsp/src/server.rs
crates/rome_lsp/src/session.rs
editors/vscode/package.json

This adds config for diagnostics and code actions so that they're disabled by default. Once we resume work on analysis and there are some worthwhile diagnostics/actions, we can change the defaults (and likely put more thought into our config structure).

feat(lsp): add settings for diagnostics and actions

---

.github/workflows/release.yml

In the last PR, myself and @leops  missed an important part, where the inline change of the version has be done next to packaging and publishing. This PR moves that logic
Merge and kick off a release

ci: move `package.json` version change next to packaging and publish

---

Cargo.lock
crates/rome_analyze/Cargo.toml
crates/rome_analyze/src/analyzers.rs
crates/rome_analyze/src/analyzers/no_double_equals.rs
crates/rome_analyze/src/analyzers/no_var.rs
crates/rome_analyze/src/analyzers/use_single_case_statement.rs
crates/rome_analyze/src/analyzers/use_while.rs
crates/rome_analyze/src/assists.rs
crates/rome_analyze/src/assists/flip_bin_exp.rs

By using `const` over lazily built statics, we can remove the dependency
on `once_cell`.
We do not require `once_cell` in this scenario because Rust's `const` can achieve better results: compile-time evaluation, in-built language feature, no extra dependency.
Public API remains the same.

refactor(rome_analyze): remove dependency on once_cell

---

crates/rslint_lexer/src/lib.rs
xtask/bench/src/libs-js.txt

The lexer uses a `unwind_loop` macro that unwinds loops by repeating the same statement 5 times, then repeating it 5 times inside a `loop` statement:
https://github.com/rome/tools/blob/3a22852e9b129a59e0d3b8eb4dbc48bb9675be7a/crates/rslint_lexer/src/lib.rs#L41-L57
```
unwind_loop!(self.next_byte())
```
becomes
```
self.next_byte();
self.next_byte();
self.next_byte();
self.next_byte();
self.next_byte();
loop {
self.next_byte();
self.next_byte();
self.next_byte();
self.next_byte();
self.next_byte();
}
```
I don't know how much this improves performance, but it causes a significant binary bloat in the case of `read_regex` that uses a nested `unwind_loop`: The outer for parsing the regex, the inner for parsing the flags.
This PR removes the inner unwind because:
- Regular expressions aren't …

fix(rslint_lexer): `read_regex` binary size

---

.github/workflows/release.yml
editors/vscode/package.json
editors/vscode/scripts/updateVersionForPrerelease.mjs

This PR adds the CLI to the binaries being built in the `release` workflow besides the LSP. For now this means the CLI and VSCode Extension will be released in lockstep, which should work well enough for an initial release but is probably not how we'll want to version these in the long term.
Additional changes include:
- Changed the LTO mode from `thin` to `fat` and enabled the `strip=symbols` option on rustc to further optimize and trim down the size of the binaries
- Renamed the version update script to `updateVersionForPrerelease.mjs` and remove the `"type": "module"` fields in the manifest of the extension as it was causing issues with VSCode (I also removed the invocation of the script in the `publish` job since it was not being called and thus did not seem to be needed)

chore(ci): add the CLI to the release workflow

---

.github/workflows/deploy_playground.yml

Needed because the `CF_API_KEY` secret is in the Cloudflare environment

fix(playground): Add `Cloudflare` environment to deploy playground workflow

---

crates/rslint_parser/src/syntax/function.rs
crates/rslint_parser/src/syntax/jsx/mod.rs
crates/rslint_parser/src/tests.rs
crates/rslint_parser/test_data/inline/ok/tsx_type_arguments.rast
crates/rslint_parser/test_data/inline/ok/tsx_type_arguments.tsx
crates/rslint_parser/test_data/inline/ok/type_arguments.jsx
crates/rslint_parser/test_data/inline/ok/type_arguments.rast
xtask/codegen/src/parser_tests.rs

Don't parse `<A extends>()` or `<A extends=B>`  as arrow functions, these must be starts of a JSX element.
Depends on attribute parsing for the tests to pass
#2224

fix(rslint_parser): Don't parse JSX as arrow functions

---

xtask/coverage/src/compare.rs

Sort the coverage results by test suite name to ensure the suites don't get reordered when the comment gets updated.

chore(coverage): Sort test suite names before comparing results

---

Cargo.lock
crates/rome_lsp/Cargo.toml
crates/rome_lsp/src/server.rs
crates/rome_lsp/src/session.rs

This PR allows the LSP server to register for `workspace/didChangeConfiguration` notifications so that VS Code will send them. There doesn't seem to be a way to register that statically as part of the `initialize` response, so this adds dynamic registration via `client/registerCapability` as part of the `initialized` handler.
VS Code doesn't seem to include changes as part of `DidChangeConfigurationParams` (or `params.initialization_options`) so this always uses a `workspace/configuration` request to update the workspace settings. And it updates diagnostics whenever the value of `analysis.enable_diagnostics` changes.
Tested manually in VS Code on macOS.

fix(rome_lsp): handle changes to workspace settings

---

Cargo.lock
crates/rome_cli/Cargo.toml
crates/rome_cli/src/commands/format.rs
crates/rome_cli/src/lib.rs
crates/rome_cli/src/metrics.rs
crates/rome_formatter/Cargo.toml
crates/rome_formatter/src/formatter.rs
crates/rome_formatter/src/lib.rs
crates/rome_formatter/src/printer.rs
crates/rslint_parser/Cargo.toml
crates/rslint_parser/src/parse.rs

This PR introduces a `MetricsLayer` that collects timing metrics from the execution of `tracing` spans. Spans with a level of `DEBUG` and below only have their total (wall time) duration calculated while spans with a level of `TRACE` track both their busy (self time) and idle (child span) time. When the execution of a span completes, the timing data is accumulated into a histogram and this data is later retrieved in the `print_metrics` function to display a graphical visualization of the statistical data associated with each metric.
Both the `init_metrics` (injection of the collection layer) and `print_metrics` functions are only called when the `--show-metrics` flags is passed to the CLI (and the `format` subcommand is being used), so the overhead of metrics collection should be …

feat(rome_cli): add tracing metrics collection and printing

---

crates/rome_analyze/src/signals.rs
crates/rome_cli/src/commands/format.rs
crates/rome_formatter/src/printer.rs
crates/rome_js_syntax/src/numbers.rs
crates/rslint_errors/src/emit.rs
crates/rslint_parser/src/tests.rs
rust-toolchain.toml
xtask/coverage/src/runner.rs

Upgrades toolchain to Rust 1.59 and fixes any new clippy errors.
`cargo test`

chore: Upgrade to Rust 1.59.0

---

crates/rome_formatter/src/lib.rs
crates/rome_lsp/src/config.rs
crates/rome_lsp/src/handlers/formatting.rs
crates/rome_lsp/src/server.rs
crates/rome_playground/package.json
editors/vscode/package-lock.json
editors/vscode/package.json

This PR add three more options to the VSCode extension, allowing to customize the formatting experience.
By default, VSCode reads the `.editorconfig` inside the project and it has also its own defaults, but this file doesn't exist or the user wants to use different formatting styles, we should be able to override these defaults.
There's an existing issue where new settings are not applied on the fly. This means, for now, there's need to reload VSCode in order to read the new settings. I will investigate this issue in a different PR.
Manually edited settings and made sure that the formatter uses different line width or indent style

feat(vscode): add further options for formatting

---

crates/rome_formatter/src/formatter.rs
crates/rome_formatter/src/utils/mod.rs
crates/rome_js_syntax/src/lib.rs
crates/rome_js_syntax/src/util.rs
crates/rome_rowan/src/cursor.rs
crates/rslint_parser/src/parse.rs
crates/rslint_parser/src/tests.rs
crates/rslint_parser/test_data/inline/err/jsx_namespace_member_element_name.rast
crates/rslint_parser/test_data/inline/err/spread_attribute_error.rast
xtask/Cargo.toml
xtask/bench/Cargo.toml
xtask/codegen/Cargo.toml
xtask/coverage/Cargo.toml

* Remove unused methods
* Avoid allocating a vector for `first_comment`, `last_comment`, and `has_comments`
Random:
* Use 2021 Rust Edition for xtask package
`cargo test`

refactor(rome_js_syntax): Syntax `utils` improvements

---

crates/rome_formatter/src/js/expressions/in_expression.rs
crates/rome_formatter/src/js/expressions/instanceof_expression.rs
crates/rome_formatter/src/utils/binarish_expression.rs
crates/rome_formatter/tests/specs/js/module/expression/binaryish_expression.js
crates/rome_formatter/tests/specs/js/module/expression/binaryish_expression.js.snap
crates/rome_formatter/tests/specs/js/module/expression/logical_expression.js
crates/rome_formatter/tests/specs/js/module/expression/logical_expression.js.snap
crates/rome_formatter/tests/specs/prettier/js/babel-plugins/private-fields-in-in.js.snap
crates/rome_formatter/tests/specs/prettier/js/binary-expressions/test.js.snap
crates/rome_formatter/tests/specs/prettier/js/in/arrow-function.js.snap
crates/rome_formatter/tests/specs/prettier/js/method-chain/issue-4125.js.snap
crates/rome_formatter/tests/specs/prettier/typescript/private-fields-in-in/basic.ts.snap

This PR adds `JsInstanceofExpression` and `JsInExpression` to be considered inside the formatting of binaryish expressions.
I took the opportunity to also refactor and generalize a bit the implementation of some parts of the code.
The formatted result of the new tests is a bit strange, also because it's highly impossible to have some code like this, but it's completely inline with the whole algorithm.
Also Prettier formats them at the same way.
New tests

feat(rome_formatter): add instanceof expr and in expr

---

crates/rome_formatter/src/lib.rs
crates/rome_formatter/tests/specs/prettier/js/babel-plugins/decimal.js.snap
crates/rome_formatter/tests/specs/prettier/js/do/do.js.snap
crates/rome_formatter/tests/specs/prettier/js/multiparser-graphql/invalid.js.snap
crates/rome_formatter/tests/specs/prettier/js/multiparser-invalid/text.js.snap
crates/rome_formatter/tests/specs/prettier/js/numeric-separators/number.js.snap
crates/rome_formatter/tests/specs/prettier/js/record/syntax.js.snap
crates/rome_formatter/tests/specs/prettier/js/tuple/syntax.js.snap
crates/rome_formatter/tests/specs/prettier/js/tuple/tuple-trailing-comma.js.snap
crates/rome_formatter/tests/specs/prettier/typescript/angular-component-examples/test.component.ts.snap
crates/rome_formatter/tests/specs/prettier/typescript/decorators-ts/angular.ts.snap
crates/rslint_lexer/src/buffered_lexer.rs
crates/rslint_lexer/src/errors.rs
crates/rslint_lexer/src/lib.rs
crates/rslint_lexer/src/tests.rs
crates/rslint_parser/src/parser.rs
crates/rslint_parser/src/token_source.rs
crates/rslint_parser/test_data/inline/err/literals.rast
crates/rslint_parser/test_data/inline/err/subscripts_err.rast
crates/rslint_parser/test_data/inline/err/template_literal_unterminated.rast

This PR changes the lexer to store the diagnostics instead of returning them when calling `next_token`. The main motivation is to improve performance:
```
group                                    PR                                    main
-----                                    ----                                    ----
parser/checker.ts                        1.00     81.6±2.90ms    31.8 MB/sec    1.04     84.5±2.68ms    30.8 MB/sec
parser/compiler.js                       1.00     49.5±1.98ms    21.2 MB/sec    1.04     51.7±2.29ms    20.3 MB/sec
parser/d3.min.js                         1.00     31.5±1.15ms     8.3 MB/sec    1.03     32.5±1.03ms     8.1 MB/sec
parser/dojo.js                           1.00      2.6±0.06ms    26.1 MB/sec    1.02      2.7±0.04ms    25.5 MB/sec …
```

refactor: Lexer Diagnostics

---

crates/rome_js_syntax/src/lib.rs
crates/rome_js_syntax/src/modifier_ext.rs
crates/rome_rowan/src/api.rs
crates/rome_rowan/src/arc.rs
crates/rome_rowan/src/cursor.rs
crates/rome_rowan/src/green.rs
crates/rome_rowan/src/green/node_cache.rs
crates/rome_rowan/src/green/token.rs
crates/rome_rowan/src/green/trivia.rs
crates/rslint_parser/src/lossless_tree_sink.rs
crates/rslint_parser/src/syntax/function.rs
crates/rslint_parser/src/syntax/stmt.rs
crates/rslint_parser/src/syntax/util.rs
crates/rslint_parser/src/token_source.rs

This PR reduces the memory footprint for storing trivia by:
* Caching and re-using trivia across tokens
* Reducing the size of `GreenTrivia` from `16` to `8` bytes which, in turn, reduces the size of `GreenTokenData` from 36 bytes to 20 bytes. That means, we save 16 bytes for every allocated token. 
* Reducing the size for a "many" trivia from: 32 (8 byte pointer + tag, 16 byte vec + trivia) to 16 bytes (8 byte pointer, 8 byte len + trivia)
Downside:
* This now requires a heap allocation for trivia containing a single piece which is, for example, very common for whitespace. This comes with a slight memory increase because of the heap metadata but that is amortized by caching the trivia across multiple tokens. 
Related discussion #1809
The optimization for storing a single trivia inline …

refactor(rome_rowan): Reduce Trivia Memory footprint

---

crates/rslint_parser/src/syntax/expr.rs
crates/rslint_parser/test_data/inline/err/import_keyword_in_expression_position.js
crates/rslint_parser/test_data/inline/err/import_keyword_in_expression_position.rast

Fix a panic in the parser if `import` appears in an expression position, for example: `let a = import`.
Added a new parser test

fix(rslint_parser): Don't panic for `import` in expression position

---

crates/rome_formatter/src/utils/binarish_expression.rs

This PR removes the usage of saving a node inside a variant. The logic was copied from a different algorithm, but now that the formatting of binaryish expression is stable, we can safely remove some code.
Existing tests

refactor(rome_formatter): remove usage of saving nodes

---

crates/rome_formatter/src/format_element.rs

When we concat elements, we create a list and flat items in it. Sometimes the first item is actually a list. Sometimes a big list, actually. In this case, we hijack this list instead of creating a new one and avoid moving all elements.
Another advantage is that we can use ```size_hint``` better.
On ```rsuite``` case, when formatting 600 files this hijacking happened more than 120K times and the biggest list had 150 items.
On our benchmark:
jquery: +38K times, +800 items;
threejs: +170K times; +3000 items;
Maybe we want a "lazy list" like rope? But a linked list of vecs.

feat(rome_formatter): less allocation when concat elements

---

crates/rome_formatter/src/formatter.rs
crates/rome_formatter/src/lib.rs
crates/rome_formatter/src/ts/bindings/type_parameters.rs
crates/rome_formatter/src/ts/lists/type_parameter_list.rs
crates/rome_formatter/tests/prettier_tests.rs
crates/rome_formatter/tests/specs/prettier/typescript/assignment/issue-10848.tsx.snap
crates/rome_formatter/tests/specs/prettier/typescript/tsx/generic-component.tsx.snap
crates/rome_formatter/tests/specs/prettier/typescript/tsx/keyword.tsx.snap
crates/rome_formatter/tests/specs/prettier/typescript/tsx/member-expression.tsx.snap
crates/rome_formatter/tests/specs/prettier/typescript/tsx/react.tsx.snap
crates/rome_formatter/tests/specs/prettier/typescript/tsx/this.tsx.snap
crates/rome_formatter/tests/specs/prettier/typescript/tsx/type-parameters.tsx.snap
crates/rome_formatter/tests/specs/prettier/typescript/tsx/url.tsx.snap
crates/rome_js_parser/src/tests.rs

This PR does two things:
- enables `tsx` parsing inside the prettier test suite
- fixes a issue due to the trailing comma inside TS type parameters when parsed as `Source_type::tsx()`.
The issue was that before we were removing the trailing comma in case the group doesn't break. We are now forced to have it. Unfortunately we don't have a perfect heuristic because we can't access to the source type of the file, as a consequence I had to create a small workaround.
The drawback of the workaround is that the trailing comma is now kept even when we are in a TS context.
Current prettier test suite should not fail

test(rome_formatter): enable TSX parsing for tsx files

---

crates/rome_formatter/src/formatter_traits.rs
crates/rome_formatter/src/lib.rs
crates/rome_formatter/src/prelude.rs

This PR uses the `prelude`  terminology to expose our traits. Now `formatter_prelude` only contains these traits.
The implementation has been moved inside `formatter.rs`. I could not find a better way to have these implementations. If you have a better idea, it's very welcome!
Existing CI

refactor(rome_formatter): use `prelude` terminology

---

crates/rome_formatter/src/utils/mod.rs
crates/rome_formatter/tests/specs/js/module/assignment/assignment.js
crates/rome_formatter/tests/specs/js/module/assignment/assignment.js.snap

I played around with our formatter and noticed that formatting the benchmark test files twice results in the following parse errors:
```
error[SyntaxError]: Invalid assignment to `s || (s = Object.create(null))[i]`
┌─ vue.global.prod.js:4372:44
│
4372 │                             this._props[i] = Z(this._props[i]), s || (s = Object.create(null))[i] =
│                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ This expression cannot be assigned to
```
The issue is that the formatter removes the parenthesis around the `object` of a static or computed member assignment.
This PR ensures that parenthesis around removed from the left-hand sie of a member assignment which is in line with what the formatter does for expressions.
Added a new formatter test. …

fix(rome_formatter): Don't remove parenthesis from member assignments

---

crates/rome_cli/src/bin/rome.rs
crates/rome_cli/src/lib.rs
crates/rome_cli/src/panic.rs

This PR replaces the default Rust panic hook with a custom printing logic for the CLI, directing users towards the GitHub issue tracker in case the CLI panics. The new format for panic errors is:
```text
> rome format --indent-size -1
The Rome CLI encountered an unexpected error
This is a bug in Rome, not an error in your code, and we would appreciate it if you could report it to https://github.com/rome/tools/ along with the following information to help us fixing the issue:
Source Location: crates\rome_cli\src\commands\format.rs:35:10
Thread Name: main
Message: failed to parse indent-size argument: Utf8ArgumentParsingFailed { value: "-1", cause: "invalid digit found in string" }
```
The new panic hook is implemented in the cli library, but is only installed in the cli binary and not the …

feat(rome_cli): add a user-friendly panic hook to the CLI

---

crates/rome_js_parser/src/lexer/mod.rs
crates/rome_js_parser/src/syntax/jsx/mod.rs
crates/rome_js_parser/test_data/inline/err/jsx_closing_element_mismatch.rast
crates/rome_js_parser/test_data/inline/ok/jsx_equal_content.jsx
crates/rome_js_parser/test_data/inline/ok/jsx_equal_content.rast

The parser failed to parse `<span>=</span>` because the lexer lexed `>=` as a single token rather than a `>` and a `=` token.
This PR changes the lexer to always lex `>=` (and `>>=` and `>>>=` as single tokens and only lex them as binary operators when called with `ReLex::BinaryOperator`.
Part of #2310
Added a new test verifying that `>=` works correctly

fix(rome_js_parser: JSX `>=` parsing

---

crates/rome_js_parser/src/parser/parsed_syntax.rs
crates/rome_js_parser/src/syntax/module.rs
crates/rome_js_parser/test_data/inline/err/export_named_clause_err.rast
crates/rome_js_parser/test_data/inline/ok/export_from_clause.js
crates/rome_js_parser/test_data/inline/ok/export_from_clause.rast

This fixes the "export { \n default" bug at https://github.com/rome/tools/issues/2310
```js
export {
default as a } from "b";
```
The problem is that we parse "export" initially without being an "export ... from...". Then we see a "from" token, rewind everything and parse everything again as an "export ... from...". They have completely different CST nodes.
Before "default" was faulting the "export" parsing, error recovery was kicking in and failing the "export" parse. In this case, the rewind would never occur. If this is not an "export", it cannot be an "export ... from..." is the logic used here.
Now we parse everything correctly and let the rewind kick in as expected.

fix(rome_js_parser): export default working with newlines

---

crates/rome_js_parser/src/lexer/mod.rs

Doesn't seem to provide any real performance improvement
`cargo test`
Reduces the parser crate size by 20Kb.

refactor(rome_js_parser): Remove `unwind_loop` macro

---

internal/cli-flags/Parser.ts

This PR adds a small banner to the **Rome classic**. The banner is displayed every time the CLI is run, regardless of arguments and commands.
This is the look and feel:
None

chore: add banner to rome classic CLI

---

website/src/_includes/docs/formatter.md

This PR adds two sections to how and why our formatter is different from the others, and how to migrate from them. 
I added a section around comments, which - I believe - is the most important one. It's where we deal things differently because of one CST works and we managed to find a way to consistently print comments.
The migration strategy should be simple enough.
Check the cloudflare pages

docs: add diff and migration against other formatters

---

Cargo.lock
crates/rome_cli/src/commands/format.rs
crates/rome_console/Cargo.toml
crates/rome_console/README.md
crates/rome_console/src/diff.rs
crates/rome_console/src/fmt.rs
crates/rome_console/src/lib.rs
crates/rome_console/src/markup.rs
crates/rome_console/tests/macro.rs
crates/rome_console/tests/markup/invalid_group.rs
crates/rome_console/tests/markup/invalid_group.stderr
crates/rome_console/tests/markup/invalid_literal.rs
crates/rome_console/tests/markup/invalid_literal.stderr
crates/rome_markup/src/lib.rs

This PR introduces a new `rome_console::fmt::Display` trait that is directly equivalent to `std::fmt::Display`: the trait declares a single `fn fmt(&self, &mut Formatter) -> Result` method where implementing types can decide on how they want to be printed by submitting additional printing commands to the `Formatter`. Said formatter implements a `write_markup` method that allows `Display`-able types to submit new markup pieces to the console, as well as two `write_fmt` and `write_str` methods equivalent to the ones found in `std::fmt::Formatter` and making the console formatter compatible with the `write!` and `writeln!` macros.
To make use of this new trait the PR also modifies the `markup!` procedural macro to allow any literal (of a type that implements `Display`) inside markup …

feat(rome_console): Display trait and diff printing

---

.github/workflows/deploy_playground.yml
crates/rome_playground/src/App.tsx

They playground crashed because `btoa` only supports ASCII.
This PR ensures that non ASCII characters are propertly encoded before running the code throuh `btoa`.

fix(rome_playground): Unicode Support

---

crates/rome_formatter/src/utils/mod.rs
crates/rome_formatter/tests/specs/js/module/interpreter.js
crates/rome_formatter/tests/specs/js/module/interpreter.js.snap
crates/rome_formatter/tests/specs/js/script/script.js.snap
crates/rome_formatter/tests/specs/prettier/js/comments/trailing_space.js.snap
crates/rome_formatter/tests/specs/prettier/js/shebang/shebang-newline.js.snap
crates/rome_formatter/tests/specs/prettier/js/shebang/shebang.js.snap

Fixes #2325 
It adds always an empty line after the interpreter.
New test case

fix(rome_formatter): add empty line after interpreter

---

npm/rome/package.json
npm/rome/scripts/postinstall.js

Add a `postinstall` script to the `rome` npm package to verify the installation of the native binary, and print a warning to the user immediately if something went wrong.
I decided to only print a warning when something is wrong instead of exiting with an error so that it won't cause an `npm install` on a whole workspace where `rome` is a dependency to fail, in case the user didn't intend to use the Rome CLI anyway.

feat(npm): add a postinstall script to the cli package

---

crates/rome_js_parser/src/event.rs
crates/rome_js_parser/src/lib.rs
crates/rome_js_parser/src/lossless_tree_sink.rs
crates/rome_js_parser/src/parser.rs
crates/rome_js_parser/src/parser/rewrite_parser.rs
crates/rome_js_parser/src/syntax/class.rs
crates/rome_js_parser/src/syntax/function.rs
crates/rome_js_parser/src/syntax/module.rs

Reduce the size of a single parser event from 16 bytes to 8 bytes each by:
* Using a `NonZeroU32` for the forward parent. The forward parent can never be 0 because it stores the offset from the current event to the start of the "forwarded" parent.
* Store the `start` of a node in the `CompletedMarker` (can't be computed because of forward parents)
* Remove `end` from the `Finish` event and instead retrieve the last token of the node when queried (mainly to produce diagnostics).
* Only store the end offset for each Token instead of the full range. The end offset is sufficient to reconstruct the length in the tree sink.
This reduces the memory consumption during the parse phase significantly:
* `jquery`:
* Current Bytes: 4.12 MB -> 2.12 MB
* Max Bytes: 5.82 MB -> 3.82 MB
* Total Bytes: 8.45 …

refactor(rome_js_parser): Streamline parser events

---

.github/workflows/release.yml
editors/vscode/package.json
npm/rome/package.json

Enable the `generate_release_notes` option of the `action-gh-release` action to use GitHub's auto-generated changelog as a release note text. This also bumps the version numbers of the npm package and VSCode extension to trigger a new release when this PR gets merged to main.

chore(ci): enable changelog generation and bump the version numbers for the extension and CLI

---

crates/rome_js_parser/src/lexer/mod.rs
crates/rome_js_parser/src/syntax/expr.rs
crates/rome_js_parser/test_data/inline/ok/literals.js
crates/rome_js_parser/test_data/inline/ok/literals.rast

for more details about the problem see https://github.com/rome/tools/issues/2310#issuecomment-1083630383
This PR fix our regex parser that was ignoring Unicode completely. So in the example below, it was interpreting some random byte inside the regex as a new line and failing to parser the regex.
```
/^[يفمئامئ‍ئاسۆند]/i;
```
Now we correctly respect UTF8 chars boundaries.
PS: I don't speak Arabic so no idea what this string means, but Google Translate is describing precisely my feelings when bit twiddling Unicode.

fix(rome_js_parser): correctly parse regex with unicode chars

---

editors/vscode/package-lock.json
editors/vscode/package.json
npm/rome/package.json

Updates the format of the `package-lock.json` file for the VScode extension to version 2 (and bump the package number versions again)

fix(vscode): update the format of the npm lockfile

---

crates/rome_cli/src/commands/format.rs

This PR moves the ending message for the `format` command after having the diagnostics printed.
Myself and Leo noticed that having the message "Formatted files ..." before the diagnostics wasn't helpful, especially if the number of diagnostics/warning was high.
This PR doesn't handle the "errors where emitted while formatting" message.
Existing CI. I checked manually that the message shows up after printing diagnostics.

chore(rome_cli): move ending message after diagnostics

---

crates/rome_js_parser/src/parser.rs
crates/rome_js_parser/src/syntax/typescript.rs
crates/rome_js_parser/test_data/inline/ok/ts_decorator_call_expression_with_arrow.rast
crates/rome_js_parser/test_data/inline/ok/ts_decorator_call_expression_with_arrow.ts

#2327 changed the parser to not store the last parsed token but instead
retrieve it by getting the kind from the last `Token` event in the parser events.
This didn't play well with skipping tokens because the parser didn't add any tokens to the `events` collection while in `skipping` mode.
This PR changes the `skipping` mode so that it only changes whatever the parser calls `bump` or `skip_as_token_trivia` but the parser will always add it to the `events` collection.
This adds a few unnecessary writes but this should be neglectable because
* Skipping token is rare and even then, often limited to very few tokens
* Moving the `bump` out of the condition may even help with branch prediction.
Fixes #2358
Added a new parser test. 
The …

fix(rome_js_parser): Fix TS Decorator with arrow param parsing

---

Cargo.lock
crates/rome_cli/Cargo.toml
crates/rome_cli/src/commands/format.rs
crates/rome_cli/src/commands/help.rs
crates/rome_cli/src/lib.rs
crates/rome_cli/src/termination.rs
crates/rome_cli/tests/main.rs
crates/rome_console/src/lib.rs
crates/rome_core/src/lib.rs
crates/rome_diagnostics/src/emit.rs
crates/rome_diagnostics/src/lib.rs
crates/rome_formatter/src/format_element.rs
crates/rome_formatter/src/lib.rs
crates/rome_formatter/src/printer.rs
crates/rome_js_formatter/tests/spec_test.rs
crates/rome_lsp/src/handlers/formatting.rs
website/playground/src/lib.rs

I batched together a few QoL improvements to the CLI:
- Show the help for a subcommand when it's called with no other arguments (`rome format`), but still exit with an error
- Expose the line width formatting option through the `--line-width` CLI arguments
- Add a `--dry-run` mode to the CLI to print the diff to the console instead of writing the formatting result to the file (similar to how CI mode works, except the diff isn't reported as an error)
- Reworked how messages are printed to the console: they are now being handled by a dedicated thread in parallel to the formatting process instead of being buffered and flushed once the traversal is complete
- Add a `LineWidth` wrapper type for the `line_width` formatter setting to validate the value is within an acceptable range (`1..=320`) …

feat(rome_cli): CLI Improvements

---

website/src/_includes/docs/getting-started.md

* pnpm deprecated `pnpx` in favor of [`pnpm dlx`](https://pnpm.io/cli/dlx)
* pnpm suggests using [`pnpm add <pkg>`](https://pnpm.io/cli/add) in its docs and does not mention `pnpm i <pkg>` (although it is supported)
* pnpm allows passing through script names like Yarn (`pnpm format` instead of `pnpm run format`)
n/a

docs(website): update pnpm commands

---

website/playground/package.json
website/playground/src/App.tsx

Use `babel-typescript` in the playground when formatting a TypeScript file.
Verified that
```ts
export interface Class<T, Args extends any[] = ClassConstructorParams<T>> {
new(...args: Args): T,
prototype: T,
}
```
gets formatted with semicolon separators.

fix(playground): Prettier TS formatting

---

website/playground/src/SourceTypeSelect.tsx

Fixes bug in playground where changing the typescript checkbox deactivates the jsx one.

fix(playground): checkbox bug

---

.github/workflows/deploy_playground.yml
.github/workflows/deploy_playground_on_main.yml

It can be annoying to play around with people's changes to the formatter. By deploying on every commit and storing in a subdomain, we can try out people's changes to the formatter in the playground.
The only issue I could see is that too many commits can clog up the actions pipeline.

feature(playground): Deploy every commit to subdomain

---

crates/rome_js_formatter/src/utils/mod.rs
crates/rome_rowan/src/cursor/token.rs
crates/rome_rowan/src/cursor/trivia.rs
crates/rome_rowan/src/green/token.rs
crates/rome_rowan/src/green/trivia.rs
crates/rome_rowan/src/raw_language.rs
crates/rome_rowan/src/syntax/trivia.rs

The existing `SyntaxTriviaPiece.text()` method called into `SyntaxTrivia.text_range()` which is expensive because it must iterate over all pieces to get the absolute offset.
The result was that `fourslash/reallyLargeFile` took minutes on my computer to format.
This PR changes the `piece.text` implementation to instead retrieve the text directly from the token because the piece is already aware of its absolute offset in the file, making the operation `O(1)`. 
I don't expect this change to have any perf improvements for the majority of files. It's only relevant for files with a massive number of trivia pieces. 
There are still some places where the implementation calls into `text_range` to get the offsets which always requires iterating over all trivia pieces to get the total length. This …

perf(rome_rowan): `SyntaxTriviaPiece.text()`

---

crates/rome_js_parser/src/parser/rewrite_parser.rs
crates/rome_js_parser/src/token_source.rs
crates/rome_js_parser/test_data/inline/err/js_invalid_assignment.rast
crates/rome_js_parser/test_data/inline/ok/ts_decorator_assignment.rast
crates/rome_js_parser/test_data/inline/ok/ts_decorator_assignment.ts
xtask/codegen/src/parser_tests.rs

Assignments are hard...
This PR fixes an issue where an assignment is used inside a decorator, e.g. `@test(--a)`
The parser used to panic when rewriting the assignment because any skipped tokens (the case for all tokens inside a decorator) are in the trivia collection and the parser events to ensure all parser methods work correctly.
However, this had the effect that `skip_trivia` in `rewrite_parser` moved the offset passed all skipped tokens, passed any not yet processed token (that ultimately get skipped).
This PR makes the rewrite parser aware of skipped tokens and only consumes them when the corresponding token gets bumped.
This prevents the parser from panicking for the following two snipped founds when fuzzing the parser  #1945 
```js
(-- @ (--(-((QQQQQ $
= 8?0 @ (--(-( A S=
```

fix(rome_js_parser): Assignment in decorator

---

crates/rome_console/src/fmt.rs

This change intercepts the writing logic of `rome_console` to replace on the fly any Unicode character with a width of zero (with the exception of code points with the `White_Space` property) with the `REPLACEMENT CHARACTER` code point. This should cover most code points in the `Cc` and `Cf` categories, and ensure they are explicitly visible in the terminal output (for instance when printing code spans)

feat(rome_console): redact Unicode control characters

---

crates/rome_js_formatter/src/ts/declarations/import_equals_declaration.rs
crates/rome_js_formatter/tests/specs/prettier/typescript/import-require/type-imports.ts.snap

Insert a space after the `type` keyword for import equals declarations.

fix(rome_js_formatter): Insert Space after `type` for import equals declaration

---

crates/rome_js_parser/src/syntax/expr.rs
crates/rome_js_parser/test_data/inline/ok/for_with_in_in_parenthesized_expression.js
crates/rome_js_parser/test_data/inline/ok/for_with_in_in_parenthesized_expression.rast

`in` expressions aren't allowed in `for` initializers but are if the initializer is parenthesized [spec](https://tc39.es/ecma262/#prod-ParenthesizedExpression). 
Fixes #2395

fix(rome_js_parser): Parsing of parenthesized `in` expression in `for` initializer

---

.github/workflows/parser_conformance.yml

Update the test262, babel, and TypeScript submodules.
The TypeScript regressions are related to the newly added Syntax in TS 4.7. I created #2400 to track the new syntax features.

Chore: update submodules

---

.github/workflows/deploy_playground.yml
.github/workflows/deploy_playground_on_main.yml

Fixes a syntax error in the `playground*.yml` files.
Triggered the deploy main workflow manually [logs](https://github.com/rome/tools/runs/6003721158?check_suite_focus=true)

chore: Fix syntax error in deploy playground workflow

---

.github/workflows/deploy_playground.yml
website/playground/src/App.tsx

I *think* that the GitHub actions `paths` option requires a `*` after a folder, i.e. `crates/*` instead of `crates/`.

ci(website): fix deploy playground workflow

---

website/playground/src/App.tsx

The options at the top of the playground take up a lot of space and are pretty empty. This PR aligns the options horizontally instead of vertically to give more space to the code.
Into:
Tested on local playground.
PS: Awesome work team! Congrats 👏 
Really need to get back to contributing!

feat(playground): align options horizontally

---

crates/rome_js_formatter/tests/specs/prettier/js/assignment/binaryish.js.prettier-snap

The formatting for the `computedDescriptionLines2` is missing for whatever reason. I formatted the input in the Rome playground and pasted the expected prettier output.

chore: Fix the expected Prettier output of the `binarish` test

---

crates/rome_js_formatter/src/js/any/array_assignment_pattern_element.rs
crates/rome_js_syntax/src/generated/nodes.rs
xtask/codegen/js.ungram
xtask/codegen/src/ast.rs

Adding a BFS search implementation to check if unions trees contain circular dependencies or reuse types.
The goal is to prevent potential union circular dependencies as well as unions having the same type in multiple branches.
Based on https://github.com/rome/tools/issues/1765
Here are the test cases I used : 
**These should succeed : **
```
UnionA =
JsIdentifierAssignment
| JsStaticMemberAssignment
| JsComputedMemberAssignment
UnionB =
JsIdentifierAssignment
| JsUnknownAssignment
```
```
UnionA =
JsIdentifierAssignment
| JsUnknownAssignment
UnionB =
JsIdentifierAssignment
| JsUnknownAssignment
```
**These should fail : **
```
UnionA =
UnionA
| JsUnknownAssignment
```
```
UnionA =
UnionB
| JsUnknownAssignment
UnionB =
JsxText
| UnionA
```
```
UnionA =
UnionB
| JsUnknownAssignment
UnionB …
```

feat(xtask): Check for sub unions overlap

---

.github/workflows/deploy_playground.yml
website/playground/vite.config.ts

Turns out we don't propagate the base url parameter properly with nested NPM scripts

fix(playground): base url not propagated to vite

---

.github/workflows/bench_formatter.yml
.github/workflows/bench_parser.yml
.github/workflows/deploy_playground.yml
.github/workflows/deploy_playground_on_main.yml
.github/workflows/main.yml
.github/workflows/parser_conformance.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml

Update `actions/xxxxx@vx` to `actions/xxxxxx@v3 or 6` since Node12 will be out of life after Aril 30, 2022 [[Reference](https://nodejs.org/en/about/releases/)].  
`actions/xxxx@v3` or `actions/xxxx@v6`  use Node16 whose support lasts until April 30, 2024.
Check if GitHub Actions workflows work well

Update GitHub Actions version

---

crates/rome_js_parser/src/lexer/mod.rs
crates/rome_js_parser/src/lexer/tests.rs

Found via fuzzing https://github.com/rome/tools/issues/1945
It panics on unterminated unicode scape at EOF. e.g. `+\\u{A`
Added a unit test.

fix(rome_js_parser): fix lexer panicking on unterminated unicode escape at EOF

---

website/playground/src/App.tsx
website/playground/src/DesktopPlayground.tsx
website/playground/src/IndentStyleSelect.tsx
website/playground/src/MobilePlayground.tsx
website/playground/src/PlaygroundSettings.tsx
website/playground/src/QuoteStyleSelect.tsx
website/playground/src/SettingsMenu.tsx
website/playground/src/SourceTypeSelect.tsx
website/playground/src/lib.rs
website/playground/src/types.ts
website/playground/src/utils.ts

We didn't have an explicit mobile view of the playground. That made it pretty hard to use because the tile layout couldn't fit into the tiny viewport of a phone.
This PR creates an explicit mobile view that puts the settings and input tiles under a tab. That way users can navigate the playground pretty easily. I also refactored the code a little, pulling out the PlaygroundSettings component and adding a utils module.

feature(playground): Mobile playground

---

crates/rome_js_parser/src/syntax/expr.rs
crates/rome_js_parser/test_data/inline/err/import_invalid_args.rast

Import expression forbids `...`, but the parser didn't consume it, so it created an invalid AST. 
This was noticed when I tried to format
```
import(x, ...y)
```
and it ended up as:
```
import(x,
...y)
```
Ran cargo `UPDATE_EXPECT=1 cargo test parser` and inspected the AST
https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#aQBtAHAAbwByAHQAKAB4ACwAIAAuAC4ALgB5ACkA
p.s. I didn't understand what recoverable meant when I wrote this part of code three months ago.

fix(rome_js_parser): consume `...` in import expression

---

crates/rome_analyze/src/analysis_server.rs
crates/rome_analyze/src/analyzers.rs
crates/rome_analyze/src/assists.rs
crates/rome_css_syntax/src/generated/nodes.rs
crates/rome_js_formatter/src/formatter.rs
crates/rome_js_formatter/src/formatter_traits.rs
crates/rome_js_formatter/src/utils/array.rs
crates/rome_js_formatter/src/utils/binary_like_expression.rs
crates/rome_js_formatter/src/utils/mod.rs
crates/rome_js_parser/src/parse.rs
crates/rome_js_syntax/src/generated/nodes.rs
crates/rome_rowan/src/ast/mod.rs
crates/rome_rowan/src/raw_language.rs
xtask/codegen/src/generate_nodes.rs

The `AstNode`, `AstNodeList`, and `AstSeparatedList` currently use generics to
parametrize the `Language` and `AstNode` (in case of the lists).
This PR changes the `Ast*` traits to use associated types instead. The semantic
difference of this change is that a single struct can no longer implement the traits for different languages.
Or, as explained in the Rust book:
> With associated types, we don’t need to annotate types because we can’t implement a trait on a type multiple times. In Listing 19-12 with the definition that uses associated types, we can only choose what the type of Item will be once, because there can only be one impl Iterator for Counter. We don’t have to specify that we want an iterator of u32 values everywhere that we call next on Counter. …

refactor(rome_rowan): Use associated types for `Ast*` traits

---

crates/rome_css_syntax/src/generated/nodes.rs
crates/rome_js_syntax/src/generated/nodes.rs
crates/rome_json_syntax/src/generated/nodes.rs
xtask/codegen/src/generate_nodes.rs

#2463 refactored the `Ast*` traits to use associated types, but I forgot to re-run the grammar generator after merging the JSON grammar #2466. This PR updates the JSON grammar to use associated types as well and suppresses two unused warnings if a syntax isn't using any `AstNodeList`s.

fix(rome_json_syntax): Update JSON AST Facade

---

crates/rome_js_formatter/src/utils/binary_like_expression.rs
crates/rome_js_formatter/src/utils/mod.rs
crates/rome_js_formatter/src/utils/simple.rs
crates/rome_js_parser/src/tests.rs
crates/rome_rowan/src/syntax/node.rs

This PR adds a new API to `rome_rowan` called `has_comments`.
This API does a shallow check if the current node contains trivia, it doesn't check the descendants.
I then updated the places where we meant to do a shallow check inside the formatter.
Added a new test

feat(rome_rowan): add `has_comments` API

---

Cargo.lock
crates/rome_js_formatter/Cargo.toml
crates/rome_js_formatter/benches/iai.rs
crates/rome_js_formatter/src/js/expressions/big_int_literal_expression.rs
crates/rome_js_formatter/src/lib.rs
crates/rome_js_formatter/src/utils/mod.rs
crates/rome_js_formatter/src/utils/quickcheck_utils.rs
crates/rome_js_formatter/src/utils/string_utils.rs
crates/rome_js_formatter/tests/specs/prettier/js/big-int/literal.js.snap

see https://github.com/rome/tools/issues/2426
For this task, I don't need a general Unicode to_lowercase, and Rust as of today only give me access to lowering the case of a Unicode through ```char::to_lowercase``` which returns an iterator (because of some crazy languages!).
This made my method slower than calling ```str::to_lowercase```.
If I simplify the assumption to support only ASCII, I can make my method faster and avoid allocations.
```
to_ascii_lowercase
Instructions:                 439
L1 Accesses:                  589
L2 Accesses:                    1
RAM Accesses:                  13
Estimated Cycles:            1049
to_ascii_lowercase_cow
Instructions:                 482
L1 Accesses:                  612
L2 Accesses:                    1
RAM Accesses:                  12 …
```

normalize big int literals

---

README.md

Throwback to #1302 and specifically https://github.com/rome/tools/pull/1302#issuecomment-773417481.
A few months ago GitHub did just that https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/!
This PR replaces the outlined logo with its dark and light version.
See for yourself https://github.com/jer3m01/rome/tree/docs/readme-logo#readme

docs: use dark and light logo

---

crates/rome_rowan/src/syntax/token.rs
crates/rome_rowan/src/syntax_token_text.rs

Fix the infinite recursion of the playground.

fix(rome_rowan): fix syntaxtokentext display infinite recursion

---

.github/workflows/pull_request_js.yml

same as #2461. Change the GitHub Actions Version for Node16
Pass GitHub Actions workflows

Update github actions version to v3

---

crates/rome_js_formatter/src/formatter.rs
crates/rome_js_formatter/src/lib.rs
crates/rome_js_formatter/src/printed_tokens.rs

The `Formatter` tracks all formatted tokens in debug builds to catch if the same token gets formatted twice or not formatted at all.
The current implementation tracks the `JsSyntaxToken`s. The downside of doing this is that a language-agnostic implementation needs to track `SyntaxToken<L>` which:
* has the consequence that `Formatter` must be generic over `L`
* which in turn has the consequence that `Format` must be generic over `L`
This PR changes the node tracking to instead only track the absolute offsets of the formatted nodes rather than holding on to the node itself. This removes the need for a generic `Language` parameter and provides the same functionality.
A next step is to move out all `format_` functions from the `Formatter` and put them into standalone functions / extension …

refactor(rome_js_formatter): Track token offsets instead of tokens

---

Cargo.lock
crates/rome_lsp/Cargo.toml
crates/rome_lsp/src/capabilities.rs
crates/rome_lsp/src/handlers/analysis.rs
crates/rome_lsp/src/handlers/formatting.rs
crates/rome_lsp/src/handlers/text_document.rs
crates/rome_lsp/src/requests/syntax_tree.rs
crates/rome_lsp/src/server.rs
crates/rome_lsp/src/session.rs
crates/rome_lsp/src/url_interner.rs
crates/rome_lsp/src/utils.rs
crates/rome_rowan/src/serde_impls.rs
editors/vscode/src/main.ts

1. migrate lsp server crate `lspower` to `tower_lsp`
2. add launch.json which is convenient for debugging, unlike before we need to compile and reinstall `.vsix` every modify,
we could now use `Launch Client` 
1. run `cargo build --package rome_lsp`, build our `rome_lsp` server   
2. cd `editors/code`, and ` code .` open this directory as workspace root
3. switch to this pannel, and click `Launch Cilent` 
4. open any js,  ts, file, use `Format document` command and choose `rome`, your file should be formatted correctly
5. Using `Rome: show Syntax tree` command, you  should see syntax tree on another split window

chore(rome_lsp):  migration to tower_lsp crate

---

Cargo.lock
xtask/codegen/Cargo.toml
xtask/codegen/src/ast.rs
xtask/codegen/src/lib.rs
xtask/codegen/src/main.rs
xtask/codegen/src/termcolorful.rs

introduce ability to optional codegen for specific language kind
1.  run `cargo codegen grammar` should code gen all ungram just like before
2. run `cargo codegen Json css` should warn you `Json` language is not support, but code gen `css` ungram works just
fine
3. run `cargo codegen json css` should codegen `json` and `css` ungram

chore(xtask): choose language when generating grammar

---

crates/rome_formatter/src/format_element.rs
crates/rome_js_formatter/src/js/lists/directive_list.rs
crates/rome_js_formatter/tests/specs/js/module/newlines.js.snap
crates/rome_js_formatter/tests/specs/prettier/js/directives/newline.js.snap
crates/rome_js_formatter/tests/specs/prettier/js/directives/test.js.snap

Fix #2437
The updated snapshot should fix related issue #2437, 
you could review the snapshot this pr updated.

fix(rome_js_formatter): 🐛 preserve new-lines after directives

---

.github/workflows/release_cli.yml
.github/workflows/release_lsp.yml
crates/rome_cli/src/commands/help.rs
npm/rome/package.json

This change allows the VSCode Extension to be versioned independently from the npm wrapper package for the CLI. The releases are still triggered by a change to `editors/vscode/package.json` for the extension (and `npm/rome/package.json` for the CLI), and will be published indepently to either the Visual Studio Marketplace or npm, along with creating a GitHub Release tagged with `lsp/vx.y.z` for the LSP and `cli/vx.y.z` for the CLI
Once we've merged in everything we want to include in the `0.5.0` release I'll edit this PR to also bump the version number of the packages, and dispatch the workflow manually a few times until I get it to work

chore(ci): split the release workflow between the vscode extension and CLI package

---

crates/rome_js_formatter/tests/specs/prettier/js/comments/html-like/comment.js.snap
crates/rome_js_parser/src/syntax/expr.rs
crates/rome_js_parser/src/syntax/jsx/jsx_parse_errors.rs
crates/rome_js_parser/src/syntax/jsx/mod.rs
crates/rome_js_parser/src/syntax/typescript/ts_parse_error.rs
crates/rome_js_parser/test_data/inline/err/ts_type_assertions_not_valid_at_new_expr.rast
crates/rome_js_parser/test_data/inline/err/ts_type_assertions_not_valid_at_new_expr.ts
crates/rome_js_parser/test_data/inline/ok/type_assertion_primary_expression.rast
crates/rome_js_parser/test_data/inline/ok/type_assertion_primary_expression.ts

This PR fixes a problem with jsx versus type assertions at primary expressions.
Currently, something like the code below was failing:
```
let a = <number>b;
```
We would treat ```b``` as ```JSXText``` and later complaint about a missing closing tag.
Now we do our best to parse JSX and type assertions separately and warn appropriately.
This changes an error on an HTML comment test, which does not matter because we still do not support these comments.
If anyone thinks that the current message is worst, I can try something to improve it.

fix(rome_js_parser): jsx vs type assertions

---

crates/rome_js_formatter/src/js/expressions/regex_literal_expression.rs
crates/rome_js_formatter/tests/specs/js/module/expression/literal_expression.js
crates/rome_js_formatter/tests/specs/js/module/expression/literal_expression.js.snap
crates/rome_js_formatter/tests/specs/prettier/js/regex/test.js.snap

Resolve #2445
Snapshot test result has been aligned to related issue, 
now regex literal flags should be sorted correctly

Fix(rome_js_formatter):regex flag order

---

editors/vscode/package-lock.json
editors/vscode/package.json

This is the same change as #2513 rebased on the latest main (with the fixed release workflow)

release(vscode): 0.6.0

---

crates/rome_js_formatter/src/js/expressions/computed_member_expression.rs
crates/rome_js_formatter/tests/specs/js/module/object/computed_member.js
crates/rome_js_formatter/tests/specs/js/module/object/computed_member.js.snap
crates/rome_js_formatter/tests/specs/prettier/js/assignment/issue-7091.js.snap
crates/rome_js_formatter/tests/specs/prettier/js/binary-expressions/comment.js.snap
crates/rome_js_formatter/tests/specs/prettier/js/member/expand.js.snap
crates/rome_js_formatter/tests/specs/prettier/js/method-chain/break-last-member.js.snap
crates/rome_js_formatter/tests/specs/prettier/js/template-literals/expressions.js.snap
crates/rome_js_formatter/tests/specs/prettier/js/ternaries/indent-after-paren.js.snap
crates/rome_js_formatter/tests/specs/prettier/typescript/cast/generic-cast.ts.snap

Fixed #2431
This PR does two things:
- it changes the way nested computed properties are formatted/navigated; it uses the same trick we use in the sequence expressions;
- creates a group around the computed properties so they break when they exceed the line width
Added new tests that cover the case we want to fix

fix(rome_js_formatter): break computed expressions like prettier

---

crates/rome_css_syntax/src/generated/nodes.rs
crates/rome_js_syntax/src/generated/nodes.rs
crates/rome_json_syntax/src/generated/nodes.rs
xtask/codegen/src/generate_nodes.rs

This PRs creates quick ```as...``` conversions methods for easy navigation on the tree. Example:
```rust
impl JsAnyExpression {
pub fn as_import_meta(&self) -> Option<&ImportMeta> {
match &self {
JsAnyExpression::ImportMeta(item) => Some(item),
_ => None,
}
}
pub fn as_js_any_literal_expression(&self) -> Option<&JsAnyLiteralExpression> {
match &self {
JsAnyExpression::JsAnyLiteralExpression(item) => Some(item),
_ => None,
}
}
....
}
```` 
This will be used in https://github.com/rome/tools/pull/2489

feat(rome_js_parser): quick cast methods for nodes

---

crates/rome_js_formatter/src/js/expressions/static_member_expression.rs
crates/rome_js_formatter/tests/specs/js/module/number/number-with-space.js
crates/rome_js_formatter/tests/specs/js/module/number/number-with-space.js.snap

Fixes #2501.
This PR adds conditional to `JsStaticMemberExpression` that checks if its value is a number literal expression that has trailing whitespace.
Added new test that covers the case.

fix(rome_js_formatter): number with trailing whitespace

---

.github/workflows/deploy_playground_on_main.yml

The command worked fine with `pnpm6` but now fails after the upgrade to v7.
```bash
pnpm build --prefix website/playground/
ERR_PNPM_NO_IMPORTER_MANIFEST_FOUND No package.json (or package.yaml, or package.json5) was found in "/home/micha/git/rome".
```
Moving the `--prefix` before the `build` subcommand fixes the issue:
```bash
pnpm --prefix website/playground/ build
> playground@0.0.0 build /home/micha/git/rome/website/playground
> pnpm build:wasm && pnpm build:js
```
Ran the commands locally to verify that they should work with PNPM7

chore: Fix deploy playground on main

---

crates/rome_js_formatter/src/js/expressions/computed_member_expression.rs
crates/rome_js_formatter/tests/specs/js/module/object/computed_member.js
crates/rome_js_formatter/tests/specs/js/module/object/computed_member.js.snap

The formatting stack overflowed in release/printed tokens twice for computed member expressions that have a computed member expression member.
The problem was that the upwards traversal logic didn't check if the `current` node is indeed the `parents.object()` node which is the rule it uses when traversing downwards.
I added a spec test and verified that it fails without the fix.
Cargo bench completes for all formatter tests
```bash
❯ cargo bench_formatter --criterion=false
Compiling rome_js_formatter v0.0.0 (/home/micha/git/rome/crates/rome_js_formatter)
Compiling xtask_bench v0.0.0 (/home/micha/git/rome/xtask/bench)
Finished release [optimized] target(s) in 7.34s
Running `target/release/xtask_bench --feature formatter --criterion=false`
[jquery.min.js] - using …
```

fix(formatter): Stack overflow in formatting computed member expressions

---

crates/rome_js_formatter/src/js/expressions/parenthesized_expression.rs
crates/rome_js_formatter/tests/specs/js/module/expression/member-chain/computed.js
crates/rome_js_formatter/tests/specs/js/module/expression/member-chain/computed.js.snap
crates/rome_js_formatter/tests/specs/js/module/object/computed_member.js
crates/rome_js_formatter/tests/specs/js/module/object/computed_member.js.snap

Fix #2558 
fix the bad case 
```js
a[("test")]
```

Fix(rome_js_formatter):🐛 fix parenthesis expression bad case

---

crates/rome_js_formatter/tests/prettier_tests.rs

Incrementing the `Countme` counter overflowed when running the tests with more than 4 threads.
@leops narrowed the issue down that this is happening because
`countme` only starts counting after calling `countme::enable` and
the counter overflows (underflows) if `Drop` is called for any counted object crated before that point in time.
The issue is inside the `prettier_tests` setup where `countme::enable` was called in the `DiffReporter`. That's too late, because some test running in another thread may have created `Syntax*` or `Green*` objects.
The fix is to move the `countme::enable` at the top of the `test_snapshot` function. That ensures that `Countme` gets enabled before any snapshot test runs (by just making sure that it's still enabled in every snapshot test)
```
cargo test
```
no …

fix: Countme overflow in tests

---

website/playground/package.json
website/playground/pnpm-lock.yaml
website/playground/src/App.tsx
website/playground/src/DesktopPlayground.tsx
website/playground/src/MobilePlayground.tsx
website/playground/src/SettingsMenu.tsx
website/playground/src/TreeStyleSelect.tsx
website/playground/src/TreeView.tsx
website/playground/src/lib.rs
website/playground/src/types.ts
website/playground/src/utils.ts

As some have pointed out, the JSON view is not optimal for some situations. This allows users to toggle between the text and JSON view.

feature(website): Toggle Tree Style

---

crates/rome_analyze/src/analyzers/no_delete.rs
crates/rome_analyze/src/analyzers/no_double_equals.rs
crates/rome_analyze/src/analyzers/use_single_var_declarator.rs
crates/rome_analyze/src/analyzers/use_while.rs
crates/rome_analyze/src/assists/flip_bin_exp.rs
crates/rome_analyze/src/categories.rs
crates/rome_analyze/src/lib.rs
crates/rome_analyze/src/registry.rs
crates/rome_analyze/src/signals.rs
crates/rome_analyze/tests/spec_tests.rs
crates/rome_analyze/tests/specs/noDelete.js.snap
crates/rome_analyze/tests/specs/noDoubleEquals.js.snap
crates/rome_analyze/tests/specs/useSingleVarDeclarator.js.snap
crates/rome_analyze/tests/specs/useWhile.js.snap
crates/rome_console/src/markup.rs
crates/rome_diagnostics/src/diagnostic.rs
crates/rome_diagnostics/src/emit.rs
crates/rome_diagnostics/src/suggestion.rs
crates/rome_lsp/src/handlers/analysis.rs
crates/rome_lsp/src/session.rs
crates/rome_lsp/src/utils.rs
website/playground/src/lib.rs
xtask/bench/src/features/analyzer.rs

This PR changes the internal representation of title, label and suggestion messages in diagnostics to use markup (`MarkupBuf`) instead of plain strings. This change is mostly transparent to the producers of diagnostics (the trait bounds for messages has been changed to `impl rome_console::fmt::Display` which is a superset of the previous `impl Into<String>`) as well as the consumers (diagnostics are already printed as markup, so whether they use strings or markup internally is an implementation detail).
This change removes the need for the intermediate `AnalyzerDiagnostic` struct (analyzer rules now return a plain diagnostic object), however the `AnalyzerAction` struct is still needed as it contains additional information not present in `CodeSuggestion` (but it's now possible to …

feat(rome_diagnostic): refactor diagnostics to use markup

---

crates/rome_formatter/src/format_element.rs
crates/rome_js_formatter/src/utils/member_chain/groups.rs

The `has_line_breaks` method is a heuristic for determining if a `FormatElement` will break for certain, similar to Prettier's `willBreak` function. 
This PR changes the function to return `false` for `LineSuffix` because a line suffix by itself doesn't introduce a line break. It only delays printing its content until the printer reaches the end of the line. A `LineSuffix` forces a group to expand but that only applies if the element is used inside of a `Group`, similar to `soft_line_break` that only expands to a line break outside of a group. That's why this PR changes the semantic to have `soft_line_break` and `LineSuffix` aligned.

fix(formatter): Tighten `has_line_breaks` method

---

crates/rome_formatter/src/format_element.rs
crates/rome_formatter/src/printer/mod.rs
crates/rome_js_formatter/src/formatter.rs
crates/rome_js_formatter/src/js/expressions/assignment_expression.rs
crates/rome_js_formatter/src/jsx/attribute/expression_attribute_value.rs
crates/rome_js_formatter/tests/specs/prettier/js/assignment-comments/function.js.snap
crates/rome_js_formatter/tests/specs/prettier/js/assignment-comments/number.js.snap
crates/rome_js_formatter/tests/specs/prettier/js/assignment-comments/string.js.snap
crates/rome_js_formatter/tests/specs/prettier/js/comments/while.js.snap

This PR introduces  two new IR elements:
* `LineSuffixBoundary`: Forces the printer to flush any pending `LineSuffix`. For example necessary to avoid a comment inside of a JSX expression accidentally getting pushed into the content of an outer element. 
* `ExpandParent`: Forces the parent group to be printed as expended. E.g. should allow us to remove the `LineSuffix` special case inside of the printer by emitting a `ExpandParent` for each block comment.
Part of #2579 
I added examples with integration tests for each new IR element

feature(formatter): `LineSuffixBoundary` and `ExpandParent` IR

---

website/playground/src/DesktopPlayground.tsx
website/playground/src/MobilePlayground.tsx
website/playground/src/types.ts
website/playground/src/utils.ts

Prettier has some utility functions to clean up the IR before showing it in the debug panel. I changed our
Playground to also use these functions because it significantly improves readability (less noise)
**Before**
**After**

chore(playground): Display cleaned prettier IR
